components/tailored/core/sidebar/Sidebar.vue

Have sidebar on mobile devices close automatically when a user goes to `chat-direct` or `files-browse`

Mobile sidebar close

---

components/tailored/core/chatbar/fileupload/FileUpload.html
components/tailored/core/chatbar/fileupload/FileUpload.vue

sa-29: non-image formats show fontawesome file icon instead of broken image

chore(file upload)

---

components/tailored/files/file/File.html
components/tailored/files/file/File.less
pages/files/browse/Browse.html
pages/files/browse/Browse.less

SA-119: Make the files page responsive
fix(Files Page): Have "files" on mobile stack up to 2 in a row
fix(Files Page): Have "files-aside" to render at the top of the page on mobile, but still on the right side on the desktop.
fix(Files Page): Add scrolling for "Files Browse" when on mobile to accommodate for "files-aside" being rendered at the top.

fix(Files Page): File page to be responsive

---

components/ui/Embeds/AudioPlayer/AudioPlayer.vue
components/ui/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.vue
components/ui/Embeds/File/File.vue
components/ui/Embeds/VideoPlayer/VideoPlayer.vue

Upgraded nuxt was throwing an error if a components prop was a function in the embeds.

fix(embeds): 

---

components/tailored/core/sidebar/Sidebar.html
pages/friends/list/index.vue

Fix 'The "Add Friends" button in the Side Menu should take you to the Add Friends tab'

fix(Add Friends): Fix 'The "Add Friends" button in the Side Menu should take you to the Add Friends tab'

---

components/tailored/settings/pages/network/index.vue

Allow Embeds button located in Network tab in Settings is unresponsive

Fix(Network Settings): Fix 'Allow Embeds toggle not works'

---

components/tailored/core/chatbar/Chatbar.html
components/tailored/core/chatbar/Chatbar.less

https://satellite-im.atlassian.net/jira/software/projects/SA/boards/3?selectedIssue=SA-306
"Speak Freely" in the text box for chat does not disappear when pasting a link.
Convert placeholder from individual span to natural placeholder.

fix(chat bar): Fix placeholder overlapping issue on chat bar

---

components/tailored/core/chatbar/Chatbar.vue

Prevent empty message from being sent when clicking the send button

fix(Chat bar): Prevent empty message from being sent when clicking the send button

---

components/tailored/messaging/message/edit/Edit.vue

Fix 'After editing a message in chat, the message will be missing the last character'

fix(Chat): Fix 'After editing a message in chat, the message will be missing the last character'

---

components/tailored/core/user/create/Create.vue

Improves user error message on /auth/register

---

locales/en-US.js

Fix typo on personalize section
Before
After

Fix typo on personalize section

---

components/tailored/core/chatbar/controls/Controls.html
components/tailored/messaging/enhancers/Enhancers.vue

Fix 'After opening the Glyphs menu, user should be able to press it again to close it'

fix(Glyph): Fix 'After opening the Glyphs menu, user should be able to press it again to close it'

---

components/interactables/Search/Input/Input.less

Fix 'iOS issue: the X used for clearing in the search bar is cut off a little at the end'

fix(search): Fix 'iOS issue: the X used for clearing in the search bar is cut off a little at the end'

---

PULL_REQUEST_TEMPLATE.md

Summary
- Add PR template into project
This can be helpful to add more information on the PR description when opening the PR. 
cc @WanderingHogan let me know your thoughts on it! we can also remove/add any information from the PR template.

Add PR template into project

---

components/mixins/Swipe/Swipe.ts

Fix 'Swiping through settings pages is actually swiping through chat screen in the background'

fix(swipe): Fix 'Swiping through settings pages is actually swiping through chat screen in the background'

---

pages/auth/unlock/Unlock.html

Fix typo on /auth/unlock

---

components/tailored/friends/quick/Quick.html
components/tailored/friends/quick/Quick.less
components/tailored/friends/quick/Quick.vue
locales/en-US.js

Add friends component to new chat modal
SA-370
Fixes #
- Get rid of standard inputs & Add friends components
- @RetroPronghorn  I think we don't need copy logic from Create server modal.
I already copied logic but decided to remove all because we can share TailoredSettingsPagesUserSearch component on Create Server Modal & New Chat Modal.  If we need some fixes or tweak, we can update TailoredSettingsPagesUserSearch  component.
- For now, group messages are not implemented (Manuel said we have to find a way to share a secret key between all the participants)... so in this case, We need to wait until they solve that..  We can just create group chat by modifying mock up data but that has no meaning.

fix(Chat): Add friends component to new chat modal

---

components/interactables/ButtonGroup/ButtonGroup.vue
components/tailored/core/chatbar/controls/Controls.html
components/tailored/core/chatbar/controls/Controls.vue
components/tailored/messaging/enhancers/Enhancers.vue
components/tailored/wallet/mini/Mini.vue
locales/en-US.js

Fix 'Issue with clicking between send money, glyphs/emoji'
Jira ref: AP-62
**Fixes 
- Add missing locales
- If enhancer is opened & glyphs or emoji is clicked , just switch tabs
- Ignore outside toggling when glyph & emoji toggle btn is clickd
- Close send money dialog when outside area is clicked
- Update button active style when model is changed

fix(chat bar): Fix 'Issue with clicking between send money, glyphs/emoji'

---

components/tailored/messaging/group/Group.html
components/tailored/messaging/group/Group.vue
components/tailored/messaging/message/Message.html
components/tailored/messaging/message/Message.vue
config.ts
utilities/Messaging.ts

Update timestamp message every minute
timestamp message not updating (‘A few seconds ago' for ever unless component rebuilds)
Fixes #AP-43

fix(message): update timestamp message every minute

---

.prettierrc
cypress/integration/create-account-negative-tests.js
jest.config.js
tsconfig.json

- Removes not needed files and directories from Jest coverage report
- Adds `jest` to `tsconfig.json`
- Updates prettier rules, they were conflicting with the eslint ones, `prettier` wanted '','' on the last line, `eslint` doesn't want the'','' on the last line
- Removes not needed line on Cypress test

chore: update jest coverage rules + update prettier rules

---

libraries/WebRTC/Wire.ts
nuxt.config.js

fix build
update babel to not throw vuetify error
build was failing with the capitalized 'Encoders'. Also updated babel to remove newlines and excess whitespace to get rid of babel error on dev/build
Fixes # n/a

chore(build): fix build

---

libraries/Enums/enums.ts
libraries/Enums/types/message-routes.ts
store/textile/actions.ts
store/textile/mutations.ts
store/textile/types.ts

Added timestamps for user and convo on conversation object
#AP-125
This adds two timestamps to the conversations textile object, which will make it easier for UI updates in the sidebar (sorting based on last message sent/received, show timestamp for last time friend responded, etc)
Fixes #
AP-125
No UI changes, you can see the object being updated in the debugger > application > local storage > satellite-store > and see the new lastMsgReceived and lastConvoUpdate keys in the textile conversations object.

chore(textile-store): update textile convo to have timestamps on top level

---

package.json

Git is forcing ssl even when explicitely requesting http
#AP-00
This fixes the build on netlify. The build is failing because yarn is forcing ssh instead of https for the submodules and satellite owned git repos our packages point to. Here is the same issue in NPM's repos, https://github.com/npm/cli/issues/2610 the same fix helps us.
Fixes #

chore(build): dev build fix

---

components/tailored/core/fileupload/FileUpload.html
components/tailored/core/fileupload/FileUpload.less
components/tailored/core/fileupload/FileUpload.vue
components/tailored/files/uploader/Uploader.vue
config.ts

nsfw check was hogging too much memory and crashing for large files. skips check above 8MB
closes #91
reopening previous PR. I messed the old branch up, recreated
Fixes #

fix(upload): fix upload for large files

---

components/tailored/files/filepath/Filepath.less
layouts/Layout.less
layouts/files.vue

https://satellite-im.atlassian.net/browse/AP-156
Fixes #

fix(homeIconOnFiles): adjust home icon down to avoid icon clash

---

components/tailored/core/chatbar/Chatbar.html
components/tailored/core/chatbar/Chatbar.vue
layouts/chat.vue
plugins/thirdparty/persist.ts

* Fix a style bug on the chatbar when a reply is in place;
* Remove a reply when switching conversations;
* Does not persist the reply in the store;
* Focus the chatbar when hitting reply.
JIRA: AP-155
We should persist the replies when switching conversations but this needs a refactor in the way we store replies. Please open a ticket to keep track of this, thanks!

fix(chatbar): replies style and focus on reply AP-155

---

components/tailored/core/media/heading/Heading.html
components/tailored/core/media/heading/Heading.vue

Makes timer interval 1 second. Minor cleanup
Fixes # N/A

chore(timeLabel): increased interval, made label work from translations

---

package.json

Updates Cypress version from `9.1.0` to `9.1.1`

chore: update cypress version

---

components/ui/TypeHead/TypeHead.vue
pages/setup/InputAccount/InputAccount.html
pages/setup/InputAccount/README.md
pages/setup/InputAccount/index.vue
store/accounts/actions.ts

Recover account from phrases you input
Fixes # AP-15
Test Case for reviewers:
1. create an account
2. while creating an account, you should save recover phrases
3. after you register and login.. clear localStorage and go to '/'
4. input pin and click import account
5. input recover phrases you saved
6. after clicking import account you can log in with your created account

feat(import account): recover account from phrases you input

---

components/tailored/friends/nav/Nav.html
components/tailored/friends/nav/Nav.less
components/tailored/friends/nav/Nav.vue

https://satellite-im.atlassian.net/browse/AP-121
Fixes #

[AP-121]-Friend req count

---

components/tailored/core/chatbar/reply/Reply.html

If a user has a link in their name, it was being made linkable. This disables links in the chatbar reply indicator component.
Fixes #

fix(ChatReply): disable links in reply bar if user has one in their name

---

components/tailored/messaging/message/actions/Actions.html

fix wrong string on emoji reaction on chat
before 
after

fix: fix wrong string on emoji reaction on chat

---

.github/workflows/add-conflicts-label.yml

This action checks all open Pull Requests for merge conflicts and marks them with a Github label.
Once a conflict is resolved the label is automatically removed.

task: add github action for conflicts label

---

store/textile/actions.ts

maybe it was accidentally deleted
Permanent message loading icon
Fixes #

fix(loading icon): messageLoading was never being set to false

---

components/interactables/QuickProfile/QuickProfile.html
components/interactables/QuickProfile/QuickProfile.vue
components/ui/Global/Global.html
components/views/chat/group/Group.vue
components/views/chat/message/reply/Reply.vue
utilities/Messaging.ts

When you click a users picture in chat, and the quick profile appears, it should have their name/icon, and the ability to message them
Fixes # AP-268
I think all functionalities are implemented except icon.
I can't test user icon on quick profile because.. updating icon on settings/profile is not fully implemented.
We can create individual ticket for that.

feat(Quick Profile): Implement Quick Profile

---

components/views/friends/add/Add.vue

friends - account id should be cleared after friend request is sent
Fixes # AP-294

fix(friends): friends - account id should be cleared after friend request is sent

---

components/views/chat/chatbar/Chatbar.vue
components/views/chat/message/actions/Actions.vue
components/views/chat/message/reply/Reply.html
layouts/default.vue
libraries/Textile/MailboxManager.ts
libraries/Textile/encoders.ts
store/textile/actions.ts

- Displays replies in chat
- remove blue reply banner while message is sending
- clear chatbar after reply has been sent
- fix file message encoder to account for jeffs update
- restructure message encoders (with guidance from Manuel)
Fixes # AP-124, AP-243
I noticed three bugs that are somewhat tricky and maybe better suited for a separate issue:
- emoji reactions are applied to every reply of a message.
- attempting to emoji react to a reply crashes
- you can only reply to the first message of a group

fix(replies): show replies and improve UX related to sending a reply - AP-124

---

.github/workflows/add-label.yml

Adds Github Action to automatically add the `missing dev review` label whenever a PR is added

task(githubAction): add github action to add labels

---

cypress.json
cypress/integration/create-account.js
cypress/support/commands.js
package.json

- increase the timeout on cypress tests from 30s to 60s because sometimes takes a while to enter the application
- updates Cypress version
- avoid memory issue

test(Cypress): increase timeout on cypress tests

---

nuxt.config.js

- service worker caches ipfs responses like glyphs and mute/deafen/video mp3
- using StaleWhileRevalidate since ipfs sends opaque responses. If we enable CORS on ipfs, we could look into cacheFirst
N/A
https://pwa.nuxtjs.org/workbox/#enabled
- documentation recommends testing by running prod locally. I couldn't get that to work, so I just switch enabled to true in nuxt.config
- you will need to check application tab of chrome dev tools to see details about service worker

feat(cache): use service worker to cache ipfs responses

---

pages/index.vue

On desktop, when you log in the container would shift left+up, leaving whitespace.
n/a
before:

chore(login): prevent shifting of login on desktop

---

assets/styles/platforms/iOS.less
assets/styles/themes/moonless_night.less
components/views/friends/add/Add.less
mock/friends.ts
pages/friends/list/FriendsList.html
pages/friends/list/FriendsList.less

feat(Friends): combine friends routes

---

components/ui/Chat/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.vue
components/ui/Chat/Embeds/VideoPlayer/VideoPlayer.vue
components/views/chat/chatbar/reply/Reply.less
components/views/chat/enhancers/glyphs/Glyphs.html
components/views/chat/enhancers/glyphs/Glyphs.less
components/views/chat/enhancers/glyphs/item/Item.html
components/views/chat/enhancers/glyphs/item/Item.vue
components/views/chat/enhancers/glyphs/nav/Nav.html
components/views/chat/enhancers/glyphs/nav/Nav.less
components/views/chat/enhancers/glyphs/nav/Nav.vue
components/views/chat/message/Message.vue
config.ts
nuxt.config.js
store/ui/getters.ts
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts

AP-341
- added state for recently used glyphs including a counter
- removed global style that was hiding typographyText on xs devices
- limit recently used glyph array size on mobile devices
- introduce mq xs breakpoint
AP-318
- add padding to bottom of enhancers glyph list to show all
AP-264
- add small img to reply rather than string of glyph url
AP-314, AP-318, AP-264
- I'm not a good copywriter, nor do I claim to be. If anyone has something better than 'Try using some glyphs', go for it. This phrase will be displayed when recently used glyphs state is empty
- in regards to UX, do we want to close the enhancers menu after sending a glyph?

feat(glyphs): recently used glyphs functionality AP-341

---

components/views/media/Media.less

fix 'video viewers are not adjusting to size when entering fullscreen'
AP-388
-When entering to fullscreen and resize, it has some issues while resizing. we can make that as another ticket.

fix(call): fix 'video viewers are not adjusting to size when entering fullscreen'

---

components/ui/Chat/Image/Image.html
components/ui/Chat/Image/Image.vue
components/views/files/upload/Upload.vue

Blocks sending images deemed nsfw and shows an alert notifying user that file/s were not sent that were nsfw
AP-285
Alert should pop up on it's own and auto close after 5ish seconds, the user can also click the close on the alert to close before then.

fix(nsfw): don't allow nsfw images to be sent

---

plugins/thirdparty/persist.ts

Fix 'Video call modal should be removed from state so if something goes wrong with the app they don't get fake phone call notifications when they reload'
AP-351
- This needs to be tested on fresh env ( that means if you need to initialize webrtc state on localstorage before test... of course If you already stored values)

fix(call): set incoming call properties in webrtc in blacklist for vuex-persist

---

components/views/navigation/toolbar/Toolbar.html

Disable call buttons after it is clicked until hang up or error happened
AP-348

fix(call): disable call buttons after it is clicked until hang up or error happened

---

components/views/chat/chatbar/Chatbar.vue

Fix 'When clicking back in a message, anything typed will be added to the end of the message instead of where user clicked'
AP-55

fix(chat): fix 'anything typed will be added to the end of the text instead of where user clicked'

---

components/views/chat/message/reply/Reply.vue
utilities/Messaging.ts

- render replies for all messages. They were being stored in textile properly. for any 'new message' (at the beginning of a new group based on time or message sender), replies and reactions were being set to []. Now they're set based on info coming from textile.
- Fix type name to reflect past updates
AP-271
- responses are still buggy. Replies will have the same responses as their parent messages

fix(replies): render replies for all messages AP-271

---

utilities/Messaging.ts

Pretty specific use case, but I noticed something was still buggy after mine and David's fixes earlier.
Emoji reacts to a reply of a message which _is not_ the first message of a group were still not working.
With this, two reactions for 'reply test' will now appear

fix(reaction): fixes emoji reacts for reply messages of inner messages

---

components/ui/Chat/Scroll/Scroll.less
components/views/media/Media.less

Fix ' When the user hovers over the Settings icon in the media viewer half of the Settings label will be layered behind the Sidemenu'
AP-412

fix(media): fix settings tooltip layered issue AP-412

---

components/views/chat/enhancers/Enhancers.vue
components/views/chat/enhancers/glyphs/item/Item.vue

Fix Emoji/Glyph menu should close after a user has selected and sent an emoji. (See discord for an example)
AP-488
For now when send emoji, it does not appear in chatbar and that's what David is currently working.

fix(enhancer): close enhancer(emoji,glyph) after choose

---

assets/styles/framework/breakpoints.less
components/interactables/Tabs/Tabs.html
components/interactables/Tabs/Tabs.less
components/interactables/Tabs/Tabs.vue
components/interactables/Tabs/types.d.ts
components/ui/Global/Global.html
components/ui/HorizontalRule/HorizontalRule.vue
components/ui/Popups/Error/Error.less
components/ui/User/State/State.less
components/ui/User/State/State.vue
components/views/chat/enhancers/Enhancers.less
components/views/servers/create/Create.less
components/views/user/create/Create.less
components/views/user/profile/Profile.html
components/views/user/profile/Profile.less
components/views/user/profile/Profile.vue

- backbone of the profile modal (fully responsive) with..
- mock profile images (pull real data after it's added to store)
- real user name, status, and picture
- generic tab component (can be reused elsewhere)
- refactor UserState size so I can use large version on profile
- fix unrelated margin bug for enhancers mobile
- adjust a few css files to use breakpoint variables rather than hard coded pixel values
AP-507

feat(profile): profile modal responsive layout AP-507

---

components/views/settings/Sidebar.vue
components/views/settings/modal/Modal.html
components/views/settings/pages/privacy/Privacy.html
components/views/settings/pages/privacy/index.vue

Create privacy settings tab like below screen
The embeds option is currently available in ‘Network’ in settings, and needs to be relocated, the others are not and need to be added.
Disable the ‘register username’ toggle
AP-485

feat(privacySettings): create privacy settings tab

---

components/views/user/create/Create.vue
config.ts

- block nsfw profile pictures on account registration
- block pictures that are too large to be NSFW scanned. I think hogan said we may ultimately break the nsfw check off to a separate service to allow for larger files to be scanned. Although, profile pic ultimately gets cropped and scaled down quite a bit anyway, so allowing larger files here doesn't seem mission critical.
- fix minor linter suggestion on config file
AP-503

feat(profilePic): block nsfw profile picture uploads AP-503

---

libraries/ui/Alerts.test.ts
libraries/ui/Alerts.ts

- lint ui/Alerts
- remove useless constructor, 
- and 100% coverage for libraries/ui/Alerts.ts unit test
AP-565

add(jest): 100% coverage for libraries/ui/Alerts.ts unit test

---

libraries/SoundManager/SoundManager.test.ts
libraries/SoundManager/__snapshots__/SoundManager.test.ts.snap

Add unit tests (100% coverage) for the SoundManager unit test.
AP-139
The `this.sounds[sound].play()` returns two weird `console.error`:
I did some googling and came across [this](https://stackoverflow.com/questions/51829319/how-to-mock-video-pause-function-using-jest/51831366), to which I tried to add to the code but it didn't work so I just commented it out for further debugging!
I think it's a particular problem to` .play()` because other units in the test suite are written identically and yet only `.play()` have those two console errors:

add(jest): 100% coverage for SoundManager unit test

---

store/webrtc/actions.ts
store/webrtc/mutations.test.ts
store/webrtc/mutations.ts

Omitted the redundant `setConnectedTime` with `updateCreatedAt` does the exact same thing, as per the discussion on #1152 
AP-606

fix(webrtc): replace setConnectedTime with updateCreatedAt

---

.eslintrc.js

- ignore cypress folder and package.json when running eslint

chore(eslint): improve eslint

---

components/views/files/upload/Upload.html
components/views/files/upload/Upload.vue

If you try to upload the same file twice from the chatbar, the first time works fine but then if you remove the preview and try to re-upload it the preview won't show, and this PR fix this.
AP-649

fix(upload): upload same file twice second preview not showing

---

components/interactables/Select/Select.less
components/interactables/Select/Select.vue
components/interactables/Switch/Switch.less
components/views/settings/pages/personalize/Personalize.html
components/views/settings/pages/personalize/index.vue

Themes - the flair dropdown be deactivated until the user selects the moonlight theme
deactivate flair dropdown until selects moonless night and set the satellite as default.
AP-424

fix(Theme): deactivate flair dropdown until selects moonless night

---

jest.config.js

Adds ignored folders on jest.config.js to avoid spam when running the jest coverage command
before
after

chore(jest): improve jest config

---

components/views/settings/profile/card/Card.html
locales/en-US.js

… off
on settings/profile page, search location, and language multi-select dropdown, when no search result, the message is cut off. put custom no result message instead of default one to fix this issue.
AP-310

fix(ui): update locale on settings/profile 

---

jest-setup.js
jest.config.js
libraries/Files/FilSystem.ts
libraries/Files/FileSystem.ts
libraries/Files/abstracts/Item.abstract.ts
libraries/Files/remote/abstracts/RFM.abstract.ts
libraries/Files/remote/interface/RFM.interface.ts
libraries/Files/remote/textile/Bucket.ts
libraries/Files/test/Bucket.test.ts
libraries/Files/test/FSImport.test.ts
libraries/Files/test/FilSystem.test.ts
libraries/Files/test/FileSystem.test.ts
plugins/local/classLoader.ts

- TextEncoder, TextDecoder don't exist by default in jsdom. needed to add or test would fail
- fix import and improve typing for FS export
- tests laid out in JIRA
- add init to classLoader for project
AP-468
- typescript has its own FileSystem interface, so we either need to rename or be careful with imports

feat(bucket): add methods in Bucket retrieve Files Manager exports

---

components/views/friends/add/Add.vue
components/views/friends/friend/Friend.html
components/views/friends/friend/Friend.vue
locales/en-US.js
pages/friends/list/FriendsList.html
store/friends/actions.ts
types/ui/friends.d.ts

- show list of outgoing friend requests
AP-702

feat(friends): display outgoing friend requests after send

---

components/views/settings/pages/storage/Storage.html
components/views/settings/pages/storage/index.vue
locales/en-US.js
store/settings/actions.ts
store/settings/types.ts

implement clear localstorage and indexed db feature by clicking on "clear local storage" button in settings
[AP-700](https://satellite-im.atlassian.net/browse/AP-700)

feat(settings): add clearLocalStorage action

---

components/typography/NumberedWord/NumberedWord.less
pages/setup/ImportAccount/ImportAccount.less

on most of mobile devices, top padding of import account page is very narrow, this PR adds more to padding of import account page. and yes, close button of word phrase lacks a bit padding, so add more gap.
AP-281

fix(ui): fix padding issue on importAccount page

---

components/views/chat/chatbar/Chatbar.vue
components/views/chat/conversation/Conversation.vue
components/views/chat/group/Group.vue
components/views/group/Group.vue
components/views/group/aside/Aside.html
components/views/group/aside/Aside.vue
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.vue
config.ts
layouts/chat.vue
libraries/Textile/GroupChatManager.ts
libraries/Textile/TextileManager.ts
libraries/Textile/schema.ts
libraries/WebRTC/Wire.ts
mock/groups.ts
pages/chat/groups/Group.html
pages/chat/groups/_id.vue
store/textile/actions.ts
store/textile/mutations.ts

create a groupChat manager to create separate collections on a thread, allow sending messages, listening to the collection for changes, eventEmitters for testing I presume
AP-660
EDIT: Testable now. 3 Groups are hardcoded for testing. Users will show as unknown unless it's your user. There are also other bug's and features missing currently. Most have been identified in AP-732 -> AP-744

feat(groupChatManager): create a groupChat manager to create separate collections on a thread

---

components/views/files/upload/Upload.vue

https://satellite-im.atlassian.net/browse/AP-113
Upload modal changes when switching between chats and preserves pending uploads. No longer uses store due to store size limitations
changed the way uploads work so that pressing the upload button again with pending uploads will add to the list instead of replacing the list of pending uploads. However, line 99 of Upload.vue checks if over 8 files have been selected and throws an error if this is the case, and I'm not sure if this should be updated to check the count of files already in the list as well.

feat(chatImageUpload): have images persist in each chat

---

components/views/chat/group/Group.vue

Fixes an issue that happens on the message group component when a friend is not found.
AP-772
Try to write in a group chat with 2 accounts that are friend with each other

fix(MessageGroup): fix group picture when friend is not found

---

components/views/settings/modal/Modal.less

on Samsung A71, bottom part of settings modal is cut off, this PR just adds more bottom padding on settings modal
AP-677

fix(ui): fix mobile bottom padding cut off on settings modal

---

libraries/Solana/FriendsProgram/FriendsProgram.layout.test.ts
libraries/Solana/ServerProgram/ServerProgram.layout.test.ts
libraries/Solana/Solana.test.ts
libraries/SoundManager/SolanaManager.test.ts
libraries/Textile/Utils.test.ts
libraries/ui/Commands.test.ts
libraries/ui/Friends.test.ts
store/audio/actions.test.ts
store/audio/mutations.test.ts
store/audio/state.test.ts
store/chat/mutations.test.ts
store/chat/state.test.ts
store/dataState/state.test.ts
store/files/actions.test.ts
store/files/mutations.test.ts
store/files/state.test.ts
store/media/actions.test.ts
store/prerequisites/getters.test.ts
store/prerequisites/mutations.test.ts
store/prerequisites/state.test.ts
store/search/mutations.test.ts
store/search/state.test.ts
store/settings/mutations.test.ts
store/video/mutations.test.ts
store/video/state.test.ts
utilities/ConsoleWarning.test.ts
utilities/Messaging.test.ts
utilities/SimpleWrap.test.ts
utilities/io-ts.test.ts

- Removes not needed `import { expect } from '@jest/globals'` on Jest tests
- Minor linting

test(jest): remove not needed imports + minor lint

---

store/media/actions.test.ts

AP-779
I wrote this unit test based on https://github.com/lmiller1990/vue-testing-handbook/blob/master/demo-app/tests/unit/actions.spec.js which were testing https://github.com/lmiller1990/vue-testing-handbook/blob/master/demo-app/src/store/actions.js, let me know if I made a mistake in how I'm testing these code lines!

feat(jest): 100% code coverage for store/media/actions.test.ts

---

pages/friends/list/FriendsList.html
pages/friends/list/index.vue
types/ui/friends.d.ts

https://satellite-im.atlassian.net/browse/AP-713?filter=-1
- alphabetically sort outgoing friend requests. If we want to sort by letter into groups, let me know. from a UX perspective, I don't think it's necessary. it's nice to have on the friends list since a user may have many friends. I imagine they won't have too many outgoing friend requests at one time though
AP-713

feat(outgoingFriends): alpha sort to outgoing friends AP-713

---

layouts/chat.vue

If a user is in chat and swipes over to the Sidebar, the keyboard was not minimized. This PR fixes this by blurring active element 
AP-688

fix(mobile): minimize keyboard when swipe sidebar

---

libraries/ui/ReleaseNotes.test.ts
libraries/ui/ReleaseNotes.ts
package.json

- Add dependency: `jest-fetch-mock`
- Remove uncoverable line (shown below)
- 100% Jest coverage for libraries/ui/ReleaseNotes.ts
The `responseBody` variable will be undefined every time, hence `!responseBody` will be `!undefined` which evaluates to `true`. Essentially the code was something like this:
```
if (true) {
...
}
```
Since there was no way I could think of to cover the last line (line 19), I removed it. Let me know if it was not the right call.
AP-569

feat(jest): 100% coverage for libraries/ui/ReleaseNotes.ts

---

libraries/Security/Security.test.ts

feat(jest): 100% coverage for libraries/Security/Security.ts

---

components/views/files/upload/Upload.vue

assigns the address in the store for uploaded images to be the one from the time the upload is initiated, not the one at the time the file has finished processing.
Previously, changing chats while an image is in the NSFW check phase would cause it to get added to the wrong chat's files array. This fixes this.
the store solution @josephmcg used for upload persists is a nice one that solves some problems I couldn't figure out how to work around, and investigating how his solution worked is what led me to finding this bug that would've affected both our solutions

fix(imageUpload): fixes uploaded images being added to the wrong chat when changing during NSFW check

---

components/views/media/Media.html
components/views/media/Media.vue
layouts/Layout.less

Adds back again the "connecting animation", whenever a user got connected it stops the animation.
Fixed media width (now it's fullwidth)
AP-794
I know for sure there's a cleaner code... If someone has any idea, let me know that i change my code! 👍 
By fixing media width, i found out the blink was still on after the other user joined the call, so i removed that too. (my bad i didn't open a new ticket for that)

chore(media): when a track is found, called one stops blinking

---

store/ui/actions.test.ts
store/ui/actions.ts

Self-explanatory. Still a work in progress on that particular `activateKeybinds` function.
AP-778

feat(jest): 88% coverage for store/ui/actions.ts

---

components/views/friends/add/Add.html
components/views/friends/add/Add.vue

Hides scan QR code section
before
after

chore(update): hide scan qr friend code

---

components/views/settings/profile/card/Card.html
components/views/settings/profile/card/Card.vue

Hides language section on the profile
before
after

chore(update): hide language section on profile

---

components/views/settings/pages/audio/Audio.html
components/views/settings/pages/audio/index.vue

Hides capture mouse section
before
after

chore(update): hide capture mouse section

---

components/views/settings/pages/storage/Storage.html
components/views/settings/pages/storage/index.vue

Hides export storage button.
before
after

chore(update): hide export storage button

---

components/views/chat/message/actions/Actions.html
components/views/chat/message/actions/Actions.vue

Hides pin icon on chat.
before
after

chore(update): hide pin icon on chat

---

components/views/settings/Sidebar.vue

Hides mock and tweak section
before
after

chore(update): hide mock and tweak section

---

store/files/__snapshots__/actions.test.ts.snap
store/files/actions.test.ts
store/files/actions.ts

In light of https://github.com/Satellite-im/Core-PWA/pull/1655 in which Sara said that the test was taking too long and ended up removing it, I did some digging and found this Promise timeout that I'm not sure why it's there. I removed it and tested back the coverage and it's working well without it being as slow as how it used to be.
Was once resolved, but using it again: AP-571

feat(jest): add back store/files/actions unit test

---

mock/tests/__snapshots__/messages.test.ts.snap
mock/tests/messages.test.ts

feat(jest): 100% coverage for mock/messages.ts

---

store/sounds/__snapshots__/actions.test.ts.snap
store/sounds/actions.test.ts

feat(jest): 100% coverage for store/sounds/actions

---

libraries/IndexedDB/index.test.ts

Self-explanatory. The reason the coverage is not higher at the moment is that I need an actual mock (and an address) to simulate the forEach loops; I am currently asking David C for it. 
AP-892

feat(jest): 42% coverage for libraries/IndexedDB AP-892

---

store/textile/actions.test.ts

Self-explanatory. We have a long way to go to work on this file, one of them is by getting some of the mocks ready for the units we need to test.

feat(jest): kickstart unit test for store/textile/actions

---

components/views/files/aside/Aside.html
components/views/files/aside/Aside.less
locales/en-US.js

- change button color to gray
- add tooltip
AP-911
- I didn't set button to disabled because it makes the tooltip very difficult to read

fix(filesUpgrade): dull the storage space upgrade button

---

components/views/files/controls/Controls.vue
locales/en-US.js

feat(files): prevent upload if file size is 0 bytes

---

libraries/Files/FilSystem.ts
libraries/Files/TextileFileSystem.ts
libraries/Files/types/file.ts

🔴 **this will remove any current filesystem data since import is based on a valid type**
- type support for common file types
- switch type check on import to support more dynamic enums
- previous check was only checking the key, rather than value. not scalable due to MIME types structure
- add basic file types to enum
AP-906
- this will NOT work retroactively. type is registered upon upload

feat(files): file type support for common image, archive types

---

components/interactables/ContextMenu/ContextMenu.vue

Fixes an error with the context menu when clicking outside of the viewport
Not sure if there is a specific issue for this, but I fixed this while testing [AP-973](https://satellite-im.atlassian.net/browse/AP-973)
I was seeing an error in the console when clicking on dev tools or clicking back into my code editor and this change resolved it

fix(contextMenu): fix contextMenu error when clicking out of bounds

---

components/views/files/filepath/Filepath.less
components/views/files/view/View.less

- fix mobile issue where text would overlap image
- limit width of file info so buttons don't wrap
AP-962

fix(files): reduce max height of fullscreen file view

---

store/textile/actions.ts

Fixes an issue with the message loading state where, when a user sends a message but the message fails to send (for example, when sending a message with a textile account key instead of user group key), that conversation is stuck in a loading state for that user indefinitely.
Not sure if this is related to another ticket yet, but will search for one.
For now, this was found while working on [AP-973](https://satellite-im.atlassian.net/browse/AP-973)

fix(storeTextileActions): reset message load state on init

---

components/views/navigation/toolbar/Toolbar.less
layouts/Layout.less

- after hiding sidebar, clicking the toggle show sidebar wouldn't work (while in chat)
AP-976

fix(collapse): allow sidebar toggle in chat

---

utilities/Messaging.test.ts
utilities/Messaging.ts
utilities/__snapshots__/Messaging.test.ts.snap

Rewrite the setInterval problem related to the unit test of Messaging.ts, while also additionally adding tests to the other parts of the code.
AP-730

feat(jest): 93% coverage for utilities/Messaging.ts

---

components/ui/Chat/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.vue

Embedded videos would crash on this URL: https://www.youtube.com/watch?t=81&v=AdtHPZUkKWs&feature=youtu.be because of the way we were parsing youtube.com and youtube.be
On dev currently you will see this video does not embed, and gives an error message that crashes on local dev
No ticket

fix(embeddedVideo): fix parsing youtube video url

---

components/ui/Progress/Progress.vue
components/views/files/aside/Aside.html
components/views/files/aside/Aside.vue
components/views/files/controls/Controls.vue
config.ts
libraries/Files/FilSystem.ts
locales/en-US.js
plugins/thirdparty/filesize.ts
utilities/Filesize.ts

- add getter to calculate the total size of all tracked files
- update files aside to track your files usage (amount and progress bar)
- prevent further uploads if you're out of room
AP-899, AP-910
- Originally wanted to use a computed for the progress bar, but it would cause an infinite render issue. opted for watch instead

feat(filesLimit): handle if user goes over size limit

---

components/views/files/controls/Controls.vue
locales/en-US.js

- avoid bug where folders cannot be opened
- Couldn't troubleshoot this one quickly. Probably a better longterm solution if we figure out why / causes an issue in folder name. This will be a band-aid for now
AP-917

fix(files): prevent folder name issue

---

mock/tests/__snapshots__/servers.test.ts.snap
mock/tests/servers.test.ts

Self-explanatory.
No tickets at the moment

feat(jest): 100% coverage for mock/servers.ts

---

components/views/files/list/List.html
components/views/files/list/List.less
components/views/files/list/List.vue
components/views/files/row/Row.html
components/views/files/row/Row.less
components/views/files/row/Row.vue

- fix overflow scroll issue
- create separate Row component
- set click event to the entire row
- context menu on row rclick or kebab menu click. options are still todo. I made a ticket for it
AP-898
- responsive fixes are in other tickets

feat(files): Improve UX for files list view

---

components/views/files/controls/Controls.html
components/views/files/controls/Controls.less
components/views/files/controls/Controls.vue

- add small closable box for error messages
AP-901
- closing errors when you open a folder is kind of difficult due to the way components are setup. Is it ok now that it's closable?
- I asked Liz about specific error messages. If she wants to change phrasing we can do it here or in a separate ticket.

feat(files): improved files error messages

---

components/ui/Global/Global.vue
components/views/media/Media.html
components/views/media/Media.vue
components/views/media/actions/Actions.vue
components/views/navigation/sidebar/live/Live.vue

Stops users from being able to be in 2 calls by hanging up current call when accepting a new call
AP-750

fix(webrtc): hangs up call when accepting a new call

---

components/interactables/Search/Result/Result.vue
components/views/chat/chatbar/footer/is-connected/Connected.html
components/views/chat/chatbar/footer/is-connected/Connected.vue
components/views/navigation/sidebar/live/Live.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.vue
middleware/authenticated.test.ts
plugins/thirdparty/persist.ts
store/getters.test.ts
store/webrtc/__snapshots__/state.test.ts.snap
store/webrtc/actions.ts
store/webrtc/mutations.test.ts
store/webrtc/mutations.ts
store/webrtc/state.ts
store/webrtc/types.ts
utilities/Hounddog.test.ts
utilities/Notifications.ts

Before we were storing a single peer id in the state, so the last peer connection you set, if it was active, showed all of your connections as active. If that connection closed, it showed all of your dm's as not connected. Sorry the video is so long.
This update stores that data as an array. As connections are added or removed, that connection is added or removed from a list, so when you go to different users it shows the correct webrtc connection status, per user.
To test, on dev I created three users:
User A (regular Brave browser)
User B (incognito Brave Browser)
User C (regular chrome browser)
After this update you should see users appear online independent from each other.
Please use the local webtorrent when testing for the best results. …

fix(connectedPeers): fix issue showing connected peers

---

jest.config.js
libraries/Files/TextileFileSystem.ts
libraries/Files/test/Bucket.test.ts
libraries/Files/test/Directory.test.ts
libraries/Files/test/FilSystem.test.ts
libraries/Files/test/TextileFileSystem.test.ts
store/textile/__mocks__/skaler.js
store/textile/actions.test.ts

Resolves Skaler import error by applying what was written on https://stackoverflow.com/questions/70829503/jest-gives-an-error-syntaxerror-unexpected-token-export-for-node-modules-mi
AP-1061

fix(jest): resolved Skaler error import jest

---

components/views/media/Media.vue

Fix 'Mobile - Media Viewer is smaller than it is when answered after exiting fullscreen'
AP-1063

fix(media): fix media viewer issue after exiting fullscreen

---

components/views/files/controls/Controls.less

- if the error messages were long/numerous, the close icon could shrink since it's displayed with flex. this forces full size all the time

fix(files): show full size icon all the time

---

libraries/Files/test/TextileFileSystem.test.ts
utilities/assets/svg-image.svg

The image above is captured before this PR was made; the error `file.arrayBuffer is not a function` occurred because of the change being made in the Fil constructor. This error was able to be resolved by passing in a dummy file, this was advised by Joe.
AP-1062
Soon we will be able to cover more (the HEIC code lines). For now I think this is sufficient, though do let me know if it is not.

feat(jest): 58% coverage for TextileFileSystem.ts

---

libraries/Files/Directory.ts
libraries/Files/abstracts/Item.abstract.ts

- size getter for directories
AP-934

feat(files): size for folders list view

---

cypress/integration/privacy-page-toggles.js
cypress/support/commands.js

- Added test into privacy-page-toggles.js cypress script to validate that registry public toggle is locked
- Updates to existing tests on privacy-page-toggles.js cypress script to consider that registry public toggle is locked
- Updates to cypress commands to consider the registry public toggle as locked, which will fix the create account cypress tests
- Small change into cypress commands to add a timeout for status input on account creation
- Change on cypress command for visiting root page to ensure that pin data is removed before visiting main page when creating/importing an account 
AP-1029 and AP-1071
It is not possible to assert the hover image displayed when the mouse pointer is over the …

test(cypress): changes to privacy toggle and create account tests for registry public toggle

---

libraries/Files/test/Directory.test.ts

Self-explanatory; this is an increase.
Using the `AP-549` ticket again :)

feat(jest): 100% coverage for Directory.ts

---

components/interactables/ContextMenu/ContextMenu.vue
components/ui/Chat/Scroll/Scroll.vue
components/views/chat/group/Group.vue
components/views/chat/message/Message.vue
components/views/media/actions/volume/Volume.vue
components/views/media/heading/Heading.vue
components/views/settings/pages/audio/index.vue

- some components are using Vue3 syntax (beforeUnmount), probably changed by a linter while we had incorrect config

fix(lifecycleHook): fix Vue3 syntax

---

mock/tests/__snapshots__/users.test.ts.snap
mock/tests/users.test.ts

feat(jest): 100% coverage for mock/tests/users.ts

---

.github/workflows/cypress.yml

Adds Github Action to run Cypress on every PR
flow
- checkouts the code
- installs submodules
- `yarn`
- creates `.env` file same as we use locally
- `yarn dev` and runs Cypress on Chrome, on localhost:3000

chore(cypress): add github action

---

components/views/files/controls/Controls.vue
config.ts
libraries/Files/types/file.ts
libraries/Security/Security.test.ts
libraries/Security/Security.ts
utilities/NSFW.ts

- only try nsfw scan if its a valid format(embeddable images or videos)
- fix false positives for TIFF and other un-embeddable images
- use async await in favor of promises
AP-807
- I know we typically avoid else, but it saves us from repetition in this case
- `const model = await nsfwjs.load()` is declared in both the if and else. If I placed it above, I would get weird errors

fix(nsfw): nsfw check valid files, allow unscannable/unembeddable files through

---

libraries/Solana/Solana.test.ts
libraries/Solana/__snapshots__/Solana.test.ts.snap

- Adds more coverage on`libraries/Solana/Solana.test.ts`
- Removes not used import
before
after

chore(jest): add more coverage on Solana.test.ts

---

.github/workflows/cypress.yml
components/ui/UpdateModal/UpdateModal.html
components/views/chat/enhancers/Enhancers.html
components/views/friends/add/Add.html
libraries/SearchIndex/index.test.ts
libraries/Textile/BucketManager.test.ts
libraries/WebRTC/TracksManager.test.ts
libraries/WebRTC/__snapshots__/TracksManager.test.ts.snap
libraries/ui/Cursor.test.ts
libraries/ui/__snapshots__/Cursor.test.ts.snap
pages/friends/list/FriendsList.html

- Minor linting on `.github/workflows/cypress.yml ` and other files
- Removes not used test on `libraries/Textile/BucketManager.test.ts`
- Adds testing classe - `BucketManager.default.fetchIndex` on `libraries/Textile/BucketManager.test.ts`
- Adds more testing on `libraries/WebRTC/TracksManager.test.ts`
- Adds testing classe - `Cursor.default.setCurrentCursorPosition` on `Cursor.test.ts`

chore(updates): add more jest tests + minor lint

---

components/views/files/row/Row.html
components/views/files/row/Row.less
components/views/files/row/Row.vue

- flair color for icons. take advantage of global flair enforcement class already in grid view
- fix archive file check, unrelated but minor.
- I opened a ticket to clear up differences in archive icons between grid/list view. will need to consult with Liz for that one
AP-1110

fix(files): add flair color to list view file icons

---

components/views/files/view/View.less

- fix issue where fullscreen image view in filesystem would be shifted based on the sidebar toggle status
AP-913
looked liked this before
- should be easy to cleanup with Vue3 teleport later

fix(files): fullscreen view swiper issue

---

libraries/Files/test/TextileFileSystem.test.ts

Improve the naming system
AP-1087

feat(jest): improve naming on TextileFileSystem.test.ts

---

components/mixins/UserPermissions/__snapshots__/index.test.ts.snap
components/mixins/UserPermissions/index.test.ts
components/mixins/UserPermissions/index.ts

Self-explanatory. The remainder of the code is RTC stuff and from what I have heard they will undergo changes hence I did not cover it.
AP-546

feat(jest): 75% coverage for components/mixins/UserPermissions

---

components/views/navigation/toolbar/Toolbar.html
cypress/integration/chat-features.js
cypress/integration/chat-top-toolbar.js
cypress/integration/snapshots-test.js
cypress/support/commands.js

- Add cypress tests for chat toolbar icons active and with coming soon status
- Add cypress commands to validate hovering on icons
- Implemented the new command in one existing cypress test for Send Money icon on chat-features.js
- Placed send message, send emoji and edit message validations in different test blocks instead of having the 3 validations in the same it block
- Added data-cy attributes to elements on components/views/navigation/toolbar/Toolbar.html
AP-631 and AP-1031
Cypress Video for chat-top-toolbar.js:
https://user-images.githubusercontent.com/35935591/158925875-413c79c9-b0eb-4a73-b383-d96f08959b25.mp4
Cypress Video for chat-features.js: …

test(cypress): add chat toolbar cypress tests

---

utilities/Logger.test2.ts

Increases coverage on Logger.ts
before
after
the 2 tests will be converted into 1 after

chore(jest): increase coverage on Logger.ts

---

components/ui/SimpleList/SimpleList.vue
components/views/files/aside/Aside.html
components/views/files/aside/Aside.less

- was using UiSpacer, bad css practice to create empty elements with height. better to use margin/padding
AP-914

update(filesAside): fix css on files aside

---

components/views/chat/message/Message.vue
locales/en-US.js

- show edit for your own text messages
- do not show on other types 
- show image related options for images - any sender (still no functionality. will be implemented separately)
- commented out `copy link` for now, that should be a separate ticket
AP-1091
AP-1095
AP-1096
- I jumbled the order around, adding conditional options at the bottom. That way the position of static options remains the same and a user can click via muscle memory. let me know if you'd like to adjust these

fix(messages): context menu shows correct options

---

components/views/files/file/File.html
components/views/files/file/File.vue
components/views/files/view/View.html
locales/en-US.js

- remove 'pinned' button from file view after Liz confirmed files will not use pinned
- use Archive icon in both grid and list view
AP-1121

fix(files): standardize archive icon

---

package.json
plugins/thirdparty/swiper.ts

Updates swiper lib to the latest version due to
was also needed to update the imports due to this error when building
now is fixed

chore(update): update swiper due to security alert

---

libraries/SatelliteDB/SatelliteDB.test.ts

Increase coverage
No tickets IIRC

feat(jest): 100% coverage for libraries/SatelliteDB/SatelliteDB

---

store/chat/mutations.test.ts

feat(jest): 100% coverage for store/chat/mutations

---

utilities/HotkeyList.ts
utilities/__snapshots__/HotkeyList.test.ts.snap

add meta + l to blocked mac shortcuts
[AP-1144](https://satellite-im.atlassian.net/browse/AP-1144)

fix(keybinds): add meta + l to blocked mac shortcuts

---

components/views/files/file/File.vue
components/views/files/row/Row.vue
config.ts

- accurately show archive icon in filesystem, even in case of rename. uses new utility function added in a separate PR
- clean up type errors, improve doc
- remove unused regex from config
AP-1155
- context menu currently shows type errors, will be cleaned up when this merges https://github.com/Satellite-im/Core-PWA/pull/2643

fix(files): better archive file check

---

components/ui/TypeAhead/TypeAhead.html
components/ui/TypeAhead/TypeAhead.less
components/ui/TypeAhead/TypeAhead.vue
pages/setup/ImportAccount/ImportAccount.html

Implements a typeahead filter on the import account page
AP-322
Made some changes to the active item logic:
- Only one item can be active, mouse and keyboard will now take focus from one another
- Pressing enter immediately after typing will now select the first match in the list
extends #2179

feat(importAccount): typeahead support using searchindex

---

components/views/chat/message/Message.vue
components/views/files/upload/Upload.vue
locales/en-US.js
store/ui/types.ts

- reopened PR after some minor refactoring https://github.com/Satellite-im/Core-PWA/pull/2520
- copy image via clipboard API which only accepts png
- if png, copy. if other embeddable image format, convert to png with canvas
- change heic conversion in chat to png rather than jpeg. this skips a conversion step on copy
- switch ContextMenuItem definition so we don't need to do `as string` every time we use it
AP-1080
https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem#writing_to_clipboard
we need the blob to write to the clipboard. Initially I was fetching it during the copy method, but it felt very slow. Decided to fetch the blob on mounted instead. It will only convert to png one time …

feat(chat): copy image

---

layouts/Layout.less

Fixes chat scroll while the user is on call and allow him to see old messages
AP-1209
It's not clear from the ticket if the bar appears or not.
The thing that i noticed, is that when the messages go behind the modal, it's impossibile to go read them (that's the thing that got fixed 🔨 ).

chore(chat-scroll): scroll fixed while on call

---

cypress.json
cypress/integration/chat-features.js
cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/chat-top-toolbar.js
cypress/integration/mobiles-responsiveness.js
cypress/integration/pin-unlock-validations.js
cypress/integration/privacy-page-toggles.js
cypress/support/commands.js

- Removing skipped instruction for all cypress tests except mobiles-responsiveness and snapshots
- Replacing should.be.visible for should.exist in chat elements for which cypress takes some time to scroll into view
- Small change on chat text validations for cypress test for the space/emoji chars count
- Changing the type enter for clicking into send message for cypress tests, since sometimes cypress fail when sending type command twice
- Small changes on two cypress commands for replies
- Changing numOfTestsToKeepInMemory to zero since is the setup used locally
None
Sending this as a draft to see if the tests work in CI

test(cypress): small improvements to cypress scripts

---

components/views/files/controls/Controls.vue
config.ts
libraries/Files/Directory.ts
libraries/Files/Fil.ts
libraries/Files/FilSystem.ts
libraries/Files/TextileFileSystem.ts
libraries/Files/abstracts/Item.abstract.ts
libraries/Files/errors/Errors.ts
locales/en-US.js
pages/files/browse/index.vue

- enforce invalid name rules on file/directory creation and rename
- refactor name validation to a separate method which can be called from the constructor
- move Directory name validation inside constructor rather than inside of Controls.vue
- allow files of the same name to be located in different directories. Rename update switch to uuid for the bucket identifier rather than name, so now it's allowed. Still preventing same name inside a directory
AP-1179
- I want to improve file Upload validation in a separate ticket. Right now I'm checking on the front end before attempting to upload. I would much rather move it to the constructor, but it would be fairly involved
- …

fix(files): rename quality of life update

---

store/ui/mutations.test.ts

self-explanatory.
AP-781
This code doesn't seem to be doing anything by Eric's analysis. If I cover it again (see the skipped test suite on line 2160) the coverage will increase to 82%. If we ignore the whole addReaction code, we will reach 100% coverage.

feat(jest): 78% coverage for store/ui/mutations

---

components/views/chat/enhancers/glyphs/nav/Nav.html
components/views/chat/enhancers/glyphs/pack/Pack.html
cypress/integration/chat-glyphs-validations.js
cypress/support/commands.js

- Add cypress tests for glyphs on chats
- Improved cypress command for sending glyphs, so we can pass the pack and item indexes as arguments
- Added data-cy attributes to glyph pack and nav bar elements used in the new cypress test for glyphs
AP-635
All test specs passing after this change:
Cypress Video:
https://user-images.githubusercontent.com/35935591/161830470-7b3b6041-8f03-4462-b1d3-af01edcad36d.mp4

test(cypress): add tests for glyphs

---

components/views/files/list/List.html
components/views/files/list/List.less
components/views/files/list/List.vue
components/views/files/row/Row.html
components/views/files/row/Row.vue
libraries/Enums/enums.ts
libraries/Enums/types/fileSort.ts
pages/files/browse/Browse.html
pages/files/browse/index.vue
store/ui/__snapshots__/state.test.ts.snap
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts
types/files/file.ts

- default sort is ascending on modified
- sort icon indicating selected category and asc/desc status
- click column header to toggle asc/desc or change category
- added sort to store for persistence
AP-1055
- We could also try doing the sort from the Class side rather than in the component. thoughts?
- responsive isn't perfect on small desktop. the files aside takes up a lot of space. this should be a separate ticket

feat(files): sort list view columns

---

components/views/chat/message/Message.vue

- context menu was incorrectly showing options for 'copy image' & 'save image` on un-embeddable images
- remove copy image from gifs because it copies a still png
AP-1295, AP-1290

fix(chat): rclick options for non-embeddable images

---

components/views/files/controls/Controls.vue
components/views/files/rename/Rename.vue
libraries/Files/Fil.ts
libraries/Files/errors/Errors.ts
locales/en-US.js

- change enums to their translation string
- switch all try catch file system calls to translate the received error string, rather than interpret as plain text
- throw file size error from Fil constructor. this won't be triggered at the moment, but later refactoring will use this
AP-1294
- This cleans up Directory and item rename errors. Adding a new Fil will still validate in the Controls component. I have a ticket for fixing this later

update(files): fs errors are translation friendly

---

cypress/integration/chat-pair-features.js

- Add cypress tests inside chat-pair-features.js for timestamp validations
- Small improvement to regex used to assert the timestamp text
AP-630
Cypress Video:
https://user-images.githubusercontent.com/35935591/162078272-d7331025-6348-4ed1-86a8-eaab95a2c39a.mp4

test(cypress): add timestamp validations for chat

---

components/views/files/list/List.vue
libraries/Files/Directory.ts
pages/files/browse/index.vue

- this bug was introduced from files sort. I was deep cloning the directory info on the component side, so any rename/favorite wasn't going through correctly.
- now I'm returning a fresh array created from current directory _children map based on current sort config
AP-1366

fix(files): reactivity issue on files operations

---

components/views/glyphs/Glyphs.html
components/views/navigation/sidebar/status/Status.html
cypress.json
cypress/integration/chat-features.js
cypress/integration/chat-images-validations.js
cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/chat-top-toolbar.js
cypress/integration/mobiles-responsiveness.js
cypress/integration/pin-unlock-validations.js
cypress/integration/privacy-page-toggles.js
cypress/support/commands.js

- Added scenarios to validate sending links on chat-text-validations.js
- Adding a new cypress command validateURLOnClick to test the links in chat
- Adding data-cy attributes to glyph modal title and username in chat window
- Using the paste command for first scenario on chat-text-validations cypress test instead of typing, since it takes less time to be executed
- Improvements on cypress commands chatFeaturesProfileName and validateGlyphsModal to avoid failures presented on CI executions
- Setting chromeWebSecurity to false in cypress.json, which avoids the issue of failed to fetch presented in cypress tests executed on CI
- Skipping cypress tests for chat images and some test scenarios for mobile responsiveness, pin-unlock-validations and privacy-page-toggles …

test(cypress): add links validations and fixes on CI

---

components/ui/Global/Global.html
components/views/files/view/View.html
components/views/files/view/View.vue
pages/files/browse/index.vue
plugins/thirdparty/persist.ts
store/ui/mutations.ts
store/ui/types.ts

- if you refresh and then open file, it needs to fetch the blob from textile for download. the way state is handled for this modal crashes. PR fixes this crash
- less overhead in store, only keep track of name rather than full Fil

fix(files): rework store for files modal

---

components/views/chat/search/result/item/Item.html
components/views/chat/search/result/item/Item.vue
locales/en-US.js
plugins/local/dayjs.ts
store/settings/getters.ts

- switch search timestamps to be static, rather than relative to current time. more in line with figma
- https://www.figma.com/file/DSRWqZWdeElrEzH64y57qf/Search-Filter?node-id=43%3A1497
- based on timezone in store
AP-1359
🟢 I like these better than the relative timestamps in chat. Is that open for discussion? Would like to get some other opinions

fix(search): switch to static timestamps

---

components/views/chat/message/Message.html

hide action icons if message is editing status
AP-1358

fix(chat): hide action icons if message is editing status

---

components/ui/Chat/Image/Overlay/Overlay.less

depending on the size of the image, when previewed, the image is stretched
AP-1337

fix(ui): image preview stretch issue

---

cypress/integration/chat-features.js
cypress/integration/chat-glyphs-validations.js
cypress/integration/chat-images-validations.js
cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/chat-top-toolbar.js
cypress/integration/create-account.js
cypress/integration/localstorage-validations.js
cypress/integration/mobiles-responsiveness.js
cypress/integration/pin-unlock-validations.js
cypress/integration/privacy-page-toggles.js
cypress/integration/snapshots-test.js
cypress/support/commands.js

- Unskip cypress tests failing due to textile issue which is now solved
- Added a new cypress command in all chat tests to wait for page loaded
- Improvement on go to conversation cypress command so it can work different for mobile tests, which was causing issues before in this spec
- Change name of the copy image cypress test inside chat-features.js
None
All specs except the ones skipped are passing:
Mobiles Responsiveness Cypress Video:
https://user-images.githubusercontent.com/35935591/162843704-632c67f1-761b-4d1a-b8e7-12e5be26fa11.mp4

test(cypress): unskip tests, improvements on tests/commands

---

components/ui/Chat/Scroll/Scroll.html
components/ui/Chat/Scroll/Scroll.vue

with mobile on the chat page, when the user scrolls, the virtual keyboard will be hidden.
AP-1309

fix(mobile): hide virtual keyboard when scroll

---

libraries/Solana/SolanaManager/SolanaManager.test.ts
libraries/Solana/SolanaManager/__snapshots__/SolanaManager.test.ts.snap

- Adds more coverage on libraries/Solana/SolanaManager/SolanaManager.test.ts
before
after

chore(jest): add more coverage on SolanaManager.test.ts

---

components/views/files/controls/Controls.html
components/views/files/controls/Controls.less
components/views/files/controls/Controls.vue
components/views/files/upload/Upload.vue
components/views/files/view/View.html
components/views/files/view/View.less
components/views/files/view/View.vue
components/views/user/create/Create.vue
config.ts
layouts/files.vue
libraries/Files/Directory.ts
libraries/Files/TextileFileSystem.ts
libraries/Files/remote/textile/Bucket.ts
locales/en-US.js
package.json
utilities/NSFW.ts

- prevent crash by placing a memory limit on scan
- rename our nsfw limits accordingly
- remove guard clause for what I thought was a buffer issue. It was from video scan
- progress bar on upload and download
- status messages during upload indicating which file / index update
- fix unrelated display issue where mobile hamburger menu is present in desktop view
- fix css issue for fullscreen file view icons, `close` popup was cutoff. Improve overall layout using padding so progress bar wont touch the sides on mobile
AP-1280, AP-918

fix(files): nsfw scan memory limit

---

components/ui/Circle/Circle.html
components/ui/User/State/State.vue
cypress/integration/create-account.js

- Add cypress tests for account creation when attempting to upload an invalid image as profile picture
- Added small validation at the end of NSFW image last test to ensure that profile picture is a satellite circle without profile picture
- Add data-cy locators used for satellite circles in profile
AP-1138
Create Account Cypress Video:
https://user-images.githubusercontent.com/35935591/163029569-e8845091-8c21-4c71-89e1-cd9bbce0caec.mp4

test(cypress): add tests for invalid image on account creation

---

components/views/chat/search/SearchUtil.test.ts
components/views/chat/search/SearchUtil.ts
components/views/chat/search/__snapshots__/SearchUtil.test.ts.snap
components/views/chat/search/result/Result.html
components/views/chat/search/result/Result.vue
components/views/chat/search/result/meta/Meta.html
components/views/chat/search/result/meta/Meta.less
components/views/chat/search/result/meta/Meta.vue
libraries/SatelliteDB/SearchIndex.ts
store/textile/actions.ts
types/search/search.ts

- implement search 'order by' options (new, old, relevant)
- refactor search to take advantage of component info, no need to pass params
- improve type annotations
AP-1361

feat(search): orderby search results

---

components/views/settings/pages/privacy/Privacy.html
components/views/settings/pages/privacy/index.vue
libraries/Textile/TextileManager.ts
libraries/Textile/UserManager.ts
libraries/Textile/schema.ts
locales/en-US.js
store/settings/actions.ts
store/settings/mutations.ts
store/settings/state.ts
store/settings/types.ts
store/textile/actions.ts
store/textile/types.ts
types/textile/user.ts

- This is rebased PR based on https://github.com/Satellite-im/Core-PWA/pull/2780
- add a toggle for can scan and save info to textile
- add textile manager for saving user consent data
AP-1332
- This is already reviewed by devs on old PR... This is just new PR with rebase dev.

feat(csam): add toggle for csam scan and save info to textile

---

cypress/integration/create-account-negative-tests.js
cypress/integration/create-account.js
cypress/integration/pin-unlock-validations.js
cypress/integration/privacy-page-toggles.js

- After reviewing the last pr's in the repo, I found some tests failing due to timeout. I am skipping these for now in the meantime the page load times are more stable and I am able to find a better solution than increasing the timeouts, in order to have all tests in green status
None

test(cypress): skip cypress tests for timeouts

---

components/views/glyphs/Glyphs.html
components/views/glyphs/Glyphs.vue

- Removes mock description on glyphs modal
before
after
- Removes not used imports
- Adds multi line comment on existing commented out code

chore(glyphs): removes description

---

components/ui/Chat/Image/Overlay/Overlay.html
components/ui/Chat/Image/Overlay/Overlay.vue

while mobile users preview image in chat, the user can click image through mask overlay, this PR fix this
AP-1212
used setTimeOut function, not sure if there's any better solution for this. thanks.

fix(mobile): user jump between different photo

---

components/views/chat/chatbar/Chatbar.vue

in chat page on mobile(ios), when the user goes in chat page, virtual keyboard hides chatbox, and yup, this PR fixes by setting chatbarFocus flag as false
AP-1384
I had to remove line 165 in components\views\chat\chatbar.vue
this.$store.dispatch('ui/setChatbarFocus')
don't know what this line does, but had to remove it to fix this bug.

fix(mobile): virtual keyboard hide chatbox in chat

---

components/views/chat/message/Message.html
components/views/chat/message/reactions/Reactions.html
cypress/integration/chat-pair-features.js
cypress/support/commands.js

- Add cypress tests for chat reactions on text messages, images, files and glyphs
- Add cypress commands needed for above validations
- Add data-cy locators used in these new cypress tests
- Unskip chat-pair-features.js cypress tests and skip only the timestamp validations, which need rework due to the timestamp changes recently applied
- Increase timeout for goToConversation and validateChatPageIsLoaded cypress commands
- Small improvement on goToConversation cypress command to click on hamburger button if needed before clicking on friends button (before this fix, tests failed randomly, since sometimes the page loads displaying the chat conversation and not the sidebar menu)
- Small improvement on chatFeaturesSendMessage cypress command to avoid issue of cy.type() …

test(cypress): add chat reaction tests

---

store/textile/__snapshots__/getters.test.ts.snap
store/textile/getters.test.ts

- Increase coverage on store/textile/getters.test.ts
before
after

chore(jest): increase coverage on store/textile/getters.test.ts

---

components/interactables/Select/Select.html
components/interactables/Switch/Switch.html
components/views/navigation/slimbar/Slimbar.html
cypress/integration-pair-chat/chat-first-user.js
cypress/integration-pair-chat/chat-second-user.js
cypress/integration/create-account-negative-tests.js
cypress/integration/create-account.js
cypress/integration/import-account-negative-tests.js
cypress/integration/import-account.js
cypress/integration/mobiles-responsiveness.js
cypress/integration/pin-unlock-validations.js
cypress/integration/privacy-page-toggles.js
cypress/integration/snapshots-test.js
cypress/support/commands.js
pages/setup/disclaimer/Disclaimer.html
pages/setup/privacy/Privacy.html

- Add cypress tests for the new switch toggle and selector added in the privacy settings page presented during account creation
- Add new data-cy attributes to elements commonly used during create/import account first steps. Applied these new locators in cypress tests
- Improvements of cypress commands (timeouts, changed locators). Added two new commands for switch toggles validat ions.
- Added new cypress command validateUserInputIsDisplayed to add a small timeout when going to the user input page, to avoid timeout issues
- Moved into create-account.js one cypress tests that was a cypress command only used in this test (to avoid having commands that are not used in several tests)
- Skipping tests failing due to timeout presented on Linking Satellites page
**Which …

test(cypress): updates for privacy toggles and fixes

---

components/views/files/upload/Upload.html
components/views/files/upload/Upload.vue

on the mobile screen, the image picker position is weird because the virtual keyboard is hidden and shows like floating in the middle. fixed by delaying click event and shows image picker after virtual keyboard hide
AP-1385

fix(mobile): fix image picker position

---

components/views/chat/chatbar/Chatbar.vue

Fix 'When a user is replying after a few seconds (happens faster on mobile devices) the reply modal (blue bar in chat) will disappear '.
AP-1419

fix(chat): fix reply modal disappearing issue

---

components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.vue

Fixes issue with emoji which happen to disappear when user clicks outside emojis container (but inside modal)
AP-1432

fix(emoji-scroll): emoji persist on scroll

---

components/views/files/controls/Controls.html
components/views/files/controls/Controls.less
components/views/files/controls/Controls.vue
libraries/Files/remote/textile/Bucket.ts
plugins/thirdparty/persist.ts
store/ui/__snapshots__/state.test.ts.snap
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts

- remove file upload progress bar in favor of percentage in status message. more consistent ui, less jarring than seeing the progress bar appear & disappear. Liz also said we don't use progress bars, so this is more cohesive with the rest of the app
- upload status will remain if you navigate away from this page and come back
AP-1395
I made a ticket for these
- since we're using store, I'd like to add status updates for other file operations (rename, remove, favorite) after this
- could probably also clean up store, switching to this rather than the boolean for keeping track of active files operations

fix(files): persistent files upload status

---

components/views/user/create/Create.html
components/views/user/create/Create.vue
libraries/Files/TextileFileSystem.ts
locales/en-US.js
pages/auth/register/Register.html
utilities/BlobToBase64.ts

- rework signup page guard clauses
- allow heic in addition to other embeddable image types on the input
- safari doesn't fully support `<input>` accept on ios, so I set that to all images, which is then blocked on a byte check if invalid https://caniuse.com/input-file-accept
- switch to emit event rather than pass function as prop
- blob to base 64 utility function. swapped out here and in filesystem image thumbnail creation. can add to chat upload once those files are free
AP-1355

feat(account): better image format rules on profile pic creation

---

store/textile/__snapshots__/getters.test.ts.snap
store/textile/getters.test.ts

feat(jest): 100% coverage for store/textile/getters

---

components/views/chat/message/Message.less
components/views/chat/message/reply/Item/Item.html
components/views/chat/message/reply/Item/Item.less
components/views/chat/message/reply/Item/Item.vue
components/views/chat/message/reply/Reply.html
components/views/chat/message/reply/Reply.less
components/views/chat/message/reply/Reply.vue

change avatar color to correct one
[AP-1411](https://satellite-im.atlassian.net/browse/AP-1411)

fix(replies): change avatar color to correct one

---

components/views/friends/friend/Friend.html
components/views/user/User.html
cypress/integration/chat-features.js
cypress/integration/chat-glyphs-validations.js
cypress/integration/chat-images-validations.js
cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/chat-top-toolbar.js
cypress/integration/create-account-negative-tests.js
cypress/integration/create-account.js
cypress/integration/mobiles-responsiveness.js
cypress/integration/pin-unlock-validations.js
cypress/integration/privacy-page-toggles.js
cypress/integration/snapshots-test.js
cypress/support/commands.js

- Updates of privacy toggles validations due to the removal of Privacy Settings screen during account creation. Applied the proper updates to create account scenarios existing in our test suite
- Unskip cypress chat tests using accounts imported, which should work correctly now
- Added data-cy attributes for sidebar friends used in cypress commands
- Refactored mobiles-responsiveness tests to avoid switching viewport for each it block
- Improvement of goToConversation cypress command to work correctly for mobiles and standard viewports
- Update of the validation of glyph modal cypress command to match with the current DOM elements
AP-1441 and AP-1450
Keeping skipped the ones for chat creation …

test(cypress): remove privacy toggles screen validations

---

components/views/navigation/toolbar/Toolbar.html
components/views/user/profile/About.vue
components/views/user/profile/Profile.html
cypress/integration-pair-chat/chat-first-user.js
cypress/integration-pair-chat/chat-second-user.js
cypress/integration/chat-features.js
cypress/integration/chat-glyphs-validations.js
cypress/integration/chat-images-validations.js
cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/chat-top-toolbar.js
cypress/integration/mobiles-responsiveness.js

- Add cypress tests for "add note to user profile"
- Added data-cy attributes used for these tests
- Skipping cypress tests that require importing accounts with friends, due to the recent change on the friends functionality. Once that a fix is applied for this in the tests, these will be unskipped again
AP-1325
Chat Features Cypress Video (before skipping the test):
https://user-images.githubusercontent.com/35935591/164815113-10e7ef39-b184-427a-86ca-ded642e886c9.mp4

test(cypress): add tests for profile note

---

store/settings/actions.test.ts

Clean up and also catch the previous error from `setConsentScan` that was not being caught, while also adding coverage for `setBlockNsfw`.
AP-1433

feat(jest): 100% coverage for store/settings/actions

---

components/interactables/ContextMenu/ContextMenu.html
cypress/integration/chat-pair-features.js
cypress/integration/mobiles-responsiveness.js
cypress/support/commands.js
layouts/chat.vue

- Add cypress tests for context menu options
- Add cypress command for the context menu validations
- Improvement to goToConversation cypress cypress command
- Improvement on the way to look for the last chat text message in chat-pair-features.js cypress tests
- Adding data-cy attributes for DOM elements validated in new cypress tests
AP-1327
- Keeping chat tests skipped for now, due to the friends program changes about to be released
Chat Pair Features Cypress Video:
https://user-images.githubusercontent.com/35935591/165174655-c566c5b8-3e86-4b3c-a1c6-75662b035330.mp4
Mobiles Responsiveness Cypress Video:
https://user-images.githubusercontent.com/35935591/165174675-9b9179 …

test(cypress): add tests for context menu

---

locales/en-US.js

Adds a "." to the end of description for consent for file scanning in Settings
When testing Navigate into Settings/Privacy verify that the description for Consent to File Sharing has a "." at the end of it

fix(locales): add punctuation

---

components/views/files/controls/Controls.html
components/views/files/controls/Controls.vue
components/views/files/file/File.html
components/views/files/file/File.vue
components/views/files/filepath/Filepath.html
components/views/files/filepath/Filepath.vue
components/views/files/list/List.html
components/views/files/list/List.vue
components/views/files/rename/Rename.html
components/views/files/rename/Rename.vue
components/views/files/row/Row.html
components/views/files/row/Row.vue
components/views/files/view/View.html
components/views/files/view/View.vue
layouts/files.vue
locales/en-US.js
pages/files/browse/index.vue
plugins/thirdparty/persist.ts
store/ui/__snapshots__/getters.test.ts.snap
store/ui/__snapshots__/state.test.ts.snap
store/ui/getters.test.ts
store/ui/getters.ts
store/ui/mutations.test.ts
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts

- only new functionality is adding status message to rename, delete. mostly under the hood changes
- fixes redundancy in store keeping track of bucket updates. added a getter which casts status string to boolean
- remove toast after rename is done. no longer needed since the status message makes it clear enough
AP-1421, AP-1396
- when testing, please make sure the upload ui gets disabled for every files operation (upload, rename, delete, favorite)

fix(files): store cleanup and additional files status messages

---

package.json

Adds script - `yarn summary` to get the summary status of the Jest tests
so instead of running 
`yarn test --coverage --coverageReporters=text-summary`
you can just run
`yarn summary`
and will return the above stats

chore(script): add script

---

libraries/Solana/Solana.test.ts

Increase coverage. Draft for now because I'm looking for ways (asking other people) to cover that last line of code, if I'm unable to do that then I'd remove the draft label.
**Update**: Manuel informed that there is no need to cover that part.
AP-555

feat(jest): 96% coverage for libraries/Solana/Solana

---

cypress/integration/chat-features.js
cypress/integration/chat-glyphs-validations.js
cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/chat-top-toolbar.js
cypress/integration/create-account-negative-tests.js
cypress/integration/create-account.js
cypress/integration/files-features.js
cypress/integration/mobiles-responsiveness.js
cypress/integration/pin-unlock-validations.js
cypress/integration/privacy-page-toggles.js
cypress/support/commands.js
layouts/friends.vue

- Reorganizing chat features cypress tests, small improvement to click on toggle sidebar only if needed and moving files tests into a separate spec file
- On chat text validations cypress spec, added assertions to validate text is in editable input before testing the number of chars, to ensure that this test is executed in the right order. Also, using the paste command whenever is possible, since it does not causes random fails as the cy.type() command
- Updates on privacy page toggles cypress tests to consider the recent removal of the signaling selector and text modifications in the settings privacy toggles page
- Improvements on few of the cypress commands used along the tests and removal of commands no longer needed
- Adding one data-cy attribute in one of the …

test(cypress): fixes and unskips for tests

---

assets/styles/base.less
assets/styles/framework/colors.less
assets/styles/thirdparty/multiselect.less
components/ui/BadgedIcon/BadgedIcon.less
components/ui/Chat/Embeds/VideoPlayer/VideoPlayer.less
components/ui/SimpleScroll/SimpleScroll.html
components/ui/SimpleScroll/SimpleScroll.less
components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.less
components/views/marketplace/card/Card.less
components/views/marketplace/glyphs/shop/item/Item.less

AP-1481
New scrollbar component's first add, can just be found on the emoji picker

chore(scrollbar): added new scrollbar to emote

---

store/webrtc/mutations.test.ts

Self-explanatory, though there is one catch. The skipped tests is due to something I cannot yet figure out related to LibP2P's call:
We would need the constructor to be successfully called to later use it to mutate the state. Though for now, I am abandoning that particular test that is skipped before any fix comes to mind. The code that is causing the errors (the constructor):
AP-588

feat(jest): 95% coverage for store/webrtc/mutations

---

cypress/support/commands.js

- Add more timeout to wait for goToConversation cypress command to wait on user-connected to be displayed when loading a chat conversation
None
- This should avoid failures on chat-features.js cypress test

test(cypress): more timeout for conversation load

---

config.ts
libraries/Files/remote/textile/Bucket.ts
libraries/Textile/BucketManager.ts
libraries/Textile/IdentityManager.ts

Connect new textile deployment to CORE via env vars
AP-1512
Add to `.env` two vars with new textile deployment urls: `NUXT_ENV_TEXTILE_BROWSER` and `NUXT_ENV_TEXTILE_API_URL`. Also you need new api key. By default `textile.io` based addresses will be used

feat(textile): configure textile via env

---

components/views/navigation/mobile/sidebar/sidebar.vue
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.vue
components/views/navigation/slimbar/Slimbar.html
components/views/navigation/slimbar/Slimbar.less
components/views/navigation/slimbar/Slimbar.vue
components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/Profile.less
components/views/settings/pages/profile/index.vue
components/views/user/profile/About.vue
layouts/default.vue
libraries/Textile/TextileManager.ts
middleware/authenticated.ts
pages/chat/direct/Direct.html
pages/chat/direct/_address.vue
pages/chat/groups/Group.html
pages/chat/groups/_id.vue
pages/files/browse/Browse.html
pages/files/browse/index.vue
pages/friends/list/FriendsList.html
pages/friends/mobile/add/index.vue
pages/friends/mobile/incoming/index.vue
store/accounts/actions.ts
store/getters.ts
store/textile/actions.ts

Release the UI asap without waiting for Textile to init:
* the initial loader is released only once Solana and Webrtc are init;
* friends should be visibile almost immediately, they depend only on Solana;
* groups and files depends also on Textile, so loaders are put as placeholders;
* registration with an image depends on Textile so this step is still slow in this case;
* ui actions depend on Textile are disabled while it loads, if u find something not working while textile is initializing lmk.
AP-1480
Dont test it if you dont want to go too fast

feat(textile): release the ui asap

---

components/views/chat/search/input/Input.vue
components/views/chat/search/result/Result.vue
libraries/SatelliteDB/SearchIndex.ts
store/textile/actions.ts
types/search/search.ts

- only show search match if term matches payload. setup in a way that can be refined later when we add different search criteria (sender, etc..)
- previously, any message would hit a `conversation` match if the conversation ID was passed as the search query
- add return types to some computed props
AP-1333

fix(search): refine search match criterion

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/files/upload/Upload.html
components/views/files/upload/Upload.vue

- add computed return types to fix `this` context, remove unnecessary $data and $props references
- remove unused data
- remove redundant prop
N/A
- no new functionality, just code cleanup

refactor(chat): remove unnecessary code and fix intellisense

---

config.ts
libraries/SatelliteDB/SatelliteDB.ts
pages/auth/unlock/index.vue

- if user cleared localstorage manually (dev tools) and got sent back to account create/import, this will clear indexedDB if it exists
- added idb name to Config file
AP-1476

fix(indexeddb): clear idb if user manually deleted localstorage

---

components/ui/Loaders/Message/Message.vue
components/views/navigation/mobile/nav/Nav.html
cypress/integration-pair-chat/chat-first-user.js
cypress/integration-pair-chat/chat-second-user.js
cypress/integration/chat-features.js
cypress/integration/chat-glyphs-validations.js
cypress/integration/chat-top-toolbar.js
cypress/integration/create-account.js
cypress/integration/import-account.js
cypress/integration/mobiles-responsiveness.js
cypress/integration/pin-unlock-validations.js
cypress/integration/snapshots-test.js
cypress/support/commands.js
cypress/support/first-user/commands.js
cypress/support/second-user/commands.js

- Adding data-cy attribute to message loader element and implemented the usage of this locator in cypress tests/commands
- Modified cypress commands in order to ensure that when testing for mobile viewports, the mobile version of the application is loaded and commands work for this version as well
- Updated mobiles-responsiveness.js to use the new versions of the cypress commands passing the isMobile = true parameter. Removed unnecessary cy.logs from this test and added a beforeEach hook to set the viewport depending on the size passed through the fixture file. Tests are skipped for now, since I am working on the swipe/tap on this spec and it will be unskipped on my next PR
- Skip chat pair tests in order to apply the changes required after videocall updates
- …

test(cypress): fixes for tests after videocall updates

---

cypress/integration/chat-pair-features.js
cypress/integration/chat-top-toolbar.js
cypress/integration/files-features.js
cypress/support/commands.js

- Skipping tests failing on CI after the last updates from cypress were merged
- Improvement to the cypress command used for markdown tests in order to invoke cy.type instead of cy.paste command to type the test markdowns
None

test(cypress): skip and fixes cypress tests

---

components/views/files/aside/Aside.html

- hide bottom two 'shared' related options. gonna try to complete deleted and favorite soon, but these definitely wont be ready
AP-1571

fix(files): hide sidebar options that 100% wont be ready

---

cypress/fixtures/test-data-accounts.json
cypress/integration/chat-glyphs-validations.js
cypress/integration/chat-images-validations.js
cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/chat-top-toolbar.js
cypress/integration/files-features.js
cypress/integration/mobiles-responsiveness.js
cypress/support/commands.js

- Adding new accounts for cypress tests due to friends program chaneg
- Adding swipe cypress tests for settings and chat screen into mobiles-responsiveness.js
- Skipping glyphs tests that are failing now due to bugs in the application not fixed yet. In mobiles-responsiveness.js, these validations appear now as commented code
- Skipping chat-images-validations.js and one cypress test that validates sending a message with more than 2048 chars from chat-text-validations.js which are failing now. 
- Unskipped one test from files-features.js that should be working correctly now
- Small update into visitRootPage cypress command to use cy.visit instead of cy.visitMobile
AP-814 and AP-1567
**Additional …

test(cypress): add swipe tests and new accounts

---

components/typography/Text/Text.vue
components/views/chat/chatbar/footer/is-connected/Connected.html
components/views/chat/chatbar/footer/is-connected/Connected.less
components/views/chat/chatbar/footer/is-connected/Connected.vue
locales/en-US.js
store/conversation/getters.ts

This PR adds back in the offline notices in dm and group chat.
AP-1549
Added a third state for 'All users are offline'

fix(footer): adds offline text if user is offline in footer

---

cypress/integration/chat-images-validations.js
cypress/integration/mobiles-responsiveness.js
cypress/support/commands.js

- Add save image cypress test in chat-images-validations.js and unskip the describe block from this file
- Updates on mobiles-responsiveness.js file in order to have separate it blocks for tests and use skips for tests not working now instead of having commented code
- Small improvement to goToLastImageOnChat cypress command
AP-1322
Chat Images Validations Cypress Video:
https://user-images.githubusercontent.com/35935591/168914601-44333c9b-7586-467e-8ec5-8f4d340e95ed.mp4
Mobiles Responsiveness Cypress Video:
https://user-images.githubusercontent.com/35935591/168914644-7a10ea9d-f636-4e23-894f-2c02e46aad14.mp4

test(cypress): add save image test and updates to mobiles

---

components/views/group/clickable/Clickable.vue
components/views/navigation/toolbar/Toolbar.html
locales/en-US.js

Disabled the toolbar call button in group chats and adds a coming soon tooltip.
AP-1552

fix(toolbar): disable group call button

---

components/views/files/view/View.less

- svg with no inline width/height was being rendered with value of 0 for both
- 100% height and width for files image view
AP-1524

fix(files): width and height for files image view

---

store/friends/__snapshots__/state.test.ts.snap
store/friends/getters.ts
store/friends/state.ts
store/friends/types.ts
types/ui/friends.d.ts

- There were some hounddog related bugs recently, so I decided to take a look at the class. I discovered it's essentially a roundabout way of creating friends store getters
- copy hounddog methods to legit friends store getters
- in a future PR, i would like to refactor/clean up these getters and remove hounddog altogether
AP-1573
- this has 0 new functionality, just prep for future updates and hopefully getting validation that this is a good idea

fix(hounddog): copy houndog logic to store getters

---

components/views/settings/pages/audio/Audio.html

Swaps the position of the audio input/output volume sliders so that they are aligned with the input/output device controls
AP-1592

fix(settings): correct audio input/output volume control position

---

components/views/media/actions/Actions.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.vue
components/views/navigation/toolbar/alerts/Alerts.html
components/views/navigation/toolbar/alerts/Alerts.vue
components/views/navigation/toolbar/alerts/alert/Alert.html
components/views/navigation/toolbar/alerts/alert/Alert.less
components/views/navigation/toolbar/alerts/alert/Alert.vue
libraries/ui/Alerts.ts
store/ui/actions.test.ts
store/ui/actions.ts
store/ui/mutations.test.ts
store/ui/mutations.ts

- adjust notifications read indicator
- change notification unread logic
AP-1500
this is an updated version of Jeff's PR for the same feature. I wanted to give him feedback and needed to confirm my approach would work. Since it was already done, thought it was easy to open a new PR.
We could probably add some visual indicator for brand new notifications on open in a separate ticket (or this one if you really want)

fix(notification): clear alert number on open

---

components/views/settings/modal/Modal.vue

Removed redirect to profile section in modal settings when asking for file consent on iOS (redirect to privacy section instead)
AP-1529

fix(settings): remove mobile redirect to profile modal settings

---

components/ui/Circle/Circle.vue
components/ui/User/State/State.less
components/ui/User/State/State.vue
components/views/chat/group/Group.html
components/views/chat/message/reply/Item/Item.html
components/views/group/aside/Aside.html
components/views/group/icon/GroupIcon.html
components/views/media/user/User.html
components/views/navigation/toolbar/Toolbar.html
components/views/wallet/recent/item/Item.html

fix position and size of status (on the message list on the sidebar it was slightly wrong)
[AP-1462](https://satellite-im.atlassian.net/browse/AP-1462)

fix(status): position and size of status

---

components/views/media/user/User.html
components/views/media/user/User.less

- Fixes the muted audio state used to render the muted indicator.
- Updates the styling to match the figma design.
AP-1548

feat(media): update mute indicator style

---

cypress/integration/chat-features.js
cypress/integration/chat-pair-features.js
cypress/integration/import-account-negative-tests.js
cypress/integration/mobiles-responsiveness.js

- Skip chat-features.js cypress spec since several tests are failing due to textile issues
- Skip the whole cypress spec chat-pair-features.js instead of calling skip to several tests included in this spec. Tests skipped are failing due to textile issues
- Skip cypress tests failing on mobiles-responsiveness.js
- Skip one cypress tests failing on import account negative tests
None

test(cypress): skip tests failing due to textile

---

components/interactables/ContextMenu/ContextMenu.vue
components/interactables/Input/Input.html
components/interactables/Input/Input.vue
components/views/friends/add/Add.html
components/views/friends/add/Add.vue
components/views/friends/friend/Friend.vue

- switch friends input to Input component, rather than InputGroup. The button on the right wasn't serving a purpose, besides showing the loading state.
- added loading icon beneath input to indicate a search
- added max length to input, since public keys only go up to 44 length (at the moment)
- minor refactors + code cleanup
AP-1594

fix(friends): fix disabled add friends input bug

---

store/conversation/actions.test.ts

self-explanatory. Though there is 1 imperfect unit test, perhaps @aewing can help me on determining the right argument to pass in.
AP-1612

feat(jest): 94% coverage for store/conversation/action

---

components/views/settings/pages/storage/index.vue
locales/en-US.js
pages/auth/unlock/Unlock.html
pages/auth/unlock/Unlock.less
pages/auth/unlock/index.vue
store/settings/actions.test.ts
store/settings/actions.ts
store/settings/mutations.test.ts
store/settings/mutations.ts

- added button to account unlock screen that will delete indexeddb + localstorage
- updated action to be more reusable, rather than forcing a reload inside the action
- switch to dexie for db check for firefox
AP-954, AP-1621
- maybe we want some kind of warning second click (similar to settings page)? let me know what you think

feat(account): button to delete account on login screen

---

components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.less
components/views/navigation/toolbar/Toolbar.vue

Disabled the toolbar call button while in a call.
AP-1580

fix(toolbar): disable call button when in call

---

store/video/actions.test.ts

feat(jest): 84% coverage for store/video/actions

---

components/views/media/actions/Actions.vue
components/views/media/user/User.html
components/views/media/user/User.vue
components/views/navigation/sidebar/controls/Controls.vue
store/audio/actions.ts
store/webrtc/actions.ts

- update `$store.dispatch` calls for toggling audio/video muting in sidebar so that the buttons behave correctly.
- fix audio stream indicator visibility logic in media/user component so it only shows the audio stream indictor when unmuted.
AP-1581, AP-1578, AP-1466

fix(sidebar): fix toggle mute dispatch

---

libraries/Textile/NotificationManager.ts
store/textile/actions.ts
store/ui/actions.test.ts
store/ui/actions.ts

Don't have alert for chat that is active
AP-1502

fix(notifications): stop alert notification if alert would notify of message of current active chat

---

components/views/friends/friend/Friend.vue
locales/en-US.js

- Removes a superfluous throw
- Displays an error toast if the friend request isn't found
AP-1565

fix(friends): show error toast if friend request not found

---

assets/styles/base.less

Makes error toasts red
AP-1639

feat(toast): add error toast styling

---

components/views/chat/message/edit/Edit.html
components/views/chat/message/edit/Edit.less
components/views/chat/message/edit/Edit.vue
locales/en-US.js

- Prevents saving an edited message as an empty message
- Fixes styling and locale strings in the edit message UI
AP-1631

fix(message): disable save on empty message

---

assets/styles/base.less
components/views/chat/message/Markdown.vue
components/views/chat/message/Message.less
components/views/user/User.vue

- remove redundant spoiler scoped css. user sidebar and chat message will now use styles in base.less
- adjust spoiler-open class placement so background will now be transparent
AP-1648

fix(spoilers): transparent background on open spoilers

---

components/views/navigation/toolbar/alerts/alert/Alert.less

return close button to alert
[AP-1608](https://satellite-im.atlassian.net/browse/AP-1608)

fix(alerts): return close button

---

components/views/navigation/mobile/sidebar/sidebar.vue

Fix coming soon tooltip not showing in friends/groups search bar on mobile (android / iOS)
[AP-1380](https://satellite-im.atlassian.net/browse/AP-1380)

fix(mobile): fix coming soon tooltip not showing in friends/groups search bar

---

components/typography/HorizontalRuleText/HorizontalRuleText.vue
components/views/chat/group/Group.html
components/views/chat/group/Group.vue
components/views/chat/message/reply/Item/Item.vue

- remove 'yesterday' and 'now' in favor of static timestamps in chat messages and replies
- thought process outlined [here](https://github.com/Satellite-im/Core-PWA/pull/3403)
AP-1704
- do we want to update the sidebar at all?

fix(chat): static timestamps, remove interval

---

package.json

Improve Docker CI using `xvfb-run with -a` makes it automatically use the next free server number, so it doesn't return  `Error: Display :99 is already in use `

chore(ci): improve docker

---

components/views/navigation/toolbar/Toolbar.vue
layouts/chat.vue
store/groups/mutations.ts

- set group members with an alpha sort. it seems like the backend returns them in a random order every time
- improve performance w/ find rather than iterating 100% of the time. a couple other mutations here could use this same treatment
AP-1698

fix(groups): members order sorted alpha

---

components/ui/Scroll/Scroll.vue
components/views/chat/search/result/Result.html
components/views/chat/search/result/Result.vue

- Fixes the issue where paginating through search results would not reset the scroll view offset to the top of the next page's results
AP-1725

fix(search): scroll to top on paginate

---

components/views/chat/chatbar/Chatbar.less
components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/footer/Footer.vue

- switch sendMessage to guard clause if missing recipient rather than 1 big nested if
- add permanent transparent border to avoid content shift with an input length error
- switch message length counter to honor the actual length of emojis
- prevent message send if over length
AP-1722

fix(chatbar): prevent send if over limit, switch limit to be more accurate

---

components/views/settings/pages/privacy/Privacy.html
components/views/settings/pages/privacy/index.vue

- use array for loading state rather than string
- This code would incorrectly unlock a remote setting even if it wasn't done loading since the loading state was only a string
AP-1723

fix(settings): switch privacy settings loading list to array

---

pages/chat/direct/_address.vue
store/accounts/actions.ts
store/friends/actions.test.ts
store/friends/actions.ts

disable auto redirect from chat to friend list on first visit
[AP-1643](https://satellite-im.atlassian.net/browse/AP-1643)

fix(chat): disable auto redirect from chat to friend list on first visit

---

components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.vue
layouts/chat.vue
layouts/files.vue
layouts/friends.vue

- refactor Sidebar to use store values rather than layout parent components passing store values as props. This way the component is more self contained. you don't need to look around multiple files to understand what is happening
- remove unused computed and imports
shouldnt notice any difference in functionality

refactor(sidebar): switch props to store when possible

---

components/ui/Chat/TypingIndicator/TypingIndicator.vue
components/views/media/Media.vue
components/views/media/actions/volume/Volume.vue
components/views/media/user/User.html
components/views/media/user/User.vue
components/views/settings/pages/realms/realm/index.vue

- add a volume watcher to update the audioStream element
- set initial volume when audioStream is set to the current volume state
AP-352
- 🎊  This is my first PR, please review carefully and don't hesitate to give feedback and share knowledge 🙂

fix(volume): bind output slider volume to stream volume

---

layouts/chat.vue

- Fixes a conditional class being applied when the active chat is the active call
AP-1724

fix(chat): fix is active call logic

---

components/views/chat/group/Group.vue
components/views/chat/message/reply/Item/Item.vue
components/views/chat/search/result/item/Item.vue
components/views/user/User.html
components/views/user/User.vue
plugins/local/dayjs.ts
store/settings/__snapshots__/getters.test.ts.snap
store/settings/getters.test.ts
store/settings/getters.ts
store/sounds/state.ts

- I created some getters that provide a localized timestamp
- I wanted something reusable since we repeated this dayjs logic many times
- placed in settings store because it should rely on user selected timezone (settings store)
- added tests
AP-1729

refactor(timestamps): switch localized timestamps to store getter

---

components/views/friends/quick/Quick.vue
components/views/user/create/Create.html
components/views/user/create/Create.vue
config.ts
locales/en-US.js

- add red border around username while invalid after a user failed submission once
- make error message update along with our Config values (groups and accounts)
- remove unused data
AP-1741
Is the native error better regarding accessibility?

feat(createAccount): better error messages/handling on username error

---

components/views/media/incomingCall/IncomingCall.html
components/views/media/incomingCall/IncomingCall.less
components/views/media/incomingCall/IncomingCall.vue

show avatar in incoming call
[AP-1692](https://satellite-im.atlassian.net/browse/AP-1692)

fix(call): show avatar in incoming call

---

components/interactables/Button/Button.less
components/interactables/Button/types.d.ts
components/interactables/Checkbox/Checkbox.html
components/interactables/Checkbox/Checkbox.less
components/interactables/Checkbox/Checkbox.vue
components/interactables/UserPicker/ListItem/ListItem.html
components/interactables/UserPicker/ListItem/ListItem.less
components/interactables/UserPicker/ListItem/ListItem.vue
components/interactables/UserPicker/UserPicker.html
components/interactables/UserPicker/UserPicker.less
components/interactables/UserPicker/UserPicker.vue
components/views/friends/quick/Quick.html
components/views/friends/quick/Quick.less
components/views/group/icon/GroupIcon.less

- add new checkbox component
- add reusable friend picker component
- upgrade quick component to use new friend picker
- fix button animation speed when switching `type` prop in quick component
- add missing type definition
AP-1742
AP-1710

feat(interactables): user picker component

---

components/views/chat/message/Message.vue

Hide edit message on the context menu
Atm edit message is coming soon so shouldn't appear on the context menu
before
after

chore(edit): hide edit message

---

components/views/chat/group/Group.vue

- this crash was introduced when my pr to fix avatar color and Hogan's PR to load messages earlier both went it.
- mapGetters loses type safety so I didn't think to account for an undefined return on `array.find`

fix(chat): refresh crash error

---

layouts/Layout.less

- assigned z index on fullscreen was hiding search results. I couldn't find any issues by removing it.
- if this breaks something else, we can add an even higher z index to search results
AP-1802

fix(call): fullscreen call search results z index issue

---

components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.vue

- Fixes the conditional media-open class; now it's only shown if the current chat is the active call.
AP-1747

fix(chat): is active call logic

---

components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.vue
locales/en-US.js

- Wraps the chat search in a `<UiComingSoon>` if it is a group chat since it is not implemented yet
AP-1812

feat(toolbar): add coming soon to group search input

---

assets/styles/base.less
components/views/friends/quick/Quick.html
components/views/friends/quick/Quick.less
components/views/friends/quick/Quick.vue
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.less
components/views/navigation/sidebar/Sidebar.vue

- rather than assigning a relatively arbitrary `left:` value to quickchat, now it will render beneath the parent button.
- I saw some simple improvements in sidebar as well while I was there
- flex + gap
- remove isMobile conditionals since this component will only be rendered on desktop
AP-1780
quickchat would occasionally get shifted to the left during active calls, this will no longer do that. zindexes are working fine

fix(quickchat): improve quickchat/sidebar css

---

components/interactables/Input/Input.vue
components/views/user/create/Create.html
components/views/user/create/Create.vue
config.ts
locales/en-US.js

- client side validation for status (max length 128)
- switch account errors to array in case there are status and username errors at the same time
- trim status and username in validation so there's no funny business with spaces
- global change - if user enters only spaces, will reset Input to empty
AP-1806

fix(account): client side validation for user creation

---

components/views/callToAction/CallToAction.less

- Sets overflow to visible on SVG element so edges are rendered properly on Safari
AP-1718

fix(cta): svg overflow clipping

---

store/webrtc/actions.ts

Sometimes online status of friends and conversation participants is not updated. This PR intended to fix the issue.
AP-1697

fix(onlineStatus): update peer events handlers

---

components/views/chat/group/Group.vue

- show name instead of 'unknown' while loading messages
AP-1829
- this solution feels quick and dirty, should be refactored when time allows
- that `getUsernameFromState` is really slow and should be phased out

fix(chat): unknown name while loading

---

components/views/navigation/slimbar/Slimbar.less
components/views/navigation/toolbar/Toolbar.less
layouts/Layout.less

- general refactor. remove unused styles. move styles from huge Layout file to scoped css file.
- increases text overflow length from 250px to using flex. I set a margin on the toolbar controls so it doesn't hug too closely
AP-1851

refactor(toolbar): refactor styles and increase text overflow length w/ flex

---

components/views/files/aside/Aside.vue
components/views/files/controls/Controls.html
components/views/files/controls/Controls.less

- add coming soon tooltip to search
- remove right aside options that aren't ready
AP-1845, AP-1823

fix(files): remove unfinished ui

---

components/views/chat/chatbar/Chatbar.vue
store/conversation/actions.test.ts
store/conversation/actions.ts
store/webrtc/actions.ts

Restore typing notification in direct and groups chat
AP-1734
Should resolve the Textile listener as well.
The typing event will be sent only after the users are connected (as for starting a call for example)

fix(chat): is_typing indicator

---

components/views/files/view/View.vue

- fix mutation outside state bug that happened to me during demo. i accidentally wrote += for file name if missing extension
- remove local state. no longer needed since download uses streams api now
AP-1847

fix(download): remove unnecessary local state, fix string bug

---

components/ui/SatelliteCircle/SatelliteCircle.vue

- Removes the light grey color from the list of colors for the satellite circle component
AP-1597

fix(satellitecircle): remove illegible light grey color

---

store/webrtc/mutations.test.ts

feat(jest): 100% branch coverage for store/webrtc/mutations

---

components/views/files/upload/preview/item/Item.html
components/views/navigation/toolbar/Toolbar.html
cypress/integration/chat-pair-features.js
cypress/integration/chat-top-toolbar.js
cypress/support/commands.js

- Added data-cy attributes for toolbar alerts and file previews used in cypress tests
- Updates for the following cypress commands: sending images/files, hover on active/coming soon icons and go to conversation commands
- Update to pass one additional parameter on command used for send file cypress test for chat-pair-features.js
- Updates on chat-top-toolbar tests due to changes on tooltip functionality
AP-1668
Chat Top Toolbar Cypress Video:
https://user-images.githubusercontent.com/35935591/174922630-03e018f2-5ca1-40cc-bf23-82ee9c20d476.mp4
Chat Pair Features Cypress Video:
https://user-images.githubusercontent.com/35935591/174922624-8ed17600-a6c4-422f-a286-16efa4f84a12 …

test(cypress): updates to chat top toolbar tests

---

cypress/integration-pair-chat/chat-first-user.js
cypress/integration-pair-chat/chat-second-user.js

- Increased retries on test "When the user clicks the video button camera should be enabled" for chat-first-user.js due to uncaught exception randomly presented when clicking on enable camera button
- Removed unnecessary wait on chat-second-user.js that might be causing the issue in last cypress test for chat-first-user.js
None
Chat First User Cypress Video:
https://user-images.githubusercontent.com/35935591/175108340-ee7272f7-f328-48de-8ffc-ec97567f2ea7.mp4
Chat Second User Cypress Video:
https://user-images.githubusercontent.com/35935591/175108362-e2c05950-d3f7-4f57-83b9-84fc3cb80e21.mp4
Both tests passing:

test(cypress): improvements to avoid failure on last test

---

components/ui/Chat/Scroll/Scroll.vue
store/ui/__snapshots__/state.test.ts.snap
store/ui/actions.test.ts
store/ui/getters.test.ts
store/ui/mutations.test.ts
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts
store/webrtc/actions.ts

- we previously used this store value to shift the quickchat layout if something was occupying the center of the screen. However, it was removed in a recent PR. this removes the unused store value
AP-1880

chore(store): remove unused store

---

store/textile/actions.ts

- Remove redundant dispatch call to `storeInMessage` action. We already dispatch `storeInMessage` in `subscribeToGroup` method.
AP-1690
Fixed Bug:

fix(group): remove duplicated dispatch to storeInMessage action

---

components/views/user/User.vue
store/textile/actions.ts

- Sets the conversation peer ID when switching conversations
- Prevents the conversation from being updated if the user has already navigated away from the chat (async textile issue)
AP-1864

fix(textile): set peer id correctly when switching conversations

---

assets/styles/base.less
components/views/chat/message/reactions/Reactions.html
components/views/chat/message/reactions/Reactions.less
components/views/chat/message/reactions/Reactions.vue
locales/en-US.js

- fix hover css that would cause layout shift
- refactor css and html for chat reactions
- switch reaction details popup to be more relative, in relation to the parent button. rather than just slapping arbitrary left: values on it
- add keyboard accessibility for reactions
AP-1866
- this is using that getUsernameFromState (🐢 slow load and 'unknown' during textile init) . should be removed later

fix(chat): reaction buttons style and ui

---

components/views/settings/modal/Modal.html
cypress/integration/chat-features.js
cypress/integration/chat-pair-features.js
cypress/integration/create-account.js
cypress/integration/mobiles-responsiveness.js
cypress/support/commands.js

- Fixed Send Money - Coming Soon cypress test on chat-features.js
- Unskipped cypress tests on chat-pair-features.js, fixed timestamp tests and remove the timestamp validation after 60 seconds, since timestamp is displayed with HH:MM AM/PM format. The removed test scenario is no longer adding any value to the test suite now
- Fixed create-account.js cypress tests validating error messages, by implementing the use of should contain, instead of should have.text
- Unskipped cypress tests for mobiles-responsiveness.js and applied fixes to swipe and glyphs modal validations
- Added a new cypress command to retrieve the timestamp from system used to return the expected value for the chat messages timestamp
- Added data-cy attribute for close modal button on settings, …

test(cypress): updates on mobiles and pair tests

---

cypress/integration-pair-chat/chat-first-user.js
cypress/integration/chat-pair-features.js
cypress/integration/privacy-page-toggles.js

- Using an imported account for privacy-page-toggles.js cypress tests instead of creating a new account for this test
- Minor updates on the cypress tests from this file to ensure that all of them are passing
- Removed one test scenario from this file that was validating the default status of privacy toggles when a new account was created, since we are no longer creating an account to validate this test
- Skipping timestamp cypress tests on chat-pair-features.js since these require small improvements that will be addressed on a different PR. Also, skipped the last videocall test for chat-first-user.js that tends to fail and will be adjusted in a separate PR
AP-1882 …

test(cypress): updates to privacy settings tests

---

components/views/chat/message/Message.html
components/views/chat/message/Message.vue

- remove unused timestamp data, as well as other unused markup/variables.
- We were using it when timestamps were relative
- this hide-actions prop is trying to turn this into a 'god component'. should probably be removed, but wanted to hear other opinions
AP-1903

chore(message): remove unused timestamp variables

---

components/views/friends/friend/Friend.html
components/views/friends/friend/Friend.less
components/views/friends/friend/Friend.vue

- prevent shrink of profile picture on outgoing friend request
- simplify logic to show uistate or just plain circle on outgoing friend request
AP-1881
ticket mentioned it disappears at a certain point. that's the mobile breakpoint

fix(friends): prevent 'add friend' picture shrinking

---

components/views/user/User.less

fixes lineheight that caused same name's chars to be cutted out (g, y)
AP-1898

fix(user-name-style): fixed name lineheight

---

assets/styles/framework/framework.less
assets/styles/framework/ui.less
components/ui/BackgroundCall/BackgroundCall.html
components/ui/BackgroundCall/BackgroundCall.less
components/ui/BackgroundCall/BackgroundCall.vue
components/ui/Global/Global.html
components/ui/Global/Global.vue
components/ui/Modal/Modal.less
components/views/friends/friend/Friend.vue
components/views/media/Media.vue
components/views/media/heading/Heading.html
components/views/media/heading/Heading.vue
components/views/navigation/toolbar/Toolbar.html
layouts/Layout.less
layouts/chat.vue
layouts/files.vue
layouts/friends.vue
layouts/server.vue
locales/en-US.js
store/conversation/mutations.ts
store/friends/actions.ts
store/friends/getters.test.ts
store/textile/actions.ts
store/ui/mutations.ts
store/webrtc/__snapshots__/state.test.ts.snap
store/webrtc/getters.ts
store/webrtc/mutations.ts
store/webrtc/state.ts
store/webrtc/types.ts

[AP-1781](https://satellite-im.atlassian.net/browse/AP-1781)

feat(call): create background call component

---

components/views/settings/pages/audio/Audio.html
components/views/settings/pages/audio/index.vue

- Fixes the dropdown for Video Input not opening when user clicks on it in Safari.
AP-1914
- The "Video Input" dropdown problem was caused by an error spawning from missing audio output devices, as Safari does not allow setting “audio out”, which resulted in the function that set up the "Video Input" dropdown being exited before options could be set.

fix(audio): error handling for missing audio output devices

---

components/interactables/Select/Select.less
components/interactables/Volume/Volume.less
components/views/settings/page/Page.html
components/views/settings/page/Page.less
components/views/settings/page/Page.vue
components/views/settings/pages/accounts/Accounts.html
components/views/settings/pages/audio/Audio.html
components/views/settings/pages/developer/Info.html
components/views/settings/pages/info/Developer.html
components/views/settings/pages/keybinds/Keybinds.html
components/views/settings/pages/network/Network.html
components/views/settings/pages/notifications/Notifications.html
components/views/settings/pages/personalize/Personalize.html
components/views/settings/pages/privacy/Privacy.html
components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/Profile.less
components/views/settings/pages/realms/Realms.html
components/views/settings/pages/storage/Storage.html
components/views/settings/section/Section.html
components/views/settings/section/Section.less
components/views/settings/section/Section.vue
components/views/settings/unit/Unit.html
components/views/settings/unit/Unit.less
components/views/settings/unit/Unit.vue

- Adds a `SettingsPage` and `SettingsSection` component to replace the mass of divs and bulma classes.
- Update `SettingsUnit` and `InteractablesVolume` styling
- Updates settings pages to use new components
- Fixes select overflow in settings flexbox layout
AP-1889

feat(settings): add page and section components

---

components/views/user/User.less

Message preview in the sidebar has been changed to one-line to prevent long multi-line text from having a weird line-break that's visually unpleasant especially if containing spoilers
AP-1923

style(sidebar): message preview in sidebar from multi-line to one-line

---

assets/styles/base.less
assets/styles/framework/colors.less
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.less
pages/files/browse/Browse.html
pages/files/browse/Browse.less

I initially made a [huge PR](https://github.com/Satellite-im/Core-PWA/pull/3783) that affected all scrolls on the app, but then we switched main branches. This is a small chunk of that large pr
- global scroll style rules
- add lighter color on hover for webkit (thanks Thomas)
- I think being able to hide the scrollbar until you hover/focus within an element is useful functionality, but I don't think it should be applied to every scrollbar in the entire app. I created a class (.hover-scroll) which will do this. for now, I added it to the chat sidebar. You can test by manually creating elements via the inspector to trigger the overflow
AP-1929

feat(scroll): show scrollbar on hover only option

---

components/views/files/grid/item/Item.html
components/views/files/grid/item/Item.vue
components/views/files/view/View.html
components/views/files/view/View.less
components/views/files/view/View.vue
libraries/Iridium/files/FilesManager.ts
libraries/Iridium/files/types.ts

- if thumbnail can be created, upload to ipfs as a separate file. previously, we were storing base64 thumbnail inside the index. They would typically max out at a few kb, but this makes the index much more lightweight. It wasn't scalable before
- on delete, unpin both file and thumbnail (need to confirm this actually works, left todo)
- on mount, pull thumbnail blob and create object url for display
- revoke object url beforeDestroy to avoid memory leaks
- add background color for blurred nsfw images, they were slightly translucent before
- removed jsdoc from self explanatory computed
- minor refactoring around upload logic to make it reusable for thumbnails
AP-1877

feat(files): refactor thumbnails to lazy load

---

components/views/files/controls/Controls.vue
libraries/Iridium/files/FilesManager.ts
libraries/Iridium/files/types.ts

- remove component side file upload validation since it's being handled in iridium methods
- switch max upload size limit check to iridium index, was pointing at legacy FilSystem before
- prevent duplicate errors
- switch try catch to more concise promise.catch
AP-1288

refactor(files): remove redundant validation

---

components/views/friends/add/Add.less
components/views/friends/add/Add.vue
components/views/friends/friend/Friend.html
components/views/friends/friend/Friend.vue
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.vue
components/views/user/User.vue
libraries/Iridium/friends/FriendsManager.ts
libraries/Iridium/friends/types.ts
pages/auth/unlock/index.vue
pages/chat/direct/_address.vue
pages/friends/list/FriendsList.html
pages/friends/list/FriendsList.less
pages/friends/list/index.vue

Fixed friends requests display
AP-1954
Still missing some data to show (name and image, just when the other user hasn't accepted the request)

fix(friends-requests): improved requests and notifications display

---

layouts/basic.vue
pages/chat/Chat.html
pages/chat/_id.vue
pages/files/browse/Browse.html
pages/files/browse/Browse.less
pages/files/browse/index.vue

- we plan on using the same pages for mobile, but a different layout.
- this moves droppable wrapper logic upto the desktop level
- conditionally render based on path
AP-2037

refactor(layout): move droppable wrapper up to desktop layout

---

components/views/navigation/sidebar/list/List.html
components/views/navigation/sidebar/list/List.vue
components/views/navigation/sidebar/list/item/Item.vue
libraries/Iridium/chat/ChatManager.ts

- sort sidebar items by most recent
AP-2004

feat(chat): sort sidebar items

---

components/interactables/AsideMenu/AsideMenu.less
components/typography/NumberedWord/NumberedWord.less
components/views/settings/Sidebar.vue
components/views/settings/modal/Modal.html
components/views/settings/modal/Modal.less
components/views/settings/pages/accounts/Accounts.html
components/views/settings/pages/info/Developer.html
components/views/settings/pages/network/Network.html
components/views/settings/pages/realms/Realms.html
components/views/settings/pages/storage/Storage.html
package.json

- improve settings modal styles
- remove settings breadcrumbs since they're not adding a lot of value. not clickable, plus the sidebar tells you where you are
- remove swiper and scroll components from settings modal
- remove 50% limit some pages were getting from the settings layout components
AP-2041

fix(settings): improve settings modal styles, remove old swiper package

---

libraries/Iridium/groups/GroupManager.ts
libraries/Iridium/users/UsersManager.ts
libraries/Iridium/users/types.ts

- Adds a UserManager to handle iridium user data.
AP-2046
- This PR only creates UserManager, no changes in external components or managers to connect with UserManager has been made. 
- Future tickets will handle replacing the user data currently handled separately in both the FriendsManager and GroupManager with user data inside UsersManager, in order to keep user consolidated in one place.

feat(group-manager): create manager to handle iridium user data

---

components/views/group/invite/Invite.less
components/views/group/invite/Invite.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.less
components/views/navigation/toolbar/Toolbar.vue
libraries/Iridium/groups/GroupManager.ts
libraries/Iridium/groups/types.ts
store/ui/types.ts

- Fix group invite relative position
- Connect group invite UI to iridium
AP-2025
- Although the user is added to the group in both the group and conversation manager, the members list was not updated in the Toolbar component.

feat(iridium): add member to group

---

components/views/files/aside/Aside.less
components/views/files/grid/Grid.html
components/views/files/list/List.html
components/views/files/mobileList/mobileList.html
pages/files/Files.less

- append timestamp.toString() so files with the same CID have unique keys. This was breaking in 'recent' view before
- unrelated css bug where aside sticky was applied to the wrong element
AP-2039

fix(files): resolve duplicate id issue

---

components/views/chat/conversation/Conversation.vue
components/views/navigation/sidebar/list/List.vue
components/views/navigation/sidebar/list/item/Item.vue
libraries/Iridium/IridiumManager.ts
libraries/Iridium/chat/ChatManager.ts

- switch to object only message storage. experimented with an array too so it wouldn't need to be sorted, but that was complicated.
- publish entire message payload and then store for recipient. this is a temporary solution while Drew investigates the CID load method
- previous messages don't have an id attached to the payload. they will render strangely

feat(chat): render and store incoming messages

---

components/interactables/UserPicker/UserPicker.vue
components/views/navigation/mobile/toolbar/Toolbar.vue
components/views/navigation/sidebar/list/item/Item.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/friends/FriendsManager.ts

- remove Object.values getter on friendsmanager that breaks reactivity. update components accordingly. I noticed when you do an iridium.set before Vue.set, reactivity breaks
AP-2073

fix(friends): reactivity when adding friends

---

components/ui/Chat/Image/Image.less
components/views/chat/chatbar/Chatbar.vue
components/views/chat/message/Message.html
components/views/chat/message/attachments/Attachments.html
components/views/chat/message/attachments/Attachments.less
components/views/chat/message/attachments/Attachments.vue
components/views/chat/message/attachments/Item/Item.html
components/views/chat/message/attachments/Item/Item.less
components/views/chat/message/attachments/Item/Item.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts

- Connect message file upload to iridium
- Renders message attachments in the chat
AP-2059
*Node that pinning of file to IPFS isn't implemented yet so attachments don't include a `src` property yet*

feat(chat): connect file upload to iridium

---

tsconfig.json

- Fixes an invalid path in tsconfig to stop invalid root import warnings from being displayed.
AP-2170

fix(build): resolve root import warnings

---

.gitignore
linkscript.sh

A lot of people are having problems with iridium getting cloned into core to be linked, test to do everything outside of core and seeing if the autodeploy works okay with that

chore(linkscript): move iridum clone up a level, out of core

---

components/interactables/UserPicker/UserPicker.vue
components/views/friends/requests/Requests.vue
components/views/friends/search/Search.vue
components/views/media/incomingCall/IncomingCall.vue
components/views/navigation/mobile/toolbar/Toolbar.vue
components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.vue
components/views/navigation/sidebar/live/Live.vue
components/views/navigation/toolbar/Toolbar.vue
libraries/Iridium/IridiumManager.ts
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/friends/FriendsManager.ts
libraries/Iridium/groups/GroupManager.ts
libraries/Iridium/profile/ProfileManager.ts
libraries/Iridium/profile/types.ts
libraries/Iridium/users/UsersManager.ts
libraries/Iridium/webrtc/WebRTCManager.ts
pages/friends/index.vue
store/accounts/actions.ts

- Add search peer functionality to users manager
- Replace friends manager details object with users manager
- Use users manager in components
- AP-2098
- AP-2161

feat(iridium): connect to users manager

---

assets/styles/base.less
assets/styles/framework/ui.less
components/ui/BackgroundCall/BackgroundCall.html
components/ui/BackgroundCall/BackgroundCall.vue
components/ui/Global/Global.html
components/ui/Pip/Pip.vue
components/views/media/Media.vue
components/views/media/previewCall/PreviewCall.html
components/views/media/previewCall/PreviewCall.less
components/views/media/previewCall/PreviewCall.vue
components/views/media/user/User.less
config.ts
locales/en-US.js

PiP component for background calls
AP-2048
AP-2092

feat(calls): pip component

---

components/ui/Chat/TypingIndicator/TypingIndicator.less
components/ui/Chat/TypingIndicator/TypingIndicator.vue
components/ui/Global/Global.vue
components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/footer/Footer.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts
libraries/Iridium/webrtc/WebRTCManager.ts

Restore is_typing indicator in chat.
When the user sends the message, on the receiver the typing indicator is removed
AP-2017
If we will have hooks for the conversation some of the code can be refactored

feat(chat): is_typing indicator

---

components/views/files/controls/Controls.less
libraries/Iridium/files/FilesManager.ts
pages/files/index.vue
store/files/getters.ts

- Fixes reactivity for file name changes
- Fixes deletion from removing incorrect files
AP-2168
- These problems occurred due to the item data in "store/files/getters.ts" becoming cloned to avoid direct mutational changes from happening to the file state. As the file actions (including rename, delete, and like) were relying on directly mutating the file state they stopped working.
- @josephmcg Would you prefer the current fix and prevent direct mutation of the iridium file state to avoid any potential unintended side-effects? Or should we keep the original structure so the state can be directly mutated? Can understand the benefit of not cloning whenever a change is made, but considering the scope …

fix(files): fix rename reactivity and delete action

---

.eslintrc.json
jest.config.js
package.json

- Adds eslint for Cypress
- Ignores Cypress tests on Jest config
- Adds iridium to be ignored on jest.config.js to avoid running tests from iridium repo

chore(eslint): add cypress eslint 

---

assets/styles/base.less
assets/styles/framework/typography.less
components/typography/Tag/Tag.vue
components/typography/Text.vue
components/views/media/Media.html
components/views/media/Media.less
components/views/media/Media.vue
components/views/media/heading/Heading.html
components/views/media/heading/Heading.less
components/views/media/incomingCall/IncomingCall.html
components/views/media/user/User.html
components/views/media/user/User.less
pages/chat/Chat.html
pages/chat/_id.vue
types/typography.d.ts

- refactor tag component to use slots and new Text component
- remove extra container elements from mediaUser. display both video and screenshare at the same time if possible. Still needs some additional styling if 2 windows are shown for 1 user. I wanted to break this out separately since it may be fairly involved
- adjust call loader to not display user image, only loader
- switch position of incoming call buttons so accept is on the right. I believe this is the convention in most user interfaces
- add overflow scroll to media window
AP-2213

refactor(calls): improve mediaUser markup

---

assets/styles/base.less
components/ui/DroppableWrapper/DroppableWrapper.vue
components/ui/Global/Global.html
components/views/friends/requests/Requests.vue
layouts/desktop.vue
layouts/mobile.vue
utilities/notNull.ts

- remove bg call banner since PIP serves the same purpose(but does it better)
- remove background gradient from `#app` since it was stacking with the `body` gradient behind it
- break out non null filter to utility function. fix eslint error in desktop.vue related to null files
- remove guard clause from droppable wrapper. It was preventing the glow effect from showing when you drag and drop text files
AP-2204

feat(calls): remove background call banner

---

store/ui/getters.test.ts

- Skips test in order to avoid generating a snapshot that will be needed updating when we finish ditching pinata.

chore(jest): update test

---

components/interactables/DragBar/DragBar.less
components/views/chat/conversation/Conversation.less
components/views/media/Media.html
components/views/media/Media.less
components/views/media/Media.vue
components/views/media/heading/Heading.less
components/views/media/heading/Heading.vue
plugins/thirdparty/persist.ts
store/ui/__snapshots__/state.test.ts.snap
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts

- remove max height limit on call window
- add dragbar that Jason made a few months ago
AP-2224

feat(calls): add dragbar resize

---

components/views/group/invite/Invite.vue
components/views/navigation/sidebar/list/item/Item.vue
libraries/Iridium/chat/ChatManager.ts

- Fix recipient info displayed in sidebar for conversation
- Implement add to group
- Implement leave group
- AP-2223

feat(iridium): group add member

---

components/views/files/controls/switch/Switch.less
components/views/files/filepath/Filepath.less
components/views/navigation/mobile/nav/Nav.less

- wrap directory names
- add better contrast to mobile nav
AP-2227
- maybe we need to break the view switcher into a separate container. looks kinda weird once it starts wrapping. this at least fixes the overflow

fix(files): mobile wrap for directory name

---

components/views/navigation/toolbar/Toolbar.vue
libraries/Iridium/webrtc/WebRTCManager.ts
libraries/WebRTC/Call.ts

Refactor the mute/unmute logic. Now when the call is still pending you can unmute (video/audio/screen) and they'll work as expected.
AP-2211

fix(calls): mute/unmute logic

---

components/ui/Chat/TypingIndicator/TypingIndicator.vue
components/views/chat/chatbar/footer/Footer.html
components/views/chat/chatbar/footer/Footer.vue
config.ts
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts
libraries/Iridium/webrtc/WebRTCManager.ts

Move the typingStatus outside of the conversations state in the ChatManager, and set the throttle time to 5 secs (honestly more than this is not a great user experience)
AP-2219

fix(webrtc): typing status indicator

---

components/interactables/Input/Input.vue
components/views/friends/search/Search.vue

- Disables autofocus on mobile devices.
- Adds delay to autofocus for InteractablesInput component to prevent swiper animation from breaking.
AP-2239

fix(friends): stop input autofocus from breaking swiper animation

---

components/views/media/Media.html
components/views/media/Media.less
components/views/media/actions/Fullscreen.vue
components/views/media/actions/volume/Volume.html
components/views/media/actions/volume/Volume.less
components/views/media/actions/volume/Volume.vue
components/views/media/heading/Heading.html
components/views/media/heading/Heading.less
components/views/media/heading/Heading.vue

- organize call controls so theyre better positioned. the modern convention for fullscreen toggle is the bottom right. may as well put the other buttons there too since most websites do. We want a familiar UI
- remove cog button because it doesnt do anything
AP-2240
- the volume components are a bit tangled. settings uses the same volume component with a call, but greatly transforms it with props. kinda weird

feat(calls): reposition call controls

---

components/ui/Global/Global.vue
libraries/Iridium/webrtc/WebRTCManager.ts
libraries/Iridium/webrtc/types.ts
libraries/WebRTC/Call.ts
store/audio/actions.ts
store/video/actions.ts
store/webrtc/actions.ts

- Initiates WebRTCManager state with user selected audioIn and videoIn devices.
- Updates WebRTCManager state when user selected audioIn and videoIn devices change.
- Initiates calls with user selected audioIn and videoIn devices using WebRTCManager state.
AP-2231
- This PR is outside the scope of switching audio/video stream devices while call is active. Switching devices during active calls will be implemented in a separate future PR.

feat(webrtc): initialize webrtc streams with user selected devices

---

components/ui/InlineNotification/InlineNotification.html
locales/en-US.js
pages/auth/unlock/Unlock.html
pages/auth/unlock/Unlock.less
pages/auth/unlock/index.vue

Adds a warning message on unlock page to recommend Chrome, but still allow user to log in/create account
this is hidden on mobile, and removes the realms since we dont have realms rightnow. Firefox on desktop does not trigger the mobile flag when resized like chromium browsers do

chore(unlock): notice on unlock page to recommend chrome

---

components/interactables/Button/Button.less
components/views/media/incomingCall/IncomingCall.html

- added md and lg variant for now
- slightly increases font size of md size all over the app. I think it improves readability
- set incoming call to lg. looks a lot better. maybe mobile should be even bigger though. could always conditionally pass xl (or 2xl)
AP-2242

fix(buttons): build out size prop

---

components/ui/Global/Global.html
components/views/navigation/sidebar/list/List.html
components/views/navigation/sidebar/list/item/Item.vue
pages/mobile/chat/_id.vue

- enter into already selected chat on touch if user swiped back. previously, swiping was the only way to get back
- hide svg definitions, they were taking up noticeable space on mobile
- automatically go to slide 2 when you answer a call on mobile

fix(mobile): fix swiper issues around mobile chat

---

components/views/chat/message/attachments/Item/Item.less
components/views/chat/message/notice/Notice.html
components/views/navigation/sidebar/list/item/Item.vue
locales/en-US.js

- Show strings for other message types in the sidebar, eg;
- File attachments
- Glyphs
- Group join/leave messages
- Fix button alignment in file attachment component
AP-2250

feat(sidebar): display other message types in message preview

---

components/interactables/KeybindInput/KeybindInput.html
components/interactables/KeybindInput/KeybindInput.vue
components/ui/Modal/Modal.html
components/ui/Modal/Modal.vue
layouts/desktop.vue

feat(modal): close on 'Escape' key

---

assets/styles/framework/ui.less
components/ui/BackgroundCall/BackgroundCall.html
components/ui/BackgroundCall/BackgroundCall.less
components/ui/BackgroundCall/BackgroundCall.vue
components/ui/Global/Global.html
components/ui/Global/Global.vue
layouts/mobile.vue
locales/en-US.js
pages/mobile/friends/index.vue

- title
- unrelated friendsList display bug on mobile. using old variable name
AP-2175

feat(mobile): background call indicator on mobile

---

components/views/chat/chatbar/Chatbar.vue
config.ts
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/webrtc/WebRTCManager.ts

Fix some typing indicator bugs:
* Switch toggle in favour of set, more resilient;
* Added a debounce function inside the throttling so to not spam with the typing event if i send quickly a lot of messages;
* Moved function outside the methods because Vue was hiding the `.cancel` lodash method on throttle and debounce.
AP-2252

fix(typing): typing indicator bug

---

utilities/chat.test.ts

Increase coverage for two untested cases.
AP-2247

feat(jest): 100% coverage for utilities/chat

---

libraries/Iridium/notifications/__snapshots__/types.test.ts.snap
libraries/Iridium/notifications/types.test.ts

feat(jest): 100% coverage for Iridium/notifications/types

---

components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/index.vue

- Restores reactivity for template elements using iridium profile state, including for username and status updates
Resolve #4533 

fix(settings-profile): restore reactivity

---

components/views/files/grid/Grid.html
libraries/Iridium/files/FilesManager.ts

- The file item array now gets converted to arrays when stored in iridium. This PR converts them back when the files in iridium are initiated in the FilesManager state
Relolve #4549 

fix(files): convert iridium files state to FilesManager state on fetch

---

libraries/Phantom/PhantonManager.test.ts

Self-explanatory. Improvements to come as Drew will change the wallet flow.
AP-2142

feat(jest): 17% coverage for PhantomManager

---

components/views/files/mobileList/item/Item.less

look like this instead of additional border at bottom
Resolve #

fix(files): only show border if not last child

---

pages/mobile/chat/_id.vue

If you got pushed to mobile consent settings from a chat page, nav would still be hidden. Fixes that
Resolve #

fix(mobile): show mobile nav on consent push

---

components/views/settings/modal/Modal.html

- title
- did this because v-if is lazy, while v-show has a higher initial load cost. For something that will be toggled several times, v-show will have better performance
Resolve #

refactor(settings): v show instead of v if for settings modal

---

assets/styles/base.less
components/interactables/DragBar/DragBar.less
components/interactables/Volume/Volume.html
components/interactables/Volume/Volume.less
components/interactables/Volume/Volume.vue
components/views/media/Media.html
components/views/media/Media.less
components/views/media/Media.vue
components/views/media/actions/Actions.html
components/views/media/actions/Actions.less
components/views/media/actions/Actions.vue
components/views/media/actions/volume/Volume.html
components/views/media/actions/volume/Volume.less
components/views/media/actions/volume/Volume.vue
components/views/media/heading/Heading.html
components/views/media/heading/Heading.less
components/views/media/heading/Heading.vue
components/views/media/user/User.html
components/views/media/user/User.less
components/views/media/user/User.vue
components/views/settings/pages/audio/Audio.html
libraries/Iridium/users/UsersManager.ts
plugins/thirdparty/persist.ts
store/video/__snapshots__/state.test.ts.snap
store/video/state.ts
utilities/AudioStreamUtils.ts
utilities/duration.ts

- Improve volume slider
- Improve drag bar
- Calculate optimal MediaUser dimensions
- Refactor calling UI
- Update talking indicator
- #4526

feat(media): call ui updates

---

components/views/media/user/User.html
components/views/media/user/User.vue

- Setting "Mirror VIideo" in Settings > Audio & Video would not update the local video stream in the active call
Resolve #4653 

fix(reactivity): flip local video setting in calls

---

components/interactables/Button/Button.html
components/interactables/Button/Button.less
components/interactables/Button/Button.vue
components/views/navigation/sidebar/Sidebar.html
components/views/user/create/Create.html

- Adds disabled styling to InteractablesButton component
- Disable profile pic upload on account creation
- Remove disabled conditions for sidebar tab buttons
Resolve #4651 

fix(user-create): disable profile pic upload on account creation

---

components/views/settings/pages/audio/Audio.html
components/views/settings/pages/audio/index.vue
components/views/settings/pages/privacy/Privacy.html
components/views/settings/pages/privacy/index.vue

- this was more relevant while we used textile because it was super slow. The remote update is relatively quick now, so this keeps things more predictable. When a switch was changed to Locked, it would lose keyboard focus
Resolve #

fix(settings): remove loading message while updating remote settings

---

assets/styles/framework/typography.less
components/interactables/ContextMenu/ContextMenu.less
components/interactables/Input/Input.html
components/interactables/Input/Input.vue
components/interactables/Permissions/Permissions.vue
components/typography/Text.vue
components/ui/ContextMenu/ContextMenu.vue
components/views/chat/chatbar/footer/Footer.html
components/views/chat/chatbar/upload/Error.vue
components/views/files/controls/Controls.html
components/views/files/controls/Controls.vue
components/views/files/rename/Rename.html
components/views/friends/search/Search.vue
components/views/settings/pages/privacy/Privacy.html
components/views/settings/pages/realms/realm/Realm.html
components/views/user/create/Create.html
pages/auth/unlock/Unlock.html
types/typography.d.ts

- switch typography text to use 'danger' for red, rather than 'error'. this fits in better with the rest of the app
- switch a couple error messages using old component
- decrease opacity for disabled context menu items. It wasn't low enough
Resolve #

fix(errors): cleanup errors with wrong color

---

components/views/navigation/toolbar/Toolbar.vue

- couldn't find your own username via userManager direct state access. Jason and I added a guard clause (in another ticket) to the getUser method that will fetch your own info from profile state as needed
Resolve #4599 

fix(toolbar): pull your own name in group lists

---

components/ui/Pip/Pip.vue
utilities/animation.ts

- Use animation keyframe for PIP drag and drop animation
- Add animations utility functions
- Add drop shadow to PIP
Resolve #4668 

feat(pip): use animation keyframe

---

components/ui/Pip/Pip.vue
components/views/media/user/User.vue

- Stops green border around MediaUser component from disappearing after page change
Resolve #4458 

fix(media-user): ensure AudioStreamUtils is re-enabled on page changes

---

components/views/media/Media.html
components/views/media/Media.less
components/views/media/Media.vue
components/views/media/user/User.html
components/views/media/user/User.less
components/views/media/user/User.vue
utilities/AudioStreamUtils.ts

- Hide talking indicator for presenter
- Fix presenter thumbnail styling
- Fix username overflow in MediaUser
- Only show talking indicator for one participant stream (eg video only if sharing both video and screen)
Resolve #4656

fix(call): only show talking indicator for one stream

---

components/views/friends/search/Search.vue

-  i broke this when i switched the tabs to v-show. It was getting mounted while the tab was not displayed, so it wouldn't autofocus. This will force the input to remount when you open the tab
Resolve #

fix(friends): autofocus on desktop add friend

---

libraries/WebRTC/Call.ts

- Mutes the screen stream after it has been ended by the browser
Resolve #4708

fix(call): mute screen stream after it has ended

---

components/ui/CaretDivider/CaretDivider.less
components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.less
components/views/chat/conversation/Conversation.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
locales/en-US.js

- If the chat is at the bottom, scroll it to the bottom when the dom mutates
Resolve #4128

feat(chat): lock scroll to bottom of chat

---

components/views/chat/conversation/Conversation.vue

- Fixes chat items map selecting wrong prev message
Resolve #4719

fix(chat): fix chat items prev message

---

assets/styles/framework/typography.less
components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.vue

- Trims the subtitle text to a single line
- Resolve #4732

fix(sidebar-list-item): show subtitle text as single line

---

components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.less

- push scrollbar to the edge of the sidebar, rather than being snug against the list items. See ticket for screenshot of old display
- list items are visible at the very bottom of the list, rather than 16px of background-color
- Resolve #

refactor(sidebar): apply padding to individual sidebar elements

---

components/views/media/Media.vue
libraries/Iridium/IridiumManager.ts
libraries/Iridium/webrtc/WebRTCManager.ts
libraries/WebRTC/Call.ts

- when a second incoming call is happening, the UI doesn't show anymore any extra box in the Media component
- Resolve #4646
- thanks for reviewing 🙏
To test it you have to open 3 browsers with 3 different users (UserA, UserB, UserC). Make sure that one of them is friend with both the others (for example UserA is friend with both UserB and UserC). Create a call from UserA to UserB, then go to UserC and call UserA. If you look at the UserA UI you should not see any extra box in the Media component. Then if you go back to UserC and hang up, the call between UserA and UserB should keep going.

fix(webrtc): media UI + hangup during second incoming call

---

components/views/chat/UserList.vue
components/views/navigation/toolbar/Toolbar.less
components/views/navigation/toolbar/Toolbar.vue
locales/en-US.js
pages/chat/Chat.html
pages/chat/Chat.less
pages/chat/_id.vue

- create new sidebar for group chats to display user list and online/typing status
- Resolve #
- This does not show your own typing status in the group sidebar. I think that should be a separate ticket because it has potential to introduce bugs
- This can be built upon. maybe add some click logic/context menus eventually

feat(chat): new group member sidebar for group chats

---

components/views/navigation/sidebar/Sidebar.less
components/views/navigation/sidebar/list/List.less
components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.less

Before:
After:
- Resolve #4753

fix(sidebar-list-item): time section constraining last message width

---

components/views/media/Media.less

- no flex shrink on mediatream
- Resolve #4775

fix(calls): dont shrink mediastream

---

assets/styles/framework/glows.less
components/ui/Modal/Modal.less
components/ui/Pip/Pip.vue

- Removed `@ui-shadow-large` since it was causing a weird halo effect
- Use `@ui-shadow` for modal and pip container
- Resolve #4780

fix(ui): large object shadows

---

components/compositions/conversations.ts
components/views/chat/UserList.vue
components/views/chat/chatbar/Chatbar.html
components/views/navigation/mobile/toolbar/Toolbar.html
components/views/navigation/mobile/toolbar/Toolbar.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.vue
pages/chat/_id.vue

- no new functionality, just organization and consolidation.
- add a new hook ( otherTypingParticipants). haven't implemented in a component yet, that will come separately
- Resolve #
- Will add typing chat footer after new hook here gets merged

refactor(conversation): improve hooks to avoid repeated logic

---

components/ui/GroupIcon/GroupIcon.less

- group icon was getting shrunk because of recent sidebarListItem changes. This prevents the following visual bug
- I applied at the component level since it should be a universal rule. I think we already apply this independently in the two Toolbar components
- Resolve #

fix(sidebar): group icon flex bug

---

components/views/settings/pages/profile/index.vue
libraries/Iridium/profile/ProfileManager.ts
store/accounts/actions.ts

- observer was getting blasted away because profile state was reassigned after a remote set
- remove unused profile action
- Resolve #

fix(account): proper reactivity on profile update

---

components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.less

- title
- refactor to remove some redundant css classes
- Resolve #4788 
- Resolve #4778

fix(sidebar): prevent new message indicator from shrinking

---

components/views/settings/pages/profile/Profile.html

- Changed account ID's do not work in search. Disables username editing until this is resolved.
- Resolve #4802

fix(settings-profile): disable editing of username

---

components/views/chat/conversation/Conversation.vue
components/views/chat/message/replies/Replies.less

- Checks that only children message elements are add to the messages container in the MutationObserver callback
- Fix padding in message replies container
- Resolve #4795

fix(chat): only scroll to bottom when adding children

---

components/views/chat/message/actions/Actions.html

- Removes coming soon UI on groups reply to message/reactions, this is working but it had the coming soon UI that wasn't removed previously
before
https://user-images.githubusercontent.com/29093946/190521119-cdd09377-a587-4918-bf9a-d0fb992d8744.mov
after
https://user-images.githubusercontent.com/29093946/190522179-502c2299-4410-4853-89fd-5a16d432f9e1.mov

chore(groups): remove coming soon

---

components/views/friends/add/Add.html
pages/mobile/friends/index.vue

- Hide's QR section because it doesn't work
before
after

chore(qr): hide qr section

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.less
components/views/chat/conversation/Conversation.vue
locales/en-US.js
plugins/thirdparty/persist.ts
store/chat/__snapshots__/mutations.test.ts.snap
store/chat/__snapshots__/state.test.ts.snap
store/chat/mutations.test.ts
store/chat/mutations.ts
store/chat/state.ts
store/chat/types.ts

- move Chatbar uploading local state variable to vuex store.
- I did this to put the message loader in a different component
- it also ensures the state is maintained even if chatbar is unmounted
- display loader if store array contains this conversationId
- still allow new messages to be sent even if a previous upload is still in progress
- Resolve #4823

feat(chat): unblock sending while file upload in progress

---

components/interactables/Volume/Volume.html
pages/mobile/settings/index.vue

- Fix volume slider overflow on mobile
- Disable swiper on mobile when sliding volume slider
- Resolve #4875

fix(mobile): fix slider swipe and overflow

---

components/views/settings/pages/privacy/Privacy.html
components/views/settings/pages/privacy/index.vue
locales/en-US.js

- fixes the crash occured when the settings modal was opened on safari
- Resolve #

fix(settings-safari): fixed crash

---

components/views/navigation/mobile/toolbar/Toolbar.html
components/views/navigation/mobile/toolbar/Toolbar.less

- title
- hide video call icon for now
- Resolve #4893

feat(mobile): better disabled state on mobile toolbar

---

plugins/thirdparty/persist.ts
store/accounts/actions.ts

- avoid cleartext seed phrase persistence in local storage (only the encrypted version is persisted)
- avoid entropy message persistence in local storage (dynamically computed all the time)

fix(seedPhrase): avoid cleartext seed phrase persistence in local storage

---

store/accounts/mutations.test.ts
utilities/animation.test.ts

- 100% coverage for store/accounts mutations.ts
- 27% coverage for utilities animation.ts
AP-2690 for Utilities coverage, no ticket for store/accounts coverage

feat(jest): increase coverage on store/accounts & utilities

---

components/views/settings/pages/keybinds/index.vue

add a loop to reset to individually reset each keybind
- Resolve #
#4931

fix(keybinds): add new call to reset defaults

---

components/interactables/Editable/Editable.vue
components/views/chat/message/Markdown.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
components/views/chat/message/Message.vue
components/views/chat/message/actions/Actions.html
components/views/chat/message/actions/Actions.vue
components/views/chat/message/edit/Edit.html
components/views/chat/message/edit/Edit.less
components/views/chat/message/edit/Edit.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts
locales/en-US.js

Implement message edit functionality.
- Resolve #4723
If you send a new message and edit it while the other user is offline, the latter will receive the original copy. (same problem of the reactions while offline)
Noticing some problems with the enhancers, disabled here, will fix on a separate PR.

feat(chat): edit messages

---

libraries/Iridium/chat/ChatManager.ts

- Make sure not to append the message in chat until it has been stored and published in iridium. The loader in chat is missing though
- Resolve #

fix(chat): send message after store&publish

---

components/views/chat/conversation/Conversation.vue

- Insert user header in chat when lastMessage is more than 5 minutes ago or if it's the next day
- Resolve #

fix(chat): user headers fix

---

components/views/navigation/sidebar/status/Status.html
components/views/navigation/sidebar/status/Status.vue
components/views/settings/pages/profile/Profile.html
libraries/Iridium/profile/ProfileManager.ts

- fix reactivity issue
- https://github.com/Satellite-im/Core-PWA/pull/4868/files#diff-d5b9078a59a5c8f17f09c224543040f8238b1387bc842c8600ea15168ce10f0e
- Resolve #4916

fix(sidebar): user status reactivity bug

---

utilities/Timezone.test.ts
utilities/duration.test.ts

100% coverage for utilities/Timezone
88% coverage for utilities/duration
Ticket: AP-2691

feat(jest): increase coverage for time utilities

---

components/ui/EarlyAccessBanner/EarlyAccessBanner.vue

- title. noopener is important for security. noreferrer is more about privacy
- most browsers handle this automatically, but opera seems to be lagging https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#browser_compatibility:~:text=target%3D%22_blank%22%20implies%20rel%3D%22noopener%22%20behavior
- Resolve #

fix(feedback): add noopener noreferrer to outbound link

---

components/ui/ConfirmationModal/ConfirmationModal.vue
components/ui/Modal/Modal.html
components/ui/Modal/Modal.less
components/views/ModalDialog/ModalDialog.less
components/views/confirmation/Confirmation.vue
components/views/consentScanConfirmation/ConsentScanConfirmation.vue
locales/en-US.js
pages/auth/unlock/Unlock.html
pages/auth/unlock/Unlock.less
pages/auth/unlock/index.vue

- Asks users if they want to clear their account after clicking "Not you? Create or import an account"
- Resolve #4954

feat(auth): require user confirmation before clearing account

---

components/interactables/Input/Input.html
components/interactables/Input/Input.less
components/interactables/Input/Input.vue

- Add show password toggle to InteractablesInput
- Fix placeholder color
- Fix border radius when input has a button
- Resolve #4389

feat(button): show password toggle

---

components/ui/Global/Global.html
pages/auth/unlock/Unlock.html

- There was an iteration of the UpdateModal in the unlock screen that was missing a modal wrapper, resulting in it getting added to the actual layout of the unlock screen. This PR adds a modal wrapper.
- Resolve #4950

fix(update-modal): wrap unlock screen UpdateModal in modal component

---

components/ui/Popups/ErrorNetwork/ErrorNetwork.vue
components/ui/UpdateModal/UpdateModal.vue
components/ui/WelcomeModal/WelcomeModal.vue

- "tryAgain" and "$t" were returning undefined
- Resolve #4952

fix(error-network): fix undefined errors

---

libraries/Iridium/IridiumManager.ts
store/accounts/actions.ts

Adds a listener for the `stopping` event for IridiumManager. to fix an offline messages issue

fix(user): fix users offline status delay

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.less
components/views/chat/message/Message.html
components/views/chat/message/Message.less
components/views/chat/message/Message.vue

- Add last user edit message in chat when user presses arrow up on the keyboard
- Focus the chatbar after sendind/aborting the message edit
- Resolve #4983

feat(chat): edit last message on keyup

---

components/interactables/Input/Input.html
components/interactables/Input/Input.vue
components/views/user/create/Create.html
pages/auth/unlock/Unlock.html

- switch unlock input to md since it's the only one on the page, no reason to make it small
- force mobile inputs to be 1 rem (16px default) so ios won't zoom on focus
- Resolve #5014

fix(inputs): remove auto zoom on all ios inputs

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue

- Edit event on keydown
- Only edit if chatbar is empty
- Resolve #5008

fix(chat): edit on keydown and no text in chatbar

---

components/interactables/QuickProfile/QuickProfile.html
components/interactables/QuickProfile/QuickProfile.less
components/interactables/QuickProfile/QuickProfile.vue
components/views/chat/UserList.vue
components/views/chat/message/Message.html
libraries/Iridium/chat/ChatManager.ts

- add click hander on Message avatar
- improve overflow logic so it doesn't hug the edge of the screen
- add click handlers and hover state on group chat sidebar
- Resolve #4965

feat(quickProfile): improve quickProfile ui/ux

---

components/views/chat/message/attachments/Attachments.less

Before:
After:
- Resolve #4801

fix(messages): display attachments in single row

---

components/ui/InfoButton/InfoButton.vue
components/views/settings/pages/profile/Profile.html

- Hides button on settings to avoid this https://github.com/Satellite-im/Core-PWA/issues/5042
before
after

chore(hide): hide button

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/controls/Controls.html
components/views/chat/chatbar/footer/Footer.html
components/views/chat/chatbar/footer/Footer.less
components/views/chat/chatbar/footer/Footer.vue
components/views/chat/chatbar/upload/Upload.html
components/views/chat/chatbar/upload/Upload.less
components/views/chat/chatbar/upload/Upload.vue
libraries/Iridium/IridiumManager.ts
libraries/Iridium/chat/ChatManager.ts
locales/en-US.js

- Add "Please wait while connecting..." msg to footer
- Disable all controls while connecting
- Sync offline msgs at startup, once the convos subs are ready and every time a new convo is created
- Resolve #4988 
MUST make sure remote iridium is updated before testing.
The critical part is when the user is connected to the app but on the chatbar we still have the "connecting" msg. If meanwhile the other user sends a msg, this should be received once the "connecting" msg goes away.

fix(chat): add connecting msg to footer

---

components/views/chat/chatbar/Chatbar.vue

- Send typing indicator only when the draft message in the chatbar changes and is not empty
- Resolve #4970

chore(chat): typing indicator only upon text change

---

components/ui/DroppableWrapper/DroppableWrapper.vue
components/ui/ResultsMessage/ResultsMessage.vue
components/views/navigation/sidebar/Sidebar.html
layouts/desktop.vue

- Application was re-rendering between 2 Nuxt components in desktop layout, resulting in unintended side-effects, like the one found in #5047. This PR allows a single Nuxt component to be kept inside of the DroppableWrapper component by disabling the DroppableWrapper instead of conditionally rendering it.  
- Resolve #5047

fix(desktop): stop switching between multiple Nuxt components

---

components/views/files/controls/Controls.vue

- Resets file search state after page change
- Resolve #5048

fix(files): reset search state on controls component destroy

---

components/views/settings/pages/profile/Profile.html

- Whitespace in title slot was affecting layout. This PR removes that whitespace.
- Resolve #5042

fix(profile): remove whitespace from title passed to InfoButton

---

components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/slimbar/Slimbar.less

- switch from 8 on top to 16 so it's inline with the rest of the app
- also simplify props for sidebarListItem name, I've been using h4 for username everywhere and overriding color as needed
- Resolve #

fix(slimbar): vertical padding

---

components/views/chat/conversation/Conversation.vue

- Add resizeObserver on chat conversation to keep the scroll at the bottom even in the case the height of the chatbar increases (like when repling to a msg, or newlines in chatbar) 
- Resolve #5065

chore(chat): add container resize observer

---

components/interactables/Close/Close.html
components/views/glyphs/Glyphs.html
components/views/glyphs/sample/Sample.html
cypress/e2e/chat-features.js
cypress/e2e/chat-glyphs-validations.js
cypress/support/commands.js

- Added new data-cy attributes for glyphs and close button on modals
- Fixed glyphs cypress tests
- Small update to chat-features cypress test for localstorage snapshots used
- Resolve #AP-2846
- One test is skipped due to the open bug "#5069 - Modals extra close icon is fixed". It will be unskipped once that this issue is fixed
Cypress Tests Passed:
Chat Glyphs Tests Cypress Video:
https://user-images.githubusercontent.com/35935591/193355008-2255d814-e2bf-46b4-89ee-3eb3668a8d90.mp4

test(cypress): fixes for glyphs tests locators and commands

---

components/views/chat/conversation/Conversation.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
components/views/chat/message/Message.vue
components/views/chat/message/glyph/Glyph.html
components/views/chat/message/glyph/Glyph.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts

- Add pending and failed status for messages in chat
- Message actions disabled while message are not confirmed
- Red color in case of text message failed, empty `src` for glyphs
- Resolve #4999 
- Pending/failed msgs are kept in an ephemeral state, wont be there on refresh
In the future we should add the `retry` action for failed msgs

feat(chat): add message loader in chat

---

assets/styles/framework/typography.less
components/interactables/Button/Button.less
components/views/callToAction/CallToAction.html
components/views/callToAction/CallToAction.less

- Fix lg button size, lg text size
- Fix CTA modal style:
- Resolve #5118

fix(cta): layout and style

---

components/interactables/Tabs/Tabs.html
components/interactables/Tabs/Tabs.less
components/typography/Tag.vue
components/typography/Text.vue
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.less
components/views/navigation/sidebar/list/item/Item.less
components/views/navigation/sidebar/quick/Quick.less
locales/en-US.js

- switch sidebar top buttons to be more inline with figma
- switch tabs indicator to use Tag component for the friend request count indicator so everything is standardized
- Resolve #5083 
- if everybody likes this, we could make a sidebarButton component to cut back copy/paste here

refactor(sidebar): simplify sidebar button styles

---

components/interactables/Input/Input.html
components/interactables/Input/Input.less
components/interactables/Input/Input.vue
package.json

- move accessibility outline to outer input border (wraps button and appends too, similar to chatbar)
- prevent outline on autofocus inputs
- Resolve #5102

fix(input): improve a11y around input component

---

components/interactables/Editable/Editable.vue

- Hides the placeholder when using an IME:
**Before:**
**After:**
- Resolve #5136

fix(chatbar): placeholder visibility for ime langages

---

components/views/chat/chatbar/upload/Upload.html
components/views/chat/conversation/Conversation.html
components/views/confirmation/Confirmation.vue
cypress/e2e/chat-images-validations.js
cypress/support/commands.js

- Fixes for chat images cypress tests
- Added new data-cy attributes used in this spec
- Small improvements to cypress commands used on chat images tests, mostly adding the new data-cy locators
- Resolve #AP-2846
- Sending a gif with more than 5mb makes the fail test since apparently the functionality just works with smaller images. I am having this test skipped for now, to do more research on this
Cypress Video:
https://user-images.githubusercontent.com/35935591/193694227-2bacdec9-bea4-4a17-8bef-e00e48f0792d.mp4
All specs passed:

test(cypress): fixes for chat images tests

---

libraries/Iridium/chat/ChatManager.ts

- Was previously taking users to friend request page on chat notification clicks. This change takes them to the appropriate chat instead.
- Resolve #5146

fix(notifications): take user to chat on chat notification click

---

components/ui/Banner/Banner.vue
components/ui/Chat/InfiniteScroll/InfiniteScroll.less
components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.less
components/views/chat/conversation/Conversation.vue
components/views/chat/message/replies/Replies.less

- Fix new messages loading in chat once the scrollTop is reached
- Retain the current scroll position once new messages are loaded
- Debounce the 'scroll' event on the messages container
- Resolve #5060

fix(scroll): infinite scroll trigger and scroll position

---

components/views/navigation/sidebar/list/List.html
components/views/navigation/sidebar/list/List.less

- remove search term display if there aren't any results (feels a bit outdated)
- fixes overflow issue on small screens. looked like this
- Resolve #

fix(sidebar): small screen overflow issue

---

components/ui/Global/Global.html
components/ui/Modal/Modal.html
components/ui/Modal/Modal.less
components/ui/Modal/Modal.vue
components/views/files/view/View.html
components/views/files/view/View.less
components/views/files/view/View.vue

- wrap FilesView with UiModal to use better background styles, animation, modal focus trap, and esc event listener
- remove duplicate markup and download button for files with no preview
- unrelated - move incoming call to the first rendered modal. It would get hidden by settings/others. Maybe these should all be v-else-if instead
- Resolve #5149

refactor(files): use UiModal with files fullscreen preview

---

components/interactables/Editable/Editable.vue
components/views/chat/chatbar/Chatbar.html

- replaces the return key on mobile software keyboards with 'send' when composing messages
- Resolve #5215

feat(editable): enterkeyhint attr

---

components/views/chat/chatbar/Chatbar.vue
components/views/chat/conversation/Conversation.vue
components/views/files/controls/Controls.vue
components/views/navigation/sidebar/list/item/Item.vue
libraries/Iridium/chat/ChatManager.ts
store/files/getters.ts

- Array.prototype.at() isn't compatible with Capacitor. The changes made in this PR replaces .at(-1) with [array.length - 1]
- Resolve #5217

fix(native-mobile): remove prototype.at functions for compatibility

---

linkscript.sh

This makes linkscript more self contained - doesn't need env inputs for now to build it.
Should just be, from a fresh repo
`yarn && chmod +x ./linkscript.sh && yarn dev` to run it.  Front ends will need either nothing (defaults to dev), or qa/prod for an ENV for DEPLOY_ENV in the root of core
- Resolve #

chore(linkscript): update linkscript

---

.github/workflows/android-apk.yml
.github/workflows/comment-PR-apk.yml

Adds CI to generate a APK on each PR, that way if the compilation on APK breaks, we can have info about it
I also added CI to automatically add a comment when each APK finishes generating, can add a comment with the artifact like this
and if we add more commits the same comment updates as well
I can remove that part if we don't want the comment from the bot

chore(ci): generate android apk

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/footer/Footer.html
cypress/e2e/chat-glyphs-validations.js
cypress/e2e/chat-search.js
cypress/e2e/chat-text-validations.js
cypress/e2e/chat-top-toolbar.js
cypress/support/commands.js

- Fixes for chat-text-validations.js, chat-top-toolbar.js cypress tests to work now
- Updates for chat-search.js cypress test to use an account restored from localstorage. Keeping the test skipped since search bar is a coming soon feature
- Removed skip from one chat-glyphs cypress test now working correctly
- Added data-cy attributes for chatbar footer
- Improvements to cypress commands used in the tests fixed
- Resolve #AP-2846
Cypress Tests Passing:
Chat Search Cypress Video:
https://user-images.githubusercontent.com/35935591/195450394-f5d945c2-313a-4e52-90e7-7be4448a8d92.mp4
Chat Top Toolbar Cypress Video:
https://user-images.githubusercontent.com/35935591/195450421-da05a28f-5956-4cb7-87bf-bbaa11a6112a.mp4
Chat Text Validations Cypress Video: …

test(cypress): fixes for chat toolbar and text tests

---

components/compositions/listenToNotifications.ts
components/interactables/TextButton/TextButton.vue
components/ui/Global/Global.vue
components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/Profile.less
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/friends/FriendsManager.ts
libraries/Iridium/notifications/__snapshots__/types.test.ts.snap
libraries/Iridium/notifications/types.ts

- Handles the logic for notifications, such as fetching text and handling notification click events, inside of the global component
- Moves notification logic inside of the global component into a composition file
- Resolve #5242

refactor(notifications): move all notification logic to global component

---

android/app/src/main/java/im/satellite/core/MainActivity.java
android/app/src/main/res/values/styles.xml

- Utilises entire screen on android, hides status bar and navigation bar backgrounds and instead uses safe area view insets
- Resolve #5302
- 
-

feat(android): overlay status and notification bars

---

cypress/e2e/add-friends.js
cypress/e2e/create-account-negative-tests.js
cypress/e2e/create-account.js
cypress/e2e/localstorage-validations.js
cypress/e2e/mobiles-responsiveness.js
cypress/e2e/pin-unlock-validations.js
cypress/e2e/snapshots-test.js

- Implemented the usage of faker.internet.password on several cypress tests to create usernames, since this one have the capability to set the length of the username created. Setting this to 12 chars. 
- Resolve #
- 
- All tests passing:

test(cypress): update random username to have 12 chars

---

components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.less
components/views/chat/conversation/Conversation.vue
components/views/chat/message/Message.html

- Title
- Couple of bugfix in the ui when loading old messages
- Resolve #5294 
- I'll fix the "You have NUM new messages" logic in a separate ticket
- I'll fix the scroll shifting on new incoming message separately
-

feat(scroll): add leading loader in chat

---

pages/mobile/chat/_id.vue

- Closes a conversation when user returns to chat list to avoid issues such as:
- Any new messages sent to the conversation being marked as read even though the user is no longer in the chat
- Current call banner not appearing immediately after swiping away from chat 
- Resolve #5407

fix(chat): close conversation after swiping to chat list on mobile

---

cypress/integration-pair-chat/chat-first-user.js
cypress/integration-pair-chat/chat-second-user.js

- Modifying chat-first-user.js cypress spece by adding more timeout to wait until remote screen is not present on screen, since there was a timeout issue in one cypress CI execution
- Changed the Cypress.on('uncaught:exception') block to be executed on beforeEach blocks for cypress first user and second user tests
- Small update to use save pin false when creating second account to test the refresh scenario
- Resolve #
- 
-

test(cypress): fixes for cypress call tests

---

components/interactables/Select/Select.html
components/views/settings/pages/personalize/Personalize.html
cypress/e2e/settings-personalize.js
cypress/support/commands.js

- Adding data-cy attributes on [components/interactables/Select/Select.html](https://github.com/Satellite-im/Core-PWA/compare/AP-1345?expand=1#diff-28f900f4864e84fdc40c6cb08e46a6959d2c52aa2a3ed31d3b5213bddea77dc9) and [components/views/settings/pages/personalize/Personalize.html](https://github.com/Satellite-im/Core-PWA/compare/AP-1345?expand=1#diff-df523a93903d79cbd99ada5db9c40ed16b500e21ab2d62af1169a2af015c257b)
- Adding new cypress commands for settings personalize features
- Adding cypress tests for settings personalize change theme and flair
- Resolve #AP-1345
- 
- Cypress Video for Settings-Personalize.js:
https://user-images.githubusercontent.com/35935591/200701768-7bef46ff-2250-4aa9-873e-6d6688bfb0c4.mp4
- Cypress Specs Passed:
- Cypress Videocall Specs Passed:

test(cypress): add settings themes tests

---

components/views/chat/enhancers/Enhancers.vue
components/views/chat/enhancers/emoji/Emoji.html
cypress/e2e/chat-features.js
cypress/e2e/chat-text-validations.js
cypress/support/commands.js

- Adding new data-cy attributes for emoji/glyphs picker tab and emojis frequently used
- Adding new cypress tests for glyphs/emoji picker (AP-1343) on chat-features.js
- Adding new cypress tests for emojis frequently used (AP-1032) on chat-features.js
- Moved the alphabet text message cypress test to chat-text-validations.js file, because it makes more sense to be in this spec
- Found some variables declared with "let" in chat-features.js and chat-text-validations.js cypress spec files that are not reassigned at any moment, so I changed the declaration for these to use const, as per best coding practices
- Added one cypress command for validating emojis recently used displayed on emojis picker. Also, modified the send emoji cypress command to allow the option of just selecting the emoji …

test(cypress): adding emoji picker tests

---

cypress/e2e/chat-features.js
cypress/e2e/chat-pair-features.js

- Add cypress tests for emoji size validations on chat-features.js (AP-1033)
- Add cypress tests for message persisting on editable input when switching conversations on chat-pair-features.js (AP-1034)
- Resolve #AP-1033 and #AP-1034
- 
- Cypress Video for Chat Features js
https://user-images.githubusercontent.com/35935591/201247749-58cfe426-b35d-4106-bbd5-07eea3f4f80e.mp4
- Cypress Video for Chat Pair Features
https://user-images.githubusercontent.com/35935591/201247768-b70337fd-2558-43bd-94b4-da18bf6a345d.mp4
- All Cypress test specs passing:
- No updates to any files related to videocall tests for now

test(cypress): emoji size and messages persisting
