components/interactables/Select/Select.vue
components/mixins/UserPermissions/README.md
components/mixins/UserPermissions/index.ts
locales/en-US.js
package.json
pages/settings/audio/Audio.html
pages/settings/audio/index.vue
store/settings/mutations.ts
store/settings/state.ts
yarn.lock

Updating audio settings and adding permissions request to get microphone sources/inputs. Adding detectrtc library because it handles some of the problems firefox and safari have with not implementing the full permissions api.

chore(settings):

---

components/tailored/commands/preview/Preview.vue
components/tailored/core/chatbar/Chatbar.less
components/tailored/core/chatbar/Chatbar.vue
types/utils/commands.ts
utilities/commands.ts
yarn.lock

Feature finish commands

---

components/tailored/core/chatbar/fileupload/FileUpload.vue
components/tailored/files/uploader/Uploader.html
components/tailored/files/uploader/Uploader.vue

I needed to make this utility ignore case, added it to another file upload component that i don't believe is hooked up yet

bug(file upload icon/preview)

---

components/tailored/core/media/actions/Actions.html
components/tailored/core/media/actions/Actions.vue
package.json
store/dataState/state.ts
yarn.lock

feat(media): media mute button bound to global mute

---

.npmrc
components/tailored/core/incomingCall/IncomingCall.html
components/tailored/core/incomingCall/IncomingCall.less
components/tailored/core/incomingCall/IncomingCall.vue
components/tailored/core/servers/create/Create.html
components/tailored/core/servers/create/Create.less
components/tailored/core/servers/create/Create.vue
components/ui/Modal/Modal.html
components/ui/Modal/Modal.less
components/ui/Modal/Modal.vue
layouts/chat.vue
layouts/chat/Chat.html
mock/users.ts
store/index.ts
store/media/actions.ts
store/media/mutations.ts
store/media/state.ts
types/ui/core.d.ts
yarn.lock

Introducing new component for incoming calls and small refactor for create server modal DOM structure

feat(media): Introducing new component for incoming calls

---

components/interactables/ContextMenu/ContextMenu.vue
components/tailored/core/media/Media.html
layouts/chat.vue

Fixed popup positioning issue.
Coudln't find chatbox scrolldowning problem when showing popup.  
The chatbox scrolling down occurred not only when the context menu was displayed, but also when the window was resized.

SA-46 Profile popup smart positioning: Fixed

---

components/tailored/core/fileupload/FileUpload.less
components/tailored/core/fileupload/FileUpload.vue
components/tailored/files/uploader/Uploader.less
nuxt.config.js

Align file icon to top of file upload modal, set meta tags to max and min scale 1 so pwa does not auto zoom on text inputs

chore(mobile, file upload): 

---

components/tailored/core/servers/create/Create.html
components/tailored/core/servers/create/Create.less

Fix responsiveness of create server modal

fix(servers): fix mobile layout of create server modal

---

components/ui/Loaders/GenericContent/GenericContent.vue
components/ui/Loaders/Message/Message.vue

Lessen the color contrast when it comes to messages being loaded in that show the "ui/Loaders/message/Message.vue" as well as the colors in GenericContent loading UI.

SA60 - lessen contrast colors in loading components

---

components/mixins/UserPermissions/index.ts
components/tailored/core/media/actions/settings/Settings.vue
pages/settings/audio/Audio.html
pages/settings/audio/Audio.less
pages/settings/audio/index.vue

Jira ref: SA-62
I'm not completely satisfied with the UI, I'm open to suggestions. Also please let me know if you prefer using a library like Tone.js for the mic level input instead of ```audioContext.createScriptProcessor``` thanks.

feat(sounds): audio input meter

---

components/tailored/core/sidebar/Sidebar.less

Fix for bug : List of friends bounces when going from "friends" to "files".

SA82 - Prevent Friend List bounce

---

pages/settings/audio/index.vue
yarn.lock

fix: audio settings undefined

---

store/audio/mutations.ts
store/audio/state.ts

feat(audio): adjust volume based on deafen state

---

components/tailored/core/media/Media.less
components/tailored/core/media/Media.vue

fix(callers): multiple callers ui revisited

---

components/tailored/core/media/Media.less
components/tailored/core/media/Media.vue

fix(ui): fullscreen aspect ratio

---

components/tailored/core/media/Media.vue
components/tailored/core/media/user/User.html
components/tailored/core/media/user/User.less

fix(ui): user mobile aspect ratio

---

components/ui/Meter/Meter.vue

SA-89: Fixed overflow meteor

---

store/accounts/state.ts
store/audio/state.ts
store/dataState/state.ts
store/files/state.ts
store/friends/state.ts
store/media/state.ts
store/prerequisites/state.ts
store/search/state.ts
store/settings/state.ts
store/ui/state.ts

Fixed console warnings regarding nuxt state  (About Audio Context warning ... It's related with Howler library.. Will try to find a way to solve that in future)

SA-112: Fixed console warnings regarding nuxt state

---

pages/settings/profile/Profile.html
pages/settings/profile/Profile.less

Fixed Smooth issue on Mobile Device

SA-92: Fixed Smooth issue on Mobile Device

---

components/interactables/Search/Input/Input.html
components/interactables/Search/Result/Result.html
components/tailored/core/media/actions/settings/Settings.html
components/tailored/core/sidebar/Sidebar.html
locales/en-US.js

replace all hardcoded text to be located in the 'en-US.json' file

SA 103 : Replace hard coded text

---

pages/index.vue

Fixed 'Unable to scroll homepage on mobile devices'

SA-117: Fixed 'Unable to scroll homepage on mobile devices'

---

components/tailored/files/grid/Grid.html
components/tailored/files/grid/Grid.less
components/tailored/files/list/List.html
components/tailored/files/list/List.less

fix(Files Page): Fix Scrolling

---

components/tailored/core/user/create/Create.html
components/tailored/core/user/create/Create.less
components/tailored/core/user/create/Create.vue
locales/en-US.js

feature(user): new component for user registration

---

components/tailored/core/group/Group.html
components/tailored/core/group/Group.less
components/tailored/core/group/icon/GroupIcon.html
components/tailored/core/group/icon/GroupIcon.less
components/tailored/core/group/icon/GroupIcon.vue
mock/groups.ts
plugins/local/mock.ts
types/ui/core.d.ts

feat(groups): add group icon component

---

components/tailored/core/imageCropper/ImageCropper.html
components/tailored/core/user/create/Create.html
components/tailored/core/user/create/Create.vue
locales/en-US.js
middleware/authenticated.ts
nuxt.config.js
pages/allcomponents.vue
pages/auth/register/README.md
pages/auth/register/Register.html
pages/auth/register/Register.less
pages/auth/register/index.vue
pages/auth/unlock/Unlock.html
pages/auth/unlock/index.vue
pages/index.vue
plugins/local/classLoader.ts
plugins/thirdparty/persist.ts
store/accounts/actions.ts
store/accounts/getters.ts
store/accounts/mutations.ts
store/accounts/state.ts
store/accounts/types.ts
store/index.ts
store/store.types.ts
types/user/user.ts

- user registration ui
- interaction with server program
- first implementation of the typed store (to be completed in a separate task)

feat(user registration): added user registration flow

---

assets/styles/vars/global.less
components/tailored/core/chatbar/Chatbar.html
components/tailored/core/chatbar/Chatbar.less
components/tailored/core/sidebar/Sidebar.html
components/tailored/core/user/User.html
components/tailored/core/user/User.less
components/tailored/core/user/User.vue
components/ui/TypingIndicator/TypingIndicator.html
components/ui/TypingIndicator/TypingIndicator.less
components/ui/TypingIndicator/TypingIndicator.vue
layouts/chat.vue
store/ui/mutations.ts
store/ui/state.ts

feature(ui): introducing typing indicator

---

assets/styles/vars/global.less
components/interactables/Select/Select.html
components/interactables/Select/Select.less
components/interactables/Select/Select.vue

Update theme selectbox dropdowns

feat(Select Theme): Update theme selectbox dropdowns

---

components/tailored/core/media/Media.less
components/tailored/core/media/Media.vue
layouts/chat/Chat.less
layouts/server/Server.less

feat(Fullscreen): Redo Full Screen on new UI

---

components/tailored/core/group/aside/Aside.less
components/tailored/core/mobile/nav/Nav.less
components/tailored/core/sidebar/Sidebar.less
components/tailored/friends/friend/Friend.less
layouts/chat/Chat.less

chore(UI): Fix friends buttons and group aside on mobile layout

---

components/tailored/files/controls/Controls.html
components/tailored/files/controls/Controls.less

Fix Files navigation buttons stacking weird on mobile

fix(Files): Fix Files navigation buttons stacking weird on mobile

---

components/interactables/Select/Select.less
components/tailored/core/statusbar/Statusbar.less

Fix 'Tool Tips are being cut off on Status Bar'

fix(ToolTips): Tool Tips are being cut off on Status Bar

---

components/mixins/UI/Keybinds.ts

Fix page not found issue when short key for Settings

fix(Settings): Fix page not found issue when short key for Settings

---

components/tailored/core/media/user/User.html

Fix User UI broken issue when screen is small size

fix(Media): Fix User UI broken issue when screen is small size

---

components/tailored/core/statusbar/Statusbar.less
components/tailored/settings/pages/profile/Profile.html
components/tailored/settings/pages/profile/Profile.less
layouts/server.vue
layouts/server/Server.html

Jira ref: SA-158 + SA-172 + SA-178

Fix profile photo cropper

---

components/ui/ChatScroll/ChatScroll.less
components/ui/ChatScroll/ChatScroll.vue

Fix "new message" notifications pop-up issue on mobile.

fix(ChatScroll): Fix "new message" notifications pop up issue on mobile

---

components/interactables/Search/Input/Input.less

Fix issue 'White bar showing up on when trying to use search bar'.

fix(SearchBar): White bar showing up on when trying to use search bar

---

components/tailored/files/aside/Aside.less

Fix weird Upgrade button style

fix(Files): Fix weird Upgrade button style

---

components/tailored/messaging/enhancers/Enhancers.less
layouts/server/Server.html

Fix "Glyphs menu not appearing while viewing another server"

fix(Glyphs Menu): Glyphs menu not appearing while viewing another server

---

components/tailored/settings/pages/audio/index.vue
store/audio/mutations.ts

chore(audio): audio constraints

---

components/tailored/messaging/enhancers/Enhancers.vue
components/tailored/messaging/message/Message.html
components/tailored/messaging/message/actions/Actions.vue
components/tailored/messaging/message/reactions/Reactions.html
components/tailored/messaging/message/reactions/Reactions.vue
components/tailored/messaging/message/reply/Reply.html
components/tailored/messaging/message/reply/Reply.less
components/tailored/messaging/message/reply/Reply.vue
mock/messages.ts
store/ui/mutations.ts
types/messaging.d.ts

feat(chat): introducing reactions for replies

---

components/tailored/core/fileupload/FileUpload.html
components/tailored/core/fileupload/FileUpload.less

fix(file upload): add hover animation to file upload button

fix(file upload): add hover animation to file upload button

---

components/ui/Global/Global.vue
store/ui/state.ts

Fix 'toggling marketplace is glitchy'

fix(marketplace): Fix 'toggling marketplace is glitchy'

---

components/interactables/Volume/Volume.vue

fix(Volume): Fix Vue Slider type issue

---

components/tailored/core/media/Media.html
components/tailored/core/media/Media.less
components/tailored/core/media/Media.vue
layouts/chat/Chat.html

Max shown users should be 6, before adding "..." for the 7th user.
Best to test out by adding more users in a call through "users.ts" (starting from line 87)

feat(responsiveMobileFullscreenCall) :  responsive mobile media calls on fullscreen

---

config.ts
libraries/Solana/SolanaManager/SolanaManager.ts

Added support for custom faucet implementation for Solana devnet

fix: make the app compatible with custom faucet implementation

---

components/interactables/Search/Result/Result.less

Fix hovering on More Filters Btn

fix(More Filters Btn): Fix hovering on More Filters Btn

---

components/tailored/core/servers/list/List.html
components/tailored/core/servers/list/List.less

Fix 'Sidebar tooltips hidden behind elements.'

fix(Sidebar Tooltip): Fix 'Sidebar tooltips hidden behind elements.'

---

components/tailored/messaging/message/Message.html
components/tailored/settings/pages/network/Network.html
components/tailored/settings/pages/network/index.vue
components/ui/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.html
components/ui/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.less
components/ui/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.vue
components/ui/Embeds/EmbeddedLinkContent/types.d.ts
locales/en-US.js
store/settings/mutations.ts
store/settings/state.ts
store/settings/types.ts
yarn.lock

Added the option for the user to allow embedded content in the Network settings. 
Added the boilerplate to iframe/plyr in embedded videos (depending if video type is supported by plyr)

feat(EmbededVideo):

---

components/tailored/core/media/Media.less

feat(ui): hidden 'New message' notification in fullscreen

---

components/tailored/messaging/enhancers/Enhancers.html
components/tailored/messaging/enhancers/Enhancers.vue

Show emoji without click button

Show emoji without click button

---

components/tailored/core/chatbar/Chatbar.vue

Fix 'When sending a message in chat, sent message will be missing the last character typed'

fix(Chat): Fix 'When sending a message in chat, sent message will be missing the last character typed'

---

pages/allcomponents.vue
pages/chat/direct/index.vue

fix(friends): moved friends actions

---

components/ui/Modal/Modal.less

Fix 'Add an exit button on Create a Server on mobile'

fix(Create Server): Fix 'Add an exit button on Create a Server on mobile'

---

libraries/Solana/FriendsProgram/FriendsProgram.ts
store/friends/actions.ts

fix(friends): remove friend functions fixed

---

components/tailored/settings/pages/profile/Profile.html
components/ui/DynamicIcon/DynamicIcon.vue

Profile Bubble in Profile -> Settings has a little black circle where the upload button should be.

fix(Profile): Fix 'Profile Bubble in Profile '

---

components/tailored/messaging/pinned/Pinned.less

fix(Pinned Message): Blue check mark at a awkward spot in the Archived Messages

fix(Pinned Message): Blue check mark at a awkward spot in the Archived Messages

---

pages/friends/list/index.vue

Fix 'The "Add Friends" button in the Side Menu should take you to the Add Friends tab'

fix(Friends): Fix 'The "Add Friends" button in the Side Menu should take you to the Add Friends tab'

---

layouts/Layout.less

fix(fullscreen media): Fix 'Archived Messages appears while in fullscreen media'

fix(fullscreen media): Fix 'Archived Messages appears while in fullscreen media'

---

README.md

Fix typo on read me file

---

components/tailored/core/sidebar/Sidebar.html

Added swipe to hide only on left swipe, so nav does not close when scrolling up or down on menu

fix(Mobile): 

---

components/tailored/core/chatbar/Chatbar.html
components/tailored/core/chatbar/Chatbar.less
components/tailored/core/chatbar/Chatbar.vue
layouts/Layout.less

Remove autogrow in favor of flexbox

chore(AutoGrow) 

---

README.md

Fix typo on read me

---

locales/en-US.js

Fix typos on locales/en-US.js

---

components/tailored/core/group/aside/Aside.less
components/tailored/core/media/actions/settings/Settings.vue
layouts/Layout.less
layouts/chat.vue

fix(groups): group sidebar style on mobile

---

components/tailored/servers/sidebar/channels/VoiceUser/VoiceUser.vue

Fix weird user avatar on the gaming channel
https://satellite-im.atlassian.net/jira/software/projects/SA/boards/3?selectedIssue=SA-384

fix(Message): Fix weird user avatar on the gaming channel

---

store/media/state.ts

Hide the incoming call modal on fresh app
Jira ref: AP-28
Manually tested by clearing the local storage.

chore: removed incoming call on fresh app

---

store/ui/state.ts

Show the settings sidebar by default. 
Jira ref:  AP-27
Manually tested by clearing the local storage.

chore(sidebar): not collapsed by default

---

components/tailored/messaging/message/Message.html
components/tailored/messaging/message/Message.less

Fixes badge bug
AP-44
Fixes #
Badges were showing up in dm chat messages creating a double badge, in order to remove from dm's we needed to adjust so the badges would still show up in the archived messages drop down.

fix(badges): AP-44, remove Satellite Circle Badge from main user direct chat and show badge in archived messages.

---

locales/en-US.js

Improves grammar on locales file 📖 
N/A
N/A

chore - improve grammar on locales file

---

components/tailored/files/view/View.less

Fix 'Looks like some text is showing up behind the Satellite logo while viewing the Anime File'
Jira ref:  AP-73

fix(File): Fix style issue when open Anime image on File

---

components/tailored/core/statusbar/Statusbar.html

Fix typo - Marketplace instead of Market Place
Before
After
N/A
N/A

chore - fix typo

---

components/tailored/core/chatbar/Chatbar.vue
components/tailored/core/fileupload/FileUpload.html
components/tailored/core/fileupload/FileUpload.less
components/tailored/core/fileupload/FileUpload.vue
locales/en-US.js
types/files/file.ts

Update Chatbar Drop Images and File Upload to handle multiple files
SA-322
Fixes #
- Drop multi images to chatbar instead of only one
- Update FileUpload component

fix(Chat): Update Chatbar Drop Images and File Upload to handle multiple files

---

components/tailored/core/chatbar/Chatbar.html
components/tailored/core/chatbar/Chatbar.vue
locales/en-US.js

Does a proper image upload when you paste an image into the chat bar
Stops image pastes from just glitching and disappearing and instead handles them properly
Also small typo fix in locales
Fixes #

feat(Chatbar): can now paste images into chatbar 

---

components/tailored/core/sidebar/Sidebar.less
components/tailored/servers/sidebar/Sidebar.html
components/tailored/servers/sidebar/Sidebar.less
nuxt.config.js

Fixed friends box overlaying stream box in the sidebar

Fix(iOSFitScreen): Fix app doesn't fit to screen SA-298

---

babel.config.js
jest.config.js
package.json
test/Crypto.spec.ts
test/Logo.spec.js
yarn.lock

- Adds Jest into the project
- Removes logo test
- Adds crypto test
**Which issue(s) this PR adds** 🔨
[AP-98](https://satellite-im.atlassian.net/browse/AP-98)
use `yarn test`
test should be green 🎉 
N/A

test - add jest into the project

---

components/tailored/core/chatbar/Chatbar.vue

Stops empty messages from sending
Now users cant send empty messages
Fixes #

fix(Chatbar): stops empty messages from sending

---

libraries/Enums/enums.ts
libraries/Enums/types/keybindings.ts
libraries/Enums/types/prop-common-events.ts
locales/en-US.js

Adds Enum module and starts type files
NA
Fixes #
NA

update(enums): set up enum directory and start creation of types

---

.github/workflows/main.yml

- Adds Github Action to remove labels on merged PR's
N/A
N/A

Github Action - Remove labels on merged PR's

---

.github/workflows/rebase.yml

- Adds Github action to rebase when adding a comment saying /rebase on the PR

Github Action - Rebase when adding a comment saying /rebase

---

.gitignore
components/tailored/settings/pages/user/Search.html
components/tailored/settings/pages/user/Search.less
components/tailored/settings/pages/user/Search.vue
locales/en-US.js

Fixes multiple user search modal issues
AP67
Fixes #
First - when the input box expands, the typeahead stays in the same place blocking the view. 
Second - if you typeahead for someone at the top of the list, they are floating until an event happens before bringing it down to the input box.
Third - When you typeahead and click a user, the text you were typing should be removed.
Other minor fixes that occurred while fixing bugs including styling updates.

AP-67  new chat and community typehead bugs

---

components/tailored/messaging/message/Message.html
components/tailored/messaging/message/Message.less
components/tailored/messaging/message/Message.vue

The archived messages were using the wrong user icons, this fixes that.
Fixes #

fix(Archived Messages): FIxes badge used for archived messages

---

components/tailored/core/sidebar/status/Status.html
components/tailored/core/statusbar/Statusbar.html
components/tailored/core/statusbar/Statusbar.less
components/tailored/core/user/User.html
components/tailored/core/user/User.less
components/tailored/friends/add/Add.vue
components/tailored/friends/friend/Friend.html
components/tailored/friends/friend/Friend.less
components/tailored/messaging/group/Group.html
components/tailored/messaging/group/Group.vue
components/tailored/settings/pages/user/Search.vue
components/ui/User/User.html
components/ui/User/User.less
components/ui/UserState/UserState.less
components/ui/UserState/UserState.vue
pages/friends/list/index.vue
utilities/Messaging.ts

Introduce the userState component and spread it across the app so that the user state is consistent in all components that consume it
AP-30

feat(user): user state component

---

pages/auth/unlock/index.vue
plugins/thirdparty/persist.ts
store/accounts/mutations.ts
store/prerequisites/mutations.ts

https://satellite-im.atlassian.net/browse/AP-22

Fix(Login): Unlock should be persisted when store pin is enabled

---

components/tailored/core/fileupload/FileUpload.html
components/tailored/core/fileupload/FileUpload.less
components/tailored/core/fileupload/FileUpload.vue
locales/en-US.js

Fix 'Chat -  If you copy paste a invalid image, gets stuck on scanning image'
Fixes # AP-90

fix(Drop File): Fix 'Chat -  If you copy paste a invalid image, gets stuck on scanning image'

---

.husky/commit-msg
commitlint.config.js

Lint commits before they are created using Husky's `commit-msg` hook 
Wrong commit format

feat(commitlint): add husky commit-msg check

---

utilities/Messaging.ts

Fix 'Emoji reactions will increase if user navigates to a different page and back to chat again'
Fixes # AP-58

fix(chat reaction): Fix 'Emoji reactions will increase if user navigates to a different page and back to chat again'

---

store/friends/actions.ts
store/friends/mutations.ts

PR request david/fixing to dev branch
store/friends/actions.js file
Fixes #
I fixed duplicated friends issue.
I thought duplicated issue is because addFriend same friend object when visit friends page.
But it was not that problem.
It is updateFriend method issue.

fix - Duplicate friends are being added when page is re-rendered - AP-64

---

utilities/Messaging.ts

feat(groupbehavior): modify message grouping behavior AP-107

---

nuxt.config.js

remove data-cy attributes on nuxt build
closes #49
remove data-cy attributes on nuxt build
Fixes #49
I used this thread https://forum.vuejs.org/t/how-to-remove-attributes-from-tags-inside-vue-components/24138/11

fix(webpack): remove test attributes from build

---

components/tailored/core/chatbar/Chatbar.vue
components/ui/NumberedWord/NumberedWord.html
components/ui/NumberedWord/NumberedWord.less
components/ui/NumberedWord/NumberedWord.vue
libraries/Enums/enums.ts
libraries/Enums/types/message-routes.ts
locales/en-US.js
middleware/authenticated.ts
pages/setup/InputAccount/InputAccount.html
pages/setup/InputAccount/InputAccount.less
pages/setup/InputAccount/index.vue
pages/setup/disclaimer/Disclaimer.html
pages/setup/disclaimer/index.vue
store/textile/actions.ts
store/textile/mutations.ts
store/textile/types.ts

fix 'unable to paste the text into chat'
Jira ref: AP-108

fix(chat): fix 'unable to paste text into chat'

---

components/tailored/core/media/actions/volume/Volume.vue
components/tailored/settings/pages/audio/Audio.html
components/tailored/settings/pages/audio/index.vue
locales/en-US.js
store/audio/mutations.ts
store/audio/state.ts
store/audio/types.ts

Refactor our state to prepare using system sounds, refactor the media volume to effect output volume in settings and vice versa. 
AP-10

refactor(volumes): update state for system sounds, media volume to change with output volume

---

components/tailored/core/statusbar/Statusbar.html

AP-157 Chat - Video and Call icons are missing in the top bar

---

components/tailored/friends/add/Add.html

This PR displays the correct type of error message when there are error(s) when a user is adding friends.
https://satellite-im.atlassian.net/browse/AP-97
Fixes #

fix(friendErrorMessage): have correct error messages show on user adding friends

---

libraries/WebRTC/WebRTC.ts
pages/auth/register/index.vue
pages/generic/loading/index.vue
store/accounts/actions.ts
store/accounts/state.ts
store/accounts/types.ts
store/audio/state.ts
store/files/state.ts
store/friends/state.ts
store/prerequisites/state.ts
store/search/state.ts
store/settings/state.ts
store/textile/state.ts
store/ui/state.ts
store/video/state.ts
store/webrtc/state.ts

- fix bulk typo `Initial` instead of `Inital`
- fix bulk typo `UNKNOWN` instead of `UKNOWN`

chore: fix bulk typo

---

components/tailored/core/sidebar/Sidebar.html

feat(friendrouter): click friends with open friend request take to request tab (AP-170)

---

mock/groups.ts

fix typos on AP-199
Fixes AP-199
N/A 
N/A

chore: fix typos - AP-199

---

components/tailored/core/user/User.vue

feat(contextmenu): sidebar contextmenu in the friends list updated (AP-172)

---

libraries/WebRTC/Wire.ts

In the console, fixes an error 'vue is not defined'
Fixes # N/A

chore(wire): fix console error for vue not defined

---

components/tailored/settings/profile/card/Card.html
components/tailored/settings/profile/card/Card.vue
mock/profile.ts

Pulls users location to display in user profile
AP-63
This is a beginning for future tickets implementing locations within users profile - will be creating now

refactor(profile locations): automatically grab users location to display in profile

---

components/tailored/friends/friend/Friend.html
components/tailored/friends/friend/Friend.vue
utilities/Messaging.ts

AP-171 Friend Page Minor Updates

---

.gitmodules
components/tailored/core/chatbar/Chatbar.html
components/tailored/core/chatbar/Chatbar.vue
components/tailored/core/chatbar/fileupload/FileUpload.html
components/tailored/core/fileupload/FileUpload.html
components/tailored/files/uploader/Uploader.html
config.ts
package.json

Submodule updates stop saying there are updates to the submodules
Moved blankspace regex to config file
Added upload text to global because the same text was going to be in three different places
updated the way a class was updating in view so we didn't need to do a weird string concat thing
Fixes # n/a

chore(updates): minor updates throughout

---

.gitmodules
components/tailored/core/chatbar/Chatbar.html
components/tailored/core/chatbar/Chatbar.vue
components/tailored/core/chatbar/fileupload/FileUpload.html
components/tailored/core/fileupload/FileUpload.html
components/tailored/files/uploader/Uploader.html
config.ts
package.json
store/textile/actions.ts

fix(replybar): blue reply bar does not disappear after reply is sent(AP-60)

---

components/tailored/core/statusbar/Statusbar.less

Chat - Cut off user name on nav bar

---

components/ui/TypeHead/TypeHead.vue
pages/setup/InputAccount/InputAccount.html
pages/setup/InputAccount/index.vue

feat(inputmultiple): allow user to paste recovery phrase into text input (AP-244)

---

.gitmodules
middleware/authenticated.ts
pages/index.vue
pages/setup/InputAccount/InputAccount.html
pages/setup/InputAccount/InputAccount.less
pages/setup/InputAccount/index.vue
store/accounts/actions.ts

On import account page, if passphrase doesn't work:
- prevent redirect
- show error message
- hide error if you remove a word
- add top margin to error message
- allow repeated words on paste in
- various prettier/eslint updates in pages I went to
On login page, if user derivation fails (for example if you have wrong passphrase in storage), take user to disclaimer/recovery page
update gitmodules to try and always force current branch on deploy
Fixes #582 

fix(ImportAccount): added import account error message

---

package.json

- update commit name from `AP-110` to `chore: streamline add friend functionality AP-110`
- improved husky rules based on @josephmcg 's comment [here](https://github.com/Satellite-im/Core-PWA/pull/474#issuecomment-987485150)
note:
the code changes on `Layout.less` was to test the prettier command on the pre-commit hook

chore: improve husky rules

---

package.json

This reverts commit c9d627e5c4255397200e4d652eed4d0b2db34254.
Reverts husky changes until we can test them and fix a few issues
Fixes #

Revert "chore: improve husky rules (#479)"

---

components/ui/TypeHead/TypeHead.html
cypress/integration/import-account.js
cypress/support/commands.js
nuxt.config.js

- chore: add `data-cy` label to submit passphrase
- test: add import account test
https://user-images.githubusercontent.com/29093946/145622448-d5fc53ef-99b2-4450-a454-457fa6b3999d.mp4
- chore: adds @josephmcg 's fix on `nuxt.config.js`, there weren't any `data-cy` labels appearing locally
- test: add import test on commands to be reusable
N/A
N/A

Cypress - Add Import Account test + data-cy labels + add joe's fix on nuxt config

---

package.json
pages/setup/InputAccount/InputAccount.html
pages/setup/InputAccount/InputAccount.less
pages/setup/disclaimer/Disclaimer.less

fix(importaccount): entire page sits off center on mobile (AP-253)

---

package.json
pages/setup/disclaimer/Disclaimer.html
pages/setup/disclaimer/index.vue
pages/setup/privacy/Privacy.html
pages/setup/privacy/Privacy.less
pages/setup/privacy/index.vue
store/settings/mutations.ts
store/settings/state.ts
store/settings/types.ts

Privacy Settings Step during Sign Up Flow
Fixes # AP-19
1.  When test , first clear local storage -> input pin -> create account -> privacy page
2. This needs locales change. please test this after https://github.com/Satellite-im/locales/pull/11 is merged to locales.

feat(privacy page): Privacy Settings Step during Sign Up Flow

---

cypress/integration/chat-features.js
cypress/integration/create-account.js
cypress/integration/import-account.js
cypress/support/commands.js

- moves command delay into commands
- adds minor improvement on import account flow
- adds Cypress chat flows such as sending a written message and an emoji 
https://user-images.githubusercontent.com/29093946/145905721-09c81bf0-40b1-4cad-92d9-21d08afbeb0c.mp4

test: add more cypress tests + improvements

---

components/interactables/Input/types.d.ts
components/ui/TypeHead/TypeHead.html
components/ui/TypeHead/TypeHead.vue
pages/setup/InputAccount/InputAccount.html

fix: presuggestion not working on mobile devices if word start capitalized (AP-254)

---

middleware/authenticated.ts
pages/index.vue
store/accounts/mutations.ts
store/accounts/state.ts
store/accounts/types.ts

feat: app should remember last page, when you reload/come back to app (AP-173)

---

components/interactables/Button/README.md
components/interactables/ContextMenu/ContextMenu.vue
components/interactables/InputGroup/InputGroup.vue
components/interactables/QuickProfile/QuickProfile.vue
components/tailored/core/chatbar/controls/Controls.vue
components/tailored/core/chatbar/reply/Reply.vue
components/tailored/core/media/Media.vue
components/tailored/core/media/heading/Heading.vue
components/tailored/files/controls/Controls.vue
components/tailored/messaging/enhancers/Enhancers.vue
components/ui/Global/Global.vue
libraries/WebRTC/WebRTC.ts
plugins/thirdparty/persist.ts
startup.js

fix typos from misspell report

chore: fix typos

---

assets/styles/iOS.less
layouts/default.vue
nuxt.config.js

fix(iOS): remove white bar from bottom of iOS, fix topbar

---

pages/setup/InputAccount/InputAccount.less
pages/setup/InputAccount/index.vue

fix mobile cut off phrases on import account
Fixes # AP-159

fix: fix mobile cut off phrases on import account AP-159

---

.github/workflows/lint-PR-title.yml

This enforces the good practices of the PR title convention that we use
in case it's not how it should this will add a comment with the following

task(githubAction): add github action lint PR title

---

components/ui/TypeHead/TypeHead.vue

fix(ImportAccount): last typed phrase suggestions when user starts to type next phrase - AP-256

---

components/ui/TypeHead/TypeHead.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
components/views/chat/message/Message.vue
components/views/chat/message/edit/Edit.vue
libraries/Textile/MailboxManager.ts
libraries/Textile/encoders.ts
store/textile/actions.ts

feat: the original sender of a specific message should be able to edit that message (AP-39)

---

components/ui/Version/Version.vue
cypress/integration/chat-features.js
cypress/integration/create-account-negative-tests.js
cypress/integration/create-account.js
cypress/integration/verify-toggles-privacy-settings.js
cypress/integration/version-release-notes.js
cypress/support/commands.js

- Adds Cypress test to verify user cant create an account without username
- Adds Cypress test to verify toggles on privacy settings
- Minor improvements

task(Cypress): add more Cypress tests

---

.github/workflows/lint-PR-title.yml

- Update regex on Github Action to include `test` type
- Improve copy on Github Action

task(githubAction): update regex to include test type

---

PULL_REQUEST_TEMPLATE.md

- Minor improvement on PR template

task(template): minor improvement on PR template

---

components/views/files/view/View.html

https://satellite-im.atlassian.net/browse/AP-279
add string 'Unpin' for when hovering over a selected file on the Files page

fix(unpinStringOnFile): add correct string to render

---

config.ts

fix(chat): send empty message when click send icon

---

utilities/Messaging.ts

refactor replies, reactions tracker codes
Fixes # AP-242

fix(refactor): refactor tracker codes

---

components/interactables/Search/Result/Result.html
components/ui/UpdateModal/UpdateModal.html
components/views/chat/chatbar/footer/Footer.vue
components/views/chat/enhancers/Enhancers.html
components/views/files/aside/Aside.html
components/views/files/controls/Controls.html
components/views/files/upload/Upload.html
components/views/friends/add/Add.html
components/views/friends/quick/Quick.html
components/views/marketplace/Marketplace.html
components/views/marketplace/glyphs/Glyphs.html
components/views/marketplace/glyphs/featured/Featured.html
components/views/marketplace/glyphs/popular/Popular.html
components/views/marketplace/glyphs/recommended/Recommended.html
components/views/marketplace/glyphs/trending/Trending.html
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/live/Live.html
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/pinned/Pinned.html
components/views/settings/pages/keybinds/Keybinds.html
components/views/wallet/accounts/Accounts.html
components/views/wallet/balance/Balance.html
components/views/wallet/mini/body/Body.html
components/views/wallet/popup/Popup.html
components/views/wallet/recent/Recent.html
pages/files/browse/Browse.html

https://satellite-im.atlassian.net/browse/AP-277
Fixes #

fix(engTranslations): add text to translation file - AP-277 

---

components/ui/TypeHead/TypeHead.html
components/ui/TypeHead/TypeHead.vue
pages/setup/ImportAccount/index.vue

This PR allows for users to pick specific phrases with their keyboard, making it easier to use/more accessible
#AP-258

feat(importAccount): allow picking phrases with keyboard #AP-258

---

components/views/chat/chatbar/Chatbar.vue

fix 'unable to paste the text into chat'
AP-108

fix(paste): fix 'unable to paste the text into chat'

---

components/views/servers/create/Create.vue
components/views/user/create/Create.vue

https://satellite-im.atlassian.net/browse/AP-296

fix(createErrorsInLocales): set up errors for locales

---

components/views/chat/message/edit/Edit.html
components/views/chat/message/edit/Edit.less
components/views/chat/message/edit/Edit.vue

fix(chatEdit): fix broken layout if edit a message without anyspaces

---

components/views/chat/chatbar/Chatbar.vue

fix(chatBar): address undefined issue in chat page

---

components/ui/Global/Global.html
components/views/media/Media.html
utilities/Hounddog.ts

chore(Hounddog): moved some call data to hounddog

---

components/ui/Global/Global.html

revert hounddog

---

libraries/Solana/ServerProgram/ServerProgram.ts

Adds a function to the server program class that allows to search users by name
N/A
The functionality is not yet connected to the UI, so the code must be updated in order to test

chore(search): add function to search users by name

---

components/interactables/InputGroup/InputGroup.html
components/interactables/InputGroup/InputGroup.less
components/interactables/InputGroup/InputGroup.vue
components/interactables/QuickProfile/QuickProfile.html
components/interactables/QuickProfile/QuickProfile.vue
components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/footer/Footer.vue
config.ts

-move max chars to config for several components
-Implement input length limit for quick profile
AP-295

fix(chat): Implement input length limit for quick profile #AP-295

---

components/views/chat/chatbar/Chatbar.vue
components/views/files/upload/Upload.vue
libraries/Enums/types/messaging-types.ts
libraries/Enums/types/prop-common-events.ts
libraries/Textile/BucketManager.ts
store/textile/actions.ts

Fix multi upload bug
AP-274
Not nearly as pretty of code but is fully functional for me!

fix(images): fix multi upload bug

---

libraries/Enums/types/messaging-types.ts

fix invalid message payload when replying to message
AP-336

fix(reply): fix invalid message payload when replying to message

---

components/views/chat/message/edit/Edit.html

https://satellite-im.atlassian.net/browse/AP-342

fix(translationUpdate): add proper text to translation file

---

components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/footer/Footer.vue
components/views/chat/message/Message.vue
components/views/chat/message/edit/Edit.html
components/views/chat/message/edit/Edit.less
components/views/chat/message/edit/Edit.vue
config.ts
libraries/Enums/types/keybindings.ts

feat(editChat): improve messages edit

---

assets/styles/themes/moonless_night.less
components/ui/Chat/Embeds/File/File.html
components/ui/Chat/Embeds/File/File.less
components/ui/Chat/Image/Image.html
components/ui/Chat/Image/Image.less
components/ui/Chat/Image/Image.vue

feat(Embedded Images): updated image embeds to use the correct component

---

components/views/user/create/Create.vue

fix(signup): fix sign up with just spaces on username

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.less
components/views/chat/chatbar/Chatbar.vue
components/views/files/upload/Upload.html
components/views/files/upload/Upload.less
components/views/files/upload/Upload.vue
layouts/Layout.less

feat(chat): improve UX when user tries to copy paste images

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.less
components/views/chat/chatbar/Chatbar.vue
components/views/files/upload/Upload.html
components/views/files/upload/Upload.less
components/views/files/upload/Upload.vue
layouts/Layout.less

Reverts Satellite-im/Core-PWA#791 until we can figure out swiper issue this introduces

Revert "feat(chat): improve UX when user tries to copy paste images"

---

store/ui/state.ts

Fixes an accident from a previous PR
was accidentally removed here
https://github.com/Satellite-im/Core-PWA/pull/802/files

fix(glyph): state was removed in a PR, file was throwing error

---

components/views/settings/modal/Modal.html
components/views/settings/modal/Modal.vue

fix(settingsNav): shows the page when selecting menu in settings

---

components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.less
components/views/navigation/toolbar/Toolbar.vue
libraries/WebRTC/WebRTC.ts
plugins/thirdparty/persist.ts
store/webrtc/actions.ts
store/webrtc/mutations.ts
store/webrtc/state.ts
store/webrtc/types.ts

Do not allow clicking the video or phone icons in the top bar if the peer is not connected
AP-349
-Before testing this PR, please check this PR is merged. (https://github.com/Satellite-im/locales/pull/18 Because this needs locale updates)
-Sometimes Webrtc connect/disconnect events trigger delays a little so please check it after some time.

feat(call): dont allow clicking icons if peer is not connected

---

.gitmodules
cypress.json

chore(cypress): add cypress as submodule

---

components/views/chat/enhancers/Enhancers.vue
components/views/chat/message/reply/Reply.html
components/views/files/upload/Upload.vue
components/views/friends/add/Add.vue
components/views/media/Media.html
components/views/media/Media.vue
components/views/navigation/server/sidebar/channels/Channels.vue
layouts/chat.vue
libraries/Solana/ServerProgram/ServerProgram.ts
libraries/Textile/BucketManager.ts
libraries/WebRTC/Wire.ts
libraries/ui/Alerts.ts
middleware/authenticated.ts
pages/auth/register/index.vue
types/ui/friends.d.ts
utilities/Messaging.ts

- Added all the TODO's in code into JIRA and updated those comments with the ticket ID

chore(update): add todo's on JIRA

---

components/views/navigation/toolbar/Toolbar.vue

- Removes commented out console log

chore(console): remove console log

---

components/views/media/actions/Actions.html
components/views/media/actions/settings/Settings.html

update(video): disabled buttons and made to show not available tooltip

---

.github/workflows/pr-conflicts.yml
commit-guide.md

When pull requests are created or updated, this action compare all other pull requests and then leaves comments on the pull requests if same files are changed, and there is any possibility to be conflicted when other pull requests merged first.

task(githubAction): conflicts checker

---

commit-guide.md
components/interactables/QuickProfile/QuickProfile.vue
components/ui/Chat/Embeds/File/File.html
components/ui/Chat/Embeds/File/File.less
libraries/ui/Alerts.ts

chore(typos): fix typo

---

assets/styles/base.less
assets/styles/themes/moonless_night.less
components/ui/Chat/Embeds/File/File.html
components/ui/Chat/Embeds/File/File.less
components/ui/Chat/Image/Image.html
components/ui/Chat/Image/Image.less
components/ui/Chat/Image/Image.vue
components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/chat/message/actions/Actions.vue
components/views/files/file/File.less
components/views/files/upload/Upload.html
components/views/files/upload/Upload.less
components/views/files/upload/Upload.vue
libraries/Textile/BucketManager.ts
libraries/ui/Alerts.ts

Adds link to enable downloading shared files
AP-299
I thought about leaving in all the textile work but since it wasn't exactly functional anyway decided to keep it small and simple.

feat(files): download files implementation

---

.gitmodules

Attempt to fix build on Netlify

chore(submodule): update to https instead of ssh to fix build

---

components/views/friends/friend/Friend.vue
store/friends/actions.ts
store/friends/mutations.ts

fix 'removing one friend will remove all of user's friends'
AP-115

fix(friends): fix 'removing one friend will remove all of user's friends'

---

assets/styles/base.less
assets/styles/themes/moonless_night.less
components/interactables/Close/Close.less

- removes double ;
- removes double font-size
- removes double background

fix(fixing): minor fixing

---

components/views/chat/message/edit/Edit.html
components/views/chat/message/edit/Edit.less

fix style issues in edit message
AP-362

fix(chat): fix style issues in edit message

---

components/ui/Popups/Error/Error.vue
components/views/chat/message/Message.vue
components/views/settings/pages/audio/index.vue
components/views/settings/pages/info/Developer.html
components/views/settings/pages/info/index.vue
components/views/settings/pages/notifications/index.vue
nuxt.config.js
plugins/local/envinfo.ts
utilities/ConsoleWarning.ts
utilities/EnvInfo.ts
utilities/Notifications.ts

update(utils): centralize get platform helpers/utilities AP-409

---

components/interactables/Switch/Switch.less

fix(settings): fix copy not aligned to the toggle AP-309

---

components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.vue
components/views/user/User.vue
layouts/chat.vue
layouts/files.vue
layouts/friends.vue
store/ui/getters.ts
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts

fix(addFriends): click Add Friends to swipe into friends page

---

components/views/glyphs/Glyphs.vue
store/ui/state.ts

fixed marketplace modal issue
AP-269

fix(marketplace): marketplace button not working AP-269

---

layouts/chat.vue
layouts/files.vue
layouts/friends.vue
layouts/server.vue
pages/friends/list/FriendsList.less

Made to close the side menu when open the pages in the mobile.
AP-417

update(sidebar): sidemenu should auto close in mobile AP-417

---

cypress.json

- add cypress.json file on the main repo in order to cypress to run properly

chore(cypress): add missing file

---

components/views/media/Media.html
components/views/media/Media.less
components/views/media/Media.vue

Fix 'Currently, when a user disables video the square just disappears entirely making it feel like they are not in the call anymore'
AP-343

fix(call): fix issues when disable video

---

components/ui/Popups/Error/Error.vue
components/views/chat/message/reply/Reply.html
package.json

- bumped nuxt-bridge version to current (was 2 months old)
- fixed lint error wanting methods after mount in a vue component
- moved ticket number inside comment on todo, on replies the 'AP-397' text was showing up on each reply
N/A
Only visible change will be "//AP-397" text wont show up on every reply

chore(various): minor updates

---

components/views/chat/message/reactions/Reactions.vue
components/views/chat/message/reply/Reply.html
utilities/Messaging.ts

Fixed message reply reaction issue
AP-413

fix(reaction): fix message reply reaction issue AP-413

---

.eslintrc.js
.vscode/settings.json
package.json
store/sounds/types.ts
store/textile/actions.ts
store/textile/types.ts

- ts linting for nuxt
- disable certain ts lint rules
- force prettier format on save for vscode users
N/A
- edited `store/textile/actions.ts` to test if tslint errors would block a commit through husky. working as intended. Positive side effect of formatting the file too

feat(tslint): added typescript eslint for nuxt and force vscode prettier format on save

---

components/ui/Chat/Embeds/File/File.html
components/ui/Chat/Image/Image.html
components/ui/Chat/Image/Image.less
libraries/Files/Directory.ts
libraries/Files/Fil.ts
libraries/Files/FileSystem.ts
libraries/Files/test/Directory.test.ts
libraries/Files/test/FileSystem.test.ts
libraries/Files/types/directory.ts
libraries/Files/types/file.ts
libraries/Files/types/filesystem.ts

removes extra files download info that isn't needed for images.
Also includes a few small fixes for from prettier for the filesystem stuff.

feat(files): embed images

---

components/views/wallet/mini/Mini.less
components/views/wallet/mini/Mini.vue
components/views/wallet/mini/body/Body.vue

fix send money modal issue
AP-470

fix(modal): fix send money modal issue AP-470

---

mock/glyphs.ts

fix(glyphs): add missing glyphs that were previously returning 404

---

components/views/friends/quick/Quick.vue

fix(ui): quick chat modal action for 1on1 chat AP-475

---

assets/styles/framework/ui.less
components/views/navigation/sidebar/Sidebar.less
components/views/navigation/slimbar/Slimbar.less

fix(ui): sidebar stretching outside view AP-383

---

components/views/settings/pages/keybinds/index.vue

Ignored modified keys on mac
AP-427

fix(keybinds): ignore modified keys in keybinding AP-427

---

components/interactables/Button/Button.html
pages/setup/disclaimer/Disclaimer.html
pages/setup/disclaimer/Disclaimer.less

fix(login): fix padding issues on create/import account buttons

---

components/interactables/Select/Select.html
components/interactables/Select/Select.less
components/interactables/Select/Select.vue
components/views/settings/pages/personalize/Personalize.html
components/views/settings/pages/personalize/index.vue

feat(themes): flair dropdown deactivated until user select theme

---

components/views/chat/chatbar/footer/Footer.vue

fix 'Clicking out of Send Money will highlight the 0 in the character count'
AP-492

fix(highlight): fix 'highlight issue in character count'

---

components/interactables/QuickProfile/QuickProfile.html
components/interactables/QuickProfile/QuickProfile.less
components/ui/Global/Global.html
components/views/user/User.vue
components/views/user/profile/Profile.html
components/views/user/profile/Profile.less
components/views/user/profile/Profile.vue
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts

Added user profile modal, and added close button in quickprofile
AP-489

add(userprofile): add user profile modal AP-489

---

components/views/chat/chatbar/Chatbar.vue

Fix “user is typing…” appears when the user is not typing
AP-379

fix(typing): fix “user is typing…” appears when the user is not typing

---

components/interactables/Search/Result/Result.html
components/interactables/Search/Result/Result.less

fix(ui): ui issues in search results AP-496

---

components/views/media/Media.vue
components/views/media/actions/Actions.vue
components/views/media/heading/Heading.vue
components/views/navigation/sidebar/controls/Controls.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.vue
libraries/Enums/enums.ts
libraries/Enums/types/webrtc.ts
libraries/WebRTC/Call.ts
store/webrtc/mutations.ts

This PR addresses several calling issues
AP-344, AP-345, AP-350, AP-353
This is a re-do of the pr that went in earlier today

fix(call): fixed timer not reseting, toggle video button, and user feedback for muting AP-344, AP-345, AP-350, AP-353

---

assets/styles/themes/moonless_night.less

fix(ui): missing components on themes

---

PULL_REQUEST_TEMPLATE.md

As Joe mentioned, whenever we open a PR with the template not filled up, the AP - 100 gets reopened automatically. Removing that ticket number from the template.

chore(template): update PR template

---

components/views/media/heading/Heading.html
components/views/media/heading/Heading.vue
store/webrtc/actions.ts
store/webrtc/mutations.ts
store/webrtc/state.ts

Sync Call Timer for when a call is first connected.
AP-506

fix(call): sync call timer

---

pages/chat/direct/_address.vue
pages/index.vue
utilities/Hounddog.ts

fix(lastVisited): handles last visited to get existing route

---

assets/styles/base.less
assets/styles/framework/colors.less
assets/styles/themes/moonless_night.less
assets/styles/thirdparty/multiselect.less
assets/styles/thirdparty/scrollbar.less
components/interactables/AsideMenu/AsideMenu.less
components/interactables/ButtonGroup/ButtonGroup.less
components/interactables/Search/Input/Input.less
components/interactables/Select/Select.less
components/interactables/Switch/Switch.html
components/interactables/Switch/Switch.less
components/interactables/Switch/Switch.vue
components/ui/SimpleList/SimpleList.html
components/ui/SimpleList/SimpleList.less
components/views/navigation/server/sidebar/Sidebar.html
components/views/navigation/server/sidebar/Sidebar.less
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.less
components/views/settings/pages/personalize/Personalize.html
layouts/Layout.less
store/ui/types.ts

Fixes theme issues with the buttons and reorders the code, every color-related thing is now in a unique style file
AP-414 and AP-428 
Created a new "satellite" flair and set it as default, so is no longer necessary locking the flair select

fix(theme): fixed bugs related to buttons flair and text

---

PULL_REQUEST_TEMPLATE.md

chore(update): PR template update

---

store/ui/types.ts

Update theme naming from purpler to lavender

chore(colors): update naming

---

libraries/Files/FileSystem.ts
libraries/Files/test/FileSystem.test.ts
package.json

Added new search function
AP-479

feat(filesystem): add new fuzzySearch function AP-479

---

components/views/media/Media.html
components/views/media/Media.less
components/views/media/Media.vue

Adds visual indicator to let users know when the person they're calling mutes their mic
AP-502
<!--AP-X->
Ty Sara for reminding me to do this lol

feat(media): indicator added for remote user muted

---

components/views/chat/chatbar/Chatbar.vue

enforce the 256 chars when sending
AP-512

fix(chat): enforce the 256 chars when sending

---

store/webrtc/__snapshots__/state.test.ts.snap
store/webrtc/state.test.ts

Complete coverage for store/webrtc/state.ts
AP-589

add(jest): 100% coverage for store/webrtc/state.ts unit test

---

package.json

- check if all packages are installed on yarn dev
- if missing, install. if everything is there, it just adds a second or two of checking
AP-597

fix(build): check if all packages are installed on yarn dev AP-597

---

components/views/chat/chatbar/Chatbar.vue

enforce chat limit on chatbar
AP-512

fix(chat): enforce chat limit on chatbar

---

store/ui/__snapshots__/types.test.ts.snap
store/ui/types.test.ts

Complete coverage for store/ui/types.ts
AP-586

add(jest): 100% coverage for store/ui/types.ts unit test

---

store/friends/__snapshots__/state.test.ts.snap
store/friends/state.test.ts

Complete coverage for store/friends/state.ts
AP-574

add(jest): 100% coverage for store/friends/state.ts unit test

---

store/ui/__snapshots__/state.test.ts.snap
store/ui/state.test.ts

Add unit tests (100% coverage) for the store/ui/state.ts unit test
AP-584

add(jest): 100% coverage for store/ui/state.ts unit test

---

components/views/chat/message/Message.less

make emoji throbbing more fluid/less jerky
fixed emoji appearance in chatbox smoothly.
AP-284

fix(emoji): fix emoji appearance in chatbox smooth

---

store/webrtc/mutations.test.ts
store/webrtc/mutations.ts

Add unit tests (100% coverage) for the store/webrtc/mutations.ts unit test, while also updating the mutations.ts module in accordance with #1149 
AP-588

add(jest): 100% coverage for store/webrtc/mutations.ts unit test

---

store/sounds/mutations.test.ts

Add unit tests (100% coverage) for the store/sounds/mutations.ts unit test
AP-576

add(jest): 100% coverage for store/sounds/mutations.ts unit test

---

store/sounds/__snapshots__/state.test.ts.snap
store/sounds/state.test.ts

Add unit tests (100% coverage) for the store/sounds/state.ts unit test
AP-577

add(jest): 100% coverage for store/sounds/state.ts unit test

---

.vscode/extensions.json

Adds a new file so that VS code will recommend plugins we use.
https://satellite-im.atlassian.net/browse/AP-510
Are these the right plugins? When you search for prettier and eslint in vs code there are results that are SUPER POPULAR (which are the ones I picked) but the second results look good too. 
I removed WebStorm as a requirement on account of webstorm being the new vim.

chore(vscode): create a vscode plugin recommendation file

---

components/views/media/Media.html
components/views/media/user/User.html
components/views/media/user/User.less
components/views/media/user/User.vue

Voice/Video Calling - waiting for other user to accept indication
AP-523

feat(call): call - waiting for other user to accept indication

---

utilities/Hounddog.test.ts
utilities/Hounddog.ts
utilities/Logger.test.ts
utilities/__snapshots__/Hounddog.test.ts.snap

Add unit tests (100% coverage) for the Hounddog and Logger utilities.
AP-531
I've added a comment on JIRA at this ticket regarding how we can bump up the branches coverage of Hounddog.test.ts.
-

add(jest): unit tests for Hounddog and Logger

---

store/friends/mutations.test.ts

add(jest): 100% for store/friends/mutations.ts unit test

---

store/dataState/mutations.test.ts
store/dataState/mutations.ts

Bump coverage for dataState.mutation.ts while also linting it
No ticket has been made yet.

update(jest): improve data state.mutations.ts

---

libraries/WebRTC/__snapshots__/encoders.test.ts.snap
libraries/WebRTC/encoders.test.ts
libraries/WebRTC/encoders.ts

- lint libraries/WebRTC/encoders.ts
- add unit test for libraries/WebRTC/encoders.ts with 100% coverage
AP-564

add(jest): 100% coverage for libraries/WebRTC/encoders.ts

---

store/textile/__snapshots__/getters.test.ts.snap
store/textile/getters.test.ts

add(jest): 100% coverage for store/textile/getters.ts unit test

---

components/views/navigation/sidebar/controls/Controls.html

Fixes control buttons not resting on hangup
AP-491

fix(controls): toggle buttons go off correctly after hangup

---

store/media/mutations.test.ts

add(jest): 100% coverage for store/media/mutations.ts

---

store/media/__snapshots__/state.test.ts.snap
store/media/state.test.ts

add(jest): 100% coverage for store/media/state.ts

---

plugins/thirdparty/dexie.ts
store/textile/actions.ts

added lastInbound to indexeddb records
AP-598

feat(textile): add lastInbound to indexeddb records AP-598

---

.eslintrc.js
libraries/Solana/Solana.test.ts
package.json
utilities/Logger.test.ts

- adds `prettier` to husky
- improves `eslint` command
- adds cypress folder and package.json to the `ignorePatterns` section

chore(husky): improve husky

---

package.json

We don't need canvas, just the things to mock canvas.
N/A

chore(canvas): we do not need canvas, just canvas-mock for tests

---

components/views/chat/message/actions/Actions.html
components/views/chat/message/actions/Actions.vue

Removed more option button
AP-419

fix(actions): remove more option button AP-419

---

mock/glyphs.ts

fix some glyphs are returning 404
AP-311
This would fix AP-484 too.

fix(glyph): fix some glyphs are returning 404

---

components/ui/Global/Global.vue

fix(call): dismiss incoming call when click deny button
AP-524

fix(call): dismiss incoming call when click deny button

---

.eslintrc.js
libraries/Solana/Solana.test.ts
package.json

Reverts Satellite-im/Core-PWA#1249

Revert "chore(husky): improve husky"

---

libraries/Files/test/Fil.test.ts

add(jest): 100% coverage for Files/Fil.ts unit test

---

libraries/Solana/Solana.test.ts
locales/README.md

chore(prettier): minor lint

---

store/ui/__snapshots__/getters.test.ts.snap
store/ui/getters.test.ts

add(jest): 100% coverage for store/ui/getters.ts

---

libraries/Files/Directory.ts
libraries/Files/test/Directory.test.ts

Improve coverage by covering two errors.
AP-549

add(jest): 100% coverage for Files/Directory.ts

---

components/views/settings/pages/accounts/Accounts.html
components/views/settings/pages/accounts/Accounts.less
components/views/settings/pages/accounts/index.vue
components/views/settings/pages/network/Network.html
components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/Profile.less
components/views/settings/pages/profile/index.vue

remove unnecessary items 
AP-653

fix(settings): remove unnecessary items AP-653

---

components/views/settings/modal/Modal.less

fix settings background issue on mobile
AP-627

fix(settings): fix background issue on mobile

---

components/views/files/list/List.vue

^
Made a mistake in recent Files ui PR

fix(files): fix files list view. broken guard clause

---

store/accounts/__snapshots__/state.test.ts.snap
store/accounts/state.test.ts

There was no ticket for this, but we're grinding for that 70%+ coverage!

add(jest): 100% coverage for store/accounts/state.ts AP-682

---

components/views/media/Media.less
components/views/media/user/User.html
components/views/media/user/User.less

fix ui issues when fullscreen mode
AP-622

fix(fullscreen): fix ui issues when fullscreen mode

---

store/accounts/getters.test.ts

add(jest): 100% coverage for store/accounts/getters.ts unit test

---

assets/styles/base.less
components/interactables/Switch/Switch.html
components/interactables/Switch/Switch.less
components/interactables/Switch/Switch.vue
components/views/settings/pages/privacy/Privacy.html

Implementation of layout for locked toggle
AP-530

feat(ui): implementation of layout for locked toggle

---

components/views/chat/chatbar/Chatbar.less
components/views/chat/chatbar/Editable.vue

add custom scrollbar to chatbar
AP-659

fix(ui): added custom scrollbar to chatbar

---

components/views/user/User.html
components/views/user/User.vue

added correct timestamp for last message
AP-118

feat(user): fix timestamp for user list AP-118

---

libraries/Files/test/FileSystem.test.ts

…
Increase the coverage from ~75% to 80%, from yellow to green.
AP-551

update(jest): add coverage for libraries/Files/FileSystem.ts

---

components/views/user/User.html
components/views/user/User.vue

hide the users has no messages in the sidebar
AP-116

feat(user): hide the users have no any message AP-116

---

components/interactables/Search/Result/Result.less

fix ui issues & scrolling issues in search result
AP-613, AP-692

fix(search): fix ui issues in search result

---

package.json

chore(lint): minor lint

---

components/interactables/ImageCropper/ImageCropper.vue
config.ts

update image cropper on sign up page
AP-654

fix(image-cropper): update image cropper on sign up page

---

components/views/chat/chatbar/Chatbar.vue
libraries/ui/Commands.ts

Typing indicator would get stuck on because of minor typo. Other changes were ESLint updates
[AP-669](https://satellite-im.atlassian.net/browse/AP-669)

fix(chatbar): fix typing indicator, minor eslint updates

---

store/audio/actions.ts

Fixed ToggleMute and ToggleDeafen in audio/actions which in turn fixes the issue with the keybind functions not working
AP-462

fix(audio-actions): fixed togglemute + toggledeafen for keybinds

---

store/settings/state.test.ts

add(jest): 100% code coverage for store/settings/state.test.ts

---

pages/chat/direct/_address.vue

first created/user with no friends goes to the direct message, and on mobile UI is broken, this PR fix this by redirecting to add friend page.
AP-668

fix(ui): redirect to add friend when no friends

---

libraries/WebRTC/TracksManager.test.ts
libraries/WebRTC/TracksManager.ts

add(jest): 100% code coverage for TracksManager.test.ts

---

components/ui/Breadcrumbs/Breadcrumbs.less

on settings > personalize page, user code is cut off on mobile, to fix this truncated the code using CSS
AP-684

fix(ui): fix user code cut off on settings > personalize

---

components/views/settings/pages/audio/options/__snapshots__/index.test.ts.snap
components/views/settings/pages/audio/options/index.test.ts

add(jest): 100% code coverage for settings/pages/audio/options

---

components/interactables/QuickProfile/QuickProfile.html
components/interactables/QuickProfile/QuickProfile.less

fix(quick-profile): fix 'x' mark style issues on popup
AP-679

fix(quick-profile): fix 'x' mark style issues on popup

---

libraries/Textile/TextileManager.ts

Remove duplicated initialization code in TextileManager class
AP-723

fix(TextileManager): remove duplicated initialization AP-723

---

components/views/settings/pages/storage/Storage.html
components/views/settings/profile/card/Card.html

chore(lint): minor linting

---

components/interactables/Search/Result/Result.less
components/interactables/Search/Result/Result.vue
libraries/IndexedDB/index.ts
types/ui/query.d.ts

modify search library response to include everything the UI will need
AP-707

fix(result): modify search library response to include everything the UI will need AP-707

---

components/interactables/Search/Input/Input.less

fix search option issues on iOS
AP-624

fix(search): fix search option issues on iOS

---

libraries/IndexedDB/index.ts

Fix crashing issue when input search options
AP-764

fix(search): prevent crashing for search options

---

components/interactables/Search/Result/Result.less

fix(search): fix search results ui on mobile
AP-755

fix(search): fix search results ui on mobile

---

components/ui/Global/Global.vue
components/ui/UpdateModal/UpdateModal.vue
components/views/chat/conversation/Conversation.less
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/toolbar/Toolbar.vue
components/views/navigation/toolbar/alerts/Alerts.vue
components/views/settings/pages/notifications/index.vue
libraries/IndexedDB/index.ts
libraries/Textile/BucketManager.ts
libraries/Textile/IdentityManager.ts
libraries/Textile/MailboxManager.ts
libraries/Textile/encoders.test.ts
libraries/ui/Alerts.test.ts
pages/generic/loading/index.vue
pages/server/chat/index.vue
store/prerequisites/actions.ts
store/settings/state.test.ts
store/textile/getters.test.ts
utilities/Heic.ts
utilities/Notifications.ts

- Removes commented-out code
- Removes console.log's
- Removes spam of comments and converts those to multiline comments
- Removes double spacing on comments
- Update comments - iOS instead of ios
- Minor linting

chore(update): minor updates

---

libraries/ui/Cursor.test.ts
libraries/ui/__snapshots__/Cursor.test.ts.snap

test(jest): add Cursor.ts test

---

libraries/Textile/BucketManager.test.ts
libraries/Textile/GroupChatManager.test.ts
libraries/Textile/__snapshots__/BucketManager.test.ts.snap
libraries/Textile/__snapshots__/GroupChatManager.test.ts.snap

- Adds `BucketManager.test.ts`
- Adds `GroupChatManager.test.ts`

add(jest): add tests BucketManager + GroupChatManager

---

store/ui/__snapshots__/mutations.test.ts.snap
store/ui/mutations.test.ts

- Adds `store/ui/mutations.test.ts`

test(jest): add jest test - store/ui/mutations.test.ts

---

store/friends/mutations.ts

Fixes type in /store/friends/mutations.ts 

chore(typo): fix typo

---

components/interactables/Search/SearchQuery.test.ts
libraries/Textile/BucketManager.test.ts

AP-787
The coverage on these files needs to be worked on more, though its warnings and errors from the lint have been resolved; it has not completely improved its coverage.

update(jest): patch lint errors and warnings

---

assets/styles/base.less

remove highlight from first suggested word
[AP-765](https://satellite-im.atlassian.net/browse/AP-765)

fix(accounts): remove highlight from first suggested word

---

components/views/chat/chatbar/controls/Controls.less

show tooltips above modals
[AP-760](https://satellite-im.atlassian.net/browse/AP-760)

fix(chat): tooltips show above modals

---

components/interactables/Search/Input/Input.less

fix "x" in the search bar is cutoff
AP-770

fix(search): fix "x" in search bar is cutoff

---

components/interactables/Search/SearchQuery.test.ts
components/interactables/Search/__snapshots__/SearchQuery.test.ts.snap

I investigate why a test unit is not behaving as it should, while also passing in an actual HTML argument into the test. In retrospect: the test was wrong because it's not calling querySelector correctly, while lack of documentation on the `caretPosition` function exacerbates this problem.
AP-780
Let me know if what I've written is incorrect, I would most be glad to improve them.

feat(jest): investigate testing issue, improving arguments

---

components/views/chat/group/Group.vue
components/views/files/upload/Upload.vue
components/views/friends/friend/Friend.vue
components/views/user/User.html
components/views/user/User.less
components/views/user/User.vue
locales/en-US.js
store/friends/actions.ts
store/friends/mutations.test.ts
store/friends/mutations.ts

remove friend on both client and ex friend sides by clicking on "remove friend" button
[AP-693](https://satellite-im.atlassian.net/browse/AP-693)

fix(friends): remove friends on both sides

---

cypress.json

Updates numTestsKeptInMemory value from 0 to 1

chore(cypress): update numTestsKeptInMemory value

---

store/files/actions.test.ts

feat(jest): 100% coverage for store/files/actions.ts

---

components/views/friends/quick/Quick.html
components/views/friends/quick/Quick.less
components/views/friends/quick/Quick.vue
store/ui/__snapshots__/state.test.ts.snap
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts
store/webrtc/actions.ts

change quick-chat popup position depend on active call
[AP-611](https://satellite-im.atlassian.net/browse/AP-611)

fix(chat): change quick-chat popup position on active call

---

package.json

Updates Cypress version from 9.2.0 to 9.5.0

chore(cypress): update cypress version

---

store/textile/mutations.test.ts

feat(jest): 100% coverage for store/textile/mutations.ts

---

components/views/files/upload/Upload.vue
plugins/thirdparty/persist.ts
store/chat/__snapshots__/state.test.ts.snap
store/chat/mutations.ts
store/chat/state.ts
store/chat/types.ts
types/ui/friends.d.ts

- persist uploaded images if the user switches chats or goes to friends list/files page
- clean up eslint error related to filter expecting return
AP-113
- I would like to refactor Upload.vue when things aren't as busy

fix(eslint): Persist uploaded chat images during session AP-113

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/Editable.vue
components/views/chat/enhancers/Enhancers.less
components/views/chat/enhancers/Enhancers.vue
components/views/chat/message/Message.less
layouts/chat.vue

Emojis in the chatbar now are correctly placed based on the last user selection
AP-809
https://user-images.githubusercontent.com/50131258/154547783-ad459589-06b8-4723-b0be-f1806ccae369.mov

chore(chatbar): chatbar selection and emoji insertion AP-809

---

components/ui/ComingSoon/ComingSoon.html
components/ui/ComingSoon/ComingSoon.less
components/ui/ComingSoon/ComingSoon.vue
components/views/chat/chatbar/controls/Controls.html
components/views/navigation/slimbar/Slimbar.html
components/views/settings/pages/audio/Audio.html
locales/en-US.js
package.json

…ed items
This adds a coming soon wrapper that we can put on components. This is not tied to a ticket yet, but Sheldon and I are working on a ticket to add coming soon indicators for the alpha launch.
As a test, disables the server list in the slimbar, and send money in the chatbar

chore(comingSoon): coming soon component soon to be added

---

components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/Editable.vue
store/ui/actions.ts

fix focus issue on chatbar
AP-823

fix(chat): fix focus issue on chatbar

---

components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.vue

fix disappearing of emojis
[AP-796](https://satellite-im.atlassian.net/browse/AP-796)

fix(chat): fix disappearing of emojis

---

components/ui/ComingSoon/ComingSoon.html
components/ui/ComingSoon/ComingSoon.less

cut off hover on the coming soon
AP-825

fix(chat): cut off hover on the coming soon

---

mock/tests/__snapshots__/glyphs.test.ts.snap
mock/tests/glyphs.test.ts

feat(jest): 100% coverage for mock/tests/glyph.test.ts

---

mock/tests/__snapshots__/friends.test.ts.snap
mock/tests/friends.test.ts

feat(jest): 100% coverage for mock/tests/friends.test.ts

---

libraries/Solana/SolanaManager/SolanaManager.test.ts
libraries/Solana/SolanaManager/__snapshots__/SolanaManager.test.ts.snap

Adds `libraries/Solana/SolanaManager/SolanaManager.test.ts`

chore(jest): add solana manager test

---

store/webrtc/actions.ts

correct position of quick chat while calling
[AP-820](https://satellite-im.atlassian.net/browse/AP-820)

fix(chat): quick chat position while calling

---

components/views/settings/profile/card/Card.less

fix timezone cut issues on mobile
AP-727

fix(timezone): fix timezone cut issues on mobile

---

assets/styles/base.less
components/interactables/Switch/Switch.less

fix cursor for disabled dropdown
AP-690

fix(dropdown): fix cursor for disabled dropdown

---

libraries/Files/test/Bucket.test.ts

Self-explanatory. Currently trying to figure out how I can cover the init function; could just merge this for now, I'll add it later.
AP-554

feat(jest): 54% coverage for libraries/Files/remote/textile/Bucket

---

libraries/Solana/ServerProgram/ServerProgram.test.ts

chore(jest): minor lint

---

libraries/Textile/IdentityManager.test.ts
libraries/Textile/__snapshots__/IdentityManager.test.ts.snap

chore(jest): add identity manager test jest

---

libraries/Textile/TextileManager.test.ts
libraries/Textile/__snapshots__/TextileManager.test.ts.snap

Adds libraries/Textile/TextileManager.test.ts

chore(jest): add jest test for textile manager

---

components/views/chat/search/Result/Result.html
components/views/chat/search/Result/Result.vue
components/views/chat/search/SearchUtil.ts
components/views/chat/search/__snapshots__/SearchUtil.test.ts.snap

Show correct counts info when search messages
AP-768-new

fix(result): fix result count issue

---

components/views/chat/search/Input/Input.html
components/views/chat/search/Input/Input.vue
components/views/chat/search/Result/Item/Item.vue
components/views/chat/search/Result/Result.vue
libraries/IndexedDB/index.ts
types/ui/query.d.ts

fix indexeddb function and relevant issues with new table strcture
AP-707, AP-709, AP-758

fix(result): fix indexeddb function and relevant issues

---

components/ui/Global/Global.vue
components/views/navigation/toolbar/Toolbar.vue
libraries/WebRTC/Call.ts
locales/en-US.js

show toast with error of permissions instead of app crash
[AP-824](https://satellite-im.atlassian.net/browse/AP-824)

fix(chat): show toast with error of permissions instead of app crash

---

locales/en-US.js

fix friends.all title issue on mobile device
AP-842

fix(friends): fix friends.all title issue on mobile device

---

components/views/settings/pages/accounts/Accounts.html
components/views/settings/pages/accounts/index.vue

Hides transaction fee limit
before
after

chore(update): hides transaction fee limit

---

mock/tests/__snapshots__/groups.test.ts.snap
mock/tests/groups.test.ts

feat(jest): 100% coverage for mock/tests/groups.test.ts

---

components/views/chat/message/Message.less

There is a minor UI issue in archived messages. This PR fix this.
AP-695

fix(ui): ui issue in archived message

---

components/views/media/incomingCall/IncomingCall.vue

Stop incoming call sounds after user answered. This was already resolved but we introduced a regression.

fix(webrtc): changed beforeUnmount regression to beforeDestroy

---

components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/index.vue

This wasn't on the hide list but this title/subtitle doesn't have any features below so I hid those.
before
after

chore(update): hide title subtitle profile

---

store/ui/__snapshots__/mutations.test.ts.snap
store/ui/mutations.test.ts

Self-explanatory. There's room for improvement, but I think this will do for now.
AP-781

feat(jest): 80% coverage for store/ui/mutations

---

libraries/Crypto/Crypto.test.ts
libraries/Solana/ServerProgram/ServerProgram.test.ts
libraries/SoundManager/SolanaManager.test.ts
libraries/Textile/TextileManager.test.ts

Fix the errors and warnings on the files (libraries/Crypto/Crypto.test.ts, libraries/Solana/ServerProgram/ServerProgram.test.ts, libraries/SoundManager/SolanaManager.test.ts, libraries/Textile/TextileManager.test.ts) by adhering to the warnings it raised (`eslint(new-cap)`, `eslint(prefer-const)`)
AP-838

chore(jest): fix lint error and warnings

---

cypress.json

Updates Cypress config file due to snapshots

chore(cypress): update cypress file

---

components/ui/Global/Global.vue

When accepting a call routes user to chat for whoever is calling
AP-710

feat(global): routes to user when accepting call

---

.eslintrc.js

- I noticed a bit of back and forth regarding vue3 lint suggestions. This will keep things less confusing until we're able to upgrade

chore(lint): remove vue3 suggestions until we upgrade

---

components/views/files/upload/Upload.vue

when entering to 'chat/direct' (click satellite logo), the screen sometimes crashed
AP-897

fix(chat): when entering to 'chat/direct', fix crash

---

components/views/settings/Sidebar.vue
components/views/settings/breadcrumbs/Breadcrumbs.html
components/views/settings/breadcrumbs/Breadcrumbs.less
components/views/settings/breadcrumbs/Breadcrumbs.vue
components/views/settings/modal/Modal.html
components/views/settings/modal/Modal.vue
store/ui/types.ts

On settings modal, the breadcrumbs navigation is weird, This PR fixes these weird breadcrumbs.
AP-728

feat(ui): change the breadcrumbs on settings modal

---

components/ui/UpdateModal/UpdateModal.html
components/ui/UpdateModal/UpdateModal.less
components/ui/UpdateModal/UpdateModal.vue
libraries/ui/ReleaseNotes.ts

…ting
fix update modal, add loader while realese notes are getting
[AP-841](https://satellite-im.atlassian.net/browse/AP-841)

fix(unlock): fix update modal, add loader on release notes

---

components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.vue

fix 'clicking in and out of emoji's/glyphs will cause a menu to disappear'
AP-895

fix(emoji): fix 'clicking in and out of emoji's/glyphs will cause menu to disappear'

---

utilities/Messaging.ts

Users color of they're profile bubble will be a different color from one in chat
AP-921

fix(chat): fix profile different bubble color issue

---

components/ui/Chat/Embeds/File/File.vue
components/ui/Chat/Image/Image.html
components/ui/Chat/Image/Image.vue
components/views/chat/message/Message.html
package.json

- switch any manual filesize conversion to use the npm package that was already installed
- I did this because it will have an easier time with locales in the future
- update filesize package
- cleanup data attributes/methods that aren't being used
AP-827

fix(fileSize): standardize filesize conversion and general component cleanup

---

components/views/chat/message/Message.vue
config.ts

fix displaying emojies with modificators 
[AP-767](https://satellite-im.atlassian.net/browse/AP-767)

fix(chat): fix big emoji with letter c

---

components/views/files/file/File.vue
components/views/files/view/View.html
components/views/files/view/View.less
components/views/files/view/View.vue

- show image preview on file view if possible.
- clean up css
AP-902, AP-900

fix(files): show image if possible and css cleanup

---

libraries/Textile/GroupChatManager.ts
libraries/Textile/TextileManager.ts
locales/en-US.js
mock/groups.ts
store/accounts/types.ts
types/ui/core.d.ts

Encrypts and decrypts messages sent to group chats
Ap 721
I think testing would just be making sure messages are still sending, unsure though if there is a better way

fix(encryption): encrypt group chat messages

---

mock/tests/__snapshots__/groups.test.ts.snap

chore(jest): update snap

---

store/getters.test.ts

feat(jest): 100% coverage for store/getters AP-964

---

components/ui/Chat/Image/Image.html

currently crashes when you click an image in chat
AP-965

fix(image): fix crashes when you click an image in chat

---

components/interactables/QuickProfile/QuickProfile.vue
components/ui/User/State/State.vue
components/views/chat/group/Group.vue
components/views/chat/message/reply/Reply.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.less
components/views/navigation/toolbar/Toolbar.vue
store/ui/actions.ts
store/ui/mutations.ts
store/ui/types.ts

fix mobile adaptation of chat toolbar
[AP-840](https://satellite-im.atlassian.net/browse/AP-840)

fix(chat): mobile adaptation of chat toolbar

---

components/views/files/list/List.html
components/views/files/list/List.vue
components/views/media/incomingCall/IncomingCall.vue
config.ts
libraries/Files/Directory.ts
libraries/Files/Fil.ts
libraries/Files/FilSystem.ts
libraries/Files/abstracts/Item.abstract.ts
libraries/Files/types/filesystem.ts
pages/files/browse/Browse.html
utilities/__snapshots__/Messaging.test.ts.snap

- store modified in Item class
- dynamically set modified for a Directory based on latest modified value of a child
- update modified on like/share
- refresh every minute on list view
AP-907

feat(files): add support for last modified timestamp

---

components/views/files/upload/Upload.vue

Fix the upload image error.
AP-967
Test it also on localhost! Thanks!

fix(upload): image upload

---

.env.example
config.ts
package.json

Enables the use of a dev torrent tracker URL using an env var
Change made while developing [AP-973](https://satellite-im.atlassian.net/browse/AP-973)

chore(dotenv): enable dev webtorrent tracker with env var

---

assets/styles/base.less

Fis swipe refresh issue in some mobile devices
AP-747

fix(base): fix swipe refresh issue AP-747

---

middleware/authenticated.ts

check prerequisites actions on page load
[AP-974](https://satellite-im.atlassian.net/browse/AP-974)

fix(auth): check prerequisites actions on page load

---

pages/friends/list/FriendsList.html
pages/friends/list/index.vue

Hide blocked friends section
before
after

chore(update): hide blocked friends

---

libraries/Files/types/file.ts

- support for all file types on MDN common page
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
AP-931
- if there's any that you would like to see added, let me know

fix(fileTypes): add support for common file types

---

assets/styles/base.less
components/views/chat/chatbar/controls/Controls.html
components/views/chat/chatbar/controls/Controls.less
components/views/navigation/sidebar/Sidebar.less

change send-message-button color depend on theme
[AP-869](https://satellite-im.atlassian.net/browse/AP-869)

fix(theme): send-message-button color depend on theme

---

components/views/chat/enhancers/Enhancers.less

remove emojis horizontal scroll
[AP-993](https://satellite-im.atlassian.net/browse/AP-993)

fix(chat): remove emojis horizontal scroll

---

components/views/navigation/toolbar/Toolbar.html
locales/en-US.js

grey out options & update coming soon buttons
AP-862

fix(toolbar): grey out options & update coming soon buttons

---

components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.vue

chore(gifs): hide gifs

---

jest.config.js
libraries/Files/test/Bucket.test.ts

Investigated why the Bucket.ts wasn't covered; increase coverage from 0 to 19%, the init will be covered soon.
AP-554

feat(jest): 19% coverage for Bucket.ts

---

utilities/Filesize.test.ts
utilities/__snapshots__/Filesize.test.ts.snap

feat(jest): 100% coverage for Filesize.ts

---

.env.example
README.md

Minor update on env example file.
Minor update on read me.

chore(update): minor update

---

components/views/settings/modal/Modal.html
components/views/settings/modal/Modal.less
components/views/settings/modal/Modal.vue

show full sidebar in settings on mobile
[AP-935](https://satellite-im.atlassian.net/browse/AP-935)

fix(settings): show full sidebar in settings on mobile

---

components/views/settings/Sidebar.vue

fix highlight issue on mobile settings modal
AP-963

fix(settings): fix highlight issue on mobile settings modal

---

pages/friends/list/index.vue

Fixed the null name issue
AP-968

fix(friend): fix undefined name issue

---

components/views/chat/chatbar/Chatbar.vue
components/views/chat/enhancers/Enhancers.vue
components/views/chat/enhancers/glyphs/item/Item.vue
components/views/files/upload/Upload.vue
config.ts
libraries/Textile/GroupChatManager.ts
pages/chat/groups/_id.vue
store/textile/actions.ts

Fixes message types available to group chats
AP-744
Some craziness happened when rebasing dev pulling in a ton of commits .

fix(groupChat): all message types working in group chats

---

components/views/media/user/User.less

Fixed the mute icon position issue
AP-981

fix(user): fix mute icon position issue AP-981

---

store/chat/actions.test.ts

feat(jest): 100% coverage for store/chat/actions AP-1000

---

layouts/Layout.less

fix chatbar push bottom while calling
[AP-985](https://satellite-im.atlassian.net/browse/AP-985)

fix(chat): chatbar push bottom while calling

---

assets/styles/base.less
pages/setup/privacy/Privacy.html
store/accounts/__snapshots__/state.test.ts.snap
store/accounts/state.ts

Changed the toggle default setting
AP-1016

fix(privacy): change the toggle default setting

---

layouts/Layout.less

I got overzealous removing css last week. this fixes new bug of files page expand/collapse not working
AP-976

fix(collapse): files page collapse fix

---

plugins/thirdparty/persist.ts
store/settings/actions.ts
store/settings/mutations.ts
store/settings/state.ts
store/settings/types.ts

Fixed storage clear issue
AP-785

fix(settings): fix storage clearing issue

---

components/views/chat/chatbar/Chatbar.vue
libraries/Enums/types/messaging-types.ts

fix paste from vscode
[AP-1028](https://satellite-im.atlassian.net/browse/AP-1028)

fix(chat): paste from vscode

---

store/webrtc/actions.ts

re-subscribe textile if it is unsubscribed
AP-224

fix(textile): resubscribe textile if it is unsubscribed

---

middleware/__snapshots__/authenticated.test.ts.snap
middleware/authenticated.test.ts

feat(jest): 89% coverage for middleware/authenticated.ts AP-570

---

components/views/user/profile/Profile.less

Close icon in profile is sitting in mobile status bar and causes user from not being able to close profile modal
AP-991

fix(profile): fix close button issue on ios device

---

components/views/marketplace/Marketplace.html
components/views/marketplace/Marketplace.less
components/views/marketplace/Marketplace.vue
components/views/marketplace/glyphs/Glyphs.less

add swiper to marketplace modal & fix broken styles on a mobile device
AP-325

fix(marketplace): swiper marketplace modal, fix broken styles on mobile

---

README.md
cypress.json
cypress/fixtures/example.json
cypress/fixtures/test-file.txt
cypress/integration/chat-features.js
cypress/integration/chat-pair-features.js
cypress/integration/create-account-negative-tests.js
cypress/integration/create-account.js
cypress/integration/import-account-negative-tests.js
cypress/integration/import-account.js
cypress/integration/localstorage-validations.js
cypress/integration/mobiles-responsiveness.js
cypress/integration/pair-chat/chat-first-user.js
cypress/integration/pair-chat/chat-second-user.js
cypress/integration/pin-unlock-validations.js
cypress/integration/privacy-page-toggles.js
cypress/integration/snapshots-test.js
cypress/support/commands.js

This adds the latest PR from Luis - that was already added before I merged this - [one](https://github.com/Satellite-im/Core-PWA/pull/2274)
I added this separately to not break anything else on that PR.

chore(cypress): import luis work

---

cypress/plugins/index.js
cypress/support/index.js

chore(cypress): update files

---

components/ui/Chat/Embeds/File/File.html
components/ui/Chat/Image/Image.html
components/views/chat/group/Group.html
components/views/chat/message/Message.html
components/views/chat/message/edit/Edit.html
components/views/chat/message/glyph/Glyph.html
cypress-first-user.json
cypress-second-user.json
package.json

- Adding data-cy attributes to ui/views components used in cypress tests
- Adding cypress-first-user.json and cypress-second-user.json setup files needed to run in parallel two cypress instances
- Adding scripts to package.json to run two cypress instances in parallel
- Adding the dependency "concurrently" into package.json needed to run two cypress instances in parallel
AP-714

test(cypress): add cypress locators, setup changes to test 2 accounts

---

pages/auth/register/index.vue
store/accounts/actions.ts

fix create user after page update
[AP-1027](https://satellite-im.atlassian.net/browse/AP-1027)

fix(register): create user after page update

---

cypress.json

Updates Cypress json file, removing plugin env settings from plugin that was removed.

chore(update): update cypress

---

cypress/fixtures/mobile-devices.json

Minor copy update on devices list on Cypress.

chore(cypress): minor update on devices list

---

components/interactables/AsideMenu/AsideMenu.html
components/views/settings/modal/Modal.html
components/views/settings/modal/Modal.less

Fix 'Tab for settings looks small and is sitting in top status bar of iPhone'
AP-1026

fix(settings): fix tab for settings sidebar toggle

---

libraries/WebRTC/Call.ts

1. When a user calls and hangs up it hangs up and makes the incoming call modal disappear for the user they're calling
2. When calling a user back after hanging up it works everytime
AP-875 / AP-894

fix(call): fixed webrtc signaling issues

---

components/views/media/Media.vue

Removes mute/unmute sound played on the opposite users while on call
AP-803

fix(media): removed "mute sound" played on recipient users

---

components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.less
components/views/chat/enhancers/glyphs/Glyphs.html
components/views/chat/enhancers/glyphs/Glyphs.less
components/views/chat/enhancers/glyphs/item/info/Info.less

Fix scroll through glyphs/emoji
AP-889

fix(chat): scroll through glyphs/emoji

---

assets/styles/base.less
components/interactables/Input/Input.html
components/interactables/Input/Input.less
components/interactables/Input/Input.vue
components/ui/ComingSoon/ComingSoon.html
components/ui/ComingSoon/ComingSoon.less
components/ui/ComingSoon/ComingSoon.vue
components/views/navigation/sidebar/Sidebar.html
locales/en-US.js

deactivate sidebar search
AP-1072

fix(sidebar): deactivate sidebar search

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
config.ts
store/webrtc/actions.ts

Fixes persistent "is typing" bug
AP-830

fix(chatbar): fixed persistent "is typing" bug

---

libraries/SearchIndex/__snapshots__/index.test.ts.snap
libraries/SearchIndex/index.test.ts

Adds more coverage on `libraries/SearchIndex/index.test.ts`
before
after

chore(jest): add more coverage on libraries/SearchIndex/index.test.ts

---

components/ui/Chat/Image/Image.html
components/ui/Chat/Image/Image.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
components/views/chat/message/Message.vue

fix hover on preview image
[AP-1015](https://satellite-im.atlassian.net/browse/AP-1015)

fix(chat): change message hover

---

components/views/files/row/Row.html

title - files list view
AP-1094
thanks for finding it

fix(files): prevent context click during load

---

components/views/files/controls/Controls.vue
config.ts
locales/en-US.js

fix(files): prevent folder name of pure spaces

---

components/views/files/aside/Aside.less

- remove box shadow because button is disabled
AP-1109

fix(files): remove glow on upgrade button

---

components/views/chat/message/Message.less
components/views/chat/message/Message.vue
components/views/chat/message/actions/Actions.less

fix emojies size
[AP-1103](https://satellite-im.atlassian.net/browse/AP-1103)

fix(chat): emojies size

---

libraries/Files/test/TextileFileSystem.test.ts

Self-explanatory. The way that I improved the unit test is by passing in an SVG file to satisfy the SVG condition on the module.
Increasing coverage of AP-927

feat(jest): 72% coverage for TextileFileSystem.ts

---

components/interactables/Search/SearchUtil.test.ts
libraries/SearchIndex/index.test.ts
libraries/Solana/SolanaManager/SolanaManager.test.ts
libraries/Textile/GroupChatManager.test.ts
libraries/Textile/IdentityManager.test.ts
libraries/WebRTC/TracksManager.test.ts
libraries/ui/Cursor.test.ts

Fix eslint warnings on Jest tests

chore(jest): fix warnings

---

.github/workflows/add-label.yml
.github/workflows/cypress.yml
.github/workflows/run-jest-tests.yml

Updates Github Actions, adds more types on pull request.

chore(update): update github action

---

components/views/media/Media.vue

Closes the call after reloading the tab
AP-802

fix(media): close call on tab reload

---

components/mixins/UI/WithHistory.ts
components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/Editable.vue
config.ts
libraries/Enums/types/keybindings.ts

Add undo/redo functionalities to the chatbar.
AP-515
Test with `cmd+z` (ctrl on win) and `cmd+shift+z` and also with mouse right click and then undo/redo

feat(chatbar): undo/redo manager

---

components/views/files/file/File.vue
components/views/files/list/List.html
components/views/files/list/List.less
components/views/files/row/Row.html
components/views/files/row/Row.less

- hide modified and file type columns if sidebar isn't collapsed on smaller desktops
AP-953

fix(files): responsive issue on files list view

---

mock/tests/__snapshots__/wallet.test.ts.snap
mock/tests/wallet.test.ts

feat(jest): 100% coverage for mock/wallet.ts

---

store/accounts/mutations.test.ts

Improve current coverage
AP-663

feat(jest): 100% coverage for store/accounts/mutations

---

components/views/navigation/sidebar/controls/Controls.vue
libraries/SoundManager/SoundManager.ts
store/accounts/actions.ts
store/audio/actions.ts
store/sounds/actions.ts

disable sound when deafened
[AP-1022](https://satellite-im.atlassian.net/browse/AP-1022)

fix(audio): disable sound when deafened

---

components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.vue

reset emotes search on modal close/change
[AP-1118](https://satellite-im.atlassian.net/browse/AP-1118)

fix(chat): reset emotes search on modal close/change

---

libraries/Solana/ServerProgram/ServerProgram.test.ts
store/sounds/mutations.test.ts
store/ui/mutations.test.ts

Removes not used imports in Jest tests.

chore(jest): remove not used imports

---

components/interactables/Button/Button.html
components/interactables/Button/Button.vue
components/views/user/create/Create.html
components/views/user/create/Create.vue
config.ts

submit create user form on enter
[AP-1130](https://satellite-im.atlassian.net/browse/AP-1130)

fix(register): submit form on enter

---

store/settings/actions.test.ts

No tickets iirc
I think this is the first test in our codebase that is related to localStorage. Please review my PR thoroughly and let me know if I've made any mistakes and/or if there are improvements I can make to it. Thank you!

feat(jest): 100% coverage for store/settings/actions

---

store/settings/mutations.test.ts

feat(jest): 100% coverage for store/settings/mutations

---

components/views/friends/friend/Friend.html
components/views/friends/friend/Friend.vue
libraries/Solana/FriendsProgram/FriendsProgram.ts
store/friends/actions.ts

Fix bugs for adding friends. Adds a disable button to mitigate spamming, but also runs a check to see if friend was already added.
AP-966 & AP-968
I tested everything I could possibly think of, but I believe the real test will be when it's up on dev to make sure we aren't getting any race conditions.

fix(bug): added a check to see if friend was already added

---

components/views/settings/pages/profile/Profile.less

increase line height of title
[AP-1124](https://satellite-im.atlassian.net/browse/AP-1124)

fix(profile): increase line height of title

---

components/views/settings/profile/card/Card.html
mock/profile.ts

add condition for badges
[AP-1116](https://satellite-im.atlassian.net/browse/AP-1116)

fix(profile): add condition for badges

---

components/views/files/upload/previewItem/PreviewItem.less

change close button color depend on theme
[AP-1111](https://satellite-im.atlassian.net/browse/AP-1111)

fix(upload): change close button color depend on theme

---

components/views/chat/chatbar/reply/Reply.less

change replier name color
[AP-1112](https://satellite-im.atlassian.net/browse/AP-1112)

fix(reply): change replier name color

---

libraries/SoundManager/SoundManager.test.ts

feat(jest): 100% coverage for libraries/SoundManager/SoundManager

---

components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.vue
components/views/chat/enhancers/glyphs/item/Item.vue

Fixes the issue that prevent the user to send a glyph in a group chat
AP-1176
Send a glyph in a group chat

fix: possibility to send glyphs in group chats

---

libraries/Textile/BucketManager.test.ts

Removes not used stuff on `libraries/Textile/BucketManager.test.ts`

chore(jest): remove not used stuff

---

libraries/Files/test/Fil.test.ts

feat(jest): 100% coverage for Fil.test.ts

---

libraries/Files/test/Directory.test.ts

Covered some of the uncovered branches, open to improvements.
AP-1163

feat(jest): 95% branch covered for Directory.test.ts

---

middleware/__snapshots__/authenticated.test.ts.snap
middleware/authenticated.test.ts

feat(jest): 100% coverage for authenticated.ts

---

store/ui/mutations.test.ts

feat(jest): 81% coverage for store/ui/mutations

---

store/sounds/actions.test.ts

Cover remaining uncovered function
Not quite AP-1100, but sufficient in my opinion.

feat(jest): 100% coverage for store/sounds/actions

---

cypress.json

chore(cypress): add retries

---

components/views/navigation/toolbar/Toolbar.html

on any mobile device go to chat page , video icon is touching the marketplace icon in toolbar
AP-1145

fix(mobile): video icon touching marketplace icon

---

package.json

In the spirit of improving the overall performance of the app, lets add the command for analyzing the bundle size of the app

chore(scripts): package.json updated

---

components/interactables/ClickToEdit/ClickToEdit.html
components/interactables/ClickToEdit/ClickToEdit.vue
components/interactables/Tabs/Tabs.less
components/views/user/profile/About.vue
components/views/user/profile/Profile.less
config.ts
libraries/Enums/types/keybindings.ts

Fix remaining things in profile note
1. borders on tab, 2. prevent blank, 3. cap the note length at 256
AP-1142

fix(profileNote): fix remaining issues in profile note

---

components/ui/Chat/Scroll/Scroll.html
components/ui/Chat/Scroll/Scroll.less
components/ui/Chat/Scroll/Scroll.vue
components/views/chat/conversation/Conversation.html
components/views/chat/message/glyph/Glyph.less
layouts/Layout.less
layouts/chat.vue
layouts/server.vue
pages/chat/direct/Direct.less
plugins/thirdparty/persist.ts

fix chat scroll on iOS
[AP-1008](https://satellite-im.atlassian.net/browse/AP-1008)

fix(chat): scroll on iOS

---

components/views/navigation/sidebar/Sidebar.html

change key for users
[AP-1279](https://satellite-im.atlassian.net/browse/AP-1279)

fix(sidebar): change key for users

---

components/views/user/create/Create.html
components/views/user/create/Create.vue

add loader while image uploading
[AP-1211](https://satellite-im.atlassian.net/browse/AP-1211)

fix(register): add loader while image uploading

---

assets/styles/framework/typography.less
components/ui/Chat/Embeds/AudioPlayer/AudioPlayer.less
components/ui/Chat/Embeds/File/File.html
components/ui/Chat/Embeds/File/File.less
components/ui/Chat/Embeds/File/File.vue
libraries/Files/FilSystem.ts

- refactor component to be cleaner
- improve mobile styles
- global ellipsis overflow class
- fix tiff embed issue using utility function
AP-1192, AP-1181
- mobile issue is marked low priority, but I had already done it yesterday in a PR I decided to refactor

fix(chat): mobile file embed styling

---

components/ui/ComingSoon/ComingSoon.html
components/ui/ComingSoon/ComingSoon.less
components/ui/SatelliteCircle/SatelliteCircle.html

remove glitch effect on hover in safari
[AP-1210](https://satellite-im.atlassian.net/browse/AP-1210)

fix(toolbar): remove glitch effect on hover in safari

---

components/views/chat/message/reactions/Reactions.vue
types/messaging.d.ts

Fix 'If someone reacts to a message and you click to add that reaction as well nothing will happen'
AP-986
Please try to react(emoji) to the message with User1 and after that try to add react to User1's emoji reaction.

fix(reaction): fix issue when try to add emoji reaction

---

components/views/chat/message/Message.vue

- save image functionality
- I tried to minimize the # of blobs we're storing in memory while keeping copy/save image fast

feat(chat): save image

---

store/ui/actions.test.ts

feat(jest): 84% coverage for store/ui/actions

---

libraries/ui/Common.test.ts
libraries/ui/__snapshots__/Common.test.ts.snap
utilities/FileType.test.ts
utilities/__snapshots__/FileType.test.ts.snap

- adds `Common.test.ts`
- adds `FileType.test.ts`

chore(jest): add Common.test.ts + FileType.test.ts

---

cypress/integration/chat-features.js
cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/chat-top-toolbar.js
cypress/integration/pin-unlock-validations.js
cypress/integration/privacy-page-toggles.js

- Skipping cypress tests failing in CI so we can research to fix them and meanwhile avoid failures on cypress run tasks in CI
None

test(cypress): skip cypress tests failing on CI

---

utilities/EnvInfo.ts

- minor error cleanup. noticed while I was doing canvas work and stashed for later

fix(env): clean up envinfo errors via casting

---

components/views/callToAction/CallToAction.less

in coming soon page, there's a top padding issue. it's fine on desktop and android mobile. on iPhone screen overlaps with the status bar.
AP-1129

fix(mobile): coming soon page top padding issue

---

components/views/navigation/toolbar/Toolbar.less

fix lack resolution of icons
[AP-1204](https://satellite-im.atlassian.net/browse/AP-1204)

fix(toolbar): fix lack resolution of icons

---

components/views/user/create/Create.vue
store/files/types.ts
utilities/NSFW.ts

throw error on unscannable file type and block upload
[AP-959](https://satellite-im.atlassian.net/browse/AP-959)

fix(register): throw error on unscannable file type and block upload

---

cypress/fixtures/mobile-devices.json

chore(cypress): update devices

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue

Hide commands from chatbar
AP-1315
I've commented out the parts, if you want to completely remove them let me know.

chore(commands): hide commands for early access

---

store/textile/actions.ts

fix 'if a user sends reply chat will auto-scroll to bottom'
AP-1182

fix(reply): fix 'if user sends reply chat will autoscroll to bottom'

---

components/views/chat/search/input/Input.html
components/views/chat/search/result/Result.html
components/views/chat/search/result/Result.less
components/views/chat/search/result/Result.vue
components/views/chat/search/result/ResultGlobal.less
components/views/chat/search/result/item/Item.html
components/views/chat/search/result/item/Item.less
components/views/chat/search/result/item/Item.vue
components/views/chat/search/result/meta/Meta.html
components/views/chat/search/result/meta/Meta.less
components/views/chat/search/result/meta/Meta.vue
locales/en-US.js
store/textile/actions.ts
store/ui/types.ts
types/search/search.ts

- results count that reflects current page, rather than just the total result count
- translations for a variety of results (0,1,multipage)
- fix pagination color w/ moonless night theme
- rework styles to be easier to read, concise, closer to figma
- add timestamps to search results (they update every minute)
AP-1328

feat(search): better search results pagination counter and timestamps

---

.github/workflows/cypress.yml
components/views/navigation/sidebar/Sidebar.html
cypress.json
cypress/integration/chat-features.js
cypress/integration/chat-glyphs-validations.js
cypress/integration/mobiles-responsiveness.js
cypress/support/commands.js
package.json

- Testing turning off the video capture which apparently should solve the issues on CI when cypress process gets stuck on GH action
- Fix for mobile responsiveness cypress script for chat scenarios
- Adding one data-cy attribute for the hamburger button on sidebar
- Small improvement on chat edit command and chat features cypress test related to this, since this one failed during one of my local tests
- Small improvement on chat glyphs validations cypress test
None
Cypress Video for Mobiles-responsiveness.js:
https://user-images.githubusercontent.com/35935591/162083649-50e6cfdd-830d-4307-a6b5-9ce4a0e3507c.mp4
Cypress Video for Chat-Glyphs-Validations.js: …

test(cypress): draft for fixes on ci and mobile responsiveness

---

assets/styles/base.less
assets/styles/themes/moonless_night.less
layouts/chat.vue
layouts/files.vue
layouts/friends.vue
layouts/server.vue
utilities/Colors.ts

fix selection text color in safari
[AP-1207](https://satellite-im.atlassian.net/browse/AP-1207)

fix(colors): fix selection text color in safari

---

components/views/friends/add/Add.vue
pages/friends/list/FriendsList.html
store/accounts/actions.ts
store/textile/actions.ts

fix unknown name issue when the user is registered with an avatar.
AP-920

fix(chat): fix unknown name issue when the user is registered with an avatar

---

utilities/Colors.test.ts
utilities/__snapshots__/Colors.test.ts.snap

chore(jest): add Colors.test.ts

---

components/views/chat/group/Group.vue
components/views/friends/quick/Quick.html
components/views/friends/quick/Quick.vue
components/views/group/clickable/Clickable.html
components/views/group/clickable/Clickable.vue
components/views/group/icon/GroupIcon.html
components/views/group/icon/GroupIcon.vue
components/views/group/invite/Invite.html
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.vue
components/views/navigation/toolbar/Toolbar.html
libraries/Solana/GroupChatsProgram/GroupChatsProgram.ts
libraries/Solana/GroupChatsProgram/GroupChatsProgram.types.ts
libraries/Solana/GroupChatsProgram/GroupCrypto.ts
libraries/Textile/GroupChatManager.ts
locales/en-US.js
pages/chat/groups/_id.vue
plugins/thirdparty/persist.ts
store/accounts/actions.ts
store/groups/__snapshots__/mutations.test.ts.snap
store/groups/__snapshots__/state.test.ts.snap
store/groups/actions.ts
store/groups/mutations.test.ts
store/groups/mutations.ts
store/groups/state.ts
store/groups/types.ts

Add event subscriptions to handle group updates
AP-1174

feat(groupChats): add group events AP-1174

---

components/views/chat/message/Message.vue

fix emoji picker position in message
[AP-1316](https://satellite-im.atlassian.net/browse/AP-1316)

fix(message): emoji picker position

---

libraries/Files/test/TextileFileSystem.test.ts

chore(jest): remove not used test

chore(jest): remove not used test

---

components/views/group/icon/GroupIcon.html

chore(lint): minor group lint

---

store/groups/mutations.test.ts

feat(jest): 100% coverage for store/groups/mutations

---

.github/workflows/lint-PR-title.yml

- Update action on lint PR to include more types

refactor(github): update action on lint PR - AP-1362

---

components/views/chat/message/Message.vue

cancel message edit on unmount
[AP-1357](https://satellite-im.atlassian.net/browse/AP-1357)

fix(chat): cancel message edit on unmount

---

components/views/chat/group/Group.vue
components/views/chat/message/Message.vue
components/views/chat/message/reply/Reply.html
components/views/chat/message/reply/Reply.vue
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.vue
components/views/user/User.html
components/views/user/User.less
components/views/user/User.vue
locales/en-US.js
plugins/local/dayjs.ts
store/textile/mutations.ts
utilities/Messaging.ts

Restyles user's UI on sidebar
AP-1156
For testers, dates notification correct behaviour should be:
- "now" between 0 and 1 minute
- "hh:mm AM/PM" between 1 minutes and a day
- "yesterday" the day before
- "2 d" 2 days before 
- "MM/DD/YYYY" > 2 days before
***Updated with new format

fix(user): styled as planned on figma

---

store/ui/mutations.test.ts

AP-781
It is necessary to remove `addReaction` from the code so that the coverage will go up extremely, given that it is of no use anymore in the codebase.

feat(jest): 79% coverage for store/ui/mutations.ts

---

components/views/chat/conversation/Conversation.less

White-block (scrollbar) appearing while sending message in chat
AP-1356

fix(chat): fix scrollbar appearing while sending message

---

.github/workflows/cypress.yml

- Remove cypress video artifact since we are not saving videos during CI execution of cypress
None

chore(cypress): update workflow file from cypress gh action

---

components/ui/Chat/Info/Info.html
components/ui/Chat/Info/Info.less
components/ui/Chat/Info/Info.vue
components/ui/Chat/Info/types.d.ts
components/ui/Chat/Scroll/Scroll.vue
components/views/chat/chatbar/Chatbar.less
layouts/chat.vue
locales/en-US.js
store/ui/__snapshots__/state.test.ts.snap
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts

create older messages info block above chatbar
[AP-11](https://satellite-im.atlassian.net/browse/AP-11)

feat(chat): create older messages info block above chatbar

---

components/mixins/UserPermissions/__snapshots__/index.test.ts.snap
components/mixins/UserPermissions/index.test.ts

- Adds more tests in components/mixins/UserPermissions/index.test.ts

chore(jest): add more tests on UserPermissions/index.test.ts

---

components/views/chat/search/SearchQuery.test.ts

- Removes unused declarations
- Removes not needed comment

chore(jest): update test

---

libraries/Crypto/Crypto.test.ts
libraries/Crypto/__snapshots__/Crypto.test.ts.snap

- Adds more tests in Crypto.test.ts

chore(jest): add more tests in Crypto.test.ts

---

libraries/Files/test/FilSystem2.test.ts
libraries/Files/test/__snapshots__/FilSystem2.test.ts.snap

- Adds more coverage on libraries/Files/test/FilSystem.test.ts
before
after

chore(jest): more tests

---

libraries/Solana/Solana.test.ts
libraries/Solana/__snapshots__/Solana.test.ts.snap

- Adds more coverage in libraries/Solana/Solana.test.ts
before
after

chore(jest): add more solana tests

---

components/ui/DroppableWrapper/DroppableWrapper.vue
components/views/files/controls/Controls.html
components/views/files/controls/Controls.vue
layouts/files.vue
locales/en-US.js
pages/files/browse/Browse.html
store/ui/getters.ts
tsconfig.json

- refactor files upload to accommodate file drag & drop
- improve tsconfig to support drag & drop event files
- prevent upload if currently in progress
- minor readability/type improvements along the way
AP-925
- I feel like the way I accessed the ref of a child component is wonky, any better ways?
- discussed with Phill. We eventually want to drag and drop files to move them around / upload to a specific folder on drop. This is a good first step

feat(files): dropzone for file uploads

---

store/friends/actions.ts

- Removes not used import on store/friends/actions.ts

chore(import): remove not used import

---

assets/styles/framework/ui.less
components/ui/SimpleScroll/SimpleScroll.html
components/ui/SimpleScroll/SimpleScroll.less
components/ui/SimpleScroll/SimpleScroll.vue
components/views/user/profile/Profile.html

Create a new simpler scrollbar component
AP-1336

chore(scrollbar): created new scrollbar component

---

components/ui/Chat/Scroll/Scroll.vue

Fixes a simple problem where we blur the input also on desktop when scrolling in chat

fix: mobile keyboard update

---

locales/en-US.js

Update locale
"Select which account" instead of "Select with account"

chore(locales): update locale

---

store/ui/types.ts

before
after
accounts & devices instead of accounts

chore(update): update bread

---

components/ui/Chat/Image/Image.html
components/ui/Chat/Image/Image.less
components/ui/Chat/Image/Image.vue
components/views/chat/message/Message.vue
components/views/chat/message/actions/Actions.less
components/views/chat/message/reply/Reply.html
locales/en-US.js

show placeholder on image load error
[AP-1378](https://satellite-im.atlassian.net/browse/AP-1378)

fix(chat): show placeholder on image load error

---

components/views/message/Friend.html
components/views/message/Friend.less
components/views/message/Friend.vue

checked Figma design again and found there are some useless codes in view/message/Friend.vue, this PR removes useless codes.
AP-1383

chore(ui): refactor view/message/Friend

---

components/interactables/QuickProfile/QuickProfile.vue

change quick profile position on error display
[AP-1412](https://satellite-im.atlassian.net/browse/AP-1412)

fix(profile): change quick profile position on error display

---

store/meta/__snapshots__/state.test.ts.snap
store/meta/state.test.ts

- Adds store/meta/state.test.ts

chore(jest): add jest test - store/meta/state.test.ts

---

store/meta/mutations.test.ts

feat(jest): 100% coverage for store/meta/mutations

---

components/views/chat/message/reply/Reply.less
components/views/chat/message/reply/Reply.vue
locales/en-US.js

display correct reply text
[AP-1310](https://satellite-im.atlassian.net/browse/AP-1310)

fix(replies): display correct reply text

---

store/ui/mutations.test.ts

feat(jest): 79% coverage for store/ui/mutations

---

libraries/Textile/MetadataManager.test.ts

A work in progress. Improvements soon to be made, right now we're hit by two errors:
- Textile's Query
- Textile's publickey (encrypt)
AP-1338

feat(jest): 22% coverage for MetadataManager

---

assets/styles/base.less

- minor style issue where file full page view wasn't getting proper icon color applied
AP-1407
- please ignore any other buggy aspects of file download, these are fixed in a separate PR

fix(files): missing accent color files

---

store/settings/actions.test.ts

- Increase coverage for store/settings/actions.test.ts
before
after

chore(jest): increase coverage on store/settings/actions.test.ts

---

store/ui/mutations.test.ts

- Removes skip on store/ui/mutations.test.ts

chore(jest): remove skip on test

---

components/views/chat/search/result/Result.html
nuxt.config.js
package.json
plugins/thirdparty/vuetify.ts

title
we were using v-datepicker, but its commented out at the moment. Seems like we can just use v-calendar though when we add it back.

chore(vuetify): shrink bundle, remove vuetify

---

components/views/chat/message/reply/Reply.less

fix replies width and message actions position when a long reply is sent
AP-1424

chore(chat): fixed actions position issue replies width

---

components/views/user/User.vue
locales/en-US.js

Updates translations from sidebar, now detects who sends the message
AP-1422

chore(translations): updated sidebar's translations

---

components/views/settings/pages/profile/index.vue
store/accounts/actions.ts
store/accounts/mutations.ts

in settings/profile, the user can update the profile photo.
AP-1392

feat(ui): user update profile picture

---

utilities/BlobToBase64.test.ts

feat(jest): 86% coverage for BlobToBase64.ts

---

store/ui/__snapshots__/getters.test.ts.snap
store/ui/getters.test.ts

feat(jest): 100% coverage for store/ui/getters

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/files/upload/Upload.html
components/views/files/upload/Upload.less
components/views/files/upload/Upload.vue
components/views/files/upload/filePreview/FilePreview.html
components/views/files/upload/filePreview/FilePreview.less
components/views/files/upload/filePreview/FilePreview.vue
store/chat/__snapshots__/state.test.ts.snap
store/chat/actions.ts
store/chat/getters.ts
store/chat/mutations.ts
store/chat/state.ts
store/chat/types.ts

Upload component refactor
AP-1188

chore(refactor): upload component refactor

---

store/chat/__snapshots__/getters.test.ts.snap
store/chat/__snapshots__/mutations.test.ts.snap
store/chat/getters.test.ts
store/chat/mutations.test.ts

- Adds Jest tests regarding https://github.com/Satellite-im/Core-PWA/pull/2717
depends on https://github.com/Satellite-im/Core-PWA/pull/2717 to be able to run these tests successfully

chore(jest): add jest tests - 2717

---

locales/en-US.js

- Minor improvements in locales

chore(locales): minor improvements

---

components/views/navigation/sidebar/Sidebar.less

theme color for unread badge
[AP-1443](https://satellite-im.atlassian.net/browse/AP-1443)

fix(sidebar): theme color for unread badge

---

components/views/files/view/View.html
components/views/files/view/View.less

change position of close button tooltip
[AP-1313](https://satellite-im.atlassian.net/browse/AP-1313)

fix(files): change position of close button tooltip

---

components/views/files/upload/previewItem/PreviewItem.less
components/views/files/view/View.less

change line height for image title
[AP-1312](https://satellite-im.atlassian.net/browse/AP-1312)

fix(files): change line height for image title

---

components/views/settings/pages/privacy/Privacy.html

- hide signaling server option until we're ready for it
AP-1458

fix(settings): remove signaling server setting

---

components/views/chat/search/input/Input.html
components/views/chat/search/result/Result.html
components/views/chat/search/result/item/Item.html
components/views/chat/search/result/meta/Meta.html
cypress/integration/chat-features.js
cypress/support/commands.js

- Add cypress tests for chat search bar
- Add data-cy attributes for elements used in new cypress tests added in this PR
- Add cypress commands used in new cypress tests added in this PR
- Small refactor on some of the cypress tests from same spec file (chat-features.js)
AP-1323
- Leaving this skip as unskipped since test friend program changes have not been merged yet
- Marking as draft for now until some of the questions that I shared to Sara today are solved, in case that changes are required
Cypress Video for Chat-Features.js:
https://user-images.githubusercontent.com/35935591/165370820-ae5df98f-62be-4825-b59b-c7c6389efabb.mp4
All Specs Passed:

test(cypress): add tests for chat search

---

libraries/Solana/Solana.test.ts
libraries/Solana/Solana.ts
libraries/Solana/__snapshots__/Solana.test.ts.snap

Fixed the issues pointed in the ticket, clean up code structure, and added more tests for 2 functions (and 1 incomplete for the waitForAccount function) while also removing useless code (`sleep(3000)`).
AP-1092

feat(jest): 87% coverage for libraries/Solana/Solana

---

components/views/chat/search/SearchUtil.test.ts
components/views/chat/search/SearchUtil.ts
components/views/chat/search/__snapshots__/SearchUtil.test.ts.snap

feat(jest): 100% coverage for components/views/chat/search/SearchUtil

---

components/ui/Scroll/Scroll.less
components/ui/Scroll/Scroll.vue
components/views/settings/modal/Modal.html
components/views/settings/modal/Modal.vue
components/views/settings/pages/profile/Profile.less
components/views/settings/pages/profile/index.vue
store/ui/__snapshots__/state.test.ts.snap
store/ui/state.ts
store/ui/types.ts

disable scroll while crop is opening
[AP-1444](https://satellite-im.atlassian.net/browse/AP-1444)

fix(settings): disable scroll while crop is opening

---

components/ui/Global/Global.html
components/views/chat/enhancers/glyphs/nav/Nav.vue
components/views/glyphs/Glyphs.vue
components/views/navigation/mobile/nav/Nav.vue
components/views/navigation/slimbar/Slimbar.html
components/views/navigation/toolbar/Toolbar.html
store/ui/types.ts

chore(naming): update naming

---

components/views/files/controls/Controls.html

fix(files): hide unused dropdown

---

components/views/files/file/File.vue
locales/en-US.js

- correct item count pluralization
- 0 items
- 1 item
- 2+ =  {count} items
AP-1486

fix(files): pluralization logic plus translations for dir item count

---

components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.vue
package.json

Cleans up emoji picker component
AP-1493

chore(emoji-picker): clean up component

---

store/chat/actions.test.ts

feat(jest): 100% coverage for store/chat/actions

---

components/interactables/ContextMenu/ContextMenu.less

Fixes shadow color while hovering on quick reactions menu
AP-1492

chore(quick-reactions): fixed shadow hover color

---

components/views/chat/group/Group.html
components/views/chat/group/Group.less
components/views/chat/group/Group.vue
libraries/Enums/types/messaging-types.ts
pages/chat/direct/_address.vue
store/settings/actions.test.ts
types/messaging.d.ts
utilities/Messaging.ts

change messages markdown
[AP-1454](https://satellite-im.atlassian.net/browse/AP-1454)

refactor(chat): change messages markdown

---

store/settings/actions.test.ts

chore(jest): remove duplicated test

---

store/friends/__snapshots__/mutations.test.ts.snap
store/friends/mutations.test.ts

feat(jest): 100% coverage for store/friends/mutations

---

components/ui/User/State/State.less

remove cut off of badge
[AP-1462](https://satellite-im.atlassian.net/browse/AP-1462)

fix(status): remove cut off of badge

---

components/views/friends/friend/Friend.vue

[AP-1482](https://satellite-im.atlassian.net/browse/AP-1482)
close context menu on route changed or friend removed

fix(friend): close context menu on route changed or friend removed

---

jest.config.js
libraries/Files/test/TextileFileSystem.test.ts
package.json

Increase coverage of said file, currently thinking back-and-forth if it is possible to increase the coverage. The current issue (the skipped tests) are the unit tests exceeding timeout:
AP-927

feat(jest): 36% coverage for libraries/Files/TextileFileSystem

---

store/friends/actions.test.ts
store/friends/actions.ts

Self-explanatory. A kickstart for coverage on this file, will be improved soon. Please let me know if there are improvements that can be made.
AP-572

feat(jest): 14% coverage for store/friends/actions

---

store/groups/actions.test.ts
store/groups/actions.ts

An attempt at covering Vuex actions, parts by parts. Will be improved soon.
No tickets atm

feat(jest): 18% coverage for store/groups/actions

---

store/sounds/__snapshots__/actions.test.ts.snap
store/sounds/actions.test.ts

feat(jest): 100% coverage branches for store/sounds/actions

---

components/views/chat/message/reply/Item/Item.html
components/views/chat/message/reply/Reply.vue

display correct quick profile
[AP-1506](https://satellite-im.atlassian.net/browse/AP-1506)

fix(reply): display correct quick profile

---

store/textile/actions.test.ts

Updated the tests according to the changes made on https://github.com/Satellite-im/Core-PWA/commit/04001efbcbca5e0a96338928ab2a50a24ff0744f
AP-1519

feat(jest): update tests according to code changes

---

components/ui/Unread/Unread.vue
components/views/user/User.vue
store/friends/actions.ts

remove friend from indexed db
[AP-1474](https://satellite-im.atlassian.net/browse/AP-1474)

fix(friends): remove friend from indexed db

---

libraries/Solana/Solana.test.ts

Yesterday, my manager notified me that some tests were timing out for more than 5 seconds. Today I took a look at it and it wasn't reproducible in my machine. This PR is intended to remove the skip tests and see if it will be reproduced in the CI we use in this repository.
No tickets atm

feat(jest): remove skip for timeout issue on Solana

---

store/textile/actions.test.ts

Increase a bit of coverage in an attempt to cover more of Textile and other uncovered actions files in the future.
AP-777

feat(jest): 9% coverage for store/textile/actions

---

cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/create-account.js
cypress/support/commands.js

- Updates on chat-pair-features and chat-text-validations.js cypress tests to solve issues presented on CI execution. These updates include reorganizing tests, adding timeouts and additional validations for non attached to DOM elements
- Updates on create-account.js cypress tests to add retries where needed due to timeout issues
- Increased the timeout on waiting that a message is sent in two cypress commands, since there were failures on tests due to slowness on sending messages
- Removed a command no longer need to retry on 503 errors, since we are using now cypress retries on these tests
None
Chat Text Validations Cypress Test: …

test(cypress): draft fixes for cypress on CI

---

jest.config.js
store/conversation/__snapshots__/actions.test.ts.snap
store/conversation/__snapshots__/mutations.test.ts.snap
store/conversation/__snapshots__/state.test.ts.snap
store/conversation/actions.test.ts
store/conversation/mutations.test.ts
store/conversation/state.test.ts

chore(jest): add jest tests

---

components/views/navigation/sidebar/controls/Controls.html
components/views/navigation/sidebar/controls/Controls.vue
package.json

add headphones-off-icon
[AP-1495](https://satellite-im.atlassian.net/browse/AP-1495)

feat(icons): add headphones-off-icon

---

config.ts
libraries/WebRTC/Call.ts

Adds a list of stun servers to the webrtc config

fix(webrtc): add configurable list of stun servers wrtc config

---

assets/styles/base.less
components/interactables/Switch/Switch.html
components/interactables/Switch/Switch.less
components/interactables/Switch/Switch.vue

- Adds a `<input type="checkbox">` element to the InteractablesSwitch component to improve a11y and keyboard accessibility
- css refactor, remove unused pieces of code
AP-1540

fix(input): improve a11y of interactablesswitch

---

components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/alerts/Alerts.html
components/views/navigation/toolbar/alerts/alert/Alert.html

chore(lint): lint

---

assets/styles/framework/typography.less
assets/styles/framework/ui.less
components/interactables/AsideMenu/AsideMenu.less
components/interactables/Select/Select.less
components/ui/CaretDivider/CaretDivider.less
components/ui/Chat/Image/Image.less
components/ui/Circle/Circle.html
components/ui/Circle/Circle.less
components/ui/DroppableWrapper/DroppableWrapper.less
components/ui/GlowingCursorArea/GlowingCursorArea.less
components/ui/User/User.less
components/views/chat/chatbar/Editable.vue
components/views/chat/chatbar/footer/Footer.less
components/views/chat/enhancers/Enhancers.less
components/views/files/aside/List/List.less
components/views/files/list/List.less
components/views/friends/friend/Friend.less
components/views/group/clickable/Clickable.less
components/views/message/Friend.less
components/views/navigation/toolbar/Toolbar.less
components/views/user/User.less
layouts/Layout.less

fix(user): prevent profile picture drag

---

components/views/chat/enhancers/glyphs/item/Item.vue

Fixes the target recipient when sending a glyphs so that it is always sent to the active chat
AP-1563, AP-1550, AP-1544

fix(glyph): send glyph to active chat

---

components/views/navigation/toolbar/Toolbar.vue
components/views/navigation/toolbar/alerts/Alerts.html
components/views/navigation/toolbar/alerts/Alerts.less
store/textile/mutations.ts

Removes glow from clear-all button
AP-1499
Fixed some additional typing issues I saw along the way too.

fix(notification): remove glow from clear all button

---

components/views/chat/message/Message.vue

Bug fix for edit messages
AP-1558

fix(edit): edit was not getting friends textile key anymore

---

components/views/media/incomingCall/IncomingCall.html
components/views/navigation/toolbar/Toolbar.html
libraries/WebRTC/Call.ts
libraries/WebRTC/WebRTC.ts
store/textile/mutations.ts
store/webrtc/actions.ts

Reverts Satellite-im/Core-PWA#3196

Revert "feat(calls): properly unbind all listeners after call closure"

---

components/views/media/incomingCall/IncomingCall.html
components/views/navigation/toolbar/Toolbar.html
libraries/WebRTC/Call.ts
libraries/WebRTC/WebRTC.ts
store/textile/mutations.ts
store/webrtc/actions.ts

Reverts Satellite-im/Core-PWA#3203

feat(calls): properly unbind all listeners after call closure

---

components/views/files/file/File.vue
components/views/files/list/row/Row.vue
components/views/files/view/View.html

- remove share options in files
AP-1584

fix(share): remove share for alpha prep

---

assets/styles/base.less
components/views/user/User.html
components/views/user/User.less
components/views/user/User.vue

Added markdown preview in sidebar (last message).
AP-1478

feat(markdown): added markdown preview in sidebar

---

components/views/user/User.vue
layouts/chat.vue

focus on chatbar on send message click
[AP-1535](https://satellite-im.atlassian.net/browse/AP-1535)

fix(chat): focus on chatbar on send message click

---

components/views/navigation/sidebar/status/Status.html
components/views/navigation/sidebar/status/Status.vue
nuxt.config.js
package.json
plugins/thirdparty/clipboard.ts

- remove final v clipboard dependency and package
AP-1569
- lets look around for other unused dependencies

fix(bundle): remove v clipboard

---

assets/styles/base.less

Disables all font ligatures across the app.
AP-1598

fix(style): disable font ligatures

---

components/interactables/InputGroup/InputGroup.vue
components/views/friends/add/Add.html
components/views/friends/add/Add.vue

- Adds an `autofocus` prop to the InputGroup component
- Autofocuses the add friend input field
AP-1572

feat(friends): autofocus add friend input

---

store/chat/__snapshots__/mutations.test.ts.snap
store/chat/mutations.test.ts

feat(jest): 100% branch coverage for store/chat/mutations

---

store/conversation/mutations.test.ts

Self-explanatory. Improves the unit test Sara generated previously.
No tickets at the moment (upcoming)

feat(jest): 37% coverage for store/conversation/mutations

---

cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/create-account.js
cypress/integration/files-features.js
cypress/integration/pin-unlock-validations.js

- Skip cypress tests failing on CI due to solana slowness issues
None
- Sending as draft in case that there are other tests that require to be skipped

test(cypress): skips tests due to solana issues

---

assets/styles/base.less
assets/styles/framework/colors.less

Fixes name-tag color when a call is on
AP-1603

fix(nametag): fixed tag color
