components/views/settings/modal/Modal.less
components/views/settings/modal/Modal.vue

Updates the settings min/max width/height constraints to match the figma design.
AP-1591

fix(settings): limit modal width/height

---

cypress/integration/chat-images-validations.js
cypress/integration/chat-pair-features.js
cypress/integration/chat-top-toolbar.js
cypress/integration/privacy-page-toggles.js

- Skip other cypress tests that failed on CI run from my previous PR due to textile issues
None
- Sending as draft in case other cypress tests required to be skipped

test(cypress): skip tests failing due to textile

---

libraries/Solana/FriendsProgram/FriendsProgram.ts
libraries/Solana/FriendsProgram/FriendsProgram.types.ts

Fixes all types for the word UNINITIALIZED
No ticket

chore(typo): fix typo - UNINITIALIZED

---

components/ui/Unread/Unread.vue
components/views/group/clickable/Clickable.html
components/views/group/clickable/Clickable.less
components/views/group/clickable/Clickable.vue
components/views/navigation/sidebar/Sidebar.html
components/views/user/User.vue

Fixes user state display, when conversation changes
AP-1553
Added selected flair background to the selected group

chore(userstatus): fixed user state display while changing chat

---

pages/friends/list/index.vue
pages/friends/mobile/add/index.vue
pages/friends/mobile/block/index.vue
store/friends/getters.ts

Move repeated code into friends store getters
AP-1449

refactor(friends): move sort methods into getters

---

libraries/Textile/BucketManager.test.ts
libraries/Textile/GroupChatManager.test.ts
libraries/Textile/NotificationManager.test.ts
libraries/Textile/encoders.test.ts
libraries/ui/Markdown.test.ts
store/chat/actions.test.ts
store/groups/actions.test.ts
store/settings/actions.test.ts
store/settings/state.test.ts
store/textile/actions.test.ts
store/textile/getters.test.ts
store/ui/actions.test.ts
store/ui/getters.test.ts
store/ui/mutations.test.ts
utilities/ConsoleWarning.test.ts
utilities/EnvInfo.test.ts
utilities/HotkeyList.test.ts
utilities/Hounddog.test.ts
utilities/Messaging.test.ts

chore(jest): organize jest imports

chore(jest): organize jest imports

---

store/conversation/__snapshots__/getters.test.ts.snap
store/conversation/getters.test.ts

feat(jest): 100% coverage for store/conversation/getters

---

cypress/integration/mobiles-responsiveness.js

- Skipping one cypress test that I missed to mark as skipped in my previous PR for mobiles-responsiveness.js
None

test(cypress): skip one test on mobiles

---

libraries/SatelliteDB/SatelliteDB.ts
libraries/Solana/Solana.ts
libraries/Solana/SolanaManager/SolanaManager.ts
libraries/WebRTC/encoders.ts
store/chat/getters.ts
store/ui/types.ts
store/webrtc/types.ts
utilities/Hounddog.ts
utilities/Messaging.ts

chore(imports): remove not used imports

chore(imports): remove not used imports

---

components/views/settings/pages/audio/sounds/Sounds.html
components/views/settings/pages/audio/sounds/Sounds.vue

- Removes the undeafen sound toggle in the audio & video settings.
- Adds a `toggleSounds` method which accepts an array of `Sounds` to set the value
- Combines the deafen/undeafen sounds into one toggle control
AP-1537

feat(sounds): combine deafen/undeafen into one toggle control

---

components/ui/Unread/Unread.vue
components/views/navigation/sidebar/Sidebar.html
components/views/user/User.vue

user navigate to chat
[AP-1601](https://satellite-im.atlassian.net/browse/AP-1601)

fix(chat): user navigate to chat

---

store/conversation/mutations.test.ts

feat(jest): 100% coverage for store/conversation/mutations

---

components/views/settings/pages/user/Search.vue

Fixes the new chat search input. Now you can add two separate users who have identical usernames to a group chat.
AP-1628

fix(search): filter selected by user address

---

store/accounts/actions.ts

fixes the changes I made to the account startup (await)

fix(startup): do not await promises in accounts/startup

---

pages/auth/unlock/Unlock.less

fix(login): more spacing for delete account link

---

pages/auth/unlock/Unlock.less

fix(spacing): reduce link spacing for signin delete account link

---

store/friends/__snapshots__/mutations.test.ts.snap
store/friends/mutations.test.ts

**What this PR does** 
Increases branch coverage, self-explanatory.
AP-1616

feat(jest): 100% branch coverage for store/friends/mutations

---

assets/styles/framework/blurs.less

Fix the modal background blur
AP-1641

fix(modal): modal background blur

---

components/views/media/user/User.html
components/views/media/user/User.less

- Fixes missing class on video stream container
- Removed box-shadow glow which wasn't in the figma design
- Adds `object-fit: cover` to `video` element so black bars aren't visible
AP-1629

fix(media): user video class/styling

---

package.json

Fixes a breaking change in @solana/web3.js

fix(solana): fix breaking change in @solana/web3.js

---

components/typography/NumberedWord/NumberedWord.less
components/views/settings/pages/accounts/Accounts.html
components/views/settings/pages/accounts/Accounts.less
components/views/settings/pages/accounts/index.vue
locales/en-US.js

- add copy phrase button
- general refactoring, improving styles
AP-1642

feat(account): add copy phrase button to settings page

---

components/views/user/User.html
components/views/user/User.vue
types/ui/user.d.ts

- change context menu options for sidebar friends to only include call options if they are online
- both call options are using dummy methods at the moment. call functionality will be added later
- general refactor, move methods to components when possible. improve typing. fix reference to nonexistent variable
AP-1640

fix(user): general refactor, show call options if user is online

---

store/textile/actions.test.ts

Fixed warnings that occurred due to recent changes.
AP-1656

feat(jest): fixed warnings, 8% coverage for store/textile/actions

---

store/friends/getters.test.ts

feat(jest): 100% coverage for store/friends/getters

---

store/accounts/mutations.test.ts

chore(jest): remove dup keys on jest test

---

cypress/fixtures/test-data-accounts.json
cypress/integration-pair-chat/chat-first-user.js
cypress/integration-pair-chat/chat-second-user.js
cypress/integration/chat-features.js
cypress/integration/chat-glyphs-validations.js
cypress/integration/chat-images-validations.js
cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/chat-top-toolbar.js
cypress/integration/create-account.js
cypress/integration/import-account-negative-tests.js
cypress/integration/localstorage-validations.js
cypress/integration/mobiles-responsiveness.js
cypress/integration/pin-unlock-validations.js
cypress/integration/privacy-page-toggles.js
cypress/support/commands.js

- Updates Cypress account due to Joe's Textile related PR
- Unskip tests
- Adds prettier-ignore in a specific line to avoid reverting the test 
- Organize imports 
- Removes not needed stuff
- Minor updates

test(cypress): update cypress

---

jest-setup.js

Fix minor eslint warning on `jest-setup.js`

chore(jest): minor update file

---

components/views/settings/pages/accounts/Accounts.html

- there was a new warning in terminal from something i changed the other day, this fixes it

fix(accounts): resolve for loop key warning

---

components/views/navigation/toolbar/Toolbar.html
locales/en-US.js

add tooltip to alerts
[AP-1645](https://satellite-im.atlassian.net/browse/AP-1645)

fix(toolbar): add tooltip to alerts

---

cypress/integration/chat-images-validations.js
cypress/integration/chat-pair-features.js
cypress/integration/chat-text-validations.js
cypress/integration/chat-top-toolbar.js
cypress/integration/localstorage-validations.js

chore(cypress): add comment hash 

---

components/interactables/Switch/Switch.html
components/interactables/Switch/Switch.less

- fix locked & enabled state for switch. it wasn't picking up a css rule
AP-1655

fix(switch): add white circle for locked, enabled switch

---

.github/workflows/add-conflicts-label.yml

chore(add): add name on github action

chore(add): add name on github action

---

.github/workflows/fix-typos.yml

Adds a Github Action that automatically adds a PR when it sees any typos.

chore(githubAction): fix typos

---

components/views/files/view/View.less

Fix overlap of iOS status bar on file overlay that prevented the user from clicking the close button (PWA bug only)
AP-1456

fix(ios): fix overlap of iOS status bar on file overlay

---

store/ui/actions.test.ts

feat(jest): 87% coverage for store/ui/actions

---

assets/styles/framework/ui.less
components/views/chat/chatbar/Chatbar.less
components/views/chat/chatbar/controls/Controls.html
components/views/chat/chatbar/controls/Controls.less
components/views/chat/enhancers/Enhancers.less
layouts/Layout.less

change enhancers position
[AP-1588](https://satellite-im.atlassian.net/browse/AP-1588)

fix(chat): change enhancers position

---

components/views/chat/chatbar/Chatbar.less

change enhancers z index
[AP-1587](https://satellite-im.atlassian.net/browse/AP-1587)

fix(chat): change enhancers z index

---

components/views/files/upload/Upload.vue

I was going to rip out the last reference to the deleted hounddog helper, but saw activeFriend was wasn't actually used
n/a
Should notice no difference in functionality

chore(upload): remove unused computed

---

.github/workflows/cypress-docker-pair-testing.yml

- Adds Github Action using Docker to run parallel tests.

chore(cypress): docker cypress pair testing

---

.github/workflows/cypress-docker-pair-testing.yml
.github/workflows/fix-typos.yml

chore(lint): lint actions

---

cypress/integration/localstorage-validations.js

Adds test to logout user on unlock page
https://user-images.githubusercontent.com/29093946/171298351-c0704e3e-0e6d-4a20-86a4-802dd76d6d7e.mov

test(cypress): add logout test

---

components/views/media/actions/Actions.vue
components/views/navigation/sidebar/controls/Controls.vue
libraries/WebRTC/Call.ts
libraries/WebRTC/errors/Errors.ts
store/webrtc/actions.ts

Adds a notification if the browser doesn't have permission to screen share
AP-1545

feat(call): add permission error alert for screen sharing

---

components/views/media/user/User.html
components/views/media/user/User.vue

show user avatar while calling
[AP-1489](https://satellite-im.atlassian.net/browse/AP-1489)

fix(call): show user avatar while calling

---

components/views/chat/group/Group.html
components/views/chat/group/Group.vue

fix(groups): add correct color for avatar in group chats

---

components/ui/Circle/Circle.html
components/views/group/clickable/Clickable.vue
components/views/group/icon/GroupIcon.html
components/views/group/icon/GroupIcon.less
components/views/group/icon/GroupIcon.vue

- refactor css to be less repetitive, take advantage of .less
- add color avatars if no picture is found
AP-1701
- Could probably be simplified later

fix(groups): display color avatar in sidebar if no picture found

---

components/ui/Unread/Unread.vue
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/slimbar/Slimbar.html
components/views/navigation/slimbar/Slimbar.vue
layouts/chat.vue
layouts/files.vue
layouts/friends.vue
layouts/server.vue
store/friends/getters.ts

- rather than passing store values as a prop, just pull store value directly in Slimbar component
- new friends getter to get friends w/ unread messages
AP-1699
- the logic to set the unreadCount doesn't work. Maybe that should be fixed separately
- this will not work as intended, just logic setup

fix(slimbar): logic to show only friends with unread messages

---

components/views/chat/group/Group.html
components/views/chat/group/Group.vue

- i broke 1on1 dm avatar color yesterday when i fixed it for groups. this fixes it for both
AP-1719

fix(chat): fix avatar colors for dm

---

assets/styles/base.less
components/ui/Progress/Progress.html
components/ui/Progress/Progress.less
components/views/files/upload/previewItem/PreviewItem.html
components/views/files/upload/previewItem/PreviewItem.less
components/views/files/upload/previewItem/PreviewItem.vue

- fix progress bar color
- remove .progress class to reduce our dependency on bulma (i'd like to rip that out at some point. css is fun to write)
AP-1644
- i wanted to take advantage of .less nesting, but i couldn't get some of the browser prefixes to work while nested

fix(progress): change progress bar color to your selected flair

---

cypress/integration/settings-features.js

- Add Cypress test to assert content on settings
- Add Cypress test to test clear local storage on settings
https://user-images.githubusercontent.com/29093946/171912244-e8a4d862-4450-4c33-9fd2-3ccd40f1346f.mp4

test(cypress): add settings tests

---

store/ui/actions.test.ts

Increase coverage for branches that weren't covered previously.
AP-778

feat(jest): 95% branch coverage for store/ui/actions

---

config.ts
libraries/Solana/SolanaManager/SolanaManager.ts

chore(faucet): testing different dev faucet

---

components/views/group/icon/GroupIcon.less

- Fixes count label appearance when showing numbers > 9:
- Fix count label border radius so it's a pill shape instead of an egg shape.
AP-1711

fix(sidebar): count label style

---

components/views/chat/message/edit/Edit.vue
package.json

chore(bundle): remove feather icons

---

components/views/friends/quick/Quick.html
components/views/settings/pages/user/Search.html
components/views/settings/pages/user/Search.less

- Show the autocomplete below the input field
- Fix the icon positioning
AP-1681

fix(quick): show dropdown below input

---

store/settings/actions.test.ts

feat(jest): 100% branch coverage for store/settings/actions

---

store/groups/__snapshots__/mutations.test.ts.snap
store/groups/mutations.test.ts

Increase coverage for uncovered lines, and covered branch that wasn't covered previously.
No ticket

feat(jest): 100% coverage and branch coverage for store/groups/mutations

---

locales/en-US.js

Changes Some friends . . . to Search friends . . . 
no ticket 

chore(locals): grammer fix 

---

components/interactables/QuickProfile/QuickProfile.html
components/interactables/QuickProfile/QuickProfile.less
components/interactables/QuickProfile/QuickProfile.vue
components/ui/Unread/Unread.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.less
components/views/user/User.vue

Hide profile modal 
[AP-1717](https://satellite-im.atlassian.net/browse/AP-1717)

fix(profile): disable show user profile

---

store/audio/actions.test.ts

feat(jest): 78% coverage for store/audio/actions

---

components/ui/ComingSoon/ComingSoon.html
components/ui/ComingSoon/ComingSoon.vue
components/views/chat/message/actions/Actions.html
components/views/chat/message/actions/Actions.less
components/views/chat/message/actions/Actions.vue
components/views/navigation/toolbar/Toolbar.html
locales/en-US.js

- Add click event handler to coming soon component so all *coming soon* features open the coming soon modal.
AP-1660

fix(comingsoon): show modal on click

---

components/views/media/user/User.html

hide grey border around avatar
[AP-1707](https://satellite-im.atlassian.net/browse/AP-1707)

fix(call): hide grey border around avatar

---

cypress/integration/chat-pair-features.js

chore(cypress): skip tests

---

components/views/navigation/toolbar/Toolbar.html

- Adds the missing src prop for the user avatar in the toolbar
AP-1752
AP-1746

fix(toolbar): add missing user avatar src prop

---

components/views/media/Media.vue
components/views/user/User.vue
store/conversation/actions.ts
store/conversation/mutations.ts

add posibility to call user via context menu
[AP-1097](https://satellite-im.atlassian.net/browse/AP-1097)

fix(call): add possibility to call user via context menu

---

components/views/media/incomingCall/IncomingCall.html
components/views/media/incomingCall/IncomingCall.less

overflow long user name in incoming call
[AP-1197](https://satellite-im.atlassian.net/browse/AP-1197)

fix(call): overflow for long user name in incoming call

---

libraries/Textile/TextileManager.ts

- switch bucket init to await, rather than doing them in parallel. fixes bug
AP-1760

fix(buckets): initialize buckets separately

---

components/interactables/Checkbox/Checkbox.html
components/interactables/Checkbox/Checkbox.less
components/interactables/UserPicker/ListItem/ListItem.html
components/interactables/UserPicker/ListItem/ListItem.less
components/views/navigation/toolbar/Toolbar.html
libraries/Files/remote/textile/PersonalBucket.ts

- Adding comment on libraries/Files/remote/textile/PersonalBucket.ts
- Minor lint

chore(comment): add comment + minor lint

---

cypress/support/commands.js

chore(cypress): fix cypress test

chore(cypress): fix cypress test

---

components/views/user/User.html
components/views/user/User.vue
locales/en-US.js

- remove leftover interval code
- switch some code to shorthand
- remove unused case since all image messages are encoded as 'file'. I removed all of the other associated code a week or two ago, missed this one bit

chore(cleanup): remove unused markup

---

components/views/media/actions/Actions.vue
components/views/navigation/sidebar/controls/Controls.vue
libraries/WebRTC/Call.ts
store/audio/__snapshots__/mutations.test.ts.snap
store/audio/actions.test.ts
store/audio/actions.ts
store/audio/mutations.test.ts
store/audio/mutations.ts
store/audio/types.ts
store/video/actions.test.ts
store/video/actions.ts
store/video/mutations.test.ts
store/webrtc/actions.ts

- Fix toggle video bugs.
- improve unit test for video actions and mutations, unit test whether `toggleCamera` indeed toggles the `disabled` state of the video.
AP-1620

fix(video): fix toggle video bugs, improve video unit tests

---

libraries/WebRTC/Emitter.test.ts
libraries/WebRTC/Libp2p.test.ts
libraries/WebRTC/__snapshots__/Emitter.test.ts.snap
libraries/WebRTC/__snapshots__/Libp2p.test.ts.snap

- Added `libraries/WebRTC/Emitter.test.ts`
- Added `libraries/WebRTC/Libp2p.test.ts`

chore(jest): add more jest tests

---

locales/en-US.js

chore(locales): update copy

---

store/video/actions.test.ts

chore(jest): remove not used import on test

chore(jest): remove not used import on test

---

components/interactables/Chip/Chip.vue
components/interactables/UserPicker/UserPicker.html
components/interactables/UserPicker/UserPicker.less
components/interactables/UserPicker/UserPicker.vue
locales/en-US.js

- Add empty results label to user picker
- Adds list of selected chips to user picker
- Extends chip component
- Size prop
- Friend prop to show friend picture in circle
AP-1759

feat(userpicker): add chip list

---

components/views/chat/search/SearchQuery.test.ts
components/views/chat/search/__snapshots__/SearchQuery.test.ts.snap
libraries/BlockchainClient/adapters/SolanaAdapter/__snapshots__/utils.test.ts.snap
libraries/BlockchainClient/adapters/SolanaAdapter/utils.test.ts

- Removes not needed stuff on `components/views/chat/search/SearchQuery.test.ts`
- Adds more coverage on `components/views/chat/search/SearchQuery.test.ts`
- Adds `libraries/BlockchainClient/adapters/SolanaAdapter/utils.test.ts`

chore(jest): update jest tests

---

components/views/media/incomingCall/IncomingCall.html
components/views/media/incomingCall/IncomingCall.less

show avatar placeholder on incoming call
[AP-1754](https://satellite-im.atlassian.net/browse/AP-1754)

fix(call): show avatar placeholder on incoming call

---

cypress/integration/chat-features.js

chore(cypress): skip test

---

store/groups/actions.ts

- adds message to chat when adding a new user
AP-1778
looks like this
- I plan on adding name afterwards. waiting for one of Jason's PR's first to make it easier 
- I also want to make it more of an 'admin' message rather than a regular one

feat(chat): add message when a user adds somebody to chat

---

components/ui/Global/Global.vue

destroy call on decline incoming call
[AP-1764](https://satellite-im.atlassian.net/browse/AP-1764)

fix(call): destroy call on decline incoming call

---

store/chat/mutations.test.ts

feat(jest): 100% coverage for store/chat/mutations

---

components/ui/Chat/Image/Image.vue
components/views/chat/enhancers/glyphs/item/Item.html

fix(glyphs): prevent glyph drag

---

store/webrtc/actions.ts

add exit call sound
[AP-1789](https://satellite-im.atlassian.net/browse/AP-1789)

fix(call): add exit call sound

---

store/webrtc/actions.ts

add end call sound on caller side
[AP-1791](https://satellite-im.atlassian.net/browse/AP-1791)

fix(call): add end call sound on caller side

---

assets/styles/base.less
assets/styles/framework/colors.less
assets/styles/framework/glows.less
store/friends/actions.ts
store/friends/types.ts

Prevent double friend requests to be shown (we keep the first one)
AP-1708
Although the user shouldn't be able to make multiple requests to another user, sometimes it seem to happen (i wasn't able to replicate it tho) and this PR aims to remove all multiple requests, keeping just the first made.
Also added the style for the "success" button, because was missing (the green button that appears to confirm the friend request).

fix(double-requests): removed double friends requests

---

components/views/chat/message/reply/Item/Item.html

Hides the reply button while hovering a reply
AP-1691

chore(reply): removed reply button from replies

---

components/interactables/UserPicker/ListItem/ListItem.html
components/interactables/UserPicker/ListItem/ListItem.less

- Fixes styling of long usernames in the user picker
- Adds title attr to username overflow
AP-1794

fix(userpicker): friend name overflow

---

components/views/user/User.vue

Fixes chatbar auto focus (on mobile) when entering a chat
AP-1801

fix(focus-chat): fixed auto focus when entering chat

---

components/interactables/Select/Select.html
components/interactables/Select/Select.less

- theme select was unreadable due to new scroll component. fixes style issue
AP-1815
- 🔴 timezone scroll was broken by someone else. check dev
- I will replace all the select components with something accessible at a later date

fix(select): broken select rendering

---

components/views/chat/search/SearchQuery.test.ts

chore(jest): fix lint errors on SearchQuery

---

package.json

chore(cypress): add commands locally to run tests

chore(cypress): add commands locally to run tests 

---

components/views/navigation/mobile/nav/Nav.html
components/views/navigation/mobile/nav/Nav.vue

- Hides the mobile nav bar in the chat when navigating to home
AP-1814

fix(mobile): bottom nav bar state

---

components/views/media/incomingCall/IncomingCall.vue
store/webrtc/actions.ts

- add sound for incoming and outgoing calls
- add sound for denying and hanging up calls 
- small refactor of incoming call component
[AP-1800](https://satellite-im.atlassian.net/browse/AP-1800)

fix(call): add sounds for call

---

locales/en-US.js

chore(update): update locale

---

components/views/friends/quick/Quick.less

- Fixes long error messages breaking the UI
AP-1833

fix(quick): break word

---

store/chat/actions.test.ts

feat(jest): 46% coverage for store/chat/actions

---

cypress/integration/create-account.js

chore(cypress): update

---

assets/styles/base.less
components/views/navigation/sidebar/Sidebar.less

- incoming friend request color got broken again. this fixes it and moves styles to the scoped file in an effort to keep things readable

fix(sidebar): proper color on sidebar tag

---

components/views/group/clickable/Clickable.html

Makes groups clickable again
n/a, quick fix for recent pr that remove it on accident

chore(groups): add back click action

---

cypress/integration/add-friend.js

chore(cypress): add friend test
https://user-images.githubusercontent.com/29093946/174354461-840651ca-b971-4bf1-a805-8cff7d8650d6.mov

chore(cypress): add friend test

---

store/friends/actions.ts

fix(double-requests): filtered incoming requests

---

components/views/user/User.less
store/friends/actions.ts
store/webrtc/actions.ts

fix(state): add on:discover event

---

libraries/Solana/GroupChatsProgram/GroupChatsProgram.ts
libraries/Solana/Solana.ts

Fix group creation issue
AP-1689

fix(groupChats): add retry to invite search in group creation

---

components/interactables/Chip/Chip.vue
components/interactables/UserPicker/UserPicker.html
components/interactables/UserPicker/UserPicker.less

- Fixes user picker height overflow
- Fixes chip text overflow
AP-1804
AP-1825

fix(userpicker): style & overflow issues

---

components/interactables/UserPicker/UserPicker.vue
components/views/group/invite/Invite.html
components/views/group/invite/Invite.less
components/views/group/invite/Invite.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.vue

- Use the new user picker component in the group invite UI
- Add exclude prop to userpicker so we can hide members from the group invite UI
AP-1777

feat(groupinvite): use userpicker component

---

store/textile/mutations.test.ts

feat(jest): 97% coverage for store/textile/mutations

---

assets/styles/themes/moonless_night.less

moonless night theme - looks like this before fix
AP-1872

fix(mobile): mobile nav style

---

libraries/Textile/UserManager.test.ts

- Adds `libraries/Textile/UserManager.test.ts`

chore(jest): add test

---

libraries/Files/test/Bucket.test.ts

feat(jest): 19% coverage for SharedBucket

---

plugins/thirdparty/persist.ts

fix(conversation): offline status

---

components/views/chat/group/Group.vue
locales/en-US.js

Fixes the displayname loading behavior in group chats

fix(groupchat): fix for username of unknown users during initial load

---

components/views/chat/chatbar/controls/Controls.html

- Fixed disabled prop on button
AP-1853

fix(sendmoney): disabled button prop

---

components/ui/User/State/State.less
components/ui/User/State/State.vue
components/views/friends/friend/Friend.html
components/views/friends/friend/Friend.vue

Hide online status of an user if not a friend
[AP-1820](https://satellite-im.atlassian.net/browse/AP-1820)

fix(friends): online status is hidden if not friend

---

store/webrtc/actions.ts

- Fixes the `onCallTrack` logic which fixes some bugs in track creation/muting/unmuting for video/screen share.
AP-1879
AP-1869

fix(webrtc): on call track logic

---

components/views/settings/pages/audio/Audio.html
components/views/settings/pages/audio/index.vue
store/audio/types.ts

- add required props to new Select instances
- switch type definitions to primitives
- remove unnecessary type definitions
AP-1875
- ticket showed some visual bugs with long device names. I think that should be handled in a separate ticket. We ultimately want to remove bulma, so I would probably create some custom layout css which would respond better

fix(select): cleanup select console errors

---

components/views/chat/chatbar/Chatbar.less
layouts/Layout.less

change chatbar z-index depend on fullscreen media
[AP-1587](https://satellite-im.atlassian.net/browse/AP-1587)

fix(chatbar): change chatbar z-index depend on fullscreen media

---

.vscode/settings.json

prefer imports from root w/ intelliense. this makes it easier to copy/paste if you want to add the import to another file. plus it complains less about import order if it's consistent.
will enforce a format like this

chore(vscode): default imports  - non relative

---

.github/config/changelog_config.json

Addes test and refactor to the changelog builder
n/a

chore(changelog): update changelog

---

store/webrtc/actions.ts

- add logs to monitor webrtc activities and any intermittent bugs
AP-1860

feat(logs): add logs to help monitoring webrtc activities

---

cypress/integration/create-account.js

chore(cypress): minor update

---

assets/styles/base.less

title
I accidentally broke it yesterday here, thought that line was insignificant
https://github.com/Satellite-im/Core-PWA/pull/3757/files

fix(quickchat): z index fix for quickchat modal

---

utilities/Messaging.test.ts
utilities/Messaging.ts
utilities/__snapshots__/Messaging.test.ts.snap

feat(jest): 92% coverage for utilities/Messaging

---

utilities/Messaging.ts

chore(jest): remove useless console log

---

libraries/Files/test/Fil.test.ts

feat(jest): 84% coverage for Item.abstract.ts

---

libraries/Files/test/Fil.test.ts

feat(jest): 96% coverage for Item.abstract.ts

---

components/interactables/UserPicker/UserPicker.html
components/interactables/UserPicker/UserPicker.less
components/interactables/UserPicker/UserPicker.vue
components/ui/SatelliteCircle/SatelliteCircle.less
components/views/friends/quick/Quick.html
components/views/friends/quick/Quick.less
components/views/group/invite/Invite.less
pages/message/NewMessage.html
pages/message/NewMessage.less
pages/message/index.vue

- Update the mobile new message UI to use the user picker component
- Fixes the creating a group on mobile
AP-1761
AP-1757
AP-1868

feat(newmessage): use userpicker

---

components/views/chat/message/reply/Reply.less

- wrap text if reply is very long
- minor css refactor to improve readability
AP-1890

fix(chat): break word on chat replies

---

assets/styles/base.less
components/views/navigation/slimbar/Slimbar.html
components/views/navigation/slimbar/Slimbar.less
components/views/navigation/slimbar/Slimbar.vue

- simplify markup and styles to use flex, remove weird overflows
- slightly change design to be closer to figma
- remove unused horizontal styles. we should add new styles when we actually need it
- remove duplicate unread markup, maybe rebase mistake
AP-1902
- will look slightly different. It was previously off-center with smaller settings icons

refactor(slimbar): improve styles and markup

---

components/views/media/user/User.html
components/views/media/user/User.less

- Refactor MediaUser styles
- Fix indicator style on light backgrounds (ie. show a white page on screen share while muted)
AP-1888

refactor(mediauser): styling and fix indicator color

---

components/ui/Global/Global.html
components/ui/Global/Global.vue
components/views/files/view/View.html
components/views/files/view/View.less
components/views/files/view/View.vue

- keyboard nav for files preview. It's difficult to see while we still disable outline on focus, but the tooltips should help a bit
AP-1909
This is ONLY the fullscreen file preview for filesystem. not chat preview, and not regular files page

fix(files): keyboard accessible, hit esc to close

---

components/ui/Chat/Scroll/Scroll.html
components/ui/Chat/Scroll/Scroll.vue
components/ui/Unread/Unread.vue
components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/Editable.vue
components/views/chat/message/Message.vue

Fixes the issue that occurs when a mobile user presses on the chatbar (it loses focus when trying to type a message and closes the keyboard)
AP-1910

fix(chatbar-mobile): fixed chatbar focus when pressed

---

.github/workflows/iridium-label.yml

chore(githubAction): add iridium label automatically

chore(githubAction): add iridium label automatically

---

.github/workflows/iridium-label.yml

chore(fix): fix github action

---

components/ui/Chat/Embeds/File/File.html
components/ui/Chat/Embeds/File/File.less
components/ui/Chat/Embeds/File/File.vue
components/views/chat/group/Group.less

cherry pick changes from [this pr](https://github.com/Satellite-im/Core-PWA/pull/3825) and add them to what will become the new iridium dev branch

fix(files): fix files embed overflow issue

---

components/views/chat/search/result/item/Item.vue
components/views/user/User.vue
locales/en-US.js
store/settings/getters.ts

- recreate this PR for new iridium branch https://github.com/Satellite-im/Core-PWA/pull/3874
- comment logic for now because user doesn't have the specific timestamp we are looking for

fix(sidebar): add relative timestamps to sidebar

---

libraries/Iridium/__snapshots__/encoders.test.ts.snap
store/settings/actions.test.ts
store/settings/actions.ts

Fixes the "Clear local storage" on settings.
`Promise.all` wasnt working for some reasons.
Test commented atm.

chore(dexie): clear all dbs from settings

---

components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/Profile.less
components/views/settings/pages/profile/index.vue
components/views/settings/profile/Picture.vue
components/views/settings/profile/card/Card.html
components/views/settings/profile/card/Card.less
locales/en-US.js
mock/profile.ts
types/profile/profile.ts

- Changes the style of the settings profile section to match the Figma design
AP-1951

feat(profile): change style to match figma

---

store/settings/actions.test.ts

I merged [this](https://github.com/Satellite-im/Core-PWA/pull/3940), but it was causing pre commit hook to fail because there were 0 tests in the file. added skip instead so it works again

fix(test): skip rather than comment out so the precommit hook works

---

.github/workflows/cypress.yml

chore(cypress): fix github action

chore(cypress): fix github action

---

pages/auth/unlock/Unlock.html
pages/auth/unlock/index.vue

When registering there is a small amount of time in which the login page (not the signup) is shown, causing a bad UX. This should fix that.

fix(signup): fix glitch

---

jest.config.js
store/textile/actions.test.ts
store/ui/__snapshots__/mutations.test.ts.snap
store/ui/getters.test.ts
store/ui/mutations.test.ts
store/ui/state.test.ts
store/ui/types.test.ts

- Updates `jest.config.js` to remove js, jsx files from coverage because they are not needed
- Renames tests to the original name
- Skips tests

chore(jest): jest updates

---

components/views/user/User.vue
libraries/Iridium/chat/ChatManager.ts
package.json
pages/chat/direct/_address.vue

feat(chat): chat improvement, bug fixes

---

components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/Profile.less
components/views/settings/pages/profile/index.vue
locales/en-US.js

- Allow user to remove profile picture in profile settings
- Correct an object undefined error
- Fix "add profile photo plus-button" from hovering above modals
AP-1840

feat(profile): remove photo when user already uploaded

---

components/interactables/ImageCropper/ImageCropper.html
components/interactables/ImageCropper/ImageCropper.less
components/interactables/ImageCropper/ImageCropper.vue
components/interactables/ImageInput/ImageInput.vue
components/views/chat/message/Message.vue
components/views/servers/create/Create.html
components/views/servers/create/Create.vue
components/views/settings/modal/Modal.vue
components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/Profile.less
components/views/settings/pages/profile/index.vue
components/views/user/create/Create.html
components/views/user/create/Create.less
components/views/user/create/Create.vue
config.ts
store/ui/types.ts
utilities/NSFW.ts

- reduce anti pattern of passing functions as props
- adjust config (config.ts) to use blob rather than base64
- reduce height & width in config.ts
AP-1956

refactor(imageCropper): reduce anti pattern of passing functions as props

---

components/views/files/aside/Aside.vue
pages/files/browse/Browse.html

Update "total size" and "percentage used" that's displayed in the files aside component when iridium file state changes.
AP-1991

fix(files-aside): update total size used after every operation

---

components/views/files/aside/List/List.vue
pages/files/browse/index.vue
plugins/thirdparty/persist.ts
store/files/getters.ts
store/files/mutations.ts
store/files/state.ts
store/files/types.ts

- fix recent files sidebar route. will get the most recent 15 files.
- I initially though to place in store so the getter had easy access. I realized that was a bad idea, better off just passing as a param to the getter.
AP-1994

fix(files): fix broken recent files route

---

pages/auth/unlock/Unlock.html
pages/auth/unlock/index.vue

Clear and Reset wasn't working correctly. If you cleared, it wouldn't reload so you would still have the same account if you tried to create a new one

chore(clearAndReset): fix clear and reset on sign in page

---

components/ui/SimpleScroll/SimpleScroll.vue
components/views/files/list/row/Row.less
pages/files/browse/Browse.html
pages/files/browse/Browse.less

- Switches layout to use display grid for better responsiveness
- Adjusts spacing
- Fixes screen width breaking due to overflowing file table in mobile layout
AP-1993

refactor(files): refactor layout

---

components/interactables/InputGroup/InputGroup.html
components/interactables/InputGroup/InputGroup.less
components/interactables/InputGroup/InputGroup.vue
pages/auth/unlock/Unlock.html

- properly hook up v model for inputGroup component
- remove self-explanatory jsdoc
- remove some bulma classes and unused props
AP-1995

refactor(inputGroup): simplify inputGroup component

---

components/views/media/actions/Actions.vue
components/views/navigation/sidebar/controls/Controls.vue
components/views/navigation/toolbar/Toolbar.vue
libraries/WebRTC/Call.ts
store/audio/actions.ts
store/audio/mutations.ts
store/video/actions.ts
store/webrtc/actions.ts

This copies @AlexZakablukov's changes from https://github.com/Satellite-im/Core-PWA/pull/3792 and pull requests them back on top of iridium-dev
AP-1832

fix(call): display errors on permission denied and change mute/unmute. Duplicate of Alex's pr against dev

---

components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
components/views/chat/message/Message.vue
components/views/chat/message/actions/Actions.less
components/views/chat/message/reactions/Reactions.vue
components/views/chat/message/reply/Reply.vue

- Rewrite conversation/message components for chat
- Rewrite stylesheets
AP-1971

feat(chat): conversation message components

---

components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.less
components/views/navigation/toolbar/Toolbar.vue
layouts/chat.vue

- Connects the state from iridium to the toolbar component.
AP-2007

fix(toolbar): connect conversation data using iridium

---

components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.vue
libraries/Iridium/friends/types.ts
locales/en-US.js

- conditionally render sidebar context menu items based on group vs friend
AP-2015
- remove friend may be a little buggy. will fix separately 

fix(sidebar): conditionally render context menu items based on type

---

components/ui/TypeAhead/TypeAhead.html
components/ui/TypeAhead/TypeAhead.less
components/ui/TypeAhead/TypeAhead.vue
config.ts
locales/en-US.js
pages/setup/ImportAccount/ImportAccount.html
pages/setup/ImportAccount/ImportAccount.less
pages/setup/ImportAccount/index.vue
pages/setup/phrase/Phrase.less

UX improvement to import account functionality:
- auto completion when inserting single / multiple words 
- button inside input to clear input text
- button to reset the passphrase 
- message error when one of multiple words inserted is incorrect
[AP-2000](https://satellite-im.atlassian.net/browse/AP-2000)

feat(account): ux improvement to import account functionality

---

utilities/Circle.ts

- Adds comments on each HEX based on https://www.color-name.com/

chore(names): colors

---

store/conversation/actions.ts

Same as https://github.com/Satellite-im/Core-PWA/pull/3919 but pointing to iridium-dev branch instead of dev

fix(media): prevent image update #3919

---

components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.vue
libraries/Iridium/groups/GroupManager.ts
libraries/WebRTC/Libp2p.test.ts
libraries/WebRTC/__snapshots__/Libp2p.test.ts.snap
pages/friends/list/FriendsList.html
pages/friends/list/index.vue

fix(friends): render issues surrounding friend requests. fix group hash method

---

components/views/chat/chatbar/Chatbar.vue
store/chat/__snapshots__/state.test.ts.snap
store/chat/mutations.ts
store/chat/state.ts
store/chat/types.ts

- Adds draft messages object to chat store
- Sets chat bar text to draft message value
AP-2014

feat(chat): persist draft messages in chatbar

---

components/views/chat/enhancers/Enhancers.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
components/views/chat/message/Message.vue
components/views/chat/message/reactions/Reactions.html
components/views/chat/message/reactions/Reactions.less
components/views/chat/message/reactions/Reactions.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts

- Connect message reactions to iridium
AP-1973

fix(chat): reactions

---

components/views/chat/conversation/Conversation.less
pages/chat/Chat.less

fix(layout): minor chat related layout fixes

---

components/views/chat/chatbar/Chatbar.less
components/views/chat/chatbar/footer/Footer.less
components/views/chat/chatbar/reply/Reply.less
components/views/chat/chatbar/upload/preview/Preview.less

fix: chat reply and file preview size bug

---

components/views/chat/chatbar/Chatbar.less
pages/chat/Chat.less

fix(chat): chatbar margin fix

---

components/views/navigation/sidebar/list/item/Item.vue
libraries/Iridium/groups/Group.ts
libraries/Iridium/groups/GroupManager.ts
libraries/Iridium/groups/types.ts

- Implements method to leave a group.
AP-2016
- Access to method can be found in context menu on right clicking the group to leave in the sidebar.

feat(groups): build leave group method

---

assets/styles/framework/ui.less
components/views/chat/chatbar/controls/Controls.vue
components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.less
components/views/chat/enhancers/glyphs/Glyphs.html
components/views/chat/enhancers/glyphs/Glyphs.less
components/views/chat/enhancers/glyphs/item/Item.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
libraries/Iridium/chat/types.ts

- Send chat glyphs using iridium
- Fixes some styles
- Improve Enhancers style
- AP-2033

fix(chat): glyphs

---

components/ui/ContextMenu/ContextMenu.vue
components/views/files/aside/Aside.html
components/views/files/aside/List/List.html
components/views/files/aside/List/List.less
components/views/files/controls/Controls.html
components/views/files/controls/Controls.less
components/views/files/controls/Controls.vue
components/views/files/filepath/Filepath.less
components/views/files/mobileList/mobileList.html
components/views/files/mobileList/mobileList.less
components/views/files/mobileList/mobileList.vue
pages/files/Files.html
pages/files/Files.less
pages/files/index.vue

- replace files title with breadcrumb. remove top row from grid
- put hamburger next to search input on fullscreen view
- small ux improvements
AP-2034

fix(files): adjust layout for better ux

---

assets/styles/framework/ui.less
components/ui/Chat/Image/Image.html
components/ui/Chat/Image/Image.less
components/ui/Chat/Image/Overlay/Overlay.html
components/ui/Chat/Image/Overlay/Overlay.less
components/ui/ImageContainer/ImageContainer.vue
components/views/chat/chatbar/upload/preview/item/Item.html
components/views/chat/chatbar/upload/preview/item/Item.less
components/views/files/grid/item/Item.html
components/views/files/grid/item/Item.less
components/views/files/grid/item/Item.vue
components/views/files/mobileList/item/Item.html
components/views/files/mobileList/item/Item.less
components/views/files/view/View.html
components/views/files/view/View.less

- Adds a ImageContainer component for dynamic styling (nsfw styling)
- Adds checkered background for transparent svgs and pngs (in ImageContainer component)
**Which issue(s) this PR fixes** 🔨 
AP-2040

fix(images): implement checkered background for transparent images

---

components/views/files/controls/Controls.html
components/views/files/controls/Controls.less
components/views/friends/add/Add.html
components/views/friends/add/Add.less
components/views/friends/add/Add.vue
pages/friends/Friends.html
pages/friends/Friends.less
pages/friends/index.vue

fix(friends): improve layout styles for desktop view

---

components/views/chat/chatbar/upload/Upload.html
components/views/chat/chatbar/upload/Upload.less

fix(chatbar): fix upload button positioning

---

components/interactables/ContextMenu/ContextMenu.html
components/ui/ContextMenu/ContextMenu.vue
components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.less
components/views/files/mobileList/item/Item.vue

- Fix the styling for the menus and modals in chat that are not reacting well with mobile layouts.
- Removes cancel button and adjust spacing for context menu.
AP-2045

fix(chat): adjust screen responsiveness for menus and modals in chat

---

components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.less

- Uses `flex-direction: column-reverse` on the conversation container so it scrolls from the bottom
AP-2025

feat(chat): start conversation scroll at bottom

---

components/ui/Chat/InfiniteScroll/InfiniteScroll.html
components/ui/Chat/InfiniteScroll/InfiniteScroll.less
components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.vue

- Rewrite infinite scroll to use wheel/touchmove events
- Mock loadMore functionality in conversation
AP-2026

feat(chat): connect infinite scroll

---

components/views/chat/chatbar/Chatbar.vue

- Fixes draft messages when switching chats
AP-2055

fix(chatbar): load draft content on mount

---

components/views/friends/add/Add.html
components/views/friends/add/Add.less
components/views/friends/add/Add.vue
components/views/friends/friend/Friend.less
components/views/friends/qrSection/QrSection.vue
components/views/friends/search/Search.vue
locales/en-US.js
pages/friends/Friends.html
pages/friends/Friends.less
pages/mobile/friends/index.vue

- build 'add friend' functionality for mobile
- fix friends-list column from over-expanding
AP-2053

feat(friends): build 'add friend' functionality for mobile

---

assets/styles/framework/typography.less
components/typography/Text.vue
types/typography.d.ts

refactor(types): create global type for component size and font config

---

assets/styles/base.less
assets/styles/framework/animations.less
components/interactables/Button/Button.html
components/interactables/Button/Button.less
components/interactables/Button/Button.vue
components/interactables/Button/README.md
components/ui/Loaders/LoadingBar/LoadingBar.vue
components/views/friends/friend/Friend.html
components/views/media/actions/Actions.html
components/views/navigation/sidebar/controls/Controls.html

Substitue buttons loader in the friends cards with the loader that is already in the chat and main screen
AP-2058

fix(buttons): fixed loader on friends cards

---

components/views/friends/friend/Friend.vue
components/views/friends/mobile/ListItem.vue

- Connects accept/reject friend request funcionality for mobile
AP-2072

feat(friends): implement accept/reject friend requests for mobile

---

libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/friends/FriendsManager.ts

fix(friends): remove conversation attached to friend

---

components/interactables/UserPicker/UserPicker.vue
components/views/navigation/sidebar/Sidebar.vue
libraries/Iridium/friends/FriendsManager.ts
pages/friends/index.vue

fix(friends): request reactivity issues

---

libraries/Iridium/chat/ChatManager.ts

- Fix the reactivity of message reactions if the message has no reactions prior
AP-2078

fix(message): reaction reactivity

---

pages/friends/Friends.html
pages/friends/Friends.less

fix: remove nested scroll

---

.gitignore
linkscript.sh

Adds a bash script for the fleek deploys to build and link iridium

chore(linkscript): add linkscript for fleek deploy

---

linkscript.sh

change internal node address for iridium build/link

chore(linkscript): updating iridium build node location

---

components/views/navigation/sidebar/controls/Controls.html

When call was muted, there was an errant ' / >' showing up in the UI

fix(ui): removes slash from UI

---

assets/styles/framework/glows.less
components/ui/Modal/Modal.less

fix(modal): modal animation

---

components/ui/BackgroundCall/BackgroundCall.vue
components/views/chat/chatbar/Chatbar.vue
components/views/navigation/mobile/toolbar/Toolbar.vue
components/views/navigation/sidebar/list/item/Item.vue
components/views/navigation/sidebar/live/Live.vue
components/views/navigation/toolbar/Toolbar.vue

Restored the friends state before the webrtc merge.

chore: restored friends state logic

---

.github/workflows/run-jest-tests.yml
.github/workflows/run-jest-tests2.yml

chore(jest): fix jest

---

components/ui/BackgroundCall/BackgroundCall.vue
components/views/chat/chatbar/Chatbar.vue
components/views/navigation/mobile/toolbar/Toolbar.vue
components/views/navigation/sidebar/list/item/Item.vue
components/views/navigation/sidebar/live/Live.vue
components/views/navigation/toolbar/Toolbar.vue

Reverting - causes some issues we will work through

Revert "chore: restored friends state logic"

---

components/views/files/list/List.less
components/views/files/list/row/Row.less
components/views/friends/emptyMessage/EmptyMessage.vue

- Re-aligns the table list icons for files.
AP-2084

fix(files): re-align table list icons

---

assets/styles/framework/ui.less
components/interactables/SidebarToggle/SidebarToggle.vue
components/ui/Modal/Modal.less
components/views/callToAction/CallToAction.less
components/views/files/aside/List/List.html
components/views/files/aside/List/List.less
components/views/friends/requests/Requests.vue
components/views/friends/requests/emptyMessage/EmptyMessage.vue
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.less
components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/Profile.less
components/views/settings/profile/accounts/Accounts.vue
pages/friends/Friends.less
pages/mobile/friends/index.vue
pages/mobile/settings/index.vue

- Adjusts miscellaneous alignment and padding in multiple areas, including SettingsProfile.
- Fixes z-index issues for mobile modal.
- Fixes mobile modal screen reactivity.
- Adds empty friend requests message for mobile.
AP-2093

fix(styles): adjust styles that used bulma

---

assets/styles/base.less
components/interactables/Button/Button.vue
components/interactables/DragBar/DragBar.vue
components/interactables/Input/Input.less
components/interactables/Select/Select.html
components/interactables/Select/Select.less
components/interactables/Select/Select.vue
components/interactables/SidebarToggle/SidebarToggle.vue
components/views/files/controls/Controls.less
components/views/friends/add/Add.html
components/views/friends/add/Add.vue
pages/friends/Friends.html
pages/friends/Friends.less
pages/friends/index.vue

- increase size of sidebar toggle component. add color
- move sidebar toggle for friends page outside specific route upto tab level
- remove unused global styles
- improve styles of select component

fix(styles): resolve style issues

---

components/interactables/Select/Select.html
components/interactables/Select/Select.less

- Fixes select max width/overflow in small containers
- Show ellipsis on overflow
- Add title attribute
AP-2152

fix(select): max-width overflow

---

libraries/Solana/UsersProgram/UsersProgram.types.test.ts

feat(jest): 100% coverage for UsersProgram.types.test.ts

---

libraries/Solana/GroupChatsProgram/GroupChatsProgram.types.test.ts

feat(jest): 100% coverage for GroupChatsProgram.types

---

libraries/Crypto/Crypto.test.ts

Self-explanatory. Can be improved more (see comment on ticket).
AP-2127

feat(jest): 17% coverage for libraries/Crypto

---

libraries/Iridium/chat/ChatManager.ts
nuxt.config.js

Adds sync pins for message exchange with CID

feat(iridium): sync pins for messaging

---

store/settings/getters.test.ts

Fixed branch to be merged into (#4273).
No tickets. 

feat(jest): 100% coverage for store/settings/getters

---

jest.config.js

Avoid running iridium tests from the iridium repo on core-pwa

chore(dir): ignore dir

---

linkscript.sh

updates linkscript to use pnpm 7/latest as of today

chore(linkscript): update pnpm in linkscript

---

utilities/Logger.test.ts

- Adds `utilities/Logger.test.ts`

chore(jest): add Logger.test.ts

---

package.json

- Removes console.log spam when running yarn test
before
after

chore(jest): improve jest command

---

libraries/BlockchainClient/adapters/Phantom/PhantomAdapter.test.ts

- Adds `libraries/BlockchainClient/adapters/Phantom/PhantomAdapter.test.ts`
before
after

chore(jest): add phantom test

---

components/compositions/useMeta.test.ts

- Adds `components/compositions/useMeta.test.ts
before
after

chore(jest): add meta test

---

libraries/BlockchainClient/BlockchainClient.test.ts

- Fix warning on import
before
after
- Adds empty lines for test to be better readable

chore(jest): improve test

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/footer/Footer.html
components/views/chat/chatbar/footer/Footer.vue
components/views/chat/chatbar/footer/connected/Connected.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts
locales/en-US.js
package.json

Block  message send until subscription happens - add message to alert to blocked sending
AP-2050

fix(subscription): chat active on subscribe

---

components/interactables/Input/Input.html
components/interactables/Input/Input.less
components/interactables/Input/Input.vue
components/interactables/Tabs/Tabs.less
components/ui/ResultsMessage/ResultsMessage.vue
components/views/files/controls/Controls.html
components/views/files/controls/Controls.less
components/views/files/controls/Controls.vue
components/views/files/controls/switch/Switch.less
components/views/files/filepath/Filepath.html
components/views/files/filepath/Filepath.less
components/views/friends/requests/Requests.vue
locales/en-US.js
package.json
pages/files/Files.html
pages/files/Files.less
pages/files/index.vue
pages/mobile/friends/index.vue
store/files/getters.ts

- Create UI for search buttons in input component 
- Provide option to search through all directories 
- Add text displayed when it's searching specifying what user is searching for and in which directories
- Add UiResultsMessage component and apply for empty searches
AP-2097
AP-2162

feat(files-search): implement advanced search options

---

tsconfig.json

- Include all ts, js, and vue files inside of tsconfig to resolve cypress overriding jest types in test files and missing ts lsp for vue files.
AP-2171

fix(build): resolve minor cypress and jest conflict

---

components/views/chat/enhancers/glyphs/item/Item.vue
types/ui/glyph.d.ts

fix(glyphs): fix glyphs

---

components/ui/DroppableWrapper/DroppableWrapper.less
pages/chat/Chat.less

fix(chat): overflow issue with many uploaded files

---

components/views/user/create/Create.html

- The "Sign in" button was disconnect from the "create user" form after new buttons were implemented.
AP-2190

fix(user-create): attach sign in button to create user form

---

components/views/user/create/Create.html
components/views/user/create/Create.vue

- Stops image cropper from getting triggered when enter is pressed on the user-create inputs
AP-2191

fix(user-create): fix imageCropper from incorrectly being triggered

---

middleware/authenticated.ts
pages/auth/unlock/index.vue

Fix redirect (and iridium load) when refreshing on accounts with pin stored

fix(login): redirect on refresh

---

components/ui/BackgroundCall/BackgroundCall.html
components/ui/BackgroundCall/BackgroundCall.vue
components/ui/Global/Global.vue
components/views/media/Media.vue
components/views/media/heading/Heading.vue
components/views/media/user/User.html
components/views/media/user/User.vue
components/views/navigation/mobile/toolbar/Toolbar.vue
components/views/navigation/sidebar/controls/Controls.html
components/views/navigation/sidebar/controls/Controls.vue
components/views/navigation/toolbar/Toolbar.vue
layouts/desktop.vue
libraries/Iridium/webrtc/WebRTCManager.ts
libraries/Iridium/webrtc/hooks.ts
pages/chat/_id.vue

* adds back the top app banner when moving away from the chat page
* refactor some of the components and centralized most of the call logic into hooks for better concistency 
AP-2174

feat(calls): background banner

---

assets/styles/framework/typography.less
components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/controls/Controls.html
components/views/chat/chatbar/controls/Controls.less
components/views/chat/chatbar/controls/Controls.vue
components/views/chat/chatbar/footer/Footer.html
components/views/chat/chatbar/footer/Footer.less
components/views/chat/chatbar/footer/Footer.vue
components/views/chat/chatbar/footer/connected/Connected.less
components/views/chat/chatbar/footer/connected/Connected.vue
components/views/chat/chatbar/upload/Error.vue
components/views/chat/chatbar/upload/Upload.less
components/views/chat/chatbar/upload/preview/Preview.less
components/views/chat/chatbar/upload/preview/item/Item.less
types/typography.d.ts

- prevent message send until subscription is registered.
- remove prop drilling of connected status. that will probably plug into user manager stuff later anyway
- fix funky overflow on chat upload list
AP-2192

fix(chatbar): block send message until subscribed, css improvements

---

assets/styles/framework/typography.less
components/interactables/Button/Button.html
components/interactables/Button/Button.less
components/interactables/Button/Button.vue
components/interactables/Chip/Chip.vue
components/interactables/UserPicker/ListItem/ListItem.html
components/typography/Text.vue
components/views/chat/message/attachments/Attachments.html

- Fix TypographyText font weight
- Move styles to global typography.less
- Fix Button reference to ref after unmount
- Fix Button loading spinner
AP-2196

fix(components): text/button

---

.gitignore
jest.config.js
linkscript.sh

chore(linkscript): fleek does not like cloning outside core-pwa

---

libraries/Iridium/webrtc/hooks.ts

fix(calls): update calls to usermanager for details

---

components/views/navigation/sidebar/list/item/Item.vue
libraries/Iridium/IridiumManager.ts

fix remove friend to work with user manager

fix(sidebar): remove friend context click

---

utilities/Timezone.test.ts

Update test suite on Timezone.ts
AP-2198

chore(jest): update timezone test

---

pages/mobile/friends/index.vue

fix(mobile): update mobile page to use usermanager

---

assets/styles/framework/colors.less
components/views/files/grid/item/Item.less
components/views/files/mobileList/item/Item.less
components/views/media/incomingCall/IncomingCall.html
components/views/media/incomingCall/IncomingCall.less
components/views/navigation/sidebar/Sidebar.less

- define global variable for common gradient
- simpler layout for call modal
AP-2194
- will look better after we build out the Button size prop

fix(call): style incoming call modal

---

components/views/chat/chatbar/controls/Controls.html

stop v-if from blocking send of mobile, move v-if to wallet function
AP-2210

fix(comingsoon): move vif to wallet on chatbar

---

components/ui/InfoButton/InfoButton.vue
components/ui/Modal/Modal.less
components/ui/Popups/ErrorNetwork/ErrorNetwork.html
components/ui/Popups/ErrorNetwork/ErrorNetwork.less
components/views/user/create/Create.html
components/views/user/create/Create.less
pages/auth/unlock/Unlock.html
pages/auth/unlock/Unlock.less
pages/auth/unlock/index.vue
pages/setup/ImportAccount/ImportAccount.html
pages/setup/ImportAccount/ImportAccount.less
pages/setup/disclaimer/Disclaimer.less

- Fixes styling for register related pages.
- Creates InfoModal.
- Moves the pin-info section in the signup unlock page into the InfoModal. 
AP-2022

fix(register): adjust and improve broken styling for auth pages

---

package.json
utilities/Logger.test.ts

Increase coverage for Logger. Updated npm script for jest while in the process, let me know if I need to remove it.
AP-2166

feat(jest): 80% coverage for utilities/Logger, update jest npm script

---

libraries/Iridium/users/types.test.ts

feat(jest): 100% coverage for libraries/Iridium/users/types

---

assets/styles/framework/blurs.less
components/ui/Loaders/ScaleLoader/ScaleLoader.vue
components/views/media/incomingCall/IncomingCall.html
components/views/media/user/User.html
components/views/media/user/User.less
components/views/media/user/User.vue
package.json
store/ui/__snapshots__/getters.test.ts.snap

fix(call-ui): fixed loader ui

---

libraries/Iridium/webrtc/WebRTCManager.ts
libraries/Iridium/webrtc/types.ts
libraries/WebRTC/Call.ts
libraries/WebRTC/WebRTC.ts
libraries/WebRTC/types.ts

Fix negotiating issues between peers that are causing stream errors and crashes
AP-2205

fix(calls): offer/answer fix

---

components/ui/GroupIcon/GroupIcon.html
components/ui/GroupIcon/GroupIcon.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.vue
components/views/chat/message/reactions/Reactions.vue
components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.vue
components/views/navigation/sidebar/quick/Quick.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts
libraries/Iridium/friends/FriendsManager.ts
libraries/Iridium/profile/ProfileManager.ts
store/accounts/actions.ts

feat(iridium): group chat

---

components/views/navigation/toolbar/Toolbar.vue

fix(toolbar): fix call button

---

package.json

chore(temp): remove cypress

---

libraries/Iridium/IdentityManager.test.ts
libraries/Iridium/__snapshots__/IdentityManager.test.ts.snap

Reopening #4291 in the hopes of not having identical GitHub Actions error!
AP-2128

feat(jest): 79% coverage for IdentityManager

---

assets/styles/framework/typography.less
components/typography/Text.vue
components/views/chat/chatbar/upload/preview/item/Item.html
components/views/files/view/View.html
components/views/settings/pages/realms/realm/Realm.html
components/views/settings/pages/realms/realm/index.vue
components/views/settings/pages/storage/Storage.html
components/views/settings/profile/accounts/Item/Item.html
components/views/settings/profile/card/Card.html
components/views/wallet/popup/Popup.html
components/views/wallet/recent/item/Item.html
pages/allcomponents.vue
pages/components.vue
types/typography.d.ts

- partial effort, there are still many left
- refactored some of the 'realms' page in settings styles while I was there.

refactor(subtitle): swap out subtitle instances for typographyText

---

components/ui/Chat/TypingIndicator/TypingIndicator.vue
components/views/chat/chatbar/footer/Footer.vue
components/views/files/controls/Controls.less
components/views/navigation/mobile/toolbar/Toolbar.html
pages/mobile/chat/_id.vue

fix(mobile): undefined check for route param id

---

components/views/media/actions/Actions.html
components/views/media/actions/Actions.less
components/views/media/actions/Actions.vue
components/views/navigation/sidebar/controls/Controls.html
components/views/navigation/sidebar/controls/Controls.less
components/views/navigation/sidebar/controls/Controls.vue
libraries/Enums/types/webrtc.ts
package.json

Fixes action buttons size
AP-2215

fix(call-actions): fixed action buttons size 

---

libraries/SoundManager/SoundManager.test.ts
libraries/SoundManager/SoundManager.ts
store/audio/actions.ts
store/sounds/actions.test.ts
store/sounds/actions.ts

Clears previous sounds played when mute/unmute button is pressed

fix(mute-toggle): cleared previous sounds played

---

libraries/Iridium/webrtc/WebRTCManager.ts

fix(call): calling sound fix

---

components/ui/Global/Global.vue
components/views/media/Media.html
components/views/media/Media.vue
components/views/media/heading/Heading.html
components/views/media/heading/Heading.vue
components/views/navigation/sidebar/live/Live.html
components/views/navigation/sidebar/live/Live.vue
store/ui/__snapshots__/state.test.ts.snap
store/ui/mutations.test.ts
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts
store/webrtc/actions.ts

- uses fullscreen api
- if the user wants to enlarge call window but keep other parts of the app visible, they can use the dragbar
AP-2193

feat(calls): add fullscreen support

---

.github/workflows/run-jest-tests.yml

chore(jest): update jest

---

libraries/BlockchainClient/BlockchainClient.test.ts
libraries/Crypto/Crypto.test.ts
libraries/Iridium/IdentityManager.test.ts
libraries/Solana/UsersProgram/UsersProgram.types.test.ts
store/meta/mutations.test.ts
utilities/EXIF.test.ts
utilities/Messaging.test.ts
utilities/Thumbnail.test.ts
utilities/__snapshots__/Messaging.test.ts.snap
utilities/__snapshots__/Thumbnail.test.ts.snap

feat(jest): update describe on tests

---

libraries/Iridium/webrtc/WebRTCManager.ts
libraries/WebRTC/Call.ts

Forgot to push few lines of code related to the mute/unmute fix.

fix(webrtc): streamMuted

---

components/views/chat/chatbar/reply/Reply.html
components/views/chat/chatbar/reply/Reply.less
components/views/chat/chatbar/reply/Reply.vue

fix(chat): fix reply name while drafting

---

components/views/media/user/User.html
components/views/media/user/User.vue

fix(calls): flip local video based on setting

---

components/views/chat/message/Message.html
components/views/chat/message/replies/Replies.html
components/views/chat/message/replies/Replies.vue
locales/en-US.js

- display name
- simplify translation logic
AP-2234

fix(chat): fix replies accordion text

---

components/ui/User/State/State.vue
components/views/chat/chatbar/footer/connected/Connected.vue
components/views/navigation/toolbar/Toolbar.vue
config.ts
libraries/Iridium/IridiumManager.ts
libraries/Iridium/friends/types.ts
libraries/Iridium/users/UsersManager.ts
libraries/Iridium/users/types.ts
libraries/Iridium/webrtc/WebRTCManager.ts

Fix the online indicator for users
AP-2018
Gonna take the same approach for the typing indicator

fix(user): user status

---

components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
components/views/chat/message/Message.vue
components/views/chat/message/notice/Notice.html
components/views/chat/message/notice/Notice.less
components/views/chat/message/notice/Notice.vue
components/views/navigation/toolbar/Toolbar.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts
libraries/Iridium/users/UsersManager.ts
locales/en-US.js
pages/chat/Chat.html
utilities/chat.ts

- Handle some undefined values
- Iridium now sends join/leave messages when user joins/leaves group
- Display join/leave messages in new MessageNotice compoent
- AP-2232

feat(chat): show join/leave notices messages in conversation

---

components/interactables/KeybindInput/KeybindInput.vue
components/views/friends/emptyMessage/EmptyMessage.vue
pages/mobile/friends/index.vue

- If user is on mobile and has no friends then default friends screen is the "Add Friend" screen.
AP-2237

fix(friends): send user to correct screen when "Add Friend" is pressed

---

components/ui/Global/Global.html
components/views/media/incomingCall/IncomingCall.less
pages/mobile/chat/_id.vue

fix(calls): improve mobile incoming calls

---

components/views/settings/Sidebar.vue

chore(realms): hide realms - AP-2243

---

config.ts

chore(fix): fix 404

---

assets/styles/framework/animations.less
components/ui/Chat/TypingIndicator/TypingIndicator.less
components/ui/Circle/Circle.html
components/ui/Circle/Circle.less
components/ui/Global/Global.html
components/ui/SvgDefs/SvgDefs.vue
components/ui/User/State/State.less
components/ui/User/State/State.vue
components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.vue
libraries/Iridium/users/types.ts

Bring back https://github.com/Satellite-im/Core-PWA/pull/3882 with the addition of the `busy` state:
Also linked the isTyping state on the sidebar item list, so nice to see.

fix(user): user states refactored

---

utilities/AudioStreamUtils.test.ts
utilities/__snapshots__/AudioStreamUtils.test.ts.snap

- adds `utilities/AudioStreamUtils.test.ts`

chore(jest): add AudioStreamUtils.test.ts

---

components/interactables/Button/Button.vue
components/interactables/ImageCropper/ImageCropper.html
components/interactables/KeybindInput/KeybindInput.html
components/ui/Popups/ErrorNetwork/ErrorNetwork.html
components/views/callToAction/CallToAction.html
components/views/chat/message/attachments/Item/Item.html
components/views/files/controls/Controls.html
components/views/friends/emptyMessage/EmptyMessage.vue
components/views/friends/friend/Friend.html
components/views/friends/qrSection/QrSection.vue
components/views/marketplace/glyphs/detail/Detail.html
components/views/marketplace/glyphs/popular/Popular.html
components/views/marketplace/glyphs/recommended/Recommended.html
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/alerts/Alerts.html
components/views/servers/create/Create.html
components/views/settings/pages/accounts/Accounts.html
components/views/settings/pages/audio/Audio.html
components/views/settings/pages/keybinds/Keybinds.html
components/views/settings/pages/storage/Storage.html
components/views/settings/profile/accounts/Item/Item.html
components/views/user/create/Create.html
components/views/user/profile/Profile.html
components/views/wallet/balance/Balance.html
components/views/wallet/mini/body/Body.html
pages/auth/unlock/Unlock.html
pages/components.vue

- set default button color, remove repeated 'primary' prop throughout the app

fix(buttons): default primary color

---

components/views/navigation/toolbar/alerts/alert/Alert.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/notifications/types.ts
locales/en-US.js

fix group chat notification messaging, set catch for group message type and add phrasing. 
AP-2218

fix(notifications): fix group chat notification messaging

---

components/interactables/Button/Button.less
components/interactables/Input/Input.html
components/views/navigation/sidebar/list/List.html
components/views/navigation/sidebar/list/List.less
components/views/settings/Sidebar.vue
components/views/settings/unit/Unit.html
pages/mobile/chat/_id.vue

- Add “sm” styling for InteractablesButton
- Center empty friends list for mobile
- Don’t show text container if empty for SettingsUnitUnit
AP-2258

fix(styling): add "sm" styling for InteractablesButton

---

components/views/chat/message/reactions/Reactions.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts

- Handles reaction publish/subscribe
- Receive reactions for messages in direct/group chat
- Fix local reactivity issues
- #3975
- AP-1973

feat(chat): message reaction pubsub/reactivity

---

components/views/media/Media.vue

- fix bug where component isFullscreen value wouldn't update upon esc fullscreen exit

fix(calls): fullscreen toggle bug

---

.github/workflows/issue-link.yml

When opening a PR if you add ''- Resolve #(ticket number here)'' on the description will automatically link the issue to the PR
more info [here](https://github.com/marketplace/actions/add-an-issue-link)

chore(action): link issue

---

libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
libraries/BlockchainClient/adapters/SolanaAdapter/__snapshots__/SolanaAdapter.test.ts.snap

feat(jest): 15% coverage for SolanaAdapter

---

assets/styles/base.less
components/typography/Text.vue
components/views/navigation/mobile/toolbar/Toolbar.html
components/views/navigation/mobile/toolbar/Toolbar.less
components/views/navigation/sidebar/list/item/Item.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.less
components/views/navigation/toolbar/Toolbar.vue

- fix eslint errors
- clean component markup
AP-2251

fix(toolbar): clean component

---

components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/index.vue

- Fix application from restarting on first status update for new users.
Resolve #4528 

fix(settings-profile): stop page sometimes refreshing on status update

---

components/ui/Chat/TypingIndicator/TypingIndicator.html
components/ui/Chat/TypingIndicator/TypingIndicator.vue
components/views/navigation/sidebar/status/Status.html
components/views/navigation/sidebar/status/Status.vue
components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/index.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/profile/ProfileManager.ts
libraries/Iridium/users/UsersManager.ts
libraries/Iridium/webrtc/WebRTCManager.ts
pages/setup/phrase/Phrase.html
pages/setup/phrase/index.vue

fixes chat reacts, profile status updates, typing indicators, and allows user to change their username

fix(reactions): fix emoji reactions

---

components/views/navigation/slimbar/Slimbar.html
package.json

take off click from icon
Resolve #4537

fix(icon): take off click from icon

---

components/views/settings/pages/profile/Profile.html
libraries/Iridium/profile/ProfileManager.ts
libraries/Iridium/users/types.ts
store/accounts/actions.ts

- New account profiles were being set in the incorrect location in iridium, this should fix that.
Resolve #4540 

fix(profile): change profile updates to use new iridium setters

---

components/views/friends/mobile/ListItem.vue
components/views/settings/pages/profile/index.vue

fix(settings-profile): add missing method

---

libraries/Iridium/chat/ChatManager.ts

fix(chat): add subscription handle on chat creation

---

components/views/navigation/sidebar/status/Status.html
components/views/navigation/sidebar/status/Status.vue

fix(sidebar): user status and name copy

---

components/views/chat/chatbar/upload/Upload.vue

- we used to have an 8 file limit for textile I think
- AP-2013
- https://github.com/Satellite-im/Core-PWA/issues/4050

fix(files): remove file upload count limit

---

PULL_REQUEST_TEMPLATE.md

- Updates PR template to be clear to add a Github issue number to automatically link issues

chore(update): update PR template

---

utilities/Notifications.ts

Move notification request access to pop up on first notification received.
Resolve #
4558

fix(notification): request notification on first notification received

---

components/compositions/conversations.ts
components/ui/GroupIcon/GroupIcon.html
components/ui/GroupIcon/GroupIcon.vue
components/views/navigation/mobile/toolbar/Toolbar.html
components/views/navigation/mobile/toolbar/Toolbar.vue
components/views/navigation/sidebar/live/Live.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.vue
libraries/Iridium/webrtc/WebRTCManager.ts

- fix group icon render
- improve readability & scalability for toolbar render logic
- create some conversation hooks, switch toolbar and mobileToolbar to script setup() syntax
- improve flexibility of existing call method, allowing params. this is helpful in cases of calling from the sidebar, since you don't always just want to scrape conversation id from the route. These hooks could probably use some additional refactoring in that regard, but that can be handled separately 

fix(groups): group icon render issues

---

components/views/settings/pages/profile/Profile.less
components/views/settings/pages/profile/index.vue
components/views/settings/profile/accounts/Item/Item.less
components/views/settings/profile/card/Card.less
locales/en-US.js
store/accounts/actions.ts
store/accounts/types.ts

- Allows user to update their about me in the profile settings
Resolve #4568 

feat(settings-profile): add functionality for updating about me

---

components/interactables/Button/Button.less

fix(buttons): add correct flair color glow

---

libraries/Iridium/settings/__snapshots__/types.test.ts.snap
libraries/Iridium/settings/types.test.ts

feat(jest): 100% coverage for Iridium/settings/types

---

components/views/navigation/sidebar/list/List.html

mobile will be busted until other toolbar PR goes through, will look like this
Resolve #

fix(sidebar): no friends message

---

components/views/navigation/sidebar/list/item/Item.vue

fix issue introduced in last large PR
Resolve #

fix(sidebar): timestamps

---

components/compositions/conversations.ts
components/views/navigation/mobile/toolbar/Toolbar.html
components/views/navigation/mobile/toolbar/Toolbar.vue
components/views/navigation/toolbar/Toolbar.html
components/views/navigation/toolbar/Toolbar.vue

fixes render issues for desktop and mobile toolbars
Resolve #

fix(toolbar): render issues surrounding user details

---

components/interactables/Checkbox/Checkbox.less

- checkmarks were floating in user picker. maybe a parent container had it's position:relative removed or something. either way, fixed now
Resolve #

fix(userpicker): floating checkmark for selected items

---

components/views/navigation/sidebar/list/List.vue

fix(sidebar): sort messages by latest incoming message

---

libraries/Iridium/chat/ChatManager.ts

- Add sync/validate p2p listener so that users can validate safety of attachments sent to them.
- corresponding PR on iridium https://github.com/Satellite-im/iridium/pull/46 to haven't the above logic

feat(safer): add a safer validator to verify signature

---

pages/index.vue

fix(mobile): redirect to proper page for mobile

---

components/interactables/Permissions/Permissions.vue
components/views/settings/pages/privacy/Privacy.html
components/views/settings/pages/privacy/index.vue
libraries/Iridium/NotificationManager.ts
locales/en-US.js
utilities/Notifications.ts

Improves permissions' tab ui and makes it actually work like expected
Resolve #4556 

feat(permissions): permisions functionality added, improved its ui

---

components/views/user/create/Create.html
components/views/user/create/Create.vue

fix(account): fix profile pic color on account create

---

pages/auth/register/index.vue
pages/index.vue

- mobile was busted at first due to some auth redirect
Resolve #

fix(router): fix mobile auth issue

---

libraries/Iridium/chat/ChatManager.ts

- conversation list wouldn't update properly
Resolve #

fix(sidebar): remove friend reactivity

---

store/files/__snapshots__/state.test.ts.snap
store/files/mutations.test.ts
store/files/state.test.ts

- 43% coverage for store/files/mutations
- 100% coverage for store/files/state
- Progress on coverage for store/files/getters
No ticket

feat(jest): 14% coverage for store/files

---

components/interactables/Permissions/Permissions.vue
components/views/settings/pages/privacy/Privacy.html
components/views/settings/pages/privacy/index.vue

fix(permissions): fixed browser compatibility, improved component performances

---

libraries/Iridium/IridiumManager.ts
libraries/Iridium/webrtc/WebRTCManager.ts

fix(init): fixes init duplication

---

components/views/files/controls/Controls.less

fix(files): switch search icon color to flair rather than blue

---

components/interactables/Volume/Volume.html
components/interactables/Volume/Volume.vue

- Make the volume slider draggable from any position
- Tweak animation
- Percentage number formatter
Resolve #4659 

fix(interactables): volume slider props

---

components/interactables/Button/Button.html
components/interactables/Button/Button.vue

- not fleshed out anywhere. I ran lighthouse to see possible performance improvements and this popped up
Resolve #

feat(buttons): add accessibility prop for aria label

---

components/views/files/aside/Aside.html
components/views/files/aside/Aside.less

- remove wonky styling from files aside button
- use new size and disabled props 
Resolve #

fix(files): use newly added disabled styling on button

---

utilities/AudioStreamUtils.ts

- Rewrite timeout logic for talking indicator
Resolve #4673 

fix(audio): talking indicator timeout

---

nuxt.config.js

- nuxt config was pointing to static, but static maps directly to root
Resolve #

fix(meta): fix favicon

---

components/views/settings/modal/Modal.html

- reorder page markup to match menu order. add categories as comment
- only render active pages. comment out dummy pages that aren't provided as sidebar options
Resolve #

fix(settings): only show active routes

---

pages/friends/Friends.html

- keep all friends content in DOM regardless of tab. should improve performance because things aren't added to DOM and torn down repeatedly
Resolve #

refactor(friends): dont lazy load tabs

---

components/views/chat/message/replies/Replies.vue
components/views/friends/mobile/List.vue
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.vue
components/views/navigation/sidebar/list/List.html
components/views/navigation/sidebar/list/List.less
components/views/navigation/sidebar/list/List.vue
locales/en-US.js
pages/mobile/chat/_id.vue

- sidebar search on mobile and desktop
Resolve #4684 

feat(sidebar): implement conversation search

---

components/views/settings/pages/profile/Profile.html
components/views/settings/profile/accounts/Item/Item.html
locales/en-US.js

fix(settings-profile): disable account section

---

components/ui/DotBadge/DotBadge.less
components/ui/DotBadge/DotBadge.vue
components/views/navigation/mobile/nav/Nav.html
components/views/navigation/mobile/nav/Nav.less
components/views/navigation/mobile/nav/Nav.vue
pages/mobile/friends/index.vue

- Adds new UiDotBadge component
- Implements UiDotBadge component to friends nav tab and friend requests tab 
Resolve #4680 

feat(mobile): add indicators for incoming friend requests

---

components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.vue
components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.vue
libraries/Iridium/chat/ChatManager.ts
types/typography.d.ts

feat(sidebar): add logic and styling for unread conversations

---

components/ui/Chat/Scroll/Scroll.html
components/ui/SimpleScroll/SimpleScroll.html
components/views/chat/chatbar/commands/preview/Preview.html
components/views/chat/enhancers/glyphs/Glyphs.html
components/views/navigation/server/sidebar/Sidebar.html
nuxt.config.js
package.json
plugins/thirdparty/vscrolllock.ts

- most of these components aren't rendered anywhere. only one I noticed was the Glyphs list. was working when I checked
Resolve #

chore(bundle): remove unused scroll lock package

---

components/ui/Global/Global.html
components/ui/Pip/Pip.vue
components/views/media/actions/Actions.less
components/views/media/previewCall/PreviewCall.html
components/views/media/previewCall/PreviewCall.less
components/views/media/previewCall/PreviewCall.vue
components/views/media/user/User.html
components/views/media/user/User.less
components/views/media/user/User.vue
config.ts

- Show screen, then video, then audio stream of remote participant
- Contain screen stream inside of box
Resolve #4647 

feat(pip): show screen/video/audio stream in preview

---

components/ui/Circle/Circle.test.ts
components/ui/Circle/__snapshots__/Circle.test.ts.snap
store/accounts/mutations.test.ts
store/files/mutations.test.ts
store/sounds/actions.test.ts

100% coverage for store/accounts/mutations.test.ts
100% coverage for store/sounds/actions.test.ts

feat(jest): 100% coverages

---

components/typography/Tag/Tag.vue
components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.less
components/views/navigation/sidebar/list/item/Item.vue
utilities/Logger.ts

Adds unread count back in.
Also adds timer (in milliseconds) to help seeing where we need to debug loading things
Resolve #

chore(friendList): added unread count back, adding timing to logger

---

components/views/chat/message/Message.vue
components/views/navigation/sidebar/list/item/Item.vue
config.ts
package.json
utilities/onlyHasEmoji.ts

fix(regex): use 3rd party regex package for emojis

---

components/views/chat/message/Message.html
components/views/chat/message/Message.vue
libraries/ui/Markdown.ts

- switch methods to computed because it has better caching, should help with performance
- remove unused context menu items and legacy code. Copy/save image logic will be added separately 
Resolve #

refactor(message): switch heavy methods to computed, remove unused code

---

pages/auth/unlock/Unlock.html
pages/auth/unlock/Unlock.less

a button is semantically better here
Resolve #

refactor(unlock): switch anchor tag to button

---

libraries/Iridium/profile/ProfileManager.ts
libraries/Iridium/users/UsersManager.ts

current implementation sets user status to 'changed' for connected peers
Resolve #

fix(profile): send online instead of changed on update

---

components/ui/Chat/Image/Image.html
components/ui/Chat/Image/Image.vue
components/views/chat/conversation/Conversation.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
components/views/chat/message/attachments/Item/Item.html
components/views/chat/message/attachments/Item/Item.less

feat(chat): copy/save image context menu in chat

---

PULL_REQUEST_TEMPLATE.md

- makes pr templates look like this
- na

chore: use headings in PR template markdown

---

components/ui/Popups/ErrorNetwork/ErrorNetwork.less
components/ui/WelcomeModal/WelcomeModal.less

- improve desktop and mobile styles
- Resolve #

fix(welcome): improve welcome modal styles

---

package.json
utilities/__snapshots__/io-ts.test.ts.snap
utilities/io-ts.test.ts

- 100% coverage for io-ts
- Adds `npm testdev` command for QA purposes (without `--silent`)

feat(jest): 100% coverage for io-ts

---

components/ui/User/State/State.vue
components/views/navigation/sidebar/list/item/Item.html
libraries/Iridium/IridiumManager.ts
libraries/Iridium/users/UsersManager.ts

- ensure sidebar keeps up to date with online status
- Resolve #

fix(sidebar): reactivity fix for sidebar user status

---

libraries/Iridium/files/FilesManager.ts

fix(files): set iridium state on init

---

components/ui/User/State/State.less
components/ui/User/State/State.vue
libraries/Iridium/chat/ChatManager.ts

- fix sidebar typing indicator reactivity issues. adjust render logic
- Resolve #

fix(sidebar): typing status

---

components/views/chat/conversation/Conversation.vue

fix(conversations): remove listeners on beforeDestroy

---

components/views/chat/conversation/Conversation.html
libraries/Iridium/utils.ts
libraries/Iridium/webrtc/WebRTCManager.ts
libraries/WebRTC/Call.ts
libraries/WebRTC/Peer.ts
libraries/WebRTC/Wire.ts
libraries/WebRTC/bus/DirectWebRTCBus.ts
libraries/WebRTC/bus/IridiumBus.ts
libraries/WebRTC/bus/bus.ts

- Adds a mechanism to automatically connect with friends over direct webrtc. 
- Provides a single interface to send messages to peers that support both communication channels (direct webrtc as preferred and pubsub as fallback)
Still working on retry mechanism in case the first connection attempt doesn't work

chore(webrtc): Refactor webrtc

---

libraries/Iridium/chat/ChatManager.ts

- Send message before storing
- Resolve #
#4736 
I think this is right?

fix(message): send message to user before store

---

components/ui/Pip/Pip.vue

- removes PiP shadow
- Resolve #4735

fix(pip-shadow): removed shadow

---

components/views/navigation/sidebar/list/item/Item.less

- title, sidebar looked bad without a full list
old
new
- Resolve #

fix(sidebar): add margin to last list item child

---

components/views/navigation/toolbar/Toolbar.html

fix(toolbar): hide chat search because its not ready

---

libraries/Iridium/chat/ChatManager.ts

- webrtc changes exposed holes in the old setTyping logic. This should be much better
- Resolve #

fix(typing): typing bug

---

components/views/navigation/sidebar/status/Status.html
components/views/settings/Sidebar.vue
components/views/settings/modal/Modal.html
components/views/settings/pages/accounts/Accounts.html
components/views/settings/pages/accounts/index.vue
components/views/settings/pages/privacy/Privacy.html
cypress/e2e/privacy-page-toggles.js
locales/en-US.js
pages/mobile/settings/index.vue

super minor pre ea cleanup:
Elaborated in some of the settings descriptions
Hide register username publicly
Hide display current activity
Add ability to copy friendly name to Accounts and Devices
Hide Network (testnet select screen) tab in settings
- Resolve #

chore(cleanup): pre-launch cleanup

---

pages/chat/Chat.html
pages/files/Files.html

- was missing a ref. this is a bad pattern that should be refactored with comp api, but it works for now.
- backlog ticket to refactor https://github.com/Satellite-im/Core-PWA/issues/4785
- Resolve #4783

fix(chat): restore drag and drop functionality

---

package.json

chore(cypress): install cypress

---

assets/styles/base.less
components/ui/User/State/State.less
components/ui/User/State/State.vue

- Fixes typing indicator on safari
- Resolve #

fix(typing-indicator): fixed on safari

---

libraries/Iridium/webrtc/WebRTCManager.ts

- after answering and unmuting the video the other user should see you 
on dev you should have a black box instead if the video, this PR should fix that
- Resolve #

fix(video): reactivity video

---

components/compositions/conversations.ts

- fix potential undefined crash
- Resolve #

fix(chat): add better type guard to filter undefined

---

components/views/chat/message/Message.vue

fix(chat): remove 'reply' from a reply's context menu

---

components/ui/Global/Global.html

fix(modals): display coming soon modal above all others

---

components/ui/ActionSheet/ActionSheet.vue
components/ui/WelcomeModal/WelcomeModal.less
components/views/friends/friend/Friend.html
components/views/media/actions/Fullscreen.vue

fix(friend): add context menu functionality to friend component

---

components/views/chat/conversation/Conversation.vue

- fix maxTime logic
- Resolve #4791

fix(unread): fix max message time logic

---

components/views/chat/UserList.vue
pages/chat/_id.vue
pages/friends/Friends.less

- Tweaks user list style
- Fix shadow
- Remove friend list gap
- Resolve #4817

fix(userlist): style

---

components/compositions/conversations.ts
components/ui/Loaders/ScaleLoader/ScaleLoader.vue
components/views/chat/message/Message.vue
components/views/media/incomingCall/IncomingCall.html
components/views/media/incomingCall/IncomingCall.less
libraries/Iridium/webrtc/WebRTCManager.ts

- Clear incomingCall object when denying a call
- Resolve #4813

 fix(call): clear incoming call object when denying call

---

components/views/navigation/sidebar/Sidebar.less
components/views/navigation/sidebar/list/item/Item.less
pages/mobile/chat/_id.vue

- Sidebar list items expand to edges
- Fix selected/hover highlight
- Resolve #4821

fix(sidebar): margin and hover

---

libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/friends/FriendsManager.ts
libraries/Iridium/groups/GroupManager.ts
libraries/Iridium/webrtc/WebRTCManager.ts

chore: restored vue.set

---

components/views/navigation/sidebar/list/item/Item.vue

- fixes crashes when removing a friend from the sidebar 
- Resolve #4827

fix(remove-friend): fixed sidebars' context menu

---

components/views/media/incomingCall/IncomingCall.html
components/views/media/incomingCall/IncomingCall.vue
components/views/media/user/User.html
components/views/media/user/User.vue
components/views/navigation/sidebar/list/item/Item.vue
components/views/navigation/toolbar/Toolbar.vue
libraries/Iridium/webrtc/WebRTCManager.ts
libraries/WebRTC/Call.ts
store/audio/actions.ts

- Fix call mute state when making/answering calls
- Fix MediaUser mute state indicator reactivity
- Resolve #4584
- Resolve #4768

fix(call): mute state and reactivity

---

components/views/files/aside/List/List.html
components/views/files/aside/List/List.less

fix(files): aside hover and active css

---

components/views/chat/chatbar/Chatbar.vue

fix(chat): prevent image paste if no scan permission granted

---

components/views/navigation/slimbar/Slimbar.html
locales/en-US.js

- Coherent coming soon - we have the feature name, and then coming soon everywhere besides the new community
before
after

chore(update): update coming soon

---

pages/setup/disclaimer/Disclaimer.html

- Adds coming soon on connect wallet and import account buttons, due to import account flow is broken atm and connect wallet is not fully implemented on dev
before
https://user-images.githubusercontent.com/29093946/190495246-50af5cfe-3c0e-4424-8408-22adc5742088.mov
after
https://user-images.githubusercontent.com/29093946/190495239-35056da6-a349-4123-ac82-863762a50d1c.mov

chore(sign-up): coming soon buttons

---

libraries/Iridium/chat/ChatManager.ts

- Fix typing indicator problem
- Resolve #4834

fix(chat): typing indicator

---

libraries/WebRTC/Wire.ts

- adds a connection timeout inside the wire to prevent some edge cases
- If the signaling over pubsub was failing in the middle for any reason, the connection was never retried
- thanks for reviewing 🙏

fix(webrtc): add connection timeout to fix some edge cases

---

libraries/Iridium/webrtc/WebRTCManager.ts
libraries/WebRTC/Call.ts

- Fix a reactivity problem with the video:
* A calls B with the audio unmuted
* A unmutes the video
* B answers and see the A video black
- Resolve #

fix(chat): stream reactivity

---

.prettierignore

chore(update): update prettier ignore file

---

locales/en-US.js

chore(locales): improve grammar

---

README.md

Updates read me with feedback URL

chore(update): update read me

---

.prettierignore

- recent change prevents managers from autoformatting
- Resolve #

fix(prettier): restore formatting for manager

---

components/views/chat/chatbar/upload/Upload.vue
libraries/Iridium/chat/ChatManager.ts

fix(chat): handle empty file

---

libraries/WebRTC/Call.ts

- Makes sure a stream was created before unmuting screen share state
- Resolve #4814

fix(calls): dont unmute screen share if no stream

---

components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.less

- Fixes an issue where the chat wouldnt scroll down to the bottom when sending an attachment
- Resolve #4860

fix(chat): scroll to bottom on send attachment

---

assets/styles/base.less
assets/styles/framework/colors.less
assets/styles/framework/glows.less
components/interactables/Button/Button.less
components/interactables/KeybindInput/KeybindInput.less
components/ui/Modal/Modal.less
components/views/settings/Sidebar.vue
components/views/settings/modal/Modal.less
components/views/settings/page/Page.less
components/views/settings/pages/audio/Audio.html
components/views/settings/pages/audio/sounds/Sounds.html
components/views/settings/pages/audio/sounds/Sounds.less
components/views/settings/pages/audio/sounds/item/Item.vue
components/views/settings/pages/keybinds/Keybinds.html
components/views/settings/pages/keybinds/Keybinds.less
components/views/settings/pages/profile/Profile.less
components/views/settings/pages/storage/Storage.html
components/views/settings/profile/Banner.vue
components/views/settings/profile/accounts/Accounts.vue
components/views/settings/profile/accounts/Item/Item.less
components/views/settings/profile/card/Card.less
components/views/settings/unit/Unit.less
locales/en-US.js
pages/mobile/chat/_id.vue
pages/mobile/settings/index.vue

- Improve settings modal styling
- Padding on mobile
- Margin padding gap
- Change settings background
- Restore settings sidebar background
- Fix shadows
- Disabled button styling
- Fix locales
- Keybind reset button styling
- Resolve #4855

fix(ui): settings pages and button style

---

components/views/navigation/sidebar/list/List.less

chore(list): padding for empty friends box

---

assets/styles/base.less
components/views/chat/message/Markdown.vue
components/views/files/filepath/Filepath.html
components/views/files/filepath/Filepath.less
components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.less
components/views/settings/Sidebar.vue

- change chat links to selected flair color
- remove pointer events from sidebar. You could click a link from the message preview.
- Resolve #4867

feat(chat): add link colors

---

components/interactables/Editable/Editable.vue

- Restore chat placeholder
- Resolve #

chore(chat): restored placeholder

---

components/views/user/create/Create.vue

fix(user-create): send user to home if did not set in register page

---

components/interactables/Select/Select.less
components/interactables/Volume/Volume.less
components/views/settings/pages/audio/Audio.html
components/views/settings/pages/audio/Audio.less
components/views/settings/unit/Unit.less

- Fixes audio video input output layout on mobile and desktop
- Fix select width on mobile
- Resolve #4879

fix(settings): audio video layout

---

libraries/Iridium/friends/FriendsManager.ts

fix(friends-manager): throw error if friend exists on requestCreate

---

components/ui/Global/Global.html
components/ui/Global/Global.vue
components/views/navigation/sidebar/list/item/Item.vue
libraries/Iridium/friends/FriendsManager.ts

- check if current page matches incoming friend removal. redirect to appropriate page if true
- this was previously handled on the sender side, but receiver would crash. This takes care of both
- Resolve #4882

fix(removeFriend): centralize remove friend redirect logic, prevent crash

---

components/interactables/Input/Input.less

- title. see issue for screenshot
- Resolve #4682

fix(sidebar): safari and ffx search input overflow

---

components/ui/Global/Global.vue
libraries/Iridium/chat/ChatManager.ts

fix(groups): prevent crash on leave group if active chat

---

pages/setup/disclaimer/Disclaimer.html

- title
- I changed them to disabled rather than coming soon wrapper. Jason improved disabled styles today.
- Mobile users wont have good tooltip ux so we shouldnt rely on those to block. disabled is better
issue here
- Resolve #

fix(signup): buttons weren't wrapping well on mobile

---

components/views/navigation/toolbar/alerts/Alerts.html
components/views/navigation/toolbar/alerts/Alerts.less
components/views/navigation/toolbar/alerts/alert/Alert.less

- Improve Alerts modal style on the toolbar
- Resolve #

chore(toolbar): alerts modal style

---

components/views/settings/pages/privacy/Privacy.html
locales/en-US.js

changes the word pin to pass, hide settings that dont work
- Resolve #

chore(cleanup): settings toggles, change pin to password

---

components/ui/Chat/Image/Image.html
components/ui/ImageContainer/ImageContainer.vue

fix(chat): give transparent images transparent background

---

components/views/chat/message/Message.less

- Transparent background for glyphs
- Resolve #

fix(chat): background for glyphs

---

middleware/authenticated.ts
store/accounts/actions.ts

- Fix the refresh bug when you have the pin saved
- Resolve #

fix(accounts): refresh issues

---

pages/chat/_id.vue

- When there are a lot of files the chat overflows on the x-axis breaking the ui. This fixes that
- Resolve #

fix(chat): max width

---

config.ts
libraries/Iridium/IridiumManager.ts

- add apis config from .env for Iridium initialization

fix(config): add apis config from .env for Iridium initialization

---

store/ui/mutations.test.ts
utilities/onlyHasEmoji.test.ts

- 71% coverage for store/ui/mutation
- 89% coverage for utilities/onlyHasEmoji
Ticket: AP-2692

feat(jest): improve store/ui and util

---

components/views/settings/Sidebar.vue
components/views/settings/header/Header.html
components/views/settings/header/Header.less
components/views/settings/header/Header.vue
components/views/settings/pages/accounts/Accounts.html
components/views/settings/pages/audio/Audio.html
components/views/settings/pages/developer/Developer.html
components/views/settings/pages/info/Info.html
components/views/settings/pages/keybinds/Keybinds.html
components/views/settings/pages/personalize/Personalize.html
components/views/settings/pages/privacy/Privacy.html
components/views/settings/pages/storage/Storage.html
pages/mobile/settings/index.vue

- Add SettingsHeader component
- Fix mobile styling on settings page
- Add settings page header
- Resolve #4919

feat(settings): settings header component

---

locales/en-US.js

- Improve copy to be more friendly

chore(locales): improve copy

---

pages/auth/unlock/index.vue

- Fixed minor ui glitch in the login icon
- Resolve #

fix(login): icon glitch

---

locales/en-US.js
middleware/authenticated.ts
pages/index.vue

- display window alerts in both instances if a second one is opened
- Resolve #4706

fix(window): detect multiple instances of core in same browser

---

components/views/navigation/sidebar/status/Status.html
components/views/navigation/sidebar/status/Status.vue
components/views/settings/pages/profile/Profile.html
libraries/Iridium/profile/ProfileManager.ts

Reverts Satellite-im/Core-PWA#4939

Revert "fix(sidebar): user status reactivity bug"

---

components/views/navigation/sidebar/list/List.less
components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.less

fix(sidebar-list-item): stop last message sometimes overflowing

---

utilities/Logger.test.ts

Increase logger branch coverage

feat(jest): increase Logger branch coverage to 83%

---

components/views/chat/chatbar/upload/Upload.vue

- title. this used to exist but was removed during one of the large refactors
- Resolve #4947

fix(chat): add loading cursor to file upload preview

---

components/compositions/conversations.ts
components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.vue
components/views/chat/enhancers/glyphs/item/Item.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
components/views/chat/message/Message.vue
components/views/chat/message/call/Call.html
components/views/chat/message/call/Call.less
components/views/chat/message/call/Call.vue
components/views/chat/message/call/direction/Direction.html
components/views/chat/message/call/direction/Direction.less
components/views/chat/message/call/direction/Direction.vue
components/views/chat/message/replies/Replies.html
components/views/navigation/sidebar/list/item/Item.vue
libraries/Iridium/chat/types.ts
locales/en-US.js

- Adds components
- `MessageCall`
- `MessageCallDirection`
- Adds a `call` type message and adds call history to chats
- Displays call duration in the chat
- Resolve #4957

feat(call): add call info to chat history

---

components/views/chat/message/Message.html

fix(chat): undefined crash

---

components/interactables/Input/Input.html
components/interactables/Input/Input.less
components/interactables/QuickProfile/QuickProfile.html
components/interactables/QuickProfile/QuickProfile.less
components/interactables/QuickProfile/QuickProfile.vue
components/ui/Global/Global.html
components/views/chat/message/Message.html
components/views/chat/message/Message.vue
plugins/thirdparty/persist.ts
store/ui/__snapshots__/state.test.ts.snap
store/ui/actions.ts
store/ui/mutations.test.ts
store/ui/mutations.ts
store/ui/state.ts
store/ui/types.ts

- implement quick profile
- refactor store to be simpler (1 value instead of 2)
- rework quick profile css
- Resolve #4962 
There's a couple future improvements I added to a separate ticket https://github.com/Satellite-im/Core-PWA/issues/4965

feat(chat): implement quick profile

---

components/mixins/UI/ContextMenu.ts
components/ui/User/State/State.vue
components/views/friends/add/Add.vue
components/views/friends/friend/Friend.html
components/views/friends/friend/Friend.vue
components/views/friends/search/Search.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/friends/FriendsManager.ts
libraries/Iridium/users/UsersManager.ts
libraries/WebRTC/Wire.ts
locales/en-US.js

- Fix `Wire` logic for sending events (like the typing indicator) to all related-users instead to only friends
- Keep only users needed in the userState manager instead of keeping them all
- Fix extra network request to the sender in case of accept/reject/create request and remove friend (we keep users that leave a group for old messages, we remove them when the user itself leaves the group)
- Fix some problems related to the search in "Add friend" section
- Hide the user status in the "Add friend" section
- Add error message in case of duplicate request
- Remove ContextMenu in case of a request or a preview in the "Add friend" section and in the "Request" section
- Resolve #4790 
- Resolve #4953  
Please review that friending is working and there are no problems also in special case …

fix(announce): announce to all users

---

components/views/group/invite/Invite.html
components/views/group/invite/Invite.less
components/views/navigation/sidebar/quick/Quick.html

- standardize the styles between these two similar popups.
- Resolve #4851 
- This could potentially be broken out into a single component and handled with props

style(chat): switch group member invite to match quickchat style

---

components/interactables/Input/Input.less

- title
previously looked like this 😵‍💫 
- Resolve #4980

fix(inputs): remove webkit autofill color

---

components/views/chat/chatbar/Chatbar.less
components/views/chat/chatbar/footer/Footer.less

style(chat): improve mobile chatbar styles

---

utilities/Logger.test.ts

chore(test): remove test

---

libraries/Iridium/chat/ChatManager.ts

fixes related to aws safer integration

feat(safer): add aws client for safer

---

locales/en-US.js
pages/files/Files.html

fix(files): update local address for no file results

---

assets/styles/framework/colors.less
assets/styles/framework/typography.less
components/interactables/Button/Button.less
components/interactables/Close/Close.html
components/interactables/Close/Close.less
components/interactables/ContextMenu/ContextMenu.less
components/interactables/KeybindInput/KeybindInput.html
components/interactables/Select/Select.html
components/interactables/Select/Select.less
components/typography/HorizontalRuleText/HorizontalRuleText.less
components/typography/Label/Label.less
components/typography/Text.vue
components/ui/Global/Global.html
components/ui/Modal/Modal.html
components/ui/Modal/Modal.vue
components/ui/WelcomeModal/WelcomeModal.vue
components/views/ModalDialog/ModalDialog.less
components/views/ModalDialog/ModalDialog.vue
components/views/callToAction/CallToAction.html
components/views/callToAction/CallToAction.less
components/views/confirmation/Confirmation.vue
components/views/media/heading/Heading.vue
components/views/settings/modal/Modal.html
components/views/settings/pages/accounts/Accounts.html
components/views/settings/pages/info/Info.html
components/views/settings/pages/info/index.vue
components/views/settings/pages/profile/Profile.less
components/views/settings/pages/storage/Storage.html
components/views/settings/unit/Unit.less
locales/en-US.js

- Fixes small font sizes
- Add letter-spacing tracking to uppercase labels
- Move modal close button inside of Modal, uses a prop to hide it
- Fix welcome modal style
- Fix confirmation modal style
- Resolve #5012

fix(misc): global styles

---

components/ui/Banner/Banner.less
locales/en-US.js
pages/auth/unlock/Unlock.html
pages/auth/unlock/Unlock.less

fix(unlock): improve non-chromium browser warning styling

---

libraries/Iridium/chat/ChatManager.ts

- Switch for loop in favour of Promise.all on chat initial subs. Makes a huge difference when you have a lot of convos
- Resolve #

chore(chat): promise.all on load

---

components/interactables/Input/Input.less

- lowers placeholder opacity
- adds ellipsis for text
- Resolve #5029

fix(input): minor style adjustments

---

components/views/confirmation/Confirmation.vue
components/views/friends/friend/Friend.html
components/views/friends/friend/Friend.vue
components/views/friends/requests/Requests.vue
components/views/friends/search/Search.vue
locales/en-US.js
store/ui/mutations.test.ts
store/ui/types.ts

- Shows correct buttons in friends list items (found in friend search and requests tabs) when incoming/outgoing requests exist
- Removes unused code
- Divides file scanning confirmation message into 2 paragraphs
- Resolve #5033 
For more info see comments in https://github.com/Satellite-im/Core-PWA/pull/5019

fix(friends): show correct buttons when incoming/outgoing requests exist

---

pages/friends/Friends.less

- fixes scrollbar position in the friends requests tab
- Resolve #5024

fix(requests-list): fixed scroll

---

linkscript.sh

Changes how we set SYNC_NODE_ADDR to try and do away with the 127.0.0.1 errors in the client
- 
- Resolve #

chore(linkscript): update to set SYNC_NODE_ADDR

---

components/mixins/UserPermissions/index.ts
components/views/settings/pages/audio/Audio.html
components/views/settings/pages/audio/Audio.less
components/views/settings/pages/audio/index.vue
locales/en-US.js

- will no longer automatically open audio track on settings page
- add button to create/stop audio track to test mic sensitivity
- improve type sense in audio settings index
- Resolve #5021 
- Due to better type sense, I learned that volume is deprecated. I made a ticket to replace that https://github.com/Satellite-im/Core-PWA/issues/5031

feat(settings): toggle mic sensitivity test

---

libraries/Iridium/NotificationManager.ts
libraries/Iridium/friends/FriendsManager.ts

…nd not recipient
- 
- Resolve #5055

fix(notifications): friend request notifications are sent to sender

---

libraries/Iridium/settings/types.test.ts
store/accounts/mutations.test.ts
store/audio/actions.test.disabled.ts
store/chat/mutations.test.ts
store/settings/getters.test.ts
utilities/chat.test.ts

- Organize imports in Jest tests

chore(imports): organize imports

---

components/views/chat/message/Message.vue

- As Luis mentioned, he tried the right click to edit messages and wasn't there 😂 
This PR fixes that

chore(fix): edit message context menu

---

components/views/navigation/slimbar/Slimbar.html
components/views/navigation/slimbar/Slimbar.vue

fix(slimbar): crash on coming soon click

---

components/views/navigation/sidebar/status/Status.html
components/views/navigation/sidebar/status/Status.less
components/views/navigation/sidebar/status/Status.vue

- switch to new typography
- use button instead of clickable div
- Resolve #5081

fix(sidebarStatus): fix typography and accessiblity

---

libraries/WebRTC/Peer.test.ts
store/chat/mutations.test.ts

- Increase coverage for WebRTC/Peer
- Increase coverage for store/chat/mutations
- Resolve AP-2793 (see note below)
I am currently contacting Muhammad to see what he thinks of this PR. We might be able to increase the coverage of this file (Peer.ts) overtime 😄

feat(jest): Increase coverage for WebRTC/Peer

---

components/ui/Global/Global.html
components/views/media/incomingCall/IncomingCall.vue
libraries/Iridium/webrtc/WebRTCManager.ts
libraries/Iridium/webrtc/types.ts

chore(calls): remove close on incoming modal

---

components/ui/GroupIcon/GroupIcon.html
components/ui/GroupIcon/GroupIcon.less
components/ui/GroupIcon/GroupIcon.vue

- Title
- Resolve #4982 
Kept a similar layout of the multi-icon hope you like this

chore(icon): group icon for two layout

---

components/views/chat/message/actions/Actions.html
components/views/friends/Item.vue
cypress/e2e/add-friend.js
cypress/e2e/chat-features.js
cypress/support/commands.js

- Fixed data-cy attributes recently changed
- Updated add friends tests to use new data-cy attributes
- Updated chat features spec to have Edit Messages validations working
- Resolve #AP-2846
Tests Passing:
Cypress Video Add Friends:
https://user-images.githubusercontent.com/35935591/193118424-372e8d5c-e40e-4044-9e00-5388c761370a.mp4
Cypress Video Chat Features:
https://user-images.githubusercontent.com/35935591/193118410-14234e25-b45d-444d-a42d-d4f32ef1615d.mp4

test(cypress): updates to edit chat and add friends

---

layouts/desktop.vue

fix(chat): drag and drop file upload

---

assets/styles/base.less
components/interactables/Switch/Switch.html
components/interactables/Switch/Switch.less
components/interactables/Switch/Switch.vue
components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.less
components/views/chat/chatbar/Chatbar.vue
components/views/files/controls/Controls.html
components/views/files/controls/Controls.less
components/views/user/create/Create.html

- title
- Resolve #5072 
- chatbar and switch can be implemented with css `:has`, but browser support is still too low. went with a js approach for now with event listeners

feat(a11y): outline on keyboard focus

---

components/views/friends/search/Search.vue
libraries/Iridium/utils.ts

- Return "user not found" msg in case the only match is a friend (or is in the requests) and the query string is not an exact shortDID or DID
- Add utils for checking the shortDID and DID format
- Resolve #5080

chore(search): search improved

---

libraries/WebRTC/bus/DirectWebRTCBus.test.ts

- Increase coverage for DirectWebRTCBus
- Resolve AP-2795
Related to #5092

feat(jest): 59% coverage for DirectWebRTCBus

---

assets/styles/framework/animations.less
components/ui/CaretDivider/CaretDivider.less
components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.less
components/views/chat/conversation/Conversation.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.less
components/views/chat/message/Message.vue
locales/en-US.js

- Adds top and bottom unread message indicator to chat when new messages aren't visible in the viewport
- Resolve #5002

feat(chat): unread message indicators

---

components/ui/Global/Global.html
layouts/default.vue
pages/auth/unlock/Unlock.html

chore(modals): check close button on all modals

---

components/ui/Global/Global.vue
libraries/Iridium/NotificationManager.ts
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/friends/FriendsManager.ts
libraries/Iridium/notifications/__snapshots__/types.test.ts.snap
libraries/Iridium/notifications/types.ts
pages/mobile/friends/index.vue
utilities/Notifications.ts

Takes user to app when the browser's notifications are clicked for:
- New message notifications:
- Take user to the chat with the new messages
- New friend request notifications:
- Take user to friend requests page
- All other notifications:
- Move window focus to application
- Resolve #5099

feat(notifications): add browser notification click functionality

---

store/chat/mutations.ts

fix(chat): typing indicator on new conversation fixed

---

components/ui/Global/Global.html
components/views/glyphs/Glyphs.html
layouts/default.vue

- Remove extra close button from glyph modal
- Fix close modal callbacks
- Hide close dialog button on error modal in default layout
- Resolve #5069

fix(modal): remove duplicate close button

---

components/views/navigation/toolbar/Toolbar.html

- hiding until we can refactor notificationManager
- Resolve #

fix(toolbar): hide notifications temporarily

---

store/files/mutations.test.ts

- Increase coverage for store/files/mutations

feat(jest): 93% coverage for store/files/mutations

---

components/views/chat/conversation/Conversation.vue

- fix infinity / -infinity bug
- Resolve #5122

fix(chat): switch to Date.now for timestamp update

---

components/views/chat/chatbar/controls/Controls.html
components/views/chat/chatbar/controls/Controls.less
components/views/chat/chatbar/upload/Upload.less
locales/en-US.js

- Fix disable button colors
- Improve coming soon locale strings
- Resolve #5132

fix(coming-soon): disabled button color

---

components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue

- improve consistency around chatbar keyboard focus outline
- Resolve #5124

fix(chatbar): fix a11y outline around chatbar

---

libraries/Iridium/NotificationManager.ts

- Adds sound when new browser notifications
- Resolve #5117

feat(notifications): add sound for new notifications

---

components/interactables/Switch/README.md
components/interactables/Switch/Switch.html
components/interactables/Switch/Switch.less
components/interactables/Switch/Switch.vue
components/views/settings/pages/audio/Audio.html
components/views/settings/pages/audio/sounds/item/Item.vue
components/views/settings/pages/privacy/Privacy.html
components/views/settings/profile/accounts/Item/Item.html
components/views/wallet/accounts/Accounts.html
pages/auth/unlock/Unlock.html

- require label prop for screenreader, create secondary prop for rendering title
- only show outline if keyboard selection
- Resolve #5078

feat(switch): improve switch a11y

---

components/views/chat/conversation/Conversation.vue

- Noticed that this observer can be replaced using the watcher
- Resolve #5107 
Be sure that the conversation scroll behaves as usual

chore(chat): remove observer

---

libraries/SatelliteDB/SearchIndex.test.ts

- Improve current coverage by covering method and also branches on the constructor

feat(jest): 92% coverage for SearchIndex

---

libraries/Solana/SolanaManager/SolanaManager.test.ts

- Increase coverage for SolanaManager
What am I doing wrong here? By here I mean the `Keypair.fromSeed` part. Are there initial steps I should've taken when I test this method? Thanks!

feat(jest): 46% coverage for SolanaManager

---

components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.less

feat(sidebar): add keyboard accessibility to sidebar chat list

---

assets/styles/reset.css
components/views/files/filepath/Filepath.html
components/views/files/filepath/Filepath.less

- title
- switch to ol instead of ul for better screenreader support
- Resolve #5154

feat(files): breadcrumbs a11y

---

components/ui/Chat/Image/Image.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/utils.ts

- Utilizes the updated file upload functionality on Iridium https://github.com/Satellite-im/iridium/pull/114
- We upload files to IPFS now and we allow large file uploads

feat(files): upload files to ipfs

---

components/compositions/conversations.ts
components/compositions/webrtc.ts
components/views/chat/UserList.vue
components/views/chat/chatbar/footer/TypingIndicator/TypingIndicator.vue
components/views/navigation/mobile/toolbar/Toolbar.vue
components/views/navigation/toolbar/Toolbar.vue
pages/chat/_id.vue

- title. Did this to prepare SidebarListItem to use hooks, can pass conversationId prop
- Resolve #5162

refactor(hooks): switch conversation hooks to use param id, create webrtc hooks

---

components/ui/Pip/Pip.vue

- Add momentum to the PIP while dragging, if motion is detected when the PIP is let go of, it will keep it's momentum so the user can 'throw' it into a quadrant.
- Resolve #5170

feat(pip): drag release momentum

---

libraries/WebRTC/bus/DirectWebRTCBus.test.ts
utilities/typeGuard.test.ts

- 100% coverage for DirectWebRTCBus
- 100% coverage for typeGuard

feat(jest): 100% coverage for DirectWebRTCBus

---

components/interactables/Editable/Editable.vue
components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/chat/chatbar/autocomplete/Autocomplete.html
components/views/chat/chatbar/autocomplete/Autocomplete.less
components/views/chat/chatbar/autocomplete/Autocomplete.vue

- Add ChatbarAutocomplete component
- Username autocompletion in conversations triggered by typing '@'
- Resolve #5151
We're going to add rich text insertion in a future PR! 🙇

feat(chatbar): add autocomplete to chatbar

---

libraries/Crypto/Crypto.test.ts

- Increase coverage for libraries/Crypto
- Resolve AP-2127

feat(jest): 31% coverage for libraries/Crypto

---

components/ui/Circle/Circle.less
components/views/navigation/sidebar/status/Status.html
components/views/navigation/sidebar/status/Status.less
components/views/navigation/sidebar/status/Status.vue

- Add clipboard icon next to name in sidebar status
- Resolve #5172

feat(sidebar): copy id icon

---

components/compositions/conversations.ts
components/compositions/webrtc.ts
components/views/chat/conversation/Conversation.vue
components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.vue
plugins/local/dayjs.ts
store/settings/getters.ts
utilities/timestamp.ts

- update this component to use pre-existing hooks
- create new hooks such as `numUnreadMessages` and `sortedMessages`
- move dayjs timestamp utilities outside of vuex. we should purely rely on OS timezone rather than a user controlled setting. User can update OS timezone if they choose.
- Resolve #5165 
- left behind some options API because I haven't found a clean way to interact with vuex store inside script setup(). can revise later

refactor(sidebar): switch SidebarListItem to composition api, add new hooks

---

pages/files/Files.less

- Fixes width overflow on mobile on files layout
- Resolve #5213

fix(mobile): files layout width overflow

---

android/app/src/main/AndroidManifest.xml

- Fix audio 'recording' permission in android
- Resolve #5195

fix(permissions): add modify_audio_settings to android manifest

---

components/ui/Modal/Modal.less

- Fixes incoming call modal container z index on android
- Resolve #5220

fix(modal): z-index

---

.github/workflows/cypress-tests.yml

test(test): test

---

assets/styles/base.less

- Fixes the overscroll bounce on Android
- Resolve #5226

fix(android): overscroll bounce on webview

---

components/ui/Modal/Modal.vue

- it wasn't working because the welcome modal conditionally renders a button with templates
- Resolve #5230

fix(modals): fix focus trap for welcome modal

---

android/app/capacitor.build.gradle
android/capacitor.settings.gradle
components/compositions/capacitor.ts
components/views/chat/message/Message.vue
components/views/friends/search/Search.vue
components/views/navigation/sidebar/status/Status.vue
components/views/settings/pages/accounts/Accounts.html
components/views/settings/pages/accounts/index.vue
package.json
pages/setup/phrase/Phrase.html
pages/setup/phrase/index.vue

- Uses capacitor plugin for copying text on Accounts page. Haven't been able to test the APK, so reviews are most certainly awaited :D
- Tries to solve #5199

feat(native-android): clipboard improvement

---

components/views/chat/enhancers/Enhancers.less

- it doesnt need z index because its below conversation elements in the dom
- Resolve #5236

fix(enhancers): remove z index

---

components/ui/Chat/Image/Overlay/Overlay.html
components/ui/Chat/Image/Overlay/Overlay.less
components/ui/Global/Global.html
components/ui/Modal/Modal.less
components/views/ModalDialog/ModalDialog.less
components/views/callToAction/CallToAction.less
components/views/confirmation/Confirmation.vue
components/views/files/view/View.html
components/views/media/incomingCall/IncomingCall.less

- better/more consistent background styles
- take advantage of esc listener to close modal
- 
- Resolve #5153

refactor(chat): wrap image preview overlay in Modal component

---

components/compositions/events.ts
components/interactables/QuickProfile/QuickProfile.html
components/interactables/QuickProfile/QuickProfile.vue
components/ui/Global/Global.html
components/ui/Modal/Modal.vue

- upgrade Modal.vue to use composition API
- break out esc listener to composable
- pull in said composable to quickProfile
- Resolve #5246 
- will fully upgrade QuickProfile in a separate ticket
- would also like to consolidate focustrap logic into a composable, will make a ticket

feat(quickProfile): add focus trap and upgrade to comp api

---

components/views/navigation/sidebar/Sidebar.less

- there was an arbitrary max height forcing overflow, this is better
- Resolve #

refactor(sidebar): improve overflow css rule

---

components/compositions/friends.ts
components/views/friends/search/Search.vue
components/views/navigation/sidebar/status/Status.vue
libraries/Iridium/IridiumManager.ts

- add getter to iridium manager for shortId
- rename unrelated, unimplemented friends hook to be more concise
- Resolve #5250 
- 
-

refactor(shortId): consolidate shortId logic

---

ios/readme.md

- chore(read-me): update read me

chore(read-me): update read me

---

components/compositions/events.ts
components/ui/Modal/Modal.vue

- title
- Resolve #5251 
- still need to implement in quickProfile. Will bundle it with the composition api upgrade https://github.com/Satellite-im/Core-PWA/issues/5248
-

refactor(modal): create focusTrap composable and implement in Modal

---

components/interactables/Input/Input.vue
components/ui/Global/Global.html
components/views/files/rename/Rename.vue

- i accidentally broke this the other day.
- At least it exposed some legacy code where we were passing functions as props. good opportunity to use emits instead
- Resolve #5283 
- 
-

fix(files): close after successful rename

---

store/accounts/actions.ts

fix(login): removed log error while logging in with no account

---

components/views/chat/chatbar/autocomplete/Autocomplete.html
locales/en-US.js
pages/files/Files.html

fix(searching): removed quotes from search text

---

components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
components/views/chat/chatbar/Chatbar.vue
components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.less
components/views/chat/conversation/Conversation.vue
components/views/chat/message/Message.html
components/views/chat/message/Message.vue
components/views/chat/message/replies/Replies.html
plugins/thirdparty/tooltip.ts
utilities/chat.ts

- Refactor infinite scroll component to handle all the scroll logic
- Fixed a problem when opening a reply
- Fixed a problem when hitting "Arrow up" in the chat if the last message sent was a reply
- Load messages on scrollbar release
- Resolve #5208 
- 
-

chore(scroll): better loader ux and logic

---

assets/styles/base.less
components/ui/Chat/Image/Overlay/Overlay.less
components/ui/EarlyAccessBanner/EarlyAccessBanner.vue
components/views/navigation/sidebar/Sidebar.html
components/views/navigation/sidebar/Sidebar.less
components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.less
components/views/navigation/sidebar/list/item/Item.vue

- use nuxt link for better prefetching, a11y, etc
- switch global anchor styles to only underline with specific class
- Resolve #5274 
- 
-

refactor(sidebar): use Nuxt link instead of button

---

components/compositions/listenToNotifications.ts
components/views/chat/message/notice/Notice.vue
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts
libraries/Iridium/friends/FriendsManager.ts
libraries/Iridium/notifications/types.ts
locales/en-US.js

- Adds notifications for new groups and new group members
- Refactors notification types for more robust type sense (add optional generic types for notification payloads, etc.)
- Resolve #5287 
- Resolve #5237
- As the scope of this PR was starting to overflow notifications for members leaving conversations will be added later.

feat(notifications): add new group and new group members notifications

---

components/interactables/SidebarToggle/SidebarToggle.vue
locales/en-US.js

refactor(sidebarToggle): comp api upgrade plus a11y improvement

---

components/views/callToAction/CallToAction.vue
cypress/support/commands.js

- Added data-cy attribute to locate button on Coming Soon modal
- Small update to validateURLOnComingSoon modal cypress command
- Resolve #
- 
-

test(cypress): update to validate URL On Coming Soon

---

.github/workflows/cypress-tests.yml

- chore(ci): update chrome version to latest
draft until CI finish's

chore(ci): update chrome version to latest

---

ios/readme.md

- chore(fix): fix format on read me
before
after

chore(fix): fix format on read me

---

components/compositions/listenToNotifications.ts
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/chat/types.ts
libraries/Iridium/notifications/types.ts
locales/en-US.js

- Adds notification for when a group member leaves the group
- Refactoring for sendNotification method in ChatManager
- Remove ownderId field for group conversations for now
- Resolve #5289

feat(notifications): configure notification for member leaving group

---

components/views/chat/message/edit/Edit.html
components/views/chat/message/edit/Edit.vue

- Adds auto complete to edit messages as well
- Resolve #5187 
- 
-

feat(edit-message): added auto complete

---

components/interactables/DragBar/DragBar.html
components/interactables/DragBar/DragBar.vue

refactor(dragbar): comp api upgrade

---

components/interactables/Chip/Chip.vue
components/interactables/UserPicker/UserPicker.html

- title
- improve size prop implementation. pass directly to TypographyText component so it remains accessible
- add button around x icon for a11y
- Resolve #5335 
- 
-

refactor(chip): comp api upgrade

---

components/interactables/Checkbox/Checkbox.html
components/interactables/Checkbox/Checkbox.less
components/interactables/Checkbox/Checkbox.vue

- title
- fix cursor on checkbox hover, was plain before
- Resolve #5333 
- 
-

refactor(checkbox): comp api upgrade

---

components/views/chat/UserList.vue

refactor(chat): upgrade right user list to script setup

---

components/interactables/ButtonGroup/ButtonGroup.html
components/interactables/ButtonGroup/ButtonGroup.less
components/interactables/ButtonGroup/ButtonGroup.vue
components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.less
components/views/chat/enhancers/Enhancers.html
components/views/chat/enhancers/Enhancers.less
components/views/chat/enhancers/Enhancers.vue

- title
- Resolve #5308 
- enhancers still needs a rework, some of this is kinda weird
-

refactor(enhancers): cleanup enhancers js logic, resolve css bug

---

android/app/capacitor.build.gradle
android/app/src/main/java/im/satellite/core/MainActivity.java
android/capacitor.settings.gradle
assets/styles/base.less
components/views/navigation/mobile/nav/Nav.less
ios/App/App/ViewController.swift
ios/App/Podfile
layouts/default.vue
layouts/mobile.vue
middleware/safearea.ts
package.json
pages/mobile/chat/_id.vue
pages/mobile/friends/index.vue
pages/mobile/settings/index.vue
utilities/swiper.ts

- Fixes safe area view insets
- Update safe-area-inset-bottom variable for iOS and Android
- Handle back button inside of swiper
- Resolve #5347 
- Resolve #5348 
- Resolve #5349
- 
-

feat(mobile): fix insets and handle software keyboard and back button

---

components/interactables/QuickProfile/QuickProfile.less
components/interactables/QuickProfile/QuickProfile.vue
components/views/navigation/sidebar/status/Status.vue
locales/en-US.js
store/ui/types.ts

- Add app lock button
- Resolve #5326 
- 
-

chore(add): lock app button

---

.github/workflows/cypress-tests.yml

chore(ci): update env

---

components/views/navigation/mobile/nav/Nav.vue
components/views/navigation/sidebar/Sidebar.vue

- requested by Hogan
- Resolve #
- 
-

fix(files): hide files links until functionality is smoother

---

components/views/chat/enhancers/Enhancers.vue
package.json

- install vueuse for a collection of helpful composition api utilities. Will try to use these instead of various packages whenever possible
- Resolve #5375 
- 
-

fix(enhancers): improve clickoutside behavior

---

libraries/Iridium/friends/FriendsManager.ts
libraries/Iridium/notifications/types.ts

- New friend request notifications weren't appearing as the data passed to create the notifications needed to be updated
- Resolve #5373

fix(notifications): update new friend request notification data

---

components/compositions/listenToNotifications.ts

- Notification link to friend requests on mobile needed has been updated
- Resolve #5249

fix(notifications): update broken link to mobile friend requests

---

package.json

Something in a nuxt-bridge update is killing out builds, this changes instead using the latest, to the last working nuxt-bridge
- Resolve #
- 
-

fix(build): fix issue in dependency

---

components/ui/ActionSheet/ActionSheet.vue
components/ui/ContextMenu/ContextMenu.vue
components/views/navigation/mobile/nav/Nav.less

- Fixes the styling for action sheets in mobile
- Resolve #5322 
- To bring up an action sheet long press a list item in the chat list on mobile.
- Styling bug for action sheets opened inside the friends screen will be fixed in a separate PR.

fix(context-menu): fix action sheet styles

---

components/interactables/Editable/Editable.vue
components/views/chat/chatbar/Chatbar.html
components/views/chat/chatbar/Chatbar.vue
components/views/chat/enhancers/Enhancers.less
components/views/chat/enhancers/emoji/Emoji.less
components/views/chat/enhancers/glyphs/Glyphs.less
components/views/chat/enhancers/glyphs/item/info/Info.less
components/views/navigation/mobile/nav/Nav.vue
ios/App/App/ViewController.swift
layouts/mobile.vue
middleware/safearea.ts
pages/mobile/chat/_id.vue

- Fix keyboard insets on mobile
- Fix safe area insets on pages
- Fix enhancers layout on mobile
- Disable mobile enter key to send message
- Chat icon in mobile nav
- Resolve #5390
- Resolve #5391
- Resolve #5403 
- 
-

feat(mobile): keyboard and safe area insets

---

components/compositions/listenToNotifications.ts
libraries/Iridium/chat/ChatManager.ts
libraries/Iridium/notifications/types.ts
locales/en-US.js

- Configures incoming call notifications
- Resolve #5400

feat(notifications): configure notification for incoming calls

---

compositions/release.ts

- create new compositions folder outside of /components. All compositions should be moved here eventually. we get lots of console warning about the current structure missing default exports
- settings modal is fetching data every single mount. This will fetch one time on first render, then never again.
- not yet implemented, waiting for other refactor to go through first
- Resolve #
- 
-

feat(releaseData): add new hook for release data

---

components/interactables/QuickProfile/QuickProfile.vue
components/views/chat/UserList.vue
components/views/chat/message/Message.vue

- title
- remove 0ms timeouts. We added these because the old directive would stop propagation on click
- Resolve #5394 
- 
-

refactor(quickProfile): use new clickoutside comp utility

---

components/ui/Global/Global.html
components/ui/ResultsMessage/ResultsMessage.vue
components/views/chat/conversation/Conversation.vue
components/views/friends/Item.vue
components/views/navigation/sidebar/Sidebar.less
components/views/settings/pages/profile/Profile.html
components/views/settings/pages/profile/Profile.less
components/views/settings/pages/profile/index.vue
libraries/Iridium/NotificationManager.ts
libraries/Iridium/chat/ChatManager.ts

- Fixes the issues in #5404 
- Resolve #5404

fix(misc): miscellaneous fixes

---

components/views/chat/message/notice/Notice.vue
locales/en-US.js

fix(chat): replace user's username with 'you' for member added message

---

components/views/navigation/sidebar/list/List.vue
components/views/navigation/sidebar/list/item/Item.html
pages/mobile/chat/_id.vue

- remove code no longer needed after this change https://github.com/Satellite-im/Core-PWA/pull/5410
- Resolve #
- 
-

refactor(mobile): remove unused emit

---

cypress/e2e/chat-top-toolbar.js
cypress/e2e/mobiles-responsiveness.js
cypress/e2e/snapshots-test.js
cypress/support/commands.js

- chore(cypress): minor updates

chore(cypress): minor updates

---

README.md
components/views/chat/message/call/Call.vue
components/views/media/heading/Heading.html
components/views/media/heading/Heading.vue

- Resolve duration timestamp issue
- Add a description on how to resolve Yarn cache error
- Resolve #5353 
- Please let me know if my way of patching the error needs to be polished (in the case that it needs to be rewritten to fit in with Satellite's code standard)
Proof that it works:

feat(call): resolve duration timestamp issue

---

libraries/Iridium/IdentityManager.test.ts
libraries/Phantom/PhantonManager.test.ts
libraries/SatelliteDB/SearchIndex.test.ts
libraries/SatelliteDB/__snapshots__/SearchIndex.test.ts.snap
libraries/WebRTC/Call.ts
libraries/WebRTC/bus/DirectWebRTCBus.test.ts
libraries/WebRTC/bus/DirectWebRTCBus.ts
locales/.gitignore
store/ui/mutations.ts
types/search/search.ts
utilities/duration.test.ts

- fixes warning on `libraries/Iridium/IdentityManager.test.ts`
- fixes warning on `libraries/Phantom/PhantonManager.test.ts`
- fixes warning on `libraries/SatelliteDB/SearchIndex.test.ts`
- removes unused stuff on `libraries/WebRTC/Call.ts`
- removes unused imports on `libraries/WebRTC/bus/DirectWebRTCBus.test.ts`
- removes empty file on `libraries/ui/Alerts.ts`
- removes `locales/.gitignore`, we already have a .gitignore file on the root folder
- removes not used imports on `store/ui/mutations.ts`
- removes commented out code on `types/search/search.ts`

chore(update): updates

---

.eslintrc.js

- chore(update): update eslint

chore(update): update eslint

---

components/compositions/webrtc.ts
components/ui/ActionSheet/ActionSheet.vue
components/ui/BackgroundCall/BackgroundCall.vue
components/views/chat/conversation/Conversation.vue
pages/mobile/chat/_id.vue

- title
- Resolve #5412 
- I noticed a really weird bug clicking the active call banner. It deletes a conversation from the bottom of the list. Need to look into this more
-

refactor(mobile): upgrade chat page to script setup

---

components/compositions/capacitor.ts
components/compositions/listenToNotifications.ts
components/compositions/webrtc.ts
components/interactables/QuickProfile/QuickProfile.vue
components/interactables/SidebarToggle/SidebarToggle.vue
components/views/chat/UserList.vue
components/views/chat/chatbar/controls/Controls.vue
components/views/chat/chatbar/footer/TypingIndicator/TypingIndicator.vue
components/views/chat/enhancers/Enhancers.vue
components/views/navigation/mobile/nav/Nav.vue
components/views/navigation/mobile/toolbar/Toolbar.vue
components/views/navigation/sidebar/list/item/Item.vue
components/views/navigation/sidebar/quick/Quick.vue
components/views/navigation/toolbar/Toolbar.vue
pages/chat/_id.vue
pages/mobile/chat/_id.vue
tsconfig.json

- Configures tsconfig to properly extend the tsconfig provided by Nuxt
- defines imports for useNuxt app
- Resolve #5423

fix(tsconfig): fix extends issue for nuxt tsconfig

---

ios/App/App/Info.plist

- Adds use descriptions for camera/microphone usage so calls will work on iOS
- Indentation
- Resolve #5435
- 
-

chore(ios): add camera/microphone usage descriptions

---

components/compositions/webrtc.ts
components/interactables/Input/Input.html
components/interactables/Input/Input.less
components/ui/ActionSheet/ActionSheet.vue
components/views/friends/Item.vue
components/views/friends/mobile/List.vue
components/views/navigation/sidebar/Sidebar.less
components/views/navigation/sidebar/list/item/Item.less

- Re-enable, adjust, and make fixing changes to quick profile menu for FriendsItem component.
- Resolve #5425

fix(friends-item): re-enable and adjust quick profile

---

android/app/build.gradle

Adds Leak Canary to check memory leaks as a suggestion
https://square.github.io/leakcanary/
when compiling, you can check the leaks going to the leaks extension here

chore(native-android): leak canary

---

components/views/navigation/sidebar/list/item/Item.html
components/views/navigation/sidebar/list/item/Item.vue

- Adds timestamps for sidebar list items with no messages
- Resolve #5441

fix(sidebar-list-item): implement timestamps for new conversations

---

components/views/chat/conversation/Conversation.vue

- Title
- Resolve #5445 
- Related to #5415
- @phillsatellite didnt find the one you opened Friday ;)

fix(chat): set read only if at the bottom of the scroll

---

package.json

chore(bundle): remove unused package

---

store/chat/mutations.test.ts

-  Increase coverage for store/chat/mutations
- 
-

feat(jest): 82% coverage for store/chat/mutations

---

libraries/ui/ReleaseNotes.test.ts
utilities/timestamp.test.ts

- 72% coverage for ReleaseNotes
- 100% coverage for utilities/timestamp
no ticket
- 
-

feat(jest): improve Timestamp and ReleaseNotes coverage

---

jest.config.js
utilities/timestamp.test.ts

fix(test): fixed timezone for test environment

---

components/compositions/webrtc.ts
components/ui/BackgroundCall/BackgroundCall.vue
components/views/chat/message/call/Call.vue
components/views/media/heading/Heading.vue

- reuse shared logic
- Resolve #5422 
- 
-

refactor(webrtc): composable for active call timer

---

components/compositions/listenToNotifications.ts
components/compositions/useNotifActionHandlers.ts
components/compositions/useNotifCreateHandlers.ts
components/views/settings/pages/notifications/index.vue
libraries/Iridium/NotificationManager.ts
libraries/Iridium/friends/FriendsManager.ts
libraries/Iridium/notifications/types.ts
utilities/Notifications.ts

- Refactors notifications to be expandable in the future for notification actions on all platforms, including web
- Adds notification actions for Android devices
- Resolve #5464

feat(notifications): add notification actions for android

---

cypress/e2e/chat-features.js

- Test sending all alphabet chars in a chat
- Resolve #AP-1035
- 
- Cypress video passing:
https://user-images.githubusercontent.com/35935591/200440349-4d7cf3e7-1869-47e9-9ac6-0b875ee47d09.mp4
- Cypress specs passing:

test(cypress): test all alphabet chars on chat

---

cypress/e2e/mobiles-responsiveness.js
cypress/support/commands.js
cypress/support/first-user/commands.js
cypress/support/second-user/commands.js

- Unskipped cypress tests now fixed for mobiles-responsiveness.js and added notes/comments on tests that are still skipped because we are waiting on import account feature to be fixed
- Changed how we delete localstorage, sessionstorage, indexeddb and cookies before starting the login with a local storage cached account, in order to avoid Linking Satellites issues presented randomly in CI. These changes were placed in the 3 cypress commands files.
- Resolve #
- 
- Cypress Tests Passing:
- Videocalll cypress tests passing:
- Mobiles Responsiveness Cypress Video:
https://user-images.githubusercontent.com/35935591/200651330-7269e9ce-d69f-4e4d-aa15-8c1bd4a705ad.mp4

test(cypress): updates for CI and unskip tests

---

components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
components/views/chat/conversation/Conversation.html
components/views/chat/conversation/Conversation.vue

chore(chat): set read on conversation scroll bottom

---

libraries/ui/Markdown.test.ts
store/chat/mutations.test.ts

- 93% coverage for Markdown
- 100% coverage for store/chat/mutations
- 
-

feat(jest): increase coverage for chat/mutations and Markdown
